### ISSUE TITLE
[js] thrown error got wrapped twice by HaxeError when using compilation server

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5405] opened 2016-06-23 15:15 UTC
The generated code is something like 

``` js
throw new js__$Boot_HaxeError(new js__$Boot_HaxeError('the error'));
```

But I cannot reproduce it at the moment.

@nadako

**Comment by nadako** [comment] 2016-06-23 21:12
That reproduces in my work project's code but it will be a pain to reduce...

**Comment by nadako** [comment] 2016-06-23 22:09
This seems to be related to `import.hx` being present (even if it's empty), so this could have same roots as #5397.

**Comment by nadako** [comment] 2016-06-23 22:36
Okay, I reduced it to this:

`/pack/Main.hx`:
```haxe
package pack;

class Main {
    static function main() {
        Some.f();
    }
}
```

`/Some.hx`:
```haxe
class Some {
    public static inline function f()
        throw "oh no";
}
```

If we add `pack/import.hx`, then the second compilation will wrap the thrown error twice.

**Comment by nadako** [comment] 2016-06-23 22:37
BTW here's my testing script:
```
class Build {
    static function main() {
        var proc = new sys.io.Process("haxe", ["--wait", "6000"]);
        var args = [
            "--connect", "6000",
            "-cp", "src",
            "-main", "pack.Main",
            "-js"
        ];
        var code = Sys.command("haxe", args.concat(["test.js"]));
        if (code == 0)
            Sys.command("haxe", args.concat(["test2.js"]));
        proc.kill();
    }
}
```

**Comment by nadako** [comment] 2016-06-23 22:59
I side-stepped the symptom by setting a proper type to the wrapped error, but it's not a proper fix and you can still reproduce the double-wrap if you do `throw ("oh no" : Dynamic)` there.

The real problem is that `wrap_js_exceptions` is invoked every time and since second time it filters expressions that were already filtered and saved to cache. It shouldn't do that, but I have no idea how to move it properly atm.

cc @Simn @ncannasse

**Comment by kevinresol** [comment] 2016-06-24 02:48
I don't use an import.hx but it also happens to me. But it is damn hard to reproduce.

**Comment by Simn** [comment] 2016-06-24 06:19
From what you're saying it doesn't sound like import.hx is the problem. It only causes #5397 which in turn causes this behavior.

**Comment by kevinresol** [comment] 2016-06-24 06:34
Maybe off-track: Another symptom about the compilation server is that sometimes some macro-generated types does not get generated to the output. 

For example, there is a piece of code in output.js as follow:
```js
new Validator0().validate();
```
But when I search the whole output.js for `Validator0`, there is only one occurrence which is the quoted one. 

In a generic build macro I return a Type, but that Type is "cached" from previous builds (I used a var to store the generically built type and return that in subsequent compiles). Not sure if it is that caused the problem.

But still I don't have a way to reproduce it, yet.

**Comment by nadako** [comment] 2016-06-24 10:55
Yeah, it's probably not because of `import.hx` itself, but it triggers the cache invalidation.

**Comment by nadako** [comment] 2020-05-24 19:23
It's hard to say if the related compiler cache is still there, but haxe exception was reworked since then and #5397 is long closed, so this issue is pretty useless. I'll close it.

**Closed by nadako** 2020-05-24 19:23 UTC
Labels: bug, platform-javascript
