### ISSUE TITLE
[eval] typeof() exception not catched (depending on import)

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#6736] opened 2017-11-05 10:50 UTC
I'm encountering a weird case in a build macro where it errors out with `Debug has no field or subtype log`, although `Debug` has a static function named `log`.

I've uploaded code to reproduce the issue in [this repo](https://github.com/azrafe7/macro-subst-func/tree/catch-issue).

I'd expect the error to be catched as a result of the call to `typeof` in here https://github.com/azrafe7/macro-subst-func/blob/45cf78b2073a95f5bc07a0e5985538a4d0aa89a5/src/Macros.hx#L40

What is weird is that it does work if I use `import Debug` instead of `import Debug.log` here https://github.com/azrafe7/macro-subst-func/blob/45cf78b2073a95f5bc07a0e5985538a4d0aa89a5/src/mylib/MyLib.hx#L3

Maybe this other issue is related https://github.com/HaxeFoundation/haxe/issues/5138

And sorry if this is a mistake on my side (still new to the macro world).

(compiling with 4.0.0 (git build development @ 71eab1b64))

**Comment by Simn** [comment] 2019-07-02 17:52
Does this still reproduce?

**Comment by Simn** [comment] 2020-06-05 16:18
Closing due to lack of followup, feel free to comment again if the problem remains.

**Closed by Simn** 2020-06-05 16:18 UTC
Labels: bug, platform-macro
