### ISSUE TITLE
Duplicate class field in abstract exposes _Impl_ in error message

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8718] opened 2019-08-29 09:29 UTC
```haxe
abstract Color(Int) {
	function foo() {}
	function foo() {}
}
```

```
Main.hx:11: characters 2-19 : Duplicate class field declaration : _Main.Color_Impl_.foo
```

**Comment by Aurel300** [comment] 2019-08-29 10:04
Duplicate of https://github.com/HaxeFoundation/haxe/issues/8258

**Closed as completed by Aurel300** 2019-08-29 10:04 UTC
Labels: error-reporting

**Comment by Gama11** [comment] 2019-08-29 10:16
I guess that makes this a duplicate error report of a duplicate error report. :)
