### ISSUE TITLE
[cs] StringMap doesn't use type parameter in C# code?

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5468] opened 2016-07-18 11:35 UTC
StringMap does not use type parameter for some reason. It uses `haxe.ds.StringMap<object>` regardless of type parameter. Is it for making it possible to cast any Maps to `haxe.ds.StringMap<object>`? Then, there is no way to avoid the overhead of casts?

```hx
package;

class SomeClass
{
	public function new()
	{
	}
}

class Main 
{
	static function main() 
	{
		var test:Map<String, Array<SomeClass>> = ["a" => [new SomeClass()]];
		var instance:Array<SomeClass> = test["a"];
		callTrace(instance);
	}
	
	static function callTrace(instance:Array<SomeClass>)
	{
		trace(instance);
	}	
}
```

```cs
public static void main() {
		global::haxe.ds.StringMap<object> _g = new global::haxe.ds.StringMap<object>();
		_g.@set("a", new global::Array<object>(new object[]{new global::SomeClass()}));
		global::Main.callTrace(((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) ((_g.@get("a")).@value) ))) ));
	}
	
	
	public static void callTrace(global::Array<object> instance) {
		unchecked {
			global::haxe.Log.trace.__hx_invoke2_o(default(double), instance, default(double), new global::haxe.lang.DynamicObject(new int[]{302979532, 1547539107, 1648581351}, new object[]{"callTrace", "Main", "Main.hx"}, new int[]{1981972957}, new double[]{((double) (23) )}));
		}
	}
```

**Comment by nadako** [comment] 2016-07-18 11:47
duplicate of #5434

**Closed by nadako** 2016-07-18 11:47 UTC
