### ISSUE TITLE
Cannot access private field despite said field being public.

### ISSUE THREAD

**Issue by VodOSS** [HaxeFoundation/haxe#10306] opened 2021-07-01 21:50 UTC
The title is pretty self explanatory. I can't access a field DESPITE that field is public:

     function checkEnemyVision(enemy:Enemy)
	{
		if (walls.ray(enemy.getMidpoint(), _player.getMidpoint()))
		{
			enemy.seesPlayer = true;
			enemy.playerPosition = _player.getMidpoint();
		}
		else
		{
			enemy.seesPlayer = false;
		   }
	    }
       }

And at the top of the class there are the variables:

	public var seesPlayer:Bool;
	public var playerPosition:FlxPoint;

It gives me theese errors:

Cannot access private field seesPlayer,
Cannot access private field playerPosition

**Comment by Aurel300** [comment] 2021-07-01 23:01
Can you reduce your code to a minimal sample or share some code we can use to reproduce the issue?

**Comment by RealyUniqueName** [comment] 2021-07-07 11:08
Looks like a macro magic is involved. We need a sample to proceed, as Aurel said.

**Comment by Simn** [comment] 2021-07-13 10:10
Closing this because there's a high chance that this isn't a compiler issue. Feel free to reopen if an example suggesting otherwise can be found!

**Closed as completed by Simn** 2021-07-13 10:10 UTC
Labels: waiting-for-feedback
