### ISSUE TITLE
Wrong abstract cast when using abstracts on abstracts?

### ISSUE THREAD

**Issue by Neu2o** [HaxeFoundation/haxe#9892] opened 2020-09-21 10:03 UTC
I tried to create a minimal example of a problem we are facing at InnoGames when targeting JS:

```haxe
import haxe.io.Bytes;
import js.lib.ArrayBuffer; // or js.html.ArrayBuffer for older Haxe versions

abstract ByteArray(ByteArrayData) from ByteArrayData {
	public inline function new(length:Int = 0):Void {
		this = new ByteArrayData(length);
	}
	@:to public function toArrayBuffer():ArrayBuffer {
		return this.getData();
	}
}

class ByteArrayData extends Bytes {
	public function new(length:Int = 0) {
		var bytes = Bytes.alloc(length);
		super(bytes.b.buffer);
	}
}

// I called it FLObject as it's actually openfl.utils.Object
abstract FLObject(ObjectType)
	from ObjectType
{
	public inline function new() this = {};
}

typedef ObjectType = Dynamic;

abstract ASObject(FLObject)
	from FLObject
{
	public inline function new() this = {};
}

class Test {
	static function foo(value: ASObject) {
		trace(value);
	}
	static function bar(value: FLObject) {
		trace(value);
	}
	static function wtf(value: Dynamic) {
		trace(value);
	}
	static function main() {
		var ba: ByteArray = new ByteArray();
		foo(ba);
		bar(ba);
		wtf(ba);
	}
}
```

This produces:
```js
// Haxe 3.4.4
Test.main = function() {
	var ba = new ByteArrayData(0);
	Test.foo(_$Test_ByteArray_$Impl_$.toArrayBuffer(ba));
	Test.bar(_$Test_ByteArray_$Impl_$.toArrayBuffer(ba));
	Test.wtf(ba);
};

// Haxe 4.0.5 and 4.1.4
Test.main = function() {
	var this1 = new ByteArrayData(0);
	var ba = this1;
	Test.foo(_$Test_ByteArray_$Impl_$.toArrayBuffer(ba));
	Test.bar(ba);
	Test.wtf(ba);
};
```

The problem is the toArrayBuffer call (or actually the first `@:to` call in ByteArray). It is taken to cast ByteArray to either FLObject or ASObject. In our case we have the ASObject case, and ideally it casts to the same result as FLObject (with 4.0.5), meaning to the same result as Dynamic, meaning no cast. We expected this, as ASObject is an abstract over FLObject, meaning over Dynamic. But apparently it doesn't work like that; maybe for a good reason, I'm not saying this is a great structure, but it's the result of a conversion process atm ;)
I was in contact with @Simn and as abstracts and casts were reworked a lot, in 4.2 apparently `foo(ba)` doesn't even compile anymore.

We talked a bit and decided to put this example here for now. It might help to verify if the 4.2 behavior is correct, or if it needs more rework. It might also lead to some valuable discussions, so please feel free ;)

**Comment by RealyUniqueName** [comment] 2020-09-21 12:19
If `toArrayBuffer` is involved it's a transitive cast and it should not compile.
But `from Dynamic` means "from any type". I think All three calls should compile without generating a call to `toArrayBuffer`.

**Comment by Simn** [comment] 2020-09-21 12:31
I don't think the first one should compile because it would have to go `ByteArray -> FLObject -> ASObject`, which is transitive.

**Comment by RealyUniqueName** [comment] 2020-09-21 12:41
Oh, sorry. I thought the first one is also `from Dynamic`, but it's `from FLObject`.

**Comment by Neu2o** [comment] 2020-09-21 12:59
Yes, `from Dynamic` in ASObject make it work. As FLObject is an abstract over Dynamic I guess the assumption was it's basically similar to `from Dynamic`.
Having a compile error like in 4.2 is of course already much better than a possible runtime error because of the added `toArrayBuffer` ;)

**Comment by nadako** [comment] 2020-09-21 17:09
I am on vacation right now, but I remember having to add some @:transitive to ASObject to make it compile with 4.2

**Comment by RealyUniqueName** [comment] 2020-12-14 14:00
@nadako have you resolved this with `@:transitive`?

**Comment by nadako** [comment] 2020-12-14 14:53
I have to dig into this issue to understand what is it about :) But better ask @Neu2o

**Comment by Neu2o** [comment] 2020-12-14 15:03
Well, in the PR you see I've added `from Dynamic` to `ASObject` and that avoids the described problem. I haven't checked `:@transitive` myself nor have I looked into this since a while. For now I'm fine with how it is and maybe we could also just close this issue as I'm not 100% sure if it's actually a bug or not

**Comment by Simn** [comment] 2021-11-04 10:35
With latest Haxe, the first call fails to compile with `ByteArray should be ASObject`. This can be made to work by adding `@:transitive` to `FLObject`, in which case the generated code looks like this:

```js
Main.main = function() {
	var this1 = new ByteArrayData(0);
	var ba = this1;
	Main.foo(ba);
	Main.bar(ba);
	Main.wtf(ba);
};
```

This looks like it's working as intended, so I'll close this issue. If there's still some problem, please let me know!

**Closed as completed by Simn** 2021-11-04 10:35 UTC
Labels: bug, haxe-foundation-partner
