### ISSUE TITLE
ES6 class generation  any planned key get set generation? 

### ISSUE THREAD

**Issue by longde123** [HaxeFoundation/haxe#8330] opened 2019-05-24 10:40 UTC
no

```haxe
class MyClass {
	constructor() {
		// ...
	}
	get_prop() {
		return 'getter';
	}
	set_prop(value) {
		console.log('setter: ' + value);
	}
}
```

like 

```haxe
class MyClass {
	constructor() {
		// ...
	}
	get prop() {
		return 'getter';
	}
	set prop(value) {
		console.log('setter: ' + value);
	}
}
let inst = new MyClass();
inst.prop = 123;
// setter: 123
inst.prop
// 'getter'
```

get_prop() {
return 'getter';
}
set_prop(value) {
console.log('setter: ' + value);
} 

to generation:

```
get_prop() {
    return 'getter';
}
set_prop(value) {
    console.log('setter: ' + value);
}
get prop() {
    return get_prop();
}
set prop(value) {
    return set_prop(value)
}
```

**Comment by longde123** [comment] 2019-05-24 10:52
get_prop() {
return 'getter';
}
set_prop(value) {
console.log('setter: ' + value);
} 

to generation 
get_prop() {
return 'getter';
}
set_prop(value) {
console.log('setter: ' + value);
}
get prop() {
return get_prop() ;
}
set prop(value) {
    return set_prop(value)
}

**Comment by Aurel300** [comment] 2019-05-24 10:54
Please make sure to describe problems properly, use formatting, etc …

In short, you are suggesting that property getters and setters are generated into ES6 code as actual getters rather than (or in addition to?) regular functions with `get_` and `set_` prefixes. 

Also, please don't open other issues – what you are asking for is completely unrelated to nadako's coroutines repository.

**Comment by Gama11** [comment] 2019-05-24 10:57
Duplicate of https://github.com/HaxeFoundation/haxe/issues/5104?

**Comment by RealyUniqueName** [comment] 2019-05-24 11:06
I'm not sure what exactly is proposed, so let it be a duplicate of #5104 
Feel free to reopen after clarification.

**Closed as completed by RealyUniqueName** 2019-05-24 11:06 UTC
