### ISSUE TITLE
Compiler Failure

### ISSUE THREAD

**Issue by onehundredfeet** [HaxeFoundation/haxe#10444] opened 2021-10-22 06:43 UTC
Compiler failure
Please submit an issue at https://github.com/HaxeFoundation/haxe/issues/new
Attach the following information:
Haxe: 4.2.3; OS type: unix;
File "src/generators/genhl.ml", line 1330, characters 103-110
Called from Genhl.get_access in file "src/generators/genhl.ml", line 1330, characters 96-110
Called from Genhl.eval_expr in file "src/generators/genhl.ml", line 2379, characters 10-27
Called from Genhl.eval_expr in file "src/generators/genhl.ml", line 1622, characters 10-17
Called from Genhl.make_fun in file "src/generators/genhl.ml", line 3257, characters 7-32
Called from Genhl.generate_member in file "src/generators/genhl.ml", line 3387, characters 8-106
Called from Genhl.generate_type in file "src/generators/genhl.ml", line 3429, characters 3-67
Called from Stdlib__list.iter in file "list.ml", line 110, characters 12-15
Called from Genhl.generate in file "src/generators/genhl.ml", line 4103, characters 1-24
Called from Haxe.generate in file "src/compiler/haxe.ml", line 351, characters 2-14
Called from Haxe.init in file "src/compiler/haxe.ml", line 1082, characters 25-72
Called from Haxe.process_params.loop in file "src/compiler/haxe.ml", line 642, characters 3-11
Called from Haxe in file "src/compiler/haxe.ml", line 1247, characters 1-35
File "src/core/globals.ml", line 117, characters 1-7: Assertion failed

No idea why this is happening.

**Comment by onehundredfeet** [comment] 2021-10-22 07:15
The detail you added tracked it down to a line like this (Not real variable names):

```haxe
class BaseClass {
  static var staticVar : BaseClass;
  function setStaticVar( v : Baseclass) {
    staticVar = v;
 }
}

class Foo extends BaseClass {
  public function new () {
    BaseClass.staticVar = this;  // Compiler error
    BaseClass.setStaticVar( this ); // No compiler error
  }
}
```
Removing that line bypassed the compiler failure.

**Comment by RealyUniqueName** [comment] 2021-10-22 08:32
I cannot reproduce the issue with that code. 
Can you provide a reproducible sample?

**Comment by onehundredfeet** [comment] 2021-10-22 22:24
I will try to create the smallest reproducible sample.

**Comment by Simn** [comment] 2022-01-04 10:58
There hasn't been any follow-up here, so I'll close the issue for now. If a reproducible example comes up, we can reopen.

**Closed as completed by Simn** 2022-01-04 10:58 UTC
Labels: bug, platform-hl
