### ISSUE TITLE
[cs] Haxe 3.3 is slower than 3.2, especially on Mono

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5465] opened 2016-07-18 02:04 UTC
I think Haxe 3.3 generates the code which cannot be easily optimized by Mono runtime for some reason, but I don't know which change caused this issue.

One of the library that I noticed performance problem is Starling.
On Android, performance problem is more easily noticeable than on PC. Benchmark can only render around 1000 objects with Haxe 3.3, while with Haxe 3.2 it can render more than 3500 objects. I can't simply switch to CoreCLR as it still doesn't support Android.

CoreCLR also has performance issues with assembly compiled by hxcs build tool, but not with msbuild. I'm not sure why. Visual C# do different optimization when compiled from MSBuild, perhaps.

I've also tried Mono for Windows and it also has performance issues with Haxe3.3. Slowdown is not  so huge as Android, though it's still big. Mono uses CPU a lot even with simple 2D scene.

**Comment by nadako** [comment] 2016-07-18 07:53
Is this a non-issue after all?

**Comment by vroad** [comment] 2016-07-18 08:28
@nadako I thought this(https://github.com/HaxeFoundation/haxe/issues/5467) was the cause of issue, but I'm not sure if there are other issues. Avoiding the creation of `openfl.Vector` in `openfl.display3D.Context3D.setProgramContantsFromMatrix` doesn't fully solve the issue. Maybe it would be better to leave this issue open until we find real cause.

**Comment by nadako** [comment] 2016-07-18 08:33
Well, this issue is not actionable right now, so I'd prefer not to reopen it. It might be an OpenFL problem after all. I'll look at the generated code in my work project, also if you come up with something reproducible, then reopen please.

**Comment by vroad** [comment] 2016-07-18 15:04
I did something like bisect with precompiled Haxe binaries in http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/windows/ . df58008 is the last known revison that doesn't have performance problem. This revision has issues with conditional operator that prevents csc/msbuild from compiling starling-openfl, though. (Simlilar to https://github.com/HaxeFoundation/haxe/issues/5466, but in different places.) I tried running that build by modding generated code a bit, and found that this build doesn't have performance issues. b424754 compiles starling without errors, but had performance issues.

So, what is changed between df58008 and b424754?

**Comment by vroad** [comment] 2016-07-18 15:57
I've tried building Haxe by myself. 38f5b1a4101a164e069b9e44d61a8a72d53c3b22 is the commit that fixed issue with conditional operators, and this commit introduced performance issues on Mono at the same time.

**Comment by nadako** [comment] 2016-07-18 16:15
eh... is there an (preferably small) open-source project that i could build with those two versions of haxe and diff the output to see if there's some weird code generated now?

**Comment by vroad** [comment] 2016-07-19 01:05
https://github.com/openfl/starling is open sourced, it has benchmark program that tests rendering performance, though you'll also need to check out lime, openfl, haxe, hxcs fork to simulate my environment. Official OpenFL still doesn't support C#, hxcs cannot specify x86/x64 when builiding from command line, some Haxe generated methods which have -1 in __hx_arity cannot be called with diffrent number of arguments, etc. https://github.com/HaxeFoundation/haxe/pull/5295

I built source code from older version, then checkout my branch again to avoid issues with these functions.
You may don't need to do that since latest version has the same issue. 

Maybe you could look at generated C# code instead?
I could see that lots of temp variables are used if you compile source code from that problematic Haxe version, but I don't know if it's the cause.

**Comment by vroad** [comment] 2016-07-19 03:24
Today I've just came across a tool named Germade. I inspected the code with Germade and found that Mono is slow with large number of local variables. That explains why starling got slower from that commit (https://github.com/HaxeFoundation/haxe/commit/38f5b1a4101a164e069b9e44d61a8a72d53c3b22).

You can see html report generated by Germade by saving this gist to local.

https://gist.github.com/vroad/e4ec311269820e87a4723273cf5568c6
https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Performance.AvoidLargeNumberOfLocalVariablesRule(2.10)

So I think I've found the cause, but can this be easily solved? I know nothing about Haxe compiler in this regard unfortunately.

**Comment by vroad** [comment] 2016-07-19 03:48
I paste one of the files which Germade reported as problematic. Bad version uses much larger number of tmp variables.

Good version: https://gist.github.com/vroad/ba6cc51bea0c24d6ec9133f9da5b3cdb
Bad version: https://gist.github.com/vroad/6cb5be52c9b242bbd43e773ab798673f

**Comment by ncannasse** [comment] 2016-07-21 13:11
@Simn can you have a look to see if the analyzer might be involved?

**Comment by Simn** [comment] 2016-07-22 07:13
Of course it's going to be involved, but what am I supposed to do about that? Dropping two 9.5kloc files onto me isn't gonna help much.

I'm not willing to revert the null-change for 3.3 because #5074 is a major problem otherwise. I also refuse to believe that additional temporary variables are a run-time performance problem on compiled targets.

**Comment by Simn** [comment] 2016-07-22 07:16
Closing here to avoid discussion fragmentation -> #5074.

**Closed by Simn** 2016-07-22 07:16 UTC
