### ISSUE TITLE
C# dll compiler flags not sensibly documented

### ISSUE THREAD

**Issue by pboyer** [HaxeFoundation/haxe#3829] opened 2015-02-02 22:43 UTC
As discussed here:  https://groups.google.com/forum/?hl=en#!topic/haxelang/ytuctcHOFqk

Using `-D dll` provides the ability to generate a dll (as opposed to an exe) when compiling for C#.  This is not documented at the command line or the docs - would be great if it was.  

Thanks for this great tool!

**Comment by Simn** [comment] 2015-02-02 22:46
The problem is that this flag is not used by the actual Haxe compiler but by the hxcs library: https://github.com/HaxeFoundation/hxcs

I don't know what to do with these target-specific flags; there are a lot of them for hxcpp as well and there might even be conflicts between different targets. It might be better to not have these on the command line but instead add them to the target details section of the manual.

**Comment by Justinfront** [comment] 2015-02-02 23:40
I think we should require a library preface for well established libraries, so we could list them in the compiler.
--help-library-defines
but reguire they are clearly library associated
-D hxcs-dll
or maybe get haxelib to install them. If we define them when submitting a haxelib there would be no conflict but then again -D hxcs-dll is also package safe.

**Comment by kLabz** [comment] 2019-06-12 07:34
@Simn should these defines be prefixed with `hxcpp`, `hxcs` etc.? There are already `hxcpp-api-level` and `hxcpp-smart-strings` in current `--help-defines` output.

I could make a PR to hxcs to support both prefixed and not prefixed versions + a PR here to add the prefixed ones in define.json.

**Comment by Gama11** [comment] 2019-06-12 08:42
If anything, should probably make use of the new "define namespaces"? `hxcpp.api-level`, `hxcpp.smart-strings`...

**Comment by kLabz** [comment] 2019-06-14 05:42
Added support for `hxcs.definename` in hxcs [PR](https://github.com/HaxeFoundation/hxcs/pull/40)

This also includes [some kind of documentation](https://github.com/HaxeFoundation/hxcs/blob/a9ad0603efc88054bd3dd7f3a82ed7147c74fece/build-tool/src/compiler/cs/CsCustomDefine.hx) for these specific defines, but I'm not sure how to expose them..

**Comment by Simn** [comment] 2023-03-24 14:46
Closing old C# issue that won't be addressed.

**Closed by Simn** 2023-03-24 14:46 UTC
Labels: documentation
