### ISSUE TITLE
Expose Haxe generated JS as a NPM module

### ISSUE THREAD

**Issue by zabojad** [HaxeFoundation/haxe#5169] opened 2016-04-26 09:29 UTC
Currently, there is no way to automatically expose a haxe generated piece of js code as an NPM module. The only possibilities we have are [exposing it to `window` or to `exports`](http://haxe.org/manual/target-javascript-expose.html) but not to `module.exports`.

The problem with this is that today, many js projects targeting the browser uses massively NPM to organise external libs and imports (react js, redux, flux, react router, etc...). And this limitation prevents us from easily building npm modules from haxe and distribute them... It is possible, but we have to add a little js glue file just to do the `module.exports = ...`.

Could you please add a metadata (something like `@npmExpose("...")`) that would do this:
```
(function (console, $hx_exports) { "use strict";
// blablabla
})(typeof console != "undefined" ? console : {log:function(){}}, module.exports);
```

instead of this:
```
(function (console, $hx_exports) { "use strict";
// blablabla
})(typeof console != "undefined" ? console : {log:function(){}}, typeof window != "undefined" ? window : exports);
```

**Comment by nadako** [comment] 2016-04-26 09:51
Isn't `exports` supposed to be the same as `module.exports`?

**Comment by mcheshkov** [comment] 2016-04-26 12:33
Not exaclty, `exports = 'foo';` is just a local variable assigning, and will not be visible from outside, while `module.exports = 'foo';` will. But `@:expose` always assigns a property, so nothing wrong.

**Comment by nadako** [comment] 2016-04-26 12:35
So what's the problem exactly?

**Comment by zabojad** [comment] 2016-04-26 13:01
> But @:expose always assigns a property, so nothing wrong.

@mcheshkov what do you mean by that?

> So what's the problem exactly?

@nadako @mcheshkov well, how can you achieve a `@:expose` on `module.exports` instead of `exports`? 

Just to recap: this is needed when publishing node modules. To be available from browserify `require()`, a node module need to be "exported" on `module.exports`. [If you want to read about it](https://quickleft.com/blog/creating-and-publishing-a-node-js-module/).

**Comment by nadako** [comment] 2016-04-26 13:06
Am I understanding correctly that browserify doesn't provide the [exports alias](https://nodejs.org/api/modules.html#modules_exports_alias), unlike node.js?

**Comment by nadako** [comment] 2016-04-26 13:14
>> But @:expose always assigns a property, so nothing wrong.

> @mcheshkov what do you mean by that?

In node.js, `exports` is the same as `module.exports` unless you reassign it, but Haxe doesn't reassign it, it instead sets its properties (i.e. `exports.foo = ...`), so the object stays the same and there's no problems, at least with node.js.

**Comment by zabojad** [comment] 2016-04-26 16:21
@nadako OK for the node.js context... But if you use npm for importing modules that will be used with browserify or equivalent, the module has to "expose" on `module.exports`. Actually, any lib packaged as an NPM module and used in the browser seems to expose on `module.exports`...

> Am I understanding correctly that browserify doesn't provide the exports alias, unlike node.js?

That's probably a way to say it ^^...

Maybe `@:expose` could expose on `module.exports` instead of `exports`?

**Comment by nadako** [comment] 2016-04-26 16:23
> Maybe @:expose could expose on module.exports instead of exports?

Well, yeah that makes sense, however I'll have to think if this can break something or not...

**Comment by zabojad** [comment] 2016-04-26 16:42
@nadako actually, now that I'm thinking about this issue, I think it doesn't come from browserify as [its doc says it supports both `exports`and `module.exports`](https://github.com/substack/node-browserify#example).

It's rather that when executing in the browser, the `typeof window != "undefined" ? window : exports` test returns `window` whereas in this specific context (browser + browserified code) we would like `exports`(that would work actually).

So we need one of both:
 - a way to detect we are in the browser with browserified code,
or
 - a way to tell the `@:expose` metadata that we are in the browser with browserified code and thus generate this:
```
(function (console, $hx_exports) { "use strict";
// blablabla
})(typeof console != "undefined" ? console : {log:function(){}}, exports);
```

What do you think?

**Comment by nadako** [comment] 2016-04-26 16:46
Hmm, that makes it a duplicate of #4524. Looks like we decided to just invert that check, so `exports` has more priority than `window`.

I'll close this issue then, feel free to comment in that issue.

**Closed by nadako** 2016-04-26 16:46 UTC
Labels: platform-javascript

**Comment by zabojad** [comment] 2016-04-27 09:55
Indeed, I think that would solve this. Thanks @nadako!
