### ISSUE TITLE
[C++] Crash when referencing deserialized enum

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#5943] opened 2017-01-17 01:11 UTC
A test case and more details are available in this link:

http://community.openfl.org/t/building-freezing-on-windows-build-with-embedded-font/8666/6

This occurs when trying to reference a value from an `Array<ShapeCommand>` (`ShapeCommand` is an enum with multiple constructors)

This works properly with the newest Haxe 3.4 dev build I have in Neko, and works in Neko/C++ on Haxe 3.2.1, but crashes on C++ with the latest I have.

FWIW, the array is deserialized using `haxe.Unserializer`, the contents are serialized on Neko. The "array.length" returns properly, but referencing "array[i]" crashes

The generated code looks like this:

```
::openfl::_internal::swf::ShapeCommand command = _g5->__get(_g4).StaticCast<  ::openfl::_internal::swf::ShapeCommand >();
```

I believe it's that `__get` call that fails 😦

**Comment by Simn** [comment] 2017-01-17 07:47
@hughsando: I'll check it out too but I think this is yours.

**Comment by hughsando** [comment] 2017-01-24 06:22
The problem is coming from the fact that serialization does not store the type of array it is serializing.
Normally this work ok, because then the value is fixed when it is cast into the correct format.
This breaks down when cast is hidden inside an array, since array casts are not "deep". Here is a simple example:
```
enum E { Val; }

class Test
{
   public var array2D:Array<Array<E>>;

   public function new()
   {
      array2D = [[Val]];
   }

   public static function main()
   {
      var stream = haxe.Serializer.run( new Test() );
      var test:Test = haxe.Unserializer.run(stream);
      trace(test.array2D[0][0]);
   }
}
```
The Dynamic that gets assigned to array2D is an "Array of  VirtualArray", not an "Array of Array<Object>" but the assignment only sees "Array of Object" and it thinks all is good.

I can probably fix this case, since the array type can be guessed from the first element.  This would still break down on an empty array (is it an empty array of int/floats/bools ?).
I suspect that other strongly-typed targets - eg HL, would have this problem too.
I think there is also a subtle problem with numeric types there too, but there are some checks that happen around them to avoid things.

The best for for cpp would be to encode the array type before the elements not sure that the other targets would think of that.  There would still be an underlying problem with deep arrays and casts that could be abused by Dynamic, so maybe I can address that, but I worry about performance.

**Comment by ncannasse** [comment] 2017-01-24 20:46
@hughsando FYI that works correctly with HL, since we only have specialized arrays for some numeric types, not for enums which are wrapped as Dynamic when inserted into an Array. I think that you should either have enums which carry their runtime type OR that gets boxed when cast to Dynamic. Leaving it to the Array to know which kind of enum it contains seems too weak to work correctly with Haxe.

**Closed** 2017-01-25 05:10 UTC
Labels: platform-cpp, regression

**Comment by hughsando** [comment] 2017-01-25 05:19
The problem is not with enums specifically (any object would cause the
problem).
It is because c++ thinks it is an Array-of-Array-of-Dynamic   (with
Dynamic=enum in this case, like HL)  but the deserialization stores and
Array-of-Array-Of-VirtualArray (which happens to contain objects).  Does HL
use virtual arrays?  If so, at what point does this deserialization get
converted to the correct representation - and similarly for
array-of-array-of int.  If this were stored in array-of-array-of-Dynamic,
at what point would this get converted?  Is it on the first assign from
Dynamic to strictly typed? ie, if [[[[[[[[1]]]]]]] was stored in
Array<Array<.....<Dynamic>....>>, does this generate a conversion of some
type?

**Comment by ncannasse** [comment] 2017-01-25 20:24
There is no type parameter at runtime in HL, but you have several kind of arrays : "ArrayDyn", and "ArrayBase" . You can have two kind of ArrayBase : "ArrayObj" (Array of typed object) and "ArrayBytes_xxx" (which are specialized arrays of memory aligned basic types)

So when unserializing you create an ArrayDyn which holds an ArrayBase , which itself holds ArrayDyns which are holding ArrayBases, so you have 2 extra levels of indirection.

When casting such an ArrayDyn to ArrayObj, we eventually convert the ArrayObj to an ArrayBytes if we cast to Array of Int for instance, or else we keep the ArrayObj and freeze the ArrayDyn to prevent further casting. So casting an ArrayDyn to a "real Array" is only possible once.

In that example we first cast/unwrap the first level of ArrayDyn to an ArrayObj when assigning the "array2D" value in the unserializer. Then upon each read we will cast its content from ArrayDyn to ArrayObj.

**Comment by hughsando** [comment] 2017-01-30 05:02
Yes, I guess it is the unavoidable? runtime check when unpacking an Array
element that haxe says in an array of a particular type - we can't trust
the type directly, since it might actually be a ArrayDyn. I had this check
in for "byte based" arrays, but needed to add the check objects once I
changed the ArrayDyn representation.
I think this is the only area where we can't trust the haxe typing.
