### ISSUE TITLE
--times missing something

### ISSUE THREAD

**Issue by thomasuster** [HaxeFoundation/haxe#6456] opened 2017-07-16 12:36 UTC
When using --times on my project it reports...

```
name                     | time(s) |   % |  p% |      # | info
---------------------------------------------------------
generate                 |   4.690 |  39 |  39 |      2 | 
  cpp                    |   4.690 |  39 | 100 |      2 | 
parsing                  |   1.990 |  17 |  17 |   4340 | 
typing                   |   1.790 |  15 |  15 |   7714 | 
macro                    |   1.460 |  12 |  12 |    472 | 
  jit                    |   0.010 |   0 |   1 |    416 | 
analyzer                 |   0.990 |   8 |   8 | 133801 | 
filters                  |   0.960 |   8 |   8 |      9 | 
other                    |   0.180 |   1 |   1 |      1 | 
---------------------------------------------------------
total                    |  12.060 | 100 | 100 | 146339 | 
```

When I time it with a stop watch it's taking ~27 seconds. So I would expect the total (12.060) to instead say 27.000 or so.

**Comment by thomasuster** [comment] 2017-07-16 12:37
PS, on haxe 3.4.2 my build took 41 seconds, and now in latest it's ~27 seconds. Thank you for whoever did that!

**Comment by ibilon** [comment] 2017-07-16 14:00
If by chance you are on linux (maybe mac) could you try adding the time command in front of your haxe command? (`time haxe --times -main ...`)

Maybe the total time is in actual cpu time which doesn't take into account when the process isn't doing anything (such as waiting on io).

**Comment by thomasuster** [comment] 2017-07-17 21:43
```
name                     | time(s) |   % |  p% |      # | info
---------------------------------------------------------
generate                 |   4.480 |  38 |  38 |      2 | 
  cpp                    |   4.480 |  38 | 100 |      2 | 
parsing                  |   2.080 |  18 |  18 |   4340 | 
typing                   |   1.870 |  16 |  16 |   7714 | 
macro                    |   1.310 |  11 |  11 |    472 | 
  jit                    |   0.020 |   0 |   2 |    416 | 
filters                  |   0.980 |   8 |   8 |      9 | 
analyzer                 |   0.940 |   8 |   8 | 133801 | 
other                    |   0.210 |   2 |   2 |      1 | 
---------------------------------------------------------
total                    |  11.870 | 100 | 100 | 146339 | 

real	0m24.968s
user	0m28.312s
sys	0m3.462s
```

**Comment by nadako** [comment] 2017-07-17 21:48
And I thought it's something wrong with my perception of time :)

**Comment by jcward** [comment] 2017-07-19 15:00
Ha, I've noticed the same thing: https://twitter.com/Jeff__Ward/status/852228740658733058

I assume it's some sort of IO / blocking / wait time? But I wonder why `--times` doesn't include it. You'd think it should measure based on real, wall-clock timestamps.

**Comment by ncannasse** [comment] 2017-07-19 20:00
We are using times() to measure the time on Linux, which is the current
process CPU time. It allows us to measure it accurately even when other
processes are running which might take some slice of time due to scheduling.
We should eventually have both CPU and "realtime" measure to calculate
kernel/IO.
I'm very surprised however you're having over 10 s of I/O, are you
compiling from a network drive or a 5"25 floppy disk by any chance?

**Comment by thomasuster** [comment] 2017-07-19 20:52
@ncannasse I'm surprised as you are I suppose. But then again water boils faster when you're not watching. Yes, the build time is frustrating. I'd like to optimize, so tracking down these extra 10 seconds seems important. This is my machine. No network drive or floppy disk. ;-)

![screen shot 2017-07-19 at 10 49 04 pm](https://user-images.githubusercontent.com/220965/28389005-c7dff696-6cd4-11e7-8ccf-58a5d61666d0.png)

**Comment by ousado** [comment] 2017-07-20 14:31
For some reason it doesn't seem to correctly measure the "native compilation" part
https://github.com/HaxeFoundation/haxe/blob/development/src/generators/gencpp.ml#L8256 

Compiling some smallish program for the first time (no cached files):
```
name                     | time(s) |   % |  p% |    # | info
-------------------------------------------------------
parsing                  |   0.050 |  71 |  71 |   55 |
generate                 |   0.010 |  14 |  14 |    2 |
  cpp                    |   0.010 |  14 | 100 |    2 |
typing                   |   0.010 |  14 |  14 |    1 |
-------------------------------------------------------
total                    |   0.070 | 100 | 100 | 1413 |

real    0m31.012s
user    0m45.020s
sys     0m3.288s
```
The above clearly excludes the native "compilation" part altogether. 

random subsequent run:
```
name                     | time(s) |   % |  p% |    # | info
-------------------------------------------------------
parsing                  |   0.040 |  57 |  57 |   55 |
generate                 |   0.010 |  14 |  14 |    2 |
  cpp                    |   0.010 |  14 | 100 |    2 |
    native compilation   |   0.010 |  14 | 100 |    1 |
filters                  |   0.010 |  14 |  14 |    9 |
typing                   |   0.010 |  14 |  14 |    1 |
-------------------------------------------------------
total                    |   0.070 | 100 | 100 | 1413 |

real    0m0.185s
user    0m0.152s
sys     0m0.020s
```

**Comment by jcward** [comment] 2017-07-20 15:09
@ousado - ah, my quick test agrees. The 'native compilation' line item is totally wrong for the hxcpp target.

I've seen this before in my JS project, but I'm not seeing it now, so I'll have to report back if I ever see it again and can create a reproducible testcase.

**Comment by ousado** [comment] 2017-07-20 15:35
The timer there uses `Common.get_time` which uses `times` which only measures the time spent by the calling process. So clearly not the right tool to time the native compilation part.

**Comment by ncannasse** [comment] 2017-07-20 20:22
Looks like it's a difference with Windows, which does measure the native
compilation part.
On Windows we're using QueryPerformanceCounter which is absolute time (ie
includes I/O and other processes)

**Comment by thomasuster** [comment] 2017-07-24 16:28
@ncannasse Where is the code using QueryPerformanceCounter? I can't find it in the haxe repo.

**Comment by Simn** [comment] 2017-07-24 16:32
It's in the ocamllibs submodule: https://github.com/HaxeFoundation/ocamllibs/blob/dcd31f270aa5e770d7e8af068a0a45d9e076386b/extc/extc_stubs.c#L471

**Comment by thomasuster** [comment] 2017-07-24 16:44
@Simn Thank you. So would it work to edit that file with something like this? https://developer.apple.com/library/content/qa/qa1398/_index.html

**Comment by jcward** [comment] 2017-07-24 17:06
While I'm not vehemently against custom OSX code, fixing the POSIX implementation will be necessary for Linux anyway.

Looking at [this quickly](https://stackoverflow.com/a/23097691/1026023), maybe we need to be adding child process times also, e.g.

```
return caml_copy_double( ((double)(t.tms_utime + t.tms_stime + t.tms_cutime + t.tms_cstime)) / CLK_TCK );
```

**Comment by jcward** [comment] 2017-07-24 19:06
Scratch that - that didn't work, it's now reporting much too high:

![image](https://user-images.githubusercontent.com/2192439/28539980-dea869ae-7070-11e7-9fbd-b0300b490516.png)

**Comment by thomasuster** [comment] 2017-07-25 17:59
Hey, I think I might have a fix.

It's a submodule fix, don't know how to make it one PR, so I just did 2.

https://github.com/HaxeFoundation/haxe/pull/6466/files
https://github.com/HaxeFoundation/ocamllibs/pull/25

This reports this, which seems about right.

```
name                     | time(s) |   % |  p% |      # | info
---------------------------------------------------------
generate                 |  19.722 |  70 |  70 |      2 | 
  cpp                    |  19.722 |  70 | 100 |      2 | 
    native compilation   |  14.970 |  53 |  76 |      1 | 
parsing                  |   2.836 |  10 |  10 |   4340 | 
typing                   |   1.998 |   7 |   7 |   7714 | 
macro                    |   1.599 |   6 |   6 |    472 | 
  jit                    |   0.008 |   0 |   0 |    416 | 
  add_types              |   0.007 |   0 |   0 |      9 | 
filters                  |   1.133 |   4 |   4 |      9 | 
analyzer                 |   0.810 |   3 |   3 | 133801 | 
other                    |   0.221 |   1 |   1 |      1 | 
---------------------------------------------------------
total                    |  28.319 | 100 | 100 | 146339 | 
```

**Comment by jcward** [comment] 2017-07-25 18:17
FYI, left [a comment](https://github.com/HaxeFoundation/ocamllibs/pull/25#issuecomment-317823747) on the PR -- for Linux I had to add `#include <time.h>` but then it worked.

**Comment by thomasuster** [comment] 2017-07-25 18:25
Cool, added

**Comment by jcward** [comment] 2017-07-25 18:53
So I think this fix is using "real wall clock time". @ncannasse stated above that the use of CPU tick time is intentional:

> It allows us to measure it accurately even when other processes are running which might take some slice of time due to scheduling.

I wonder if my experiment with `tms_cutime + tms_cstime` did actually work, but didn't account for the fact that the cpp compiler is run in a multi-threaded way, so that at any given time up to 8 processes are running at once. So maybe it actually did use 90 seconds worth of CPU ticks (but many simultaneously):

![image](https://user-images.githubusercontent.com/2192439/28588546-26b8f368-7138-11e7-8178-aa9c22cccc4a.png)

I wonder how "CPU tick time" schema typically deals with multi-threaded child processes.

**Comment by jcward** [comment] 2017-07-26 19:31
Ah ha, I believe my hunch is verified. With `tms_cutime + tms_cstime` it really is 90 CPU seconds in 19 wall clock seconds shown above. Because I can force hxcpp to use only 1 compile thread, and then the reported CPU time == wall time:

`> time haxe Test.hx -cpp out --times -D HXCPP_COMPILE_THREADS=1`

![image](https://user-images.githubusercontent.com/2192439/28639704-53451bc2-7206-11e7-8ae9-a383c72e2c6a.png)

**Comment by Simn** [comment] 2017-08-02 07:43
I've merged @thomasuster's PR, so this should be good now?

**Closed by Simn** 2017-08-02 07:43 UTC
