### ISSUE TITLE
[jvm] functions from superclass/interface lost

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#9768] opened 2020-07-27 12:21 UTC
fa7cea9

```haxe
import java.nio.channels.AsynchronousFileChannel;

class Main {
	static function main() {
		var channel:AsynchronousFileChannel = null;
		channel.close(); // ERROR: java.nio.channels.AsynchronousFileChannel has no field close
	}
}
```

ref: https://docs.oracle.com/javase/7/docs/api/java/nio/channels/AsynchronousChannel.html#close()

**Comment by Simn** [comment] 2020-07-27 13:09
Hmm yes, the problem is that we don't look at extern classes, so we don't do this abstract-interface-inheritance thing...

I wonder if we should do this lazily instead while resolving the field. If we try to access a field on an extern abstract class and we can't find it, we can recurse into its interfaces to look for it there. We can then even cache it onto the class itself, so the next time it is found immediately. I think this is overall better than trying to verify all extern abstract classes.

**Comment by Simn** [comment] 2020-07-27 13:15
Actually, in the case of Java we might want to do this for non-abstract (but still extern) classes as well in order to deal with default interface implementations. That requires marking those in the JAR loader, but that shouldn't be an obstacle.

**Closed as completed** 2020-07-28 14:17 UTC
Labels: platform-jvm

**Comment by Simn** [comment] 2020-07-28 14:19
I've made this a bit dumber than described: We simply browse all implemented interfaces on extern lib-types and return the field if we find it. Since we're not interested in the validity of these extern definitions, we can just assume that the class implementing such interfaces really does have the fields in question.
