### ISSUE TITLE
Escaped quotation mark inside string interpolation fails to compile

### ISSUE THREAD

**Issue by GHanehoj** [HaxeFoundation/haxe#10463] opened 2021-11-01 12:20 UTC
The following construction should be valid, but gives a compile error:
```
var a = '${'\''}';
```
```
character 20 : Unterminated string
```

**Comment by Aurel300** [comment] 2021-11-01 13:46
Duplicate of #2244.

**Closed as completed by Aurel300** 2021-11-01 13:46 UTC
