### ISSUE TITLE
Invalid position

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8527] opened 2019-07-10 12:16 UTC
The following code fails to parse with a weird error message:

```haxe
typedef Float32Array = js.html.Float32Array;
typedef Uint16Array = js.html.Uint16Array;

class Main {
	static function main() {
		var buffer = switch( Std.random(3) ) {
		case 0: new Float32Array();
		case 1: new Uint16Array();
		default: null;
		}

}
```

`Main.hx:12: characters 2-4611686018427387643 : Expected }`

**Comment by RealyUniqueName** [comment] 2019-07-10 12:24
Missing a closing `}` for the function :)

**Comment by nadako** [comment] 2019-07-10 12:24
Well the issue is a bout crazy position

**Comment by RealyUniqueName** [comment] 2019-07-10 12:25
Oh, weirdness is in error position

**Comment by RealyUniqueName** [comment] 2019-07-10 14:12
reduced
```haxe
class Main {
	static function main() {
}
```

**Closed as completed** 2019-07-10 14:27 UTC
