### ISSUE TITLE
Backwards incompatible changes between 4.3.1 and 4.3.2 

### ISSUE THREAD

**Issue by 0b1kn00b** [HaxeFoundation/haxe#11314] opened 2023-09-20 11:02 UTC
Word to the wise, a point release isn't supposed to break compatibility.

https://github.com/HaxeFoundation/haxe/blob/c0d033d25d1876b563423a34d01a12f882f3e2b2/std/haxe/macro/Expr.hx#L1007

**Comment by kLabz** [comment] 2023-09-20 11:05
Duplicate of #11307

**Closed as not planned by kLabz** 2023-09-20 11:05 UTC

**Comment by 0b1kn00b** [comment] 2023-09-20 11:10
whoops, sorry.

**Comment by kLabz** [comment] 2023-09-20 11:12
Np, my bad for introducing that :/
