### ISSUE TITLE
[php] syntax error, unexpected '::'

### ISSUE THREAD

**Issue by TzA-0x000000001** [HaxeFoundation/haxe#6155] opened 2017-04-04 09:57 UTC
Hello.
When I import classes that are not included in any package, I have this error: 
> Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting variable (T_VARIABLE) or '$'

It happens when I have a code like that : 

**Main.hx**
```haxe
package;
import Foo;
class Main {
    static public function main() {
        Foo.bar();
    }
}
```

**Foo.hx**
```haxe
package;
class Foo {
    statuc public function bar() {
        trace("bar");
    }
}
```

**Folder**
```
My Project
| -- Main.hx
| -- Foo.hx
```
---
To solve it, I have to do: 

**Main.hx**
```haxe
package;
import some.Foo;
class Main {
    static public function main() {
        Foo.bar();
    }
}
```

**Foo.hx**
```haxe
package some;
class Foo {
    statuc public function bar() {
        trace("bar");
    }
}
```

**Folder**
```
My Project
| -- Main.hx
| some
  | -- Foo.hx
```

Thank you for you attention.

**Comment by RealyUniqueName** [comment] 2017-04-04 10:39
Do you compile with or without `-D php7`?

**Comment by TzA-0x000000001** [comment] 2017-04-04 15:30
I compile without. Is it a problem ? If so, I have to check if my host is supporting php 7.

**Comment by RealyUniqueName** [comment] 2017-04-04 15:36
It's not a problem. I just need to know your setup to reproduce this issue.

**Comment by RealyUniqueName** [comment] 2017-04-04 15:54
Also wich haxe version do you use?

**Comment by RealyUniqueName** [comment] 2017-04-05 20:45
@TzA-0x000000001 I can't reproduce this issue neither with Haxe 3.4.2 nor with latest development version.

**Comment by TzA-0x000000001** [comment] 2017-04-23 11:47
@RealyUniqueName Sorry. I had some issues. I use Haxe 3.4.2 on Windows, from the official package.

**Comment by RealyUniqueName** [comment] 2017-04-26 05:09
What's your hxml setup?

**Comment by RealyUniqueName** [comment] 2017-06-13 18:45
I'm closing this because i can't reproduce it. Feel free to reopen if it still exists.

**Closed by RealyUniqueName** 2017-06-13 18:45 UTC
Labels: platform-php
