### ISSUE TITLE
[Feature request] List of all compiler exceptions in cli-docs

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxe#4351] opened 2015-06-19 11:29 UTC
Will be great if we will have a complete list of all possible exceptions of compiler (e.g.: [1], [2], [3], [4]).

### Exceptions

It need in documentation via `$ haxe --help-exceptions` -> returns parsable list like this:

```
text of error (pattern)                                             | [list-of-keywords] | comment about what & when it can be thrown
The macro accessor is not allowed for field resolve                 | macro              | description
Catch type must be a class, an enum or Dynamic                      | all                | description about try-catch-block
Local variable {name} is preventing usage of this type here         | all                | comment / description
Field {name} cannot be called directly because it has no expression | ...                | ...
Some static-target-only error                                       | cpp, flash         | comment / description
```
Here `[list-of-keywords]` is a list of keywords like target-platforms or when/where we can get exception. For example possible values can be `macro`, `cpp`, `neko`, `java`,..
It will be cool for filtering errors and work with it in IDEs.

### Warnings

Also list of warnings (e.g.: [about loop](https://github.com/HaxeFoundation/haxe/blob/development/typer.ml#L4194)) too:
`$ haxe --help-warnings`
```
text of warning (pattern)                         | [list-of-keywords] | comment about what & when it can be thrown
Warning : maybe loop in static generation of {tp} | all, macro         | ...
```

- - -

Also will be cool if std contains classes/enums/typedefs what describing macro-state-exceptions.

[1]: https://github.com/HaxeFoundation/haxe/blob/development/typer.ml#L1428
[2]: https://github.com/HaxeFoundation/haxe/blob/development/typer.ml#L3293
[3]: https://github.com/HaxeFoundation/haxe/blob/development/typer.ml#L3305
[4]: https://github.com/HaxeFoundation/haxe/blob/development/typer.ml#L3313

**Comment by Simn** [comment] 2015-06-19 11:38
The problem is that in many cases you can't properly describe the error messages like this. What I would prefer to do instead is to enumerate/identify them so that they can easily be looked up in the manual or via google.

Examples:

HXE0200: The macro accessor is not allowed for field resolve
HXE0345: Field {name} cannot be called directly because it has no expression
HXW0002: maybe loop in static generation of {tp}

But even that is going to be a lot of work to get right.

**Comment by fzzr-** [comment] 2015-06-19 11:47
@Simn Cool. Your example is :+1: in case if we will have men-readable listing in manual __and__ parsable listing too.

Mb. improve:
`HXW0002: maybe loop in static generation of {tp} {position}` because `position` isn't exists in all exceptions.

**Comment by nadako** [comment] 2015-06-19 12:59
That looks a bit microsoft-ish, but I tend to agree it's very useful for googling/stackoverflowing.

**Comment by Simn** [comment] 2015-11-28 10:41
I had a look at this and implemented a quick demo on this branch: https://github.com/Simn/haxe/tree/enumerated_errors

However, this work is too dull even for me. If someone wants to turn this into a community effort I'd be willing to help, but otherwise I don't think we'll see any major change here.

**Comment by Simn** [comment] 2016-01-17 18:11
I'll go ahead and close this because while it's "nice to have" it's also pretty much "not gonna happen".

**Closed by Simn** 2016-01-17 18:11 UTC
