### ISSUE TITLE
"Unsupported regexp option 'u'" in macro

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#2546] opened 2014-01-18 23:48 UTC
This works in haxe 3.0, but does not in current git. Interestingly enough, the `reg_lib` in `interp.ml` that contains this error has not changed since 3.0.

Should the `u` flag work in macros? It's neko after all.

``` haxe
class Main
{
    static function test()
    {
        var r = ~/l.l/u;
        trace(r.match("lol"));
    }
}
```

```
-cp src
--macro Main.test()
```

**Comment by ncannasse** [comment] 2016-12-14 20:49
Duplicate of #1775

**Closed by ncannasse** 2016-12-14 20:49 UTC
