### ISSUE TITLE
Regression: in enum abstracts this no longer can be matched against values.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#8862] opened 2019-10-03 09:34 UTC
```haxe
@:enum abstract Volume(String) {
  var Loud = "loud";
  var Quiet = "quiet";
  public function beep()
    trace(switch this {
      case Loud: 'BEEP';// --> Volume should be String
      default: 'beep';
    });
}
```

In from haxe3 to haxe4 rc.3 this compiled fine. The new behavior is arguably more correct, but quite impractical.

**Comment by Gama11** [comment] 2019-10-03 09:40
https://github.com/HaxeFoundation/haxe/issues/8579

**Comment by Gama11** [comment] 2019-10-03 10:08
(so, not a regression, since it was an intentional change, but I guess it's debatable whether it really leads to nicer code)

**Comment by nadako** [comment] 2019-10-03 10:24
I guess this should be properly fixed with https://github.com/HaxeFoundation/haxe-evolution/pull/62?

**Comment by markknol** [comment] 2019-10-03 10:31
Shouldn't this be `switch (this:Volume)`?

**Comment by Gama11** [comment] 2019-10-03 10:40
@markknol That only works if the abstract allows implicit conversions, which might not be desirable. So you have to resort to casting (`switch (cast this : Volume)`).

**Comment by markknol** [comment] 2019-10-03 10:49
You are right, I forgot the `cast`.

**Comment by RealyUniqueName** [comment] 2019-10-03 10:57
I agree new behavior is correct and we should stick to it.
Practicality will be restored with that evolution nadako has mentioned.

**Comment by Simn** [comment] 2019-11-04 09:06
This is something to document at https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-4.0.0

**Comment by RealyUniqueName** [comment] 2019-11-04 09:30
Check if this makes sense: https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-4.0.0#switching-on-this-in-member-methods-of-enum-abstracts

**Comment by Simn** [comment] 2019-11-04 09:40
Yeah, but I suppose we should suggest how to fix that.

**Comment by RealyUniqueName** [comment] 2019-11-04 10:35
Added a suggestion to use untyped cast + checktype

**Comment by Simn** [comment] 2020-06-04 14:21
This has been documented, so we can close here.

**Closed as completed by Simn** 2020-06-04 14:21 UTC
Labels: documentation

**Comment by AG-w** [comment] 2020-11-28 11:01
https://haxe.org/manual/types-abstract-enum.html
I'm not trying to necropost but maybe you should also add explanation in "since Haxe 4.0.0" part?
so newcomer actually know to put "cast" at enum abstract

**Comment by RealyUniqueName** [comment] 2020-11-28 12:02
This case is not covered by that page. And the new behavior is actually more consistent since `this` is of an underlying type inside of abstract methods.

**Comment by AG-w** [comment] 2020-11-29 18:55
I mean if you use a string enum abstract to put in a method that need string, the compiler will just reject it
This is first time I know that you need "cast" to use enum abstract in a method when I read this
for example
```
enum abstract Textual(String)
{
	var FirstCase; // implicit value: "FirstCase"
	var AnotherCase; // implicit value: "AnotherCase"
}
function showString(str:String)
{
	trace(str);
}
```
if you use `showString(Textual.FirstCase)` without casting It will just give you "Textual should be String" error

There's no mention of cast in Manual and It even say "the values for the enum cases can be omitted and are deduced by the compiler"

**Comment by Simn** [comment] 2020-11-29 19:02
This is about declaration and tells you that you can omit the `= "FirstCase"` now. It has nothing to do with how the values are assignable to types, which is a completely different concept.

**Comment by AG-w** [comment] 2020-11-30 05:43
I use enum abstract because it literally said // implicit value: "FirstCase"
The answer I got from google is people wonder why it isn't working and they just Std.string() it

**Comment by markknol** [comment] 2020-11-30 10:35
@AG-w I think you are looking for `enum abstract Textual(String) to String { .. }`, this allows it being cast to a String without wrapping it in `Std.string`.

**Comment by AG-w** [comment] 2020-12-07 08:25
oh thank you markknol.
now I can get rid of all the casting and use them like haxe 3
