### ISSUE TITLE
Duplicate properties being generated

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#3156] opened 2014-06-30 22:36 UTC
There's a strange issue over at aduros/flambe#264 that appears to be compiler related.

Could there be some corner case that would cause cl_ordered_fields to contain duplicates?

**Comment by Simn** [comment] 2015-02-22 09:58
I still don't know what to do with this. What's particularly puzzling is that the duplicates appear only in `__properties__` and not actually in the class fields themselves which should be the case if `cl_ordered_fields` had duplicate entries.

Another problem is that we can't even be sure if the issue still persists on current Haxe because it originally occurred in 3.1.3. Unless someone goes ahead and reproduces this on the current development version I can't see how we would address this for the 3.2 release.

**Comment by ncannasse** [comment] 2015-02-22 21:49
Yes, I fail to see how this can be reproduced, spent some time on it already last time.

**Comment by Simn** [comment] 2015-05-15 17:39
I'll close this now because I have no idea what else to do with it.

**Closed by Simn** 2015-05-15 17:39 UTC
