### ISSUE TITLE
Reflect.callMethod unit tests

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7106] opened 2018-05-29 11:42 UTC
There seems to be some discrepancies between targets regarding to handling of Reflect.callMethod, especially when involving closures and switching the object.

We need to improve our unit tests for it and strengthen the specification about what is allowed or not, and eventually do some platform-specific fixes to adhere to it.

**Comment by Simn** [comment] 2018-05-29 11:51
I've been wanting to ask about this as well:

```haxe
class Main {
	static public function main() {
		var main1 = new Main(1);
		var main2 = new Main(2);
		trace(Reflect.callMethod(main1, main2.getI, [])); // 1 or 2?
		trace(Reflect.callMethod(main1, Reflect.field(main2, "getI"), [])); // 1 or 2?
	}

	var i:Int;

	function new(i:Int) {
		this.i = i;
	}

	function getI() {
		return i;
	}
}
```

**Comment by aliokan** [comment] 2018-05-29 13:50
really interesting result on JS and neko target ^^ http://try-haxe.mrcdk.com/#4d615

**Comment by RealyUniqueName** [comment] 2018-05-29 14:18
PHP7 generator traces `1` in both cases.

**Comment by ncannasse** [comment] 2018-05-29 15:29
More seriously - do we some targets that creates native closures automatically and on which we don't have access to the function pointer or any other way to swap the object ?

If the answer is no, then we should specify as 1 the result in both.

There's additional thinks to deal with, such as static method calls:

```haxe
class Main {
     static function foo() {
        return 33;
     }
     static function main() {
           Reflect.callMethod(null,foo,[]) == 33;
           Reflect.callMethod(Main,foo,[]) == 33;
           Reflect.callMethod(Type,foo,[]) == 33; // ?
     }
}
```

**Comment by Simn** [comment] 2018-05-29 15:36
In case of static functions, the first argument should simply be ignored. There's no context for static functions, so the context provided should be insignificant.

**Comment by Simn** [comment] 2018-05-29 15:38
Oh and I agree that `1` is correct(er) for the other situation. I'll add a test on a branch to see how many targets disagree.

**Comment by RealyUniqueName** [comment] 2018-05-30 16:46
> Php: dies on the static test with all_user_func_array() expects parameter 1 to be a valid callback, class 'Type' does not have a method 'foo'

Fixed

**Comment by ncannasse** [comment] 2018-06-05 19:38
I think it will be hard to ensure one single specification in case we have a closure created. I think it's not possible for instance in Flash/AS3, but maybe we should try to enforce it on as much platforms as possible.

@waneck would it possible to extract the closure function without its object value so that simon tests pass on C# and Java ?

@hughsando can you look into making the tests pass on hxcpp?

Someone for python ?

**Comment by ncannasse** [comment] 2018-06-21 07:30
Related discussion in #6276 : we need to test also for optional arguments support (both with default value and nullable)

**Comment by frabbit** [comment] 2018-09-05 09:33
seems tricky in python didn't found a way yet.

**Comment by Simn** [comment] 2018-09-06 12:51
Updated the branch to see what's going on:

* [x] **neko** fails, but assume wontfix
* [x] **eval**, **hl**, **php**, **c++** pass
* [ ] **js**, **lua**: `src/unit/issues/Issue7106.hx:19: 1 should be 2`
* [ ] **flash**, **as3**, **java**, **cs**, **python**: ```src/unit/issues/Issue7106.hx:19: 1 should be 2
src/unit/issues/Issue7106.hx:20: 1 should be 2```

**Comment by Simn** [comment] 2018-09-09 15:35
hxcpp confirmed fixed!

**Comment by ncannasse** [comment] 2018-09-09 20:23
@Simn could you check that the 3 Reflect.callMethod HL issues I referenced before are covered by unit tests ?

**Comment by Simn** [comment] 2018-09-18 08:22
> @Simn could you check that the 3 Reflect.callMethod HL issues I referenced before are covered by unit tests ?

Uhm, I didn't process this message 9 days ago and now I have no idea what you're talking about...

**Comment by Simn** [comment] 2018-09-18 11:31
Closing in favor of #7442.

**Comment by ncannasse** [comment] 2018-09-18 12:57
@Simn I meant look at the following issues to see if the fixes they involved were cases covered/specified by unit tests : 
https://github.com/HaxeFoundation/hashlink/issues/152
https://github.com/HaxeFoundation/hashlink/issues/153
https://github.com/HaxeFoundation/hashlink/issues/154

**Comment by ncannasse** [comment] 2018-09-21 14:37
I have some problem with Reflect.callMethod, which i'm not sure how to address.

In HL , you can get a closure of `foo` over a value of type C in two ways:

```haxe
class C {
    function foo1() { trace(this); }
}
var x : C = ...;
x.foo1; // closure of foo1 with (x:C) pointer

// or 
var x : C = ...;
function foo2() trace(x); // closure of the function with (x:C) pointer "context" 
```

In terms of HL, both methods have the same bytecode, and can't be differentiated at runtime.
However, their behavior to Reflect.callMethod should differ. 

- Reflect.callMethod(anotherC, x.foo1, []) should switch the instance
- Reflect.callMethod(anotherC, foo2, []) should not switch instance (any ignore anotherC)

The second case can be reproduced using HScript by calling `o.foo()` on a value `o = { foo : function() return x; }`

**Comment by ncannasse** [comment] 2018-09-21 14:54
Actually, given my previous comment, maybe we should change specification using the following rule: 

- when a closure is created, its object cannot be swapped -> `eq(2, Reflect.callMethod(c1, c2.getI, []));` -- actually we could even ensure than `eq(2, Reflect.callMethod({}, c2.getI, []));` 
- some platforms have native closure support, which means that Reflect.field returns a closure instead of a "raw" method. The previous rule applies, so if it's a closure you get 2 on `eq(1, Reflect.callMethod(c1, Reflect.field(c2, "getI"), []));` , and if there's no closure created then you get 1

Any thoughts ?

**Comment by ncannasse** [comment] 2018-09-21 15:01
Ping @aliokan since you reported some rare `Reflect.callMethod` issues

**Comment by Simn** [comment] 2018-09-21 15:04
I find it weird that there's an explicit argument for the context which is ignored in almost all cases. I'm fine with it being ignored for statics simply because there is no context. But as soon as there is, an explicit context should become the context of the call.

Your proposal would be acceptable if the context was an optional argument at the end, but given that it is the first argument of `callMethod` I don't think it's correct.

**Comment by ncannasse** [comment] 2018-09-21 15:09
Well to my defense it was originally designed with object switchability in mind, hence the first argument. But looking at the platform status, it seems actually very hard to enable such think in many platforms. 

We could change the API by deprecating it and adding another one, but I can't come up with a better name than `callMethod`, so I prefer to leave with a method slightly strange wrt its first arg usage but well specified than the other way.

**Comment by RealyUniqueName** [comment] 2018-09-21 15:15
I agree it's better to deprecate `Reflect.callMethod()` as completely non-cross platform. One can use native API to achieve the same functionality on the platforms which support context replacing.

The better name is probably just `Reflect.call()`

**Comment by ncannasse** [comment] 2018-09-22 09:30
I have just pushed updated HL code that does follow the rules I stated before.

In HL case, since closure are always created when accessing a class method, it means that the `obj`  parameter of `Reflect.callMethod` is entirely ignored. However in JS and some other platforms since we don't have native closure creation it means that the `obj` value is mandatory if the function was accessed using reflection/Dynamic.

So in order to keep cross platform behavior I think it's better to always require the `obj` parameter even if it's not used in some implementations. We should just forbid it to be switched if it's already been set by a closure creation as I stated previously.

@Simn could you update the unit tests PR accordingly so we know which platforms need fixes?

**Comment by Simn** [comment] 2018-09-22 15:28
I'm concerned about this because it quietly changes behavior. Also, I'm not sure if we should punish the targets that can switch context just because some other targets cannot switch context. Given that we cannot achieve full consistency here anyway, I'm not convinced that your proposed change would be an improvement.

Given that users have to be aware of the semantics here anyway, why not simply document `callMethod` accordingly and support context switching where we can?

**Comment by ncannasse** [comment] 2018-09-22 17:08
According to your tests all the following platforms already follow the rule I stated:
js, lua, flash, as3, java, cs, python 
We can also add hl and eval which were not in Haxe 3
And I think hxcpp changed it recently to match the tests, so I think only neko did follow the previous behavior it seems...

**Comment by Simn** [comment] 2018-09-23 08:07
Right, I thought hxcpp used to match neko here. But you're right that it was failing the test until it was fixed recently.

I'm not sure how PHP used to behave, but that's fine. So the only potential problem is macros, and that's fine as well because it's an entirely new target anyway.

**Comment by Simn** [comment] 2018-09-23 08:42
Let's continue this in #7442.

**Closed by Simn** 2018-09-23 08:42 UTC
Labels: platform-lua

**Comment by hughsando** [comment] 2018-09-25 14:23
Maybe we should have Reflect.callMethodByName(obj,"fieldName",...).  I actually thought this is how it worked at first.  This should work the same on all targets.

**Comment by Simn** [comment] 2018-09-25 14:27
> Maybe we should have Reflect.callMethodByName(obj,"fieldName",...). I actually thought this is how it worked at first. This should work the same on all targets.

Yeah I always thought that's how it worked too. Fortunately it's not that much of an issue anymore now that `func` is typed as `haxe.Constraints.Function`.

**Comment by nadako** [comment] 2018-09-25 17:25
> Fortunately it's not that much of an issue anymore now that `func` is typed as `haxe.Constraints.Function`.

Still, we could save some closure object allocations on e.g. C#/Java if we had `callMethodByName`. And `Reflect.callMethod(object, Reflect.field(object, methodName), args)` is probably the most common use case anyway.

**Comment by hughsando** [comment] 2018-09-26 00:29
Yes, I can't see any use-case for getting a non-dynamic closure (var.someField) and then calling it dynamically on some other variable.  The only reason you are using this is because you have a function name.  But can we get the name of the member from then closure for the targets that do not support this directly and just call the named field on the new object?

**Comment by ncannasse** [comment] 2018-09-26 12:40
We can add `Reflect.callField/callMethodByName` that takes a String, I'm not against it but that's a separate thing, I think we did good clarifying what current Reflect.callMethod does wrt object context.
