### ISSUE TITLE
Haxe 3.4.2. haxe.ds.WeakMap not implemented for JS, but the documentation says "Available on all platforms"

### ISSUE THREAD

**Issue by SlavaRa** [HaxeFoundation/haxe#6545] opened 2017-08-31 04:54 UTC
Documentation: http://api.haxe.org/haxe/ds/WeakMap.html
https://try.haxe.org/#C4a52

**Comment by ibilon** [comment] 2017-08-31 05:46
Duplicate of https://github.com/HaxeFoundation/haxe/issues/6540

**Comment by Simn** [comment] 2017-08-31 07:13
Yep

**Closed by Simn** 2017-08-31 07:13 UTC
