### ISSUE TITLE
Type inference issues when using enum + optional parameters

### ISSUE THREAD

**Issue by indolering** [HaxeFoundation/haxe#5486] opened 2016-07-30 03:14 UTC
[The compiler produces a type error](http://try.haxe.org/#F42C8) (`haxe.ds.Option<Null<Dynamic>> should be haxe.ds.Option<Int>`) for the following function:

```
static function broken(?input:Dynamic):Option<Int>{
    if(Std.is(input, Int)){
        return Some(input);
    } else {
        return None;
    }
}
```

I suspect it's a bug in the compiler because the error goes away if I make `input` non-optional or switch to a `Null<Int>` return type.  This makes me  If this is correct is it possible to override the compiler until it is fixed?

**Comment by Simn** [comment] 2016-07-30 08:32
The real question is why it works without the `?`. `Option<Dynamic>` cannot be assigned to `Option<Int>`, with or without `Null`.

**Comment by Simn** [comment] 2016-07-30 08:43
Oh I get it, this is a top-down inference issue because we type the `Some(input)` against `Option<Int>`:

```haxe
import haxe.ds.Option;

class Main {
	static public function main() {
		var inputDynamic:Dynamic = "";
		var inputNullDynamic:Null<Dynamic> = "";
		var x:Option<Int>;
		x = Some(inputDynamic); // ok
		x = Some(inputNullDynamic); // not ok
	}
}
```

**Comment by indolering** [comment] 2016-07-30 20:12
Okay, so the compiler just doesn't enforce any type checking when `Dynamic` is involved but `Null<Dynamic>` trips it up?  I need the function parameter to have a default value, preferably null.
 
Note that I am checking `Std.is(input, Int)`, how can I override the compiler here?

**Comment by RealyUniqueName** [comment] 2019-06-25 19:01
Both samples are not reproducible with the latest Haxe

**Closed** 2019-06-25 19:06 UTC
