### ISSUE TITLE
HXB finishing line

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11479] opened 2024-01-09 17:27 UTC
* [x] Test if #11452 breaks with Shiro codebases. @kLabz 
* [x] The reader currently makes a new anon for every encoded empty anon. We should check if instead we can reuse a singular anon for all occurrences. There's a chance that mutability ruins this though. @simn (done in https://github.com/HaxeFoundation/haxe/commit/a7bebce279cbe7644b77f192d1a898fc08e55db7)
* [x] Merge the `cl_type` change separately. It's the same as `e_type` and avoids allocation of many `ClassStatics` instances.@simn (done in https://github.com/HaxeFoundation/haxe/commit/c39a83b7bb0d715197243fd304d8bbed7f099c37)
* [x] Factor out `@:generic` type parameter cloning. @simn (done in https://github.com/HaxeFoundation/haxe/commit/3c07ce1569df6daf03a4fa4a8ab520af5273759a)
* [x] Check the situation in `maybe_cache_context`. At the moment it caches even in offline mode, e.g. normal compilation, which doesn't make much sense other than to test. (Edit: This is true even on development, I suppose we never noticed it there because caching is just a hashtable update. Probably still a good idea to fix it there first.) @kLabz 
* [x] Remove roundtrip nonsense. @simn (done in https://github.com/HaxeFoundation/haxe/commit/ad161fc15c04b5b26ccfe2e1e32b979261547198)
* [x] Remind me what else I wanted to fix. @kLabz :shrug: 
* [x] Regarding `maybe_cache_context`, also check that there's no `--hxb` output when running diagnostics. It should only do that for an actual compilation. Also look into that `(* TODO use hxb cache for hxb output *)` problem. @kLabz 
* [x] Make a separate PR for the changes in tUnification and the anon identification. @kLabz https://github.com/HaxeFoundation/haxe/pull/11489
* [x]  Find a way to make current_display_file invalidation only apply to current request (only "proper" server invalidation should durably invalidate hxb cache) @kLabz 
* [x] I did some benchmarking and read a bit about the object layer of OCaml, and found that the overhead is observable for low-level functions like `write_u8`. I've changed it in the writer in https://github.com/HaxeFoundation/haxe/commit/588498e81081cf2d1ec6665fbab9e2176fa4bf26 and think we should do the same in the reader, at least for `read_u8` and the lebs. @simn (done in https://github.com/HaxeFoundation/haxe/commit/4d5ff7fcccfb212544c99f99f5b9eaa377a72d4b)
* [x] Another more important thing is that when reading for `--hxb-lib`, the reader should ignore `v_id` because it has no meaning in a different context, and might actually cause conflicts. We should also check if there's other such data. I think it's fine to handle this entirely in the reader instead of having different modes for the writer. @simn (done in https://github.com/HaxeFoundation/haxe/commit/18f74f586a810392678519e023381f711febf1a9)
* [x] better error reporting for unbound type parameters @kLabz 
* [x] repair server view @kLabz 
* [x] fix compilation server issue with vshaxe project @kLabz 
* [x] TYPF uses full paths (package + module name + type name) for the module types, but the reader simply discards the module name. It does use the package, but that also seems a bit strange because the package should always match the package of the module. Could we simply encode the type name here instead? @kLabz 
* [x] Separate field expressions from CFLD into a new chunk CFEX. @simn (done in https://github.com/HaxeFoundation/haxe/commit/bba59cd3e28738a303c757d346d84d5a186a3a88, kind of)
* [x] I just noticed `classes <- Array.append classes (Array.make 1 c);` in the TYPF reader which makes me consider going to church on Sundays again... I don't even think it's doing anything because CLSR sets `classes <-` afterwards. Please review! @kLabz (fixed during the MTF changes)
* [x] extract `display_source_at` @kLabz 
* [x] `if headers_only then HEND else TYPF` @kLabz 
* [x] fix and reenable test `tests/unit/src/unit/issues/Issue3725.hx.disabled` (activated again in https://github.com/HaxeFoundation/haxe/commit/7713b39cc88af40954a57d773401899c56fb2553. This was likely fixed by https://github.com/HaxeFoundation/haxe/commit/21bb9e15482880d4a96d53ec8c9cd74f5e6dab6c)
* [x] [server.ml] cleanup that `match type_module sctx ctx mpath p with ...` (see comment there) (comment removed in https://github.com/HaxeFoundation/haxe/commit/a517968e980325598aee41975b1d99c81942f34d. I thought this would have to deal with extern type loading, but that makes no sense because those types also require typing.)
* [x] Make sure Haxe LSP tests pass with this version of Haxe @kLabz 

Maybe-TODOs:
* [x] ~read/write class_kind `KTypeParameter`~ (not required, type parameters are never encoded as real classes)
* [x] ~optimize `TSuper`~ (not important at the moment, probably not worth it at all)
* [x] [compilationCache.ml] do something with hxb and removed files?
* [x] Run all display tests with server cache @kLabz

**Comment by Simn** [comment] 2024-01-09 17:33
Edit: moved to main post

**Comment by kLabz** [comment] 2024-01-09 17:44
Edit: moved to main post

**Comment by Simn** [comment] 2024-01-10 14:00
Edit: moved to main post

**Comment by Simn** [comment] 2024-01-10 17:35
I managed to get CI green with the roundtrip enabled, so if anyone wants to help testing, https://github.com/HaxeFoundation/haxe/commit/438139d147d9c781a7b00828073a62dfc6d8ba24 should be a good commit and have nightly builds.

The roundtrip works by compiling normally up to the point where we cache our state, then throwing everything away and starting compilation over with the cache enabled. This is obviously not something we want to have in a real compiler, but it's really good for testing. It's activated on any target other than `--interp`.

**Comment by Simn** [comment] 2024-01-10 18:28
Edit: moved to main post

**Comment by PXshadow** [comment] 2024-01-10 23:15
Hello I am trying to test it currently with go2hx's atrociously large stdlib, and after doing ``--hxb prebuild.zip`` and --hxb-lib ``prebuild.zip`` I get:
``
haxe.NativeStackTrace has no field saveStack
``

I also used the target hashlink to create the ``prebuild.zip``.
Let me know if you want a test case of it.

**Comment by Simn** [comment] 2024-01-11 05:09
We've seen that problem before but never fully isolated it. Could you give me a .hxml that I can drop in go2hx root to generate that zip? And maybe one that consumes it afterwards, that should allow me to test this easily.

**Comment by PXshadow** [comment] 2024-01-11 11:18
> We've seen that problem before but never fully isolated it. Could you give me a .hxml that I can drop in go2hx root to generate that zip? And maybe one that consumes it afterwards, that should allow me to test this easily.

Of course! Here is the instructions, I added the hxmls into the repo (it does require golang +1.20 and hashlink):
```sh
git clone https://github.com/go2hx/go2hx
cd go2hx
haxelib dev go2hx .
haxe hxb.hxml
haxe create_hxb.hxml
haxe consume_hxb.hxml
```

**Comment by kLabz** [comment] 2024-01-11 15:19
How far were you able to get? Seems to break pretty early with expected errors during `haxe create_hxb.hxml`:

```
❯ haxe create_hxb.hxml
/git/_tmp/go2hx/stdgo/bytes/Bytes.hx:158: characters 28-51 : Type not found : stdgo.StdGoTypes
/git/_tmp/go2hx/stdgo/encoding/base64/Base64.hx:554: characters 26-48 : Type not found : stdgo.StdGoTypes
/git/_tmp/go2hx/stdgo/reflect/Reflect.hx:235: characters 17-44 : Type not found : stdgo.StdGoTypes
/git/_tmp/go2hx/stdgo/io/Io.hx:183: characters 18-45 : Type not found : stdgo.StdGoTypes
/git/_tmp/go2hx/stdgo/errors/Errors.hx:86: characters 26-53 : Type not found : stdgo.StdGoTypes
/git/_tmp/go2hx/stdgo/sort/Sort.hx:30: characters 21-48 : Type not found : stdgo.StdGoTypes
/git/_tmp/go2hx/stdgo/strings/Strings.hx:46: characters 22-49 : Type not found : stdgo.StdGoTypes
/git/_tmp/go2hx/stdgo/unicode/Unicode.hx:9478: characters 37-61 : Type not found : stdgo.StdGoTypes
/git/_tmp/go2hx/stdgo/unicode/utf8/Utf8.hx:13: characters 28-52 : Type not found : stdgo.StdGoTypes
```

**Comment by Simn** [comment] 2024-01-11 15:20
Forgot to link the issue, I'm stuck on something else still: https://github.com/go2hx/go2hx/issues/174

**Comment by back2dos** [comment] 2024-01-12 07:05
> The reader currently makes a new anon for every encoded empty anon. We should check if instead we can reuse a singular anon for all occurrences. There's a chance that mutability ruins this though.

Shouldn't open anons be closed by the time they're serialized?

**Comment by Simn** [comment] 2024-01-12 07:25
Yes, in fact we should never have to encode an anon with open status. I'm never quite sure about the special semantics of `{}` though, there were some surprises there. But maybe it's fine, will try!

**Comment by Simn** [comment] 2024-01-13 18:23
I have added the required logic for CFEX, but the writer doesn't generate it yet. It's a bit problematic for the reader because it needs the accurate field context, most importantly the type parameters. I'm not sure yet how it can dig that up efficiently.

We can add this later though because the chunk is entirely optional: the option byte for field expressions will simply change from Some to None once CFEX is implemented.

Edit: Actually this might be easier than I think: the field type parameters correspond to `cf_params`, and we can move the local type parameters to CFEX anyway.

**Comment by Simn** [comment] 2024-01-14 09:50
CFEX passes the unit tests now, but I still have it commented out because it breaks server tests related to `DisplayMethods.Diagnostics`:

```
src/TestCase.hx:122: {
        hasError : false,
        prints : [],
        stdout : Processing Arguments [-main,Main,--js,no.js,--no-output,--display,{"method":"display/diagnostics","id":1,"params":{"file":"Main.hx"}}]
Defines dce=std,display=1,haxe=5.0.0-alpha.1,haxe3=1,haxe4=1,haxe_ver=5.000,js=1,js_es=5,js_es5=1,source_header=Generated by Haxe 5.0.0-alpha.1+68ea14acc,target.atomics=1,target.name=js,target.unicode=1,target.utf16=1,true=1,utf16=1 
Using signature a4ea81c37745da4c72f2c57b1a6aec05
Display position: C:\git\haxe\tests\server\test\cases\0\Main.hx: -1--1
compiler stage: CInitialized
compiler stage: CInitMacrosStart
compiler stage: CInitMacrosDone
 0, js: changed directories: []
 0, js: reusing StdTypes
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.004s
,
        stderr : ,
        stderrRaw : {
                length : 0,
                b :
        }
}
```

I don't know right now how this is related, the compiler is basically like "my work here is done".

@kLabz Any idea? The protocol itself seems fine, so this must be something quite specific. Could you check that it's not somehow related to the `headers_only` confusion? You can activate CFEX by uncommenting that block in `write_class_field_data`.

Edit: I just renamed the chunks to three letters with a consistent schema. Sorry if this is annoying, will take a bit getting used to for us.

Edit: Something was wrong with type parameter handling again. Should be fine now!

**Comment by PXshadow** [comment] 2024-01-14 14:39
This might be out of scope, so if not feel free to ignore, but looking inside of hxb's ``prebuilt.zip`` I notice that it holds all of the caching as a top level target directory, would it be possible then to have multiple targets within the same ``prebuilt.zip``?

**Comment by Simn** [comment] 2024-01-14 15:25
I suppose the first question would be if that's really a good idea because it means always loading a large archive only to use a small part of it by design. Wouldn't it be better to work with `go2hx.hl.zip` and such instead? (Probably doesn't work yet, but could be made to.)

**Comment by PXshadow** [comment] 2024-01-14 15:35
That's true, so if this feature existed, ``-hxb-lib go2hx.zip`` could be added into the ``extraParams.hxml`` and then when the user compiles using ``-lib go2hx`` for hl it looks for ``go2hx.hl.zip`` if ``go2hx.zip`` is not found?

**Comment by Simn** [comment] 2024-01-14 15:39
Yes I think all file resolution should work like that. Maybe it even works already, but probably not.

Edit: The loader code has this:

```ocaml
	let file = if Sys.file_exists file_path then
		file_path
	else try
		Common.find_file com file_path
```

`Common.find_file` is the function which handles platform-specific extensions, but it's not reached when the `Sys.file_exists` succeeds. This means that if it finds `go2hx.zip` without looking at any class paths, it's not going to look for the platform-specific ones. Probably makes sense for hxb to just remove that `file_exists` check.

**Comment by PXshadow** [comment] 2024-01-14 16:51
Perhaps it's already working as intended, I tested changing ``go2hx.zip`` to ``go2hx.hl.zip`` and it working, if I change it to ``go2hx.eval.zip`` it fails if the target is hl and if I switch the target to interp/eval then it proceeds to pass.

**Closed as completed** 2024-01-25 08:28 UTC
Labels: feature-hxb
