### ISSUE TITLE
Haxe compile server reports an error message when compiling the same code base twice

### ISSUE THREAD

**Issue by Atry** [HaxeFoundation/haxe#4626] opened 2015-11-06 03:54 UTC
```
$ haxe -version
3.2.1
```

```
haxe --wait 7777 &
git clone https://github.com/ThoughtWorksInc/json-stream.git &&
cd json-stream &&
"haxe" "-cp" "src/haxe-java" "-cp" "src/haxe" "-cp" "target/scala-2.10/src_managed/haxe-java" "-cp" "target/scala-2.10/src_managed/haxe"  "-cp" "src/haxe"  "-java" "java_output" "--connect" "7777" "-D" "no-compilation" "-lib" "continuation:1.3.2" "-lib" "microbuilder-HUGS:2.0.1" "-dce" "no"  "jsonStream.Plugins" "jsonStream.deserializerPlugin.LowPriorityDynamicDeserializerPlugin" "jsonStream.rpc.IncomingProxyFactory" "jsonStream.JsonSerializer" "jsonStream.rpc.OutgoingProxy" "jsonStream.rpc.Future" "jsonStream.io.TextParser"  "jsonStream.LowPriorityDynamic" "jsonStream.builderPlugin.LowPriorityDynamicBuilderPlugin" "jsonStream.deserializerPlugin.CSharpDeserializerPlugins"  "jsonStream.JsonBuilder" "jsonStream.io.BsonOutput" "jsonStream.unknown.UnknownFieldMap" "jsonStream.rpc.OutgoingProxyFactory" "jsonStream.deserializerPlugin.StmDeserializerPlugins" "jsonStream.io.PrettyTextPrinter"  "jsonStream.JsonDeserializer"  "jsonStream.unknown.UnknownEnumValue" "jsonStream.deserializerPlugin.RawDeserializerPlugin" "jsonStream.deserializerPlugin.ScalaDeserializerPlugins" "jsonStream.deserializerPlugin.GeneratedDeserializerPlugin" "jsonStream.RawJson" "jsonStream.builderPlugin.GeneratedBuilderPlugin" "jsonStream.serializerPlugin.CSharpSerializerPlugins"   "jsonStream.io.BsonWriter" "jsonStream.deserializerPlugin.CrossPlatformDeserializerPlugins" "jsonStream.GeneratorUtilities" "jsonStream.serializerPlugin.RawSerializerPlugin" "jsonStream.serializerPlugin.ScalaSerializerPlugins" "jsonStream.rpc.IncomingProxy"  "jsonStream.serializerPlugin.StmSerializerPlugins"  "jsonStream.rpc.JsonHandler" "jsonStream.testUtil.JsonEquality" "jsonStream.io.BsonInput"  "jsonStream.builderPlugin.PrimitiveBuilderPlugins" "jsonStream.serializerPlugin.LowPriorityDynamicSerializerPlugin" "jsonStream.builderPlugin.RawBuilderPlugin" "jsonStream.io.BsonReader" "jsonStream.rpc.IJsonService" "jsonStream.JsonBuilderFactory" "jsonStream.unknown.UnknownType" "jsonStream.deserializerPlugin.PrimitiveDeserializerPlugins" "jsonStream.serializerPlugin.GeneratedSerializerPlugin" "jsonStream.JsonStream" "jsonStream.serializerPlugin.PrimitiveSerializerPlugins" "jsonStream.testUtil.JsonTestCase" "jsonStream.serializerPlugin.CrossPlatformSerializerPlugins" &&
"haxe" "-cp" "src/haxe-java" "-cp" "src/haxe" "-cp" "target/scala-2.10/src_managed/haxe-java" "-cp" "target/scala-2.10/src_managed/haxe"  "-cp" "src/haxe"  "-java" "java_output" "--connect" "7777" "-D" "no-compilation" "-lib" "continuation:1.3.2" "-lib" "microbuilder-HUGS:2.0.1" "-dce" "no"  "jsonStream.Plugins" "jsonStream.deserializerPlugin.LowPriorityDynamicDeserializerPlugin" "jsonStream.rpc.IncomingProxyFactory" "jsonStream.JsonSerializer" "jsonStream.rpc.OutgoingProxy" "jsonStream.rpc.Future" "jsonStream.io.TextParser"  "jsonStream.LowPriorityDynamic" "jsonStream.builderPlugin.LowPriorityDynamicBuilderPlugin" "jsonStream.deserializerPlugin.CSharpDeserializerPlugins"  "jsonStream.JsonBuilder" "jsonStream.io.BsonOutput" "jsonStream.unknown.UnknownFieldMap" "jsonStream.rpc.OutgoingProxyFactory" "jsonStream.deserializerPlugin.StmDeserializerPlugins" "jsonStream.io.PrettyTextPrinter"  "jsonStream.JsonDeserializer"  "jsonStream.unknown.UnknownEnumValue" "jsonStream.deserializerPlugin.RawDeserializerPlugin" "jsonStream.deserializerPlugin.ScalaDeserializerPlugins" "jsonStream.deserializerPlugin.GeneratedDeserializerPlugin" "jsonStream.RawJson" "jsonStream.builderPlugin.GeneratedBuilderPlugin" "jsonStream.serializerPlugin.CSharpSerializerPlugins"   "jsonStream.io.BsonWriter" "jsonStream.deserializerPlugin.CrossPlatformDeserializerPlugins" "jsonStream.GeneratorUtilities" "jsonStream.serializerPlugin.RawSerializerPlugin" "jsonStream.serializerPlugin.ScalaSerializerPlugins" "jsonStream.rpc.IncomingProxy"  "jsonStream.serializerPlugin.StmSerializerPlugins"  "jsonStream.rpc.JsonHandler" "jsonStream.testUtil.JsonEquality" "jsonStream.io.BsonInput"  "jsonStream.builderPlugin.PrimitiveBuilderPlugins" "jsonStream.serializerPlugin.LowPriorityDynamicSerializerPlugin" "jsonStream.builderPlugin.RawBuilderPlugin" "jsonStream.io.BsonReader" "jsonStream.rpc.IJsonService" "jsonStream.JsonBuilderFactory" "jsonStream.unknown.UnknownType" "jsonStream.deserializerPlugin.PrimitiveDeserializerPlugins" "jsonStream.serializerPlugin.GeneratedSerializerPlugin" "jsonStream.JsonStream" "jsonStream.serializerPlugin.PrimitiveSerializerPlugins" "jsonStream.testUtil.JsonTestCase" "jsonStream.serializerPlugin.CrossPlatformSerializerPlugins"
```

The first time haxe compilation succeeded and it failed when compiling again with an error message.

```
Type name  is redefined from module java.lang.Double
```

**Comment by Simn** [comment] 2015-11-06 07:31
@waneck: That seems familiar, didn't we talk about this before?

**Comment by Atry** [comment] 2015-11-06 08:05
Looks like #4235

**Comment by Simn** [comment] 2016-03-18 09:26
Can you check if this is still a problem?

**Comment by Simn** [comment] 2016-03-22 09:18
I tried checking out the project but I get unrelated errors even on the first compilation. For the time being I'll assume that the original issue has been addressed, let me know if there are still issues.

**Comment by Simn** [comment] 2016-03-22 09:45
Turns out the failure was actually a legitimate problem which I isolated and fixed in #4969. With that I can in fact still reproduce the original error.

**Comment by Atry** [comment] 2016-03-22 09:54
Thank you for your investigation!

**Comment by waneck** [comment] 2016-04-03 06:25
@Simn do you need me to do anything here?

**Comment by Simn** [comment] 2016-04-03 06:27
I'm not sure, this actually looks a lot like https://github.com/HaxeFoundation/haxe/pull/5006#issuecomment-204704318. Nicolas basically says that this shouldn't happen, but for some reason it apparently does.

**Comment by waneck** [comment] 2016-04-03 21:29
Assigning to Nicolas then

**Comment by Simn** [comment] 2016-09-28 07:55
I just tried again and can no longer reproduce this problem.

**Closed by Simn** 2016-09-28 07:55 UTC
