### ISSUE TITLE
Int64 breaks with properties that have a setter in some cases

### ISSUE THREAD

**Issue by dogles** [HaxeFoundation/haxe#4388] opened 2015-07-06 21:37 UTC
```
package;
import haxe.Int64;

class Test
{
  public var x(default, set) : Int64;
  inline function set_x(i:Int64) : Int64 {
    return this.x = i;
  }

  function new() { this.x = 1; }

  public static function main() {
    var test = new Test();
    test.x |= 2;
    trace(test.x);
  }
}
```
http://try.haxe.org/#f1898

Expected: "3", get "1".

If you look at the generated code, the 'or' operation does not get assigned to anything.
Tested in C# and Javascript targets.

**Comment by waneck** [comment] 2015-07-06 22:26
That's strange. I can't reproduce with the example given - not on C# nor JS. Also the `try.haxe` linked seems to also trace "3". What Haxe version are you using?

**Comment by dogles** [comment] 2015-07-07 12:36
It looks like I put the wrong version in try.haxe: the x decl didn't have (default, set) specified. I updated the URL in the original description. This is with 3.2.0 - I haven't had the chance to try latest from master.

**Comment by waneck** [comment] 2015-07-07 14:27
@Simn -D dump looks like this:
```
	static public main(method) : Void -> Void

	 = function() = {
		var test = new Test();
		{
			var _g = test;
			@:requiresAssign {
				var a = _g.x;
				var b;
				@:implicitCast {
					var x1 = new haxe._Int64.___Int64(0,2);
					b = cast cast x1;
				};
				var x = new haxe._Int64.___Int64(cast cast a.high | cast b.high,cast cast a.low | cast b.low);
				cast cast x;
			};
		};
		`trace(haxe._Int64.Int64_Impl_.toString(test.x),{fileName : "Test.hx",lineNumber : 16,className : "Test",methodName : "main"});
	}
```

Seems to be a missing case when dealing with `@:requiresAssign` ? It might related to `@:implicitCast` somehow

**Comment by waneck** [comment] 2015-07-07 14:56
It's already fixed on latest

**Closed** 2015-07-07 14:56 UTC
Labels: bug, haxe-foundation-partner
