### ISSUE TITLE
XML literal: Unterminated markup literal

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#8165] opened 2019-04-15 12:20 UTC
Re-entrency doesn't work for self-closing tags.

This works:
```haxe
var markup = <some-component header=${<div />}></some-component>;
```

While this fails with `Unterminated markup literal`:
```haxe
var markup = <some-component header=${<div>Test</div>} />;
var markup = <some-component header=${<div />} />;
```

**Comment by Simn** [comment] 2019-04-16 06:55
I hate this stupid feature so much.

**Comment by Simn** [comment] 2019-04-16 07:05
> `<some-component header=${<div />} />;`

I was under the impression that this wasn't supposed to work because the first `/>` would be picked up as the document-closer. Did I get that wrong?

**Comment by kLabz** [comment] 2019-04-16 07:14
Yeah I think I read a comment of yours saying this would most probably be a limitation (in the issues discussing the feature before you implemented it, iirc).

**Comment by Simn** [comment] 2019-04-16 07:45
@back2dos confirmed that this is a limitation. I can't see a way around this unless we completely change how we handle this.

But it's a bit sad...

**Comment by kLabz** [comment] 2019-04-16 07:54
Yeah, doesn't surprise me much =/

I just rebased your commit, but I now have errors with every self-closing tags :confused:

**Comment by Simn** [comment] 2019-04-16 07:55
Uhm, can you post an example?

**Comment by kLabz** [comment] 2019-04-16 08:00
Seems like I cannot have self-closing siblings:
`var a = <div><input /><input /></div>;` fails with `Missing ;` between the inputs.

**Comment by kLabz** [comment] 2019-04-16 09:31
@Simn could you revert 67698ab before next release candidate if you haven't fixed it until then? It makes the situation worse atm (but it's no big deal between releases).

**Comment by Simn** [comment] 2019-04-16 09:48
Yes I've reverted it. The tentative answer is that both your examples are invalid because self-closing nodes are only supported if there is no `<` and `>` between the opening tag and the `/>`.

**Comment by Simn** [comment] 2019-04-18 07:19
Well, looks like that's just it: We allow self-closing tags only if no `<` or `>` are in the way. So both of these cases are not valid as far as our design is concerned.

And don't complain to me about this, I didn't design it.

**Closed as completed by Simn** 2019-04-18 07:19 UTC
Labels: strong-belgian-ale

**Comment by kLabz** [comment] 2019-04-18 07:20
Yeah I've read the discussion, seems like there isn't much choice anyway.
