### ISSUE TITLE
[lua] standard lua files not included

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/haxe#7289] opened 2018-07-20 05:38 UTC
On recent development builds the standard `/std/lua/_lua/*.lua` snippets are missing from the output.  This causes `attempt to call a nil value (global '_hx_e')` errors.

Tested with haxe cbdd69b03:

```haxe
class Hello {
  static function main()
  {
    trace("Hi, there!");
  }
}
```

```
$ haxe -lua hello.lua -main Hello
$ lua hello.lua
lua: hello.lua:2: attempt to call a nil value (global '_hx_e')
stack traceback:
	hello.lua:2: in main chunk
	[C]: in ?
```

```
$ grep -n '_hx_e' hello.lua
2:local Array = _hx_e()
3:local Hello = _hx_e()
4:local Math = _hx_e()
5:local Reflect = _hx_e()
6:local String = _hx_e()
7:local Std = _hx_e()
8:__haxe_IMap = _hx_e()
9:__haxe_Log = _hx_e()
10:__lua_Boot = _hx_e()
```

**Comment by jdonaldson** [comment] 2018-08-20 20:45
I'm not seeing this happening, either at the referenced commit, nor at the head.  Am I missing some other flag or context here?

**Comment by jdonaldson** [comment] 2018-08-25 21:50
Closing, feel free to reopen if you have a good repeatable case.

**Comment by jonasmalacofilho** [comment] 2018-08-25 22:07
I am sorry, I must have missed the notification for the other message.

Perhaps a dependency (of Haxe) is causing this?

 - there were no project or haxe build flags set (other than an unrelated `ADD_REVISION`);
 - the issue did manifest just after a fresh OS installation;
 - `strace` showed `haxe` would find and read the files (but just that).

How can I help to debug this?

---

I am not sure non-maintainers can reopen issues.

**Comment by jonasmalacofilho** [comment] 2018-09-01 23:43
I had a hard time reproducing this as well, but I eventually figured out it has to do with the compilation server ; )

```
# start a fresh compilation server
> systemctl restart --user haxe

# build once
> haxe --connect 6000 build.hxml && lua hello.lua
Hello.hx:4: Hi, there!

# build another time
> haxe --connect 6000 build.hxml && lua hello.lua
lua: hello.lua:2: attempt to call a nil value (global '_hx_e')
stack traceback:
	hello.lua:2: in main chunk
	[C]: in ?
```

---

When I originally opened the issue I must have accidentally switched to Vim between building from the command line and checking the output from Lua.  My bad!

**Comment by jdonaldson** [comment] 2018-09-02 03:34
Ahh, that's helpful!  I'll check it out.

**Comment by csterling4** [comment] 2019-01-31 00:26
This definitely occurs when using the compilation server. I think i had it where every other build was generating invalid lua files due to _hx_e being missed.

**Comment by jdonaldson** [comment] 2019-09-22 22:15
I've tried reproducing again with --connect and it looks like the problem has gone away.  Please let me know if you see this again.

**Closed by jdonaldson** 2019-09-22 22:15 UTC
Labels: platform-lua
