### ISSUE TITLE
[nullsafety] Detected nullable despite a null check

### ISSUE THREAD

**Issue by kyubuns** [HaxeFoundation/haxe#9544] opened 2020-06-07 12:30 UTC
haxe 4.1.1

```hx
class Main {
    static function main() {
        // case1 : Success
        var hoge: Null<Int> = 10;
        if (hoge != null) {
            trace('!= null');
            if (hoge > 5) trace('> 5');
        }

        // case2 : Success
        var hoge = new Hoge(10);
        if (hoge.piyo != null) {
            if (hoge.piyo > 5) trace('> 5');
        }

        // case3 : Failed `Null safety: Cannot perform binary operation on nullable value.`
        var hoge = new Hoge(10);
        if (hoge.piyo != null) {
            trace('!= null'); // Even if it's not trace, you can recreate it by inserting some other process.
            if (hoge.piyo > 5) trace('> 5');
        }
    }
}

class Hoge {
    public function new(piyo: Null<Int>) {
        this.piyo = piyo;
    }

    public var piyo: Null<Int>;
}


```

```
-main Main
--interp
--macro nullSafety("Main", Strict)
```

The build of case 1 and case 2 succeeds.
The build for case 3 will result in an error. `Null safety: Cannot perform binary operation on nullable value.`

**Comment by khalyomede** [comment] 2020-12-30 11:38
I confirm I have the same bug, with Haxe 4.1.4 on Alpine (Docker "haxe:4.1-alpine" image). Here is the snippet with which I have the issue:

```haxe
import haxe.Exception;

@:nullSafety(Strict)
class Request {
  private static var queryStrings: Map<String, String> = [];

  public static function getQueryString(key: String): String {
    if (Request.queryStrings[key] == null) {
      throw new Exception("Request::getQueryString(): key " + key + " does not exist");
    }
    
    // Null safety: Cannot return nullable value of Null<String> as String
    return Request.queryStrings[key];
  }
}
```

Same thing if I check for the existance of a key in a map using exists:

```haxe
import haxe.Exception;

@:nullSafety(Strict)
class Request {
  private static var queryStrings: Map<String, String> = [];

  public static function getQueryString(key: String): String {
    if (!Request.queryStrings.exists(key)) {
      throw new Exception("Request::getQueryString(): key " + key + " does not exist");
    }

    // Null safety: Cannot return nullable value of Null<String> as String
    return Request.queryStrings[key];
  }
}
```

However, if I specifically **add** an assigned value and check for nullity, the compiler **compiles** without errors:

```haxe
import haxe.Exception;

@:nullSafety(Strict)
class Request {
  private static var queryStrings: Map<String, String> = [];

  public static function getQueryString(key: String): String {
    var value = Request.queryStrings[key];

    if (value == null) {
      throw new Exception("Request::getQueryString(): key " + key + " does not exist");
    }

    // Passes
    return value;
  }
}
```

Hope it helps!

**Comment by RealyUniqueName** [comment] 2020-12-30 11:45
Actually, these are not bugs.
It's a specified behavior for `Strict` mode: https://api.haxe.org/haxe/macro/NullSafetyMode.html

**Comment by RblSb** [comment] 2023-04-08 22:39
Not a bug, can be fixed with using `@:nullSafety` without `Strict`.
Can be closed

**Closed as completed** 2023-04-09 05:35 UTC
Labels: bug, feature-null-safety
