### ISSUE TITLE
@:native doesn't work when defining a structure type 

### ISSUE THREAD

**Issue by xmeta** [HaxeFoundation/haxe#5209] opened 2016-05-07 11:35 UTC
- Haxe version: 3.2.1

## Example
Main.hx
```haxe
typedef Test = {
  @:native("good_name")
  var bad_name: String;
}

class Main {
    static function main() {
        var test = {
          bad_name: "foo"
        };
        trace(test);
    }
}
```

## Actual
main.js
```javascript
(function (console) { "use strict";
var Main = function() { };
Main.main = function() {
	var test = { bad_name : "foo"};
	console.log(test);
};
Main.main();
})(typeof console != "undefined" ? console : {log:function(){}});
```
## Expected
main.js
```javascript
(function (console) { "use strict";
var Main = function() { };
Main.main = function() {
	var test = { good_name : "foo"};
	console.log(test);
};
Main.main();
})(typeof console != "undefined" ? console : {log:function(){}});
```

**Comment by TheoSabattie** [comment] 2016-05-16 12:03
> @:native (Output type path)	Rewrites the path of a class or enum during generation	all

from http://haxe.org/manual/cr-metadata.html

You try to use metadata for a property.

**Comment by nadako** [comment] 2016-05-19 16:13
IIUC, this is a duplicate of #5105

**Closed by nadako** 2016-05-19 16:13 UTC
