### ISSUE TITLE
@:genericBuild does not run in all places that it claims to

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/haxe#4653] opened 2015-11-19 03:00 UTC
I am not sure exactly what situations in which @:genericBuild macros are not evaluated properly, but at the very least, for a type A to which a @:genericBuild has been applied, that generic build macro will not be run in code like this:

if (Std.is(foo, A)) { ... }

I don't know if it's because Std.is is a core API, or an extern, or who knows what.

The documentation for @:genericBuild says that the macro will be run "whenever [the type] appears in the code".  This is not true in the above case at least, possibly others.

**Comment by Simn** [comment] 2015-11-19 08:49
That's an interesting case. The original idea behind `@:genericBuild` was to use it with types that have type parameters. However, parameterized types like that cannot appear in expression syntax because it doesn't parse, by design.

This problem would occur in any place where a type is used as a value. Fixing this would require changing a rather central function (`type_type`) in order to deal with type instances instead of type definitions.

@ncannasse: Do you have any thoughts on this?

**Comment by ncannasse** [comment] 2015-11-20 22:21
It's right that for both generic and genericBuild classes we have a single type that can be runtime checked for a fixed combination of type parameters. This is not the case for other classes with type parameters: we cannot for instance runtime check if a value is an `Array<MyClass>`, so it was not necessary at first. 

This could be easily fixed with the addition of a "is" operator, but then we could loose the ability to do `v is expr`, this would then require to keep Std.is for such cases.

Another option that would work right now is maybe to go through a macro that would do a getType and return the corresponding TypeExpr that maps to the actual class that was built for it, since I think it lives in some package somewhere ?

**Comment by Simn** [comment] 2015-11-23 22:46
Note that we already support `(expr is type_path)` syntax (with the mandatory parentheses). It currently translates straight to `Std.is(expr, type_path)` but we can easily improve on that in the future.

**Closed** 2015-11-24 12:35 UTC
