### ISSUE TITLE
Private modules access inside macros

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#3808] opened 2015-01-27 13:05 UTC
One of the most annoying problems I usually encounter when writing macros is something along these lines:

`Main.hx`:
```haxe
private typedef Test = { msg:String };

class Main
{
	static function main()
	{
		var n:Test = Macro.doCast(null);
	}
}
```

`Macro.hx`:
```haxe
import haxe.macro.Expr;
import haxe.macro.Context;
import haxe.macro.Type;
using haxe.macro.TypeTools;

class Macro
{
	macro public static function doCast(e:Expr):Expr
	{
		var t = Context.getExpectedType();
		if (t == null) throw 'assert';
		var complex = t.toComplexType();
		return macro ( cast $e : $complex );
	}
}
```

This will fail with
```
Macro.hx:13: characters 15-37 : Module Main does not define type Test
```

This is very annoying, especially in that it's a very unexpected error - API-wise (why would `toComplexType` return a non-null type that can't be used?). And worst - there's no way to make this code work, since there is no way to access a private module.

Actually I've made a very hacky type to work around this limitation (see https://github.com/unihx/unihx/blob/tmp/src/unihx/pvt/macros/PrivateTypeAccess.hx and https://github.com/unihx/unihx/blob/tmp/src/unihx/pvt/macros/PrivateAccessMacro.hx ), but it not only feels very hacky, but I find myself needing to include it on every project I use `toComplexType` and `TypedExpr`.

**Comment by Simn** [comment] 2015-01-27 13:08
Can you check if the non-macro version of haxe.macro.TypeTools.toComplexType works better?

**Comment by waneck** [comment] 2015-01-27 13:09
The non-macro version fails with a different error:
```
Macro.hx:13: characters 15-37 : Class not found : _Main.Main
```

**Comment by andyli** [comment] 2015-01-27 13:37
I also need a way to access private modules when doing `getTypedExpr(typeExpr(expr))` (#3739).

**Comment by nadako** [comment] 2015-01-27 13:55
i also often stumble upon this...

**Comment by nadako** [comment] 2015-01-27 13:56
BTW isn't this a duplicate of #3589?

**Comment by Simn** [comment] 2015-01-27 13:57
Yes

**Closed by Simn** 2015-01-27 13:57 UTC

**Comment by waneck** [comment] 2015-01-27 14:00
Oops. Indeed it is

**Comment by Simn** [comment] 2015-01-27 14:01
But it's very interesting how many haxe devs came across this without addressing it. :P

**Comment by ncannasse** [comment] 2015-01-27 14:46
I haven't yet :D
