### ISSUE TITLE
`else if` without last `else` in array comprehension

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#9040] opened 2019-12-17 13:09 UTC
```haxe
[for (i in 0...100) if(i % 2 == 0) i else if(i % 3 == 0) i]
```
This expression does not compile with `Void should be Int` error.

**Comment by Gama11** [comment] 2019-12-17 13:49
That seems expected, not every branch has a value. This could probably be considered a duplicate of this feature request: https://github.com/HaxeFoundation/haxe/issues/8363

**Comment by kLabz** [comment] 2019-12-17 13:50
As a workaround, you can add `else continue`

**Comment by romamik** [comment] 2019-12-17 14:01
> That seems expected, not every branch has a value. 
```haxe
[for (i in 0...100) if(i % 2 == 0) i]
```
In this expression not every branch has a value also...

> This could probably be considered a duplicate of this feature request: #8363

I searched issues before posting and have seen this. But I do not think it's a duplicate: in case #8363 would be implemented, this issue would not be automatically resolved. 
May be this should go as comment there...

**Comment by RealyUniqueName** [comment] 2019-12-17 14:06
Seems like typer has a special case for `if` without `else` in array comprehensions. 
I agree it could have a better implementation.

**Comment by ncannasse** [comment] 2019-12-17 20:26
It should be supported, by applying the same recursion we apply on the if
branch to the else one (I guess)

**Closed as completed** 2019-12-25 15:12 UTC
