### ISSUE TITLE
crash from EReg (Haxe 3.2.1 + neko + strange text)

### ISSUE THREAD

**Issue by kobi2187** [HaxeFoundation/haxe#5175] opened 2016-04-26 19:51 UTC
The following code throws an exception. 
(This is the smallest text I could reduce to that still throws.)
It happened on neko but not on c++. 
According to try.haxe.org, doesn't happen on js.
I verified on haxe 3.2.1

```
class Test {

     static function exp()
     {
        var word = ~/:\s(.+?)\s\(\s(.+?\s)*--(\s.+?)*\s\)/;
        var str = ': <a> ( -- g )  <>    {  }       y-r    [ g ] >> ';       
        trace(word.match(str)); 
     }
    static function main() {
        trace("Haxe is great!");
        exp();
    }
}
```

I get the following message:

```
Called from sys.io.File::$statics line 1
Called from Main::main line 98
Called from Main::exp line 42
Called from EReg::match line 37
Uncaught exception - An error occured while running pcre_exec
Error: Command failed with error 1
```

the build file looks as follows:

```
 -cp ./src
 #-cp ../vmvc/src
 -main Main
 -debug
 -lib thx.core
#  -lib stdlib 

 -dce full
 -neko bin/viz.n
  --next
 # run
  -cmd neko ./bin/viz.n 70

```

**Comment by yar3333** [comment] 2016-04-26 19:57
This is a normal for regex library used by neko. Try replace `(text)*` in regex to `((?:text)*)`.

**Comment by kobi2187** [comment] 2016-04-27 05:35
well, the regex works for other text. if I just remove one space in the text above, I will get a boolean result. the exception is "unexpected". 
maybe it somehow affects the internal state in neko (or neko's pcre implementation) , like unescaped values might do sometimes.
Thanks for the suggestions though.
I stumbled upon this bug, when continuously matching over a text, and then a section of the text crashed the regex.

**Comment by yar3333** [comment] 2016-04-27 09:30
As I understand, the problem occurs on capturing. When you remove a space, whole regex or some groups not captured, so all works well.

**Comment by yar3333** [comment] 2016-04-27 09:34
I research the problem during working on my HtmlParser project (regex-based html parser). Don't use sometimes-captured expressions like `(...)?` / `(...)+` / `(...)*` and avoid nested capturing like `(...(...)...)` and all works well.

**Comment by ncannasse** [comment] 2016-05-20 00:12
@hughsando any idea why it would work with cpp but not neko?

**Comment by hughsando** [comment] 2016-05-20 02:34
What version of pcre do you use?
The hxcpp is very old, but possibly newer than neko's one.
Also, hxcpp one is compiled with -DSUPPORT_UTF8 and more recently -DSUPPORT_UCP
While this does not seem to be used here, it might make it different internally.
Other ideas are some subtle difference in the was nulls are handled, or something funny with the boehm gc missing some handles or something.

**Comment by andyli** [comment] 2016-05-20 03:29
It seems it is not a pcre version issue since I've just tested with Neko 2.1.0, which uses latest version of pcre (8.38), but got the same runtime error. I'm using Windows.

**Comment by nadako** [comment] 2016-05-21 18:57
I'm not sure what milestone to set here, but since it's not a regression, I'm gonna set it to 3.4. Feel free to fix it though :)

**Comment by ncannasse** [comment] 2016-12-14 21:25
This might be fixed by using a more recent PCRE version (see #4056)

**Closed by ncannasse** 2016-12-14 21:25 UTC
Labels: bug, platform-neko
