### ISSUE TITLE
[display] dynamically update the syntax cache

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8451] opened 2019-06-20 10:51 UTC
The completion server has a syntax cache for things like toplevel completion. It is initialized once on startup with `server/readClassPaths`. The problem is that after this point, it is never updated again.

Here's an example with a newly created `Test` type, which doesn't show up in completion and thus can't be auto-imported. It only shows up after restarting the language server.

![](https://i.imgur.com/knpImHK.png)

Conversely, `Test` will still show up after it has been deleted:

![](https://i.imgur.com/KXMEMKM.png)

To avoid these issues, Haxe needs to update its syntax cache dynamically when types are added or removed. We probably also need some new methods (`server/moduleCreated` / `server/moduleDeleted`?) to inform Haxe about changes based on file watcher events (similar to the `server/invalidate` we already have).

**Comment by Simn** [comment] 2019-06-29 07:08
This requires some design. Mostly because it's not even clear if a deleted/added file is even relevant with regards to class path resolution.

Actually, I don't think we'd need moduleDeleted because that should be the same as invalidate, right?

**Comment by Gama11** [comment] 2019-06-29 08:26
Hm, right, I guess the compiler would notice that the file doesn't exist anymore when invalidating a deleted file...

**Comment by Simn** [comment] 2019-06-29 08:32
I think the most straightforward way to implement moduleAdded is to invalidate all types (not just modules) that live in a module with the same name. It's a bit brute-force but I struggle to see how we would handle type resolution in the general case otherwise.

**Comment by djaonourside** [comment] 2019-07-28 19:55
Guys, what's the issue status? I'm asking because suppose it's rather critical and basic aspect of editor language support.

**Comment by nadako** [comment] 2019-07-28 20:13
Would be nice to have for 4.0 indeed, as it's pretty annoying when working in VS Code.

**Comment by Simn** [comment] 2019-08-06 12:11
I'm willing to work on this, but I can't do much on the vshaxe side because it only compiles for @Gama11 these days.

I'll try to construct a failing test case for this

**Comment by Simn** [comment] 2019-08-06 16:12
I have added `server/moduleCreated` and the test passes now. There's no additional invalidation going on yet, I'll have to check if that's the right thing to do. Now vshaxe needs an update.

**Comment by Simn** [comment] 2019-08-08 08:51
@Gama11's observation is correct: If the module is created in an empty state and only "filled out" later, the type is not picked up. The following test sequence doesn't pass:

```
		vfs.putContent("Empty.hx", "");
		runHaxeJson([], ServerMethods.ModuleCreated, {file: new FsPath("Empty.hx")});
		vfs.putContent("Empty.hx", getTemplate("Empty.hx"));
		runHaxeJson([], ServerMethods.Invalidate, {file: new FsPath("Empty.hx")});
		runHaxeJson([], DisplayMethods.Completion, {file: new FsPath("HelloWorld.hx"), offset: 75, wasAutoTriggered: false});
```

Note that this problem is not specific to the new moduleCreated feature. I think we have mark files upon invalidation and then re-parse them on the next request that utilizes the syntax cache (unless they were already handled inbetween).

**Comment by Simn** [comment] 2019-08-08 10:42
I have committed this approach. There's still an open debate I'm having with myself about whether or not the `server/invalidate` request is necessary for this to work. The issue is that without it, the compiler looks at the file again because it is never actually compiled.

The only way to handle that would be to check the modification time of _all_ files in the syntax cache, which would likely be insanely slow.

**Comment by Simn** [comment] 2019-08-09 06:32
I think we're done here.

**Closed as completed by Simn** 2019-08-09 06:32 UTC
Labels: enhancement, feature-ide
