### ISSUE TITLE
[cs] inlining calls with optional arguments that get applied to non-optional (constructor) arguments fails

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#4968] opened 2016-03-22 06:47 UTC
``` haxe
package ;

abstract Query(String) from String to String {  

  inline function iterator() 
    return parseString(this);

  static public inline function parseString(s:String, ?sep:String = '&', ?set:String = '=', ?pos:Int = 0)
    return new QueryStringParser(s, sep, set, pos);

}

private class QueryStringParser {

  var s:String;
  var sep:String;
  var set:String;
  var pos:Int;

  public function new(s, sep, set, pos) {
    this.s = s;
    this.sep = sep;
    this.set = set;
    this.pos = pos;
  }
}
```

This generates the following code:

``` cs
public static global::tink.url._Query.QueryStringParser iterator(string this1) {
  return new global::tink.url._Query.QueryStringParser(this1, "&", "=", (0).@value);
}
```

Notice the `(0).@value` which seems to be some unnecessary unboxing. Interestingly, the issue seems to disappear if the `?` before `pos` is removed (I didn't know that actually makes a difference and I really believe it shouldn't) or of the callee is a static function of the abstract itself.

**Comment by Simn** [comment] 2016-03-22 08:59
I'm seeing this:

```
public static global::_Main.QueryStringParser iterator(string this1) {
	return new global::_Main.QueryStringParser(this1, "&", "=", ((int) (global::haxe.lang.Runtime.toInt(0)) ));
}
```

That Runtime.toInt certainly looks weird, but at least it's better than `(0).@value`. I do wonder why it's different for you though.

**Comment by nadako** [comment] 2016-03-22 10:37
the `Runtime.toInt` happens with `-D erase-generics`

**Comment by nadako** [comment] 2016-03-22 10:46
So, `0` is typed as `Null<Int>` and then it's unified with `Int` when passed to the `QueryStringParser.new`, hence the unboxing. I'm not sure what's the right way to fix this. Is it okay for constants to be typed as `Null<T>`? If so, we could fix gencs/gencommon to not to try unboxing constants.

**Comment by Simn** [comment] 2016-03-23 09:38
I don't really see how else it would be typed, unless I'm misunderstanding the problem.

**Comment by Simn** [comment] 2016-03-23 09:39
By the way, is this a regression?

**Comment by back2dos** [comment] 2016-03-23 10:54
Nope. It fails with 3.2.1 too: https://travis-ci.org/haxetink/tink_url/jobs/117549710#L1910

**Comment by nadako** [comment] 2016-05-21 16:46
I am assigning this to 3.4 since it's not a regression and we already have too much to do deal with for 3.3, but maybe I'll look into this myself if I have time...

**Comment by nadako** [comment] 2017-10-03 23:47
Reduced sample:

```haxe
class Main {
	@:pure(false) function new(v:Int) {}

	static function main() {
		inline function g(?v = 0) new Main(v);
		g();
	}
}
```

**Closed** 2017-10-04 00:36 UTC
Labels: bug, platform-cs

**Comment by nadako** [comment] 2017-10-04 00:40
There's something fishy in CastDetect, that it always generates a `TCast` for constructor calls (IIRC for resolving overloads or something) which results in a `(Cast (Const 0 : haxe.lang.Null<Int>) : Int)` expression that is then handled by `HardNullableSynf` that generates this `.value` access.

What I did is fixed it on the `unwrap_null` function so it never tries to "unwrap" constants, even if they are `Null<Int/Float/Bool>`, which fixes the issue even tho the redundant cast is still there in the AST.

**Comment by nadako** [comment] 2017-10-04 00:43
(this is a small fix that should be safe to include in a bugfix branch btw, i wonder if we should make a `for-bugfix-release` tag for all these small fixes)
