### ISSUE TITLE
lime issues

### ISSUE THREAD

**Issue by theteamorange** [HaxeFoundation/haxe#11234] opened 2023-05-22 20:25 UTC
when i use lime appears this error:
Haxe: 4.2.5; OS type: unix;
```
File "src/context/common.ml", line 711, characters 28-35
Called from file "src/typing/typeload.ml", line 587, characters 53-66
Called from file "list.ml", line 96, characters 24-34
Called from file "src/typing/typeload.ml", line 603, characters 23-57
Called from file "src/typing/typeload.ml", line 624, characters 2-45
Called from file "src/typing/typeloadModule.ml", line 809, characters 11-46
Called from file "list.ml", line 85, characters 12-15
Called from file "src/typing/typeloadModule.ml", line 945, characters 1-53
Called from file "src/typing/typeloadModule.ml", line 1007, characters 1-35
Called from file "src/typing/typeloadModule.ml", line 1062, characters 11-48
Called from file "src/typing/typeloadModule.ml", line 1103, characters 4-45
Called from file "src/typing/macroContext.ml", line 401, characters 7-68
Called from file "src/typing/macroContext.ml", line 512, characters 2-30
Called from file "src/typing/macroContext.ml", line 535, characters 17-40
Called from file "src/typing/macroContext.ml", line 582, characters 12-45
Called from file "src/typing/macroContext.ml", line 770, characters 43-75
Called from file "src/typing/macroContext.ml", line 800, characters 8-41
Called from file "list.ml", line 85, characters 12-15
Called from file "src/compiler/haxe.ml", line 509, characters 1-71
Called from file "src/compiler/haxe.ml", line 1073, characters 3-40
Called from file "src/compiler/haxe.ml", line 642, characters 3-11
File "src/core/globals.ml", line 117, characters 1-7: Assertion failed
```
(i'm from linux btw)

**Comment by Simn** [comment] 2023-05-30 06:22
This would require some way to reproduce the issue. The line in question is the initial function assigned to `tnull`:

```ocaml
tnull = (fun _ -> die "" __LOC__);
```

The only way I could see this happen is if lime messed with the `StdTypes` module somehow.

**Comment by Simn** [comment] 2023-11-07 10:36
Closing due to lack of response.

**Closed as completed by Simn** 2023-11-07 10:36 UTC
