### ISSUE TITLE
NativeArray.toArray() - Too many arguments

### ISSUE THREAD

**Issue by darmie** [HaxeFoundation/haxe#10551] opened 2022-01-11 06:44 UTC
Haxe version 4.2.4 static extension may be broken!

NativeArray is used in Polygonal-ds library like this 
```hx
using NativeArrayTools;
public function toArray():Array<T>
{
	return mData.toArray(0, size, []);
}
```
Inside` NativeArrayTools.hx` this is the function. 
```hx
public static function toArray<T>(src:NativeArray<T>, first:Int, len:Int, dst:Array<T>):Array<T>
```

But I get this error:
```
Too many arguments
```

When I change it to this code below, it works
```hx
public function toArray():Array<T>
{
	return NativeArrayTools.toArray(mData, 0, size, []);
}
```

**Comment by Simn** [comment] 2022-01-11 07:34
What does `$type(mData)` say?

I wonder if there's some other `toArray` function that takes priority over the static extension.

**Comment by darmie** [comment] 2022-01-11 08:06
@Simn I get this `Warning : polygonal.ds.NativeArray<polygonal.ds.ArrayList.T>`

**Comment by Simn** [comment] 2022-01-11 08:10
What target are you using?

**Comment by darmie** [comment] 2022-01-11 08:15
I have tried hl, neko, and eval 

same result...

**Comment by Simn** [comment] 2022-01-11 08:19
Well, check out https://github.com/polygonal/ds/blob/master/src/ds/NativeArray.hx

On neko it uses `neko.NativeArray` which has https://github.com/HaxeFoundation/haxe/blob/development/std/neko/NativeArray.hx#L46

On eval it uses `eval.Vector` which has https://github.com/HaxeFoundation/haxe/blob/development/std/eval/Vector.hx#L29

Are you sure this also reproduces on HL?

**Comment by darmie** [comment] 2022-01-11 08:28
@Simn yes, same on HL, even cpp

**Comment by Simn** [comment] 2022-01-11 08:30
Hmm, I don't see why this would happen for those. Are you using any macros? There's a chance that the error comes from the macro environment.

**Comment by darmie** [comment] 2022-01-11 08:38
Yes I am using Macros to convert a function into an instance of a class.... but I didn't use NativeArray directly here

```hx
macro function asComponent(fun:haxe.macro.Expr, ?options:zenflo.lib.Component.ComponentOptions) {
	return switch fun.expr {
		case EFunction(kind, f): {
				var args = f.args;
				var paramNames:Array<Dynamic> = [];
				for (p in args) {
					final portOptions = {required: true};
					portOptions.required = !p.opt;

					final pName = p.name;
					final v = {name: pName, options: portOptions};
					paramNames.push(v);
				}

				var resIsPromise = macro false;

				switch f.ret {
					case TPath(p): {
							var pName = p.name;
							var pPath = p.pack.join(".");

							trace(pPath);

							if (pPath + "." + pName == "tink.core.tink.core.Promise") {
								// Result is a tink.core.Promise, resolve and handle
								resIsPromise = macro true;
							} else {
								resIsPromise = macro false;
							}
						}
					case _: resIsPromise = macro false;
				};

				var body = macro {
					final pNames = $v{paramNames}; // [for(x in ) {name:${x.name}, options: ${x.options}}];
					var c = new zenflo.lib.Component($v{options});

					for (p in pNames) {
						c.inPorts.add(p.name, p.options);
						c.forwardBrackets[p.name] = ['out', 'error'];
					}
					if (pNames.length == 0) {
						c.inPorts.add('in', {datatype: 'bang'});
					}
					c.outPorts.add('out');
					c.outPorts.add('error');

					c.process((input, output, _) -> {
						var values:Array<String> = [];
						if (pNames.length != 0) {
							for (p in pNames) {
								if (!input.hasData(p.name)) {
									return tink.core.Promise.resolve(null);
								}
							}
							values = pNames.map((p) -> input.getData(p));
						} else {
							if (!input.hasData('in')) {
								return tink.core.Promise.resolve(null);
							}
							input.getData('in');
							values = [];
						}

						// var isPromise = ${resIsPromise};

						// switch values.length
						var func:Dynamic = ${fun}.bind();

						var res:Dynamic = Reflect.callMethod(func, func, values);
						if (Type.getClassName(Type.getClass(res)) == "tink.core.FutureTrigger") {
							res.handle(_c -> {
								switch _c {
									case tink.core.Outcome.Success(v): {
											output.sendDone(v);
										}
									case tink.core.Outcome.Failure(err): {
											output.done(err);
										}
								}
							});
						} else {
							output.sendDone(res);
						}

						return tink.core.Promise.resolve(null);
					});
					return c;
				};

				return body;
			}
		case _: macro {throw "unable to generate Component from Function";};
	}
}
```

**Comment by Simn** [comment] 2022-01-11 08:41
Try hiding the function that has the `toArray` call behind `#if !macro`, I'm pretty sure the compiler tries to type it in macro-mode and then causes the original error. I'm not sure what changed here with Haxe 4.2, but this would be within the realms of expected behavior.

**Comment by darmie** [comment] 2022-01-11 08:43
So I removed the class that's relying on Macro from the test suite, and the other test classes gave this error
```
hl.types.ArrayDyn does not have field length
polygonal/ds/ArrayList.hx:102
```

**Comment by darmie** [comment] 2022-01-11 08:50
@Simn I am not sure if i can reproduce this problem at all. All previously passed tests are now failing. So what I am going to do is to try to undo very macro implementation, if it doesn't work, i'll then maybe uninstall haxe completely and reinstall it again

**Comment by Simn** [comment] 2022-01-11 08:55
It's quite easy to reproduce:

```haxe
// Main.hx
using Main.MyTools;

typedef NativeArray<T> =
	#if eval
	eval.Vector<T>;
	#else
	Array<T>;
	#end

class MyTools {
	static public function toArray<T>(arr:NativeArray<T>, arg:Int) {}
}

macro function test() {
	return macro null;
}

function main() {
	var a:NativeArray<String> = null;
	a.toArray(1);
}
```

If you comment out the macro function, the code compiles.

So while I'm not sure what changed, this is working as intended and I'll close the issue accordingly.

**Closed as completed by Simn** 2022-01-11 08:55 UTC

**Comment by darmie** [comment] 2022-01-11 08:57
Yes you are right, it worked when I removed the macro
