### ISSUE TITLE
[display] find references on interface access specifier returns garbage

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9047] opened 2019-12-19 21:45 UTC
![](https://i.imgur.com/8hwOlrH.gif)

```haxe
function test() {
	var transform = Marker.extractMarkers("interface Main { var field(never,s{-1-}et):Int; }");
	vfs.putContent("Main.hx", transform.source);
	var args = ["Main", "-js", "main.js"];

	function parseGotoDefintion():GotoDefinitionResult {
		return haxe.Json.parse(lastResult.stderr).result;
	}

	runHaxeJson(args, DisplayMethods.FindReferences, {file: new FsPath("Main.hx"), offset: transform.markers[1], contents: transform.source});
	Assert.same([], parseGotoDefintion().result);
	runHaxeJson(args, DisplayMethods.FindReferences, {file: new FsPath("Main.hx"), offset: transform.markers[1], contents: transform.source});
	Assert.same([], parseGotoDefintion().result);
}
```

**Comment by Gama11** [comment] 2019-12-19 21:54
Probably a duplicate of https://github.com/HaxeFoundation/haxe/issues/7961 - find references seems to return garbage on any keyword / anything without a position.

**Closed as completed** 2020-01-15 13:20 UTC
Labels: bug, feature-ide
