### ISSUE TITLE
[js] js.Promise mixes up resolve and reject under certain circumstances

### ISSUE THREAD

**Issue by Drakim** [HaxeFoundation/haxe#4808] opened 2016-01-24 11:31 UTC
```haxe
import js.Promise;

class Main {
    static function main():Void {
        new A().bar(function(test:{hello:String}) {

        });
    }
}

class A {
    public function new() {}
    public function bar(_callback:{hello:String}->Void) {
        Promise.all([
            new Promise(function(resolve, reject) {resolve('test');}),
            new Promise(function(resolve, reject) {resolve('test');})
        ])
        .then(function(result) {
            //if(false) {_callback({hello: result[0]});}
        });
    }
}
```
When compiled, the output's line 15 will be like this:
`})]).then(function(result) {`

But if you uncomment my if(false) statement, output's line 15 will be like this:
`})]).then(null,function(result) {`

As you can see, a null sneaked in there and made our anonymous function into the rejection callback of our Promise.all, which isn't what we want. It's extra bizzare since the if(false) statement isn't actually included in the final code, the compiler strips it away since it never triggers, meaning that extra null is the **only** difference.

Tested with version 3.2.1, and compiled with "-main Main -js code.js"

**Comment by nadako** [comment] 2016-01-24 11:55
@fponticelli could you look into it? the typing there looks pretty complicated...

**Comment by Simn** [comment] 2016-01-24 12:09
This probably works as intended. Your `_callback` call infers the type of `result` to `Array<String>` and that's then not compatible with the first function argument which I think wants `Array<Promise<String>>`. It skips that argument (because it's optional) and tries the next one, which allows `Dynamic -> Void`, so that works.

I'm not a big fan of the argument skipping feature, but given what we have I don't think there's anything wrong here.

**Comment by Simn** [comment] 2016-01-24 12:09
... unless there's something wrong with the js.Promise definition itself.

**Comment by Drakim** [comment] 2016-01-24 12:29
If it's working as intended, then I think the intentions need to be reexamined. I got burned by this and had to spend a good part of the day hunting down why my code was silently failing.

The situation that triggers this isn't very exotic or strange, and I think this issue would pop up for pretty much anybody who uses js.Promise in Haxe at length.

**Comment by Simn** [comment] 2016-01-24 16:43
Yes but I don't think there's anything we can do about that in Haxe 3.

**Comment by back2dos** [comment] 2016-01-24 17:25
The problem is cause by `Dynamic`. As @nadako suggested elsewhere, it would be good not to rely on it so much, but use something more explicit as [`tink.core.Any`](https://github.com/haxetink/tink_core/blob/master/src/tink/core/Any.hx) to avoid such conversions where they shouldn't be. With that in place, a type error in the handler will cause the code not to compile (as it should): http://try.haxe.org/#227c7

**Comment by Simn** [comment] 2016-01-24 17:32
Even without Dynamic this skipping feature can be error-prone, especially when combined with type inference.

**Comment by back2dos** [comment] 2016-01-24 17:55
I am not disputing that, but for now we'll have to make do with the semantics as they are. While I have a certain distaste for the promise spec, I think our current externs make it far worse than it actually is. Does anyone feel responsible for them? If not, I could try my best, although I think it would be preferable if the API were reviewed by someone who intends to actually use it.

**Comment by andyli** [comment] 2016-03-22 11:04
Fixed in https://github.com/HaxeFoundation/haxe/commit/2ff0b8534b691bd927d8a80f6ef8e2879a695b1d

**Closed** 2016-03-22 11:05 UTC
