### ISSUE TITLE
toComplexType does not preserve access for TAnonymous

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#10759] opened 2022-07-19 10:53 UTC
Hi,

When using a toComplexType on an TAnonymous with a final field, the resulting CTAnonymous does not have AFinal set in  cff_access, other accessors are not correctly set as well.

(tOther.ml, convert_type)

**Comment by back2dos** [comment] 2022-07-20 06:31
Duplicate of https://github.com/HaxeFoundation/haxe/issues/6063

**Closed as completed** 2022-07-20 06:50 UTC
