### ISSUE TITLE
Mysterious Disappearance of Haxe Std Files

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#5577] opened 2016-08-31 21:17 UTC
Hey guys,

With both Haxe 3.2.1 and Haxe 3.3.0-rc1, I have been experiencing reports (and issues personally) with files mysteriously disappearing out of the Haxe std directories. I've heard from maybe three or four developers with the issue.

This affects the JS target more than others, due to the sheer number of files, but it does not discriminate.

I don't know if this is caused by FlashDevelop, the Haxe compiler, haxelib, or some other tool. It's very, very weird.

This appears to be isolated to Windows, running the matching Haxe installer again copies the missing files in and fixes the issue... for a while.

I'm hoping someone else might have seen the same symptoms, and might have an idea? No other files appear to disappear -- not haxelibs, not GIT development directories, not project source directories. Random files out of Haxe standard just disappear

**Comment by Gama11** [comment] 2016-08-31 21:58
I've had issues like this when FlashDevelop is open while the Haxe installer runs. I think it may lock some std lib files sometimes.

**Comment by jgranick** [comment] 2016-08-31 22:32
That's interesting, I seem to see this problem creep in _after_ install, when I have been building projects (from the Command Prompt, GIT Bash as well as FlashDevelop) and then suddenly a build stops working due to a missing file.

Do we think that FlashDevelop is the culprit, or something where FlashDevelop and Haxe conspire?

**Comment by Gama11** [comment] 2016-09-01 06:35
I didn't notice it until after the install either. FD locking files is just what I thought the cause might be.

I'm not sure... Always seemed like it happened pretty randomly.

**Comment by Simn** [comment] 2016-09-01 06:58
I had issues with FD locking files seemingly at random too. I don't think we can do much about this on our side, except adding some "Please close your Haxe-related applications" message to the installer which then nobody reads.

**Comment by Gama11** [comment] 2016-09-01 07:00
Some installers detect specific applications and don't let you continue until they're closed... Maybe there could be a check for the HaxeDevelop / FlashDevelop process names.

**Comment by Simn** [comment] 2016-09-05 07:10
I'm not opposed to the idea but somebody would have to look into it.

Anyway, the real issue here is not a Haxe one so I'm closing this.

**Closed by Simn** 2016-09-05 07:10 UTC

**Comment by madrazo** [comment] 2016-09-05 14:10
@jgranick  Maybe the antivirus software?

**Comment by jgranick** [comment] 2016-09-13 00:02
This happened to me again -- about two weeks after the install.

It is not locked files -- they are gone from the Haxe directory.

It may be related to using Ctrl+C to cancel builds while they are active. Is there anything in the Haxe compiler that could end up removing files if it is canceled prematurely?

(I do not have antivirus software)

**Comment by T1mL3arn** [comment] 2016-10-06 08:32
> It may be related to using Ctrl+C to cancel builds

Sometimes I stopped building in HaxeDevelop or just killed haxe process in the windows task manager.

**Comment by jgranick** [comment] 2016-11-11 21:58
Reinstalling Haxe for the second time today, due to this issue. This second time, the computer crashed. :frowning:

**Comment by petithomme** [comment] 2018-01-18 20:36
I had this issue with openfl 7.0.
I had flashdevelop opened while installing it. Everything looked fine while installing but cannot finally compile.

Reinstall haxe and openfl does the fix.

**Comment by f-rank** [comment] 2018-01-19 08:06
Had this happen after cancelling build inside FD and HD. Never did it again and no problems since.
