### ISSUE TITLE
[php] Parse error on generated code for static var pointing to a class

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5383] opened 2016-06-17 09:09 UTC
Haxe 3.3.0-rc1

The following php code:

``` haxe
class Main {
    static var sys = Sys;
    static function main() {
        sys.exit(0);
    }
}
```

fails with a `Parse error` at runtime.

**Comment by kevinresol** [comment] 2016-06-17 09:11
Generated php code: `Main::$sys::hexit(0);`
but should be `Main::$sys->hexit(0);`

**Comment by Simn** [comment] 2016-07-18 07:58
I'm too scared to fix this.

**Comment by mockey** [comment] 2016-07-19 10:40
Maybe this could be fixed in `gen_member_access`. Is there a way to check the parent of a member expression, i.e. check if `Main.sys` is `TTypeExpr` when `Main.sys.exit` is generated?

**Comment by Simn** [comment] 2016-07-19 10:50
Not really, the `sys` field could even be assigned to elsewhere.

What we have here should be something like `TField(TField(Main, "sys"), "exit")`. If I understand the scope of this issue correctly, we want to check the type of the inner TField and if that's something like "Class<Sys>` we want to generate a different field access?

**Comment by kevinresol** [comment] 2016-07-19 11:02
To understand to problem more clearly, I made the following example:

```haxe
class Main {
  
  static var s = Test;
  static var m = new Test();
  
  static function main() {
    s.s();
    m.m();
  }
}

class Test {
  public static function s() {
    trace('static');
  }
  public function new(){}
  public function m() {
    trace('member');
  }
}
```

Generates:

```php
<?php

// Generated by Haxe 3.3.0 (git build development @ 0d5c46f)
class Main {
	public function __construct(){}
	static $s;
	static $m;
	static function main() {
		Main::$s::s();
		Main::$m->m();
	}
	function __toString() { return 'Main'; }
}
Main::$s = _hx_qtype("Test");
Main::$m = new Test();

```

Note the difference in the `::` and `->` for static and member access

**Comment by Simn** [comment] 2016-07-19 11:04
And that's only a problem for static vars?

**Comment by mockey** [comment] 2016-07-19 11:22
> What we have here should be something like TField(TField(Main, "sys"), "exit"). If I understand the scope of this issue correctly, we want to check the type of the inner TField and if that's something like "Class` we want to generate a different field access?

Exactly. "exit" is handled as a static (which it actually is of course) but in this weird PHP case it needs to generate instance access. Maybe it's possible to check if "sys" is a static var and a class and turn all it's statics into instance vars?
PHP-weirdness at its best :-)

**Comment by kevinresol** [comment] 2016-07-19 11:35
Updated previous post.

Note that all `::s()` should be generated as `->s()`

**Comment by mockey** [comment] 2016-07-19 12:08
Yes, and it's the same for vars BTW. `::$varname` must be accessed as `->varname`.

**Comment by Simn** [comment] 2016-07-19 12:09
As with most PHP issues we have I don't understand the scope of this, so I'm not gonna touch it for now.

**Comment by mockey** [comment] 2016-07-19 13:42
It's not a pure PHP weirdness in this case.
The problem is this `_hx_qtype()`, which actually returns an object of `_hx_class`. But I don't understand why it turns static access into instance access. Quite complicated...

**Comment by kevinresol** [comment] 2016-07-19 13:45
In the first place,  is it valid to write consecutive double colons like
x::y::z?  Because it is complaining a parse error here.

**Comment by mockey** [comment] 2016-07-19 14:20
Something like `Test::$foo::bar()` is not valid as far as I know.
```
$foo = Test::$foo;
$foo::bar();
```
would work I think. But anyway this `_hx_class` cannot handle undefined static properties with magic methods. While it would be sort of possible for methods with `__callStatic` it's not possible for vars. There is no `__getStatic`. So I think what `hx_class` delivers, is quite the best you can get, as `Test::$foo->bar()` already works fine. The only problem is that it's not generated as it should.
As I said maybe it's a solution to take the statics of the type and move them to the instance vars.

**Comment by mockey** [comment] 2016-07-19 19:51
> As I said maybe it's a solution to take the statics of the type and move them to the instance vars.

That's of course nonsense, because the correct type is needed in other places.
So: interesting problem - no solution...

**Closed** 2016-12-13 07:10 UTC
Labels: bug, platform-php
