### ISSUE TITLE
[C#] Memory leak in StringMap/ObjectMap

### ISSUE THREAD

**Issue by Muxeu** [HaxeFoundation/haxe#5862] opened 2016-12-05 19:27 UTC
StringMaps, ObjectMaps and possible IntMaps(i did't test them) are not resizing correctly. After resize vals and _keys arrays are not cleared properly and full of duplicates of keys and values. Reproduce code:

```
class Foo {
    public function new() {
        var map:Map<String, String> = new Map();

        //fill map with 3 values
        map["key_1"] = "value_1";
        map["key_2"] = "value_2";
        map["key_3"] = "value_3";

        trace("set your break point here");
        //look at map._keys;
        //look at map.vals;

        //next set will resize map
        map["key_2"] = "value_2_changed";

        trace("set your break point here");
        //look at map._keys;
        //look at map.vals;
    }
}
```
At first "break point" all is ok. 
Keys array is:
_key_2,key_3,,key_1_
Vals array is:
_value_2,value_3,,value_1_

At second "break point":

Keys array is:
_**key_2**,key_3,,**key_2**,,,,key_1_
Vals array is:
_**value_2**,value_3,,**value_2_changed**,,,,value_1_

So, GC will never collect _value_2_.
Even if to call "remove" function duplicates stay at place.

**Comment by nadako** [comment] 2016-12-06 11:37
What version are you on? I just tested the latest one with VS debugger. The arrays are resized, but there are no duplicates.

**Comment by nadako** [comment] 2016-12-06 11:39
So this looks like a duplicate of #3818, which means you're using haxe 3.1. Try with latest please!

**Comment by Muxeu** [comment] 2016-12-06 11:47
I use version 3.3.0_rc1. I can't use version 3.4 due macro include bug. Version 3.3.0 has this issue.

**Comment by nadako** [comment] 2016-12-06 11:54
Hmm. That's weird, because the commit linked to that issue says it's in 3.2.0-rc1 and later versions. Could you check your example in 3.4rc?

**Comment by nadako** [comment] 2016-12-06 11:57
> The arrays are resized, but there are no duplicates.
@waneck shouldn't there be no array resizing as well?

**Comment by Muxeu** [comment] 2016-12-06 12:00
Ok, i'll check at 3.4.

I looked in https://github.com/HaxeFoundation/haxe/issues/3818 and it sounds similar, but in my case Maps are working perfectly (no errors or collisions). Problem only in unnessary refs to stored data.

If i continue setting maps with new keys duplicates will be rewrited by new data.

**Comment by Muxeu** [comment] 2016-12-06 12:08
Just tested on 3.4
https://monosnap.com/file/HutxrFWDc7fsmE2YXetrtKqzMQXFDI
https://monosnap.com/file/QoaumKZdZtsYRPDJDdl0YI7Mn0iwur

Generated C# code:
http://pastebin.com/wVHKAKhd

**Comment by nadako** [comment] 2016-12-06 12:18
Hmm...

**Comment by nadako** [comment] 2016-12-06 14:08
Weird, for me, the generated C# code is a bit different (note that there's no reudndant `as object` casts):
```cs
global::haxe.ds.StringMap<object> map = new global::haxe.ds.StringMap<object>();
map.@set("key_1", "value_1");
map.@set("key_2", "value_2");
map.@set("key_3", "value_3");
global::haxe.Log.trace.__hx_invoke2_o(default(double), "set your break point here", default(double), new global::haxe.lang.DynamicObject(new int[]{302979532, 1547539107, 1648581351}, new object[]{"new", "Foo", "Main.hx"}, new int[]{1981972957}, new double[]{((double) (11) )}));
map.@set("key_2", "value_2_changed");
global::haxe.Log.trace.__hx_invoke2_o(default(double), "set your break point here", default(double), new global::haxe.lang.DynamicObject(new int[]{302979532, 1547539107, 1648581351}, new object[]{"new", "Foo", "Main.hx"}, new int[]{1981972957}, new double[]{((double) (18) )}));
```
What's your compiler arguments?

**Comment by waneck** [comment] 2016-12-06 14:33
Does that only happen with the key values?

**Comment by Muxeu** [comment] 2016-12-06 14:47
@nadako, i use "-D fast-cast". Other args:
-D no-compilation
-D real-position
-D no-root

**Closed** 2017-06-26 01:16 UTC
Labels: bug, platform-cs
