### ISSUE TITLE
Compilation won't complete

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6723] opened 2017-10-30 23:36 UTC
This is regression, worked on 3.4.x

Tested versions:
3efc28e
4.0.0-preview.1
4.0.0-preview.2

Compilation of the tests of https://github.com/haxetink/tink_json/commit/2c25c6813e82ddc4ca7c414894a1c367c113050d will never complete. No output, no error, just stuck.

FWIW, I also uploaded the process sample here: https://pastebin.com/Sf3Uqrum 

cc @back2dos

**Comment by back2dos** [comment] 2018-03-12 10:39
The issue is with `Null` no longer being dealt with in `Context.follow`. Fixed in tink_macro, so this can be closed.

**Closed** 2018-03-12 10:43 UTC
