### ISSUE TITLE
[Lua] Add support for varargs "..."

### ISSUE THREAD

**Issue by prnxdev** [HaxeFoundation/haxe#9267] opened 2020-03-24 19:44 UTC
Hi,

I don't see a way to support for ... in final lua code but I see that there is lua.Lua.args which is using this behavior so I think it could be supported.

**Comment by jdonaldson** [comment] 2020-03-25 17:23
Duplicate of : https://github.com/HaxeFoundation/haxe/issues/7306

**Closed as completed by jdonaldson** 2020-03-25 17:23 UTC
