### ISSUE TITLE
RegExp error generating garbage with replace()

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFoundation/haxe#6573] opened 2017-09-11 20:43 UTC
This code will generate inconsistent behavior across flash, js, and cpp targets:

```haxe
        var str = "IッCHOO";
        var bytes:Bytes = Bytes.ofString(str);
    	
        trace(str);
        for(i in 0...bytes.length)
        {
        	trace(i+"="+bytes.get(i));
        }
        
        str = new EReg("([^AEIOUN])\\1", "g").replace(str, "ッ$1");
        
        bytes = Bytes.ofString(str);
    	trace(str);
    	for(i in 0...bytes.length)
        {
        	trace(i+"="+bytes.get(i));
        }
```

The correct output is:
```
   IッCHOO
   0=73
   1=227
   2=131
   3=131
   4=67
   5=72
   6=79
   7=79
   IッCHOO
   0=73
   1=227
   2=131
   3=131
   4=67
   5=72
   6=79
   7=79
```

Which is generated on flash/js

The incorrect output generated by cpp is:
```
   IッCHOO
   i=73
   i=227
   i=131
   i=131
   i=67
   i=72
   i=79
   i=79
   I䣃ÃCHOO
   i=73
   i=227
   i=227
   i=131
   i=131
   i=131
   i=67
   i=72
   i=79
   i=79
```

I encountered this while trying to port this [Hepburn romanization library](https://github.com/lovell/hepburn) to Haxe. Right now I'm passing all the tests except for one:

https://github.com/larsiusprime/fireglyph/blob/master/fireglyph/japanese/Hepburn.hx#L480

And I've narrowed it down to this line of code in my implementation:
https://github.com/larsiusprime/fireglyph/blob/master/fireglyph/japanese/Hepburn.hx#L117

From this, I generated the above minimal reproduction sample code.

All the tests pass and I get the correct output on JS/Flash, but not on CPP. I therefore suspect this might be a bug in the Haxe implementation of EReg for the CPP target in this edge case. Printing out the code points hints at the cause -- one can see that certain bytes are repeated in the erroneous output (227 and 131).

Here's the try.haxe version of the reproduction code:

https://try.haxe.org/#88C6c

Hopefully this is a real bug and I'm not just being crazy/stupid...

**Comment by ncannasse** [comment] 2017-09-12 09:35
I think it comes from Unicode handling, maybe @hughsando can comment

**Comment by larsiusprime** [comment] 2017-09-12 13:36
Quite possibly -- is there a way to feed the RegExp engine a unicode-safe string replacement function to use as it's primitive? Surely whatever it does internally eventually boils down to one or more operations of "Replace substring of string s1 from index X to index Y with string s2", which could be swapped out with a unicode-aware string replace function, such as the one in Unifill.

**Comment by hughsando** [comment] 2017-09-19 02:27
The problem is that the pattern ("match repeated character") is triggering on the repeated '131' byte in the utf8 string.  This can be fixed with the 'u' = utf8 option when creating the regexp.
I guess I could just force this on for hxcpp.

**Comment by larsiusprime** [comment] 2017-09-19 03:00
Cool, is that option documented anywhere?

**Comment by Simn** [comment] 2017-09-19 06:34
https://haxe.org/manual/std-regex.html

I'm remembering the flags by thinking of Gimsu Regex as a video game character...

**Comment by Simn** [comment] 2018-09-18 06:21
We're going to deprecate the `u` flag and make it the default for Haxe 4.

@hughsando: You probably want both the UTF8 and UCP flags for the hxcpp regexes. See https://github.com/HaxeFoundation/haxe/commit/33a7bbfaed895264eff8f888842b1fe6fa7a04a4

**Comment by Simn** [comment] 2018-10-02 15:22
This should be fine now.

**Closed by Simn** 2018-10-02 15:22 UTC
Labels: platform-cpp, unicode
