### ISSUE TITLE
web dispatcher and python3 target

### ISSUE THREAD

**Issue by francescoagati** [HaxeFoundation/haxe#4295] opened 2015-06-06 14:34 UTC
Hi,
i get this error try using haxe web dispatcher
```
Traceback (most recent call last):
  File "bin/main.py", line 3766, in <module>
    Main.main()
  File "bin/main.py", line 227, in main
    haxe_web_Dispatch("/hello", _hx_map).runtimeDispatch(haxe_web_Dispatch.extractConfig(router))
  File "bin/main.py", line 2519, in extractConfig
    tmp3 = HxOverrides.arrayGet(Reflect.field(dc,"dispatchConfig"), 0)
AttributeError: type object 'HxOverrides' has no attribute 'arrayGet'

```
and the haxe code 

```
class Router {
  public var output:String;
  public function new() {};
  public function doHello() {
    output = "Hello";
  }

}

class Main {
  public static function main() {
    var router = new Router();
    var map = new haxe.ds.StringMap<String>();
    haxe.web.Dispatch.run("/hello",map,router);

  }
}
```

and the code generated that trigger the error
```
	@staticmethod
	def extractConfig(obj):
		c = Type.getClass(obj)
		dc = haxe_rtti_Meta.getType(c)
		m = HxOverrides.arrayGet(Reflect.field(dc,"dispatchConfig"), 0)
		if Std._hx_is(m,str):
			m = haxe_Unserializer.run(m)
			HxOverrides.arraySet(Reflect.field(dc,"dispatchConfig"),0,m)
		return _hx_AnonObject({'obj': obj, 'rules': m})

```

**Comment by Simn** [comment] 2015-06-06 15:33
@frabbit: The problem is that DCE only checks for field access on Dynamic, not `Dynamic<T>`:

```
class Main {
	static public function main() {
		var dc:Dynamic<Array<Dynamic>> = {a: [0]};
		dc.a[0];
	}
}
```

This means that the `dynamic_array_read` feature is never activated.

**Comment by francescoagati** [comment] 2015-06-06 15:39
Yes in effect  now i have added "-dce no" at it work correctly.

**Comment by francescoagati** [comment] 2015-06-06 15:54
this is the code used for testing.
https://gist.github.com/francescoagati/bf6f43561ebe22cc8e0f

**Comment by Simn** [comment] 2015-06-07 05:46
It's very nice to see someone trying something like this on the python target!

**Comment by francescoagati** [comment] 2015-06-07 13:58
thanks. you can see also this repository that have a target in python
https://github.com/francescoagati/haxe-testing-erazor

**Comment by frabbit** [comment] 2015-06-19 12:49
@simn, i don't think it's because dynamic_array_read, `dc.a` is actually typed as `Array<Dynamic>` which should not generate `HxOverrides.arrayGet` at all.

**Comment by Simn** [comment] 2015-06-19 13:34
You're right, I managed to misread my own example. Here's the dump output:

```
			[Var dc(6707):Dynamic<list<Dynamic>>] [ObjectDecl:{ a : list<Dynamic> }] a: [ArrayDecl:list<Dynamic>] [Const 0:Int]
			[Array:Dynamic]
				[Field:list<Dynamic>]
					[Local dc(6707):Dynamic<list<Dynamic>>]
					[FDynamic:list<Dynamic>] a
				[Const 0:Int]
```

That looks correct so it must still be something wrong in genpy.

**Comment by frabbit** [comment] 2015-06-22 12:05
closed by https://github.com/HaxeFoundation/haxe/commit/8a24093f20ff6e1f101e7b2069a3d73c0be11248

**Closed by frabbit** 2015-06-22 12:05 UTC
Labels: platform-python
