### ISSUE TITLE
3.2 Map regressions on native

### ISSUE THREAD

**Issue by dazKind** [HaxeFoundation/haxe#4050] opened 2015-03-18 17:42 UTC
I'm currently compiling my engine codebase to native with latest haxe and hxcpp and noticed some weird regressions concerning Map.

Problem 1: Tracing an empty map prints `null` on native while it does print `{}` on the other targets. It seems like there is a bug in the toString() function since an explicit check for `== null` returns false.

Problem 2: Iterating the keys of a map and accessing the value through the key in the loop will return `null` when the KeyType is an interface. If you use a class as KeyType it works as expected.

Here is a minimal example illustrating the issues. 

*Test.hx*:
```haxe

interface IObject {}

class Object implements IObject {
   public function new() {}
}

class Test
{
   public static function main()
   {
      // Test 1: simple trace of an empty map
      var tmp = new Map<Int, String>();
      trace(tmp);
      trace(tmp == null);

      // Test 2: ObjectMap with Interface as keytype and keys()-loop with value access
      var myObject = new Object();
      var tmp2 = new Map<IObject, Array<String>>();

      tmp2.set(myObject, ["foo", "bar"]);
      trace(tmp2);

      for (k in tmp2.keys()) {
         var value = tmp2.get(k);
         trace(value);
         trace(value == null);
      }
   }
}
```
*build.hxml:*
```
-main Test
-cpp cpp
-debug 

--next

-main Test
-neko Test.n
-debug 
```

*output:*
```
$ neko Test.n
Test.hx:14: {}
Test.hx:15: false
Test.hx:22: {{ __id__ => 0 } => [foo,bar]}
Test.hx:26: [foo,bar]
Test.hx:27: false

$ cpp/Test-debug.exe
Test.hx:14: null
Test.hx:15: false
Test.hx:22: { Object => [foo,bar]}
Test.hx:26: null
Test.hx:27: true
```

**Comment by Simn** [comment] 2015-03-18 18:55
@hughsando: This looks like a real regression so it has high priority.

**Comment by hughsando** [comment] 2015-03-19 00:25
Fixed in hxcpp.

**Comment by Simn** [comment] 2015-03-19 08:44
Need a test.

**Closed** 2015-03-19 08:50 UTC
Labels: platform-cpp, priority-urgent, regression

**Comment by Simn** [comment] 2015-03-19 08:51
@dazKind: Thanks for this wonderful code example, I wish all issue reports were like that.

**Comment by dazKind** [comment] 2015-03-19 23:34
You're welcome :)
