### ISSUE TITLE
[display] hover claims that blocks with return values are typed as Dynamic

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8008] opened 2019-03-17 14:11 UTC
Hovering over the block or the `return` keyword here shows `Dynamic`. I guess that's some compiler internals that are exposed here, but it probably shouldn't be shown to the user, since there's a high potential for confusion.

![](https://i.imgur.com/g0QQ5wy.png)

```haxe
class Main {
	static function main() {}

	function foo() {
		return 0;
	}
}
```

Without a `return`, it's fine (shows `Void`).

**Comment by Simn** [comment] 2019-03-17 14:16
Well, that's correct. I don't see what we could do about this, or why we should do something about this in the first place.

**Comment by Gama11** [comment] 2019-03-17 14:41
Because it makes it look like the code isn't statically typed? Especially people who are new to Haxe often have a hard time getting over their feat of type inference, this surely doesn't help.

It'd be better not to have a hover hint at all here if all it's going to show is `Void` or `Dynamic`.

**Comment by Simn** [comment] 2019-03-17 14:52
But the blocks' type _is_ Dynamic. This is important to understand in the everything-is-an-expression-context because it's the reason `var x = cond ? 1 : return 2` works. Of course it would be better if we had a bottom type, but we don't. And if we had, it would likely be no less confusing to show it.

**Comment by Gama11** [comment] 2019-03-17 18:43
Hm.. I wonder how others feel about this. :)

**Comment by nadako** [comment] 2019-03-17 20:40
I think we have more important stuff to care about, but then again, maybe we can say that the expected type for the function expression is `Void` and bind the monomorph to it instead of Dynamic?

**Comment by Simn** [comment] 2019-03-17 21:52
That's a separate discussion IMO. The proposal here is to hide the exact typing from the user.

**Comment by Simn** [comment] 2019-05-22 11:09
I'm closing this because I consider it working as intended. I don't want to hide details here.

**Closed as completed by Simn** 2019-05-22 11:09 UTC
Labels: bug, feature-ide
