### ISSUE TITLE
[js] haxe.ds.ObjectMap regression with -D analyzer

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3845] opened 2015-02-08 20:32 UTC
The following code will trace `1` with `-D analyzer` and `2` without it:
```haxe
class Main {
    static function main() {
        var o = {};

        var m = new haxe.ds.ObjectMap();
        m.set(o, 1);
        m.set(o, 2);

        trace(m.get(o));
    }
}
```

The problem is that this code from the `set` method:
```haxe
var id : Int = untyped key.__id__ || assignId(key);
```
will be generated as:
```js
var id = !key.__id__?key.__id__ = ++haxe_ds_ObjectMap.count:true
```
so on second `set` call, the `id` will be `true` instead of `key.__id__`

This is weird, because I thought analyzer ignores untyped blocks.

**Comment by Simn** [comment] 2015-02-14 12:08
The `untyped` is not communicated to the typed AST. The analyzer only cancels when it comes across unbound variables which do not exist here.

I guess we could just mark the current field when we come across an EUntyped.

**Comment by Simn** [comment] 2015-02-14 12:35
Note: this is not a regression because there was no analyzer in the last stable release. I'm going to fix it anyway.

**Comment by nadako** [comment] 2015-02-16 11:57
This brings back a ton of `$this` closures on JS :-)

There are quite large functions that have harmless untyped expressions (e.g `haxe.Serializer.serialize`), and ignoring the whole function because of that expr doesn't seem to be a good option (and looks more like real regression).

As you noted, this particular `ObjectMap` issue is not really a regression, so maybe we should just manually add needed `@:analyzer` flags to the specific methods and document the analyzer behaviour  wrt untyped.

So I propose reverting the fix and fixing `ObjectMap` instead.

**Comment by Simn** [comment] 2015-02-16 12:22
The problem here is the "harmless": the analyzer cannot determine what untyped is harmless and what is not, so it conservatively assumes that all untyped is harmful.

**Comment by nadako** [comment] 2015-02-16 12:29
what stops us to only ignoring the untyped expression itself? the `__js__`/`__cs__` and friends, i guess? if we had that "just insert the target source here" call standartized somehow, we could ignore only blocks that have those.
for the time being, i'm think fixing specific cases like 8355f6fbe7f4e6cdbe660f3bfc9b5675cf866e6d and 34640bae82571bcebe79ff8a100b0c740607e628 is the way to go

**Comment by Simn** [comment] 2015-02-16 12:31
Yes any `untyped` expression could have arbitrary side-effects which affects the otherwise sanely typed code. Something trivial like `untyped x++` could completely throw constant propagation off.

**Comment by nadako** [comment] 2015-02-16 12:38
I think we could still apply "some" simplfiication (e.g. `propagate_complex_rhs`), but I agree that it's better to incapsulate untyped stuff in an (inline) method that is skipped by the analyzer. One thing I would like to see is some `-D` flag to make analyzer warn about methods that are ignored because of untyped and not because of `@:analyzer` settings, so one could easily fix their code.

**Comment by Simn** [comment] 2015-02-20 10:00
I'm not sure what you want me to do here so I'll close it again.

**Closed by Simn** 2015-02-20 10:00 UTC
Labels: bug, feature-analyzer, platform-javascript
