### ISSUE TITLE
Regression Int vs UInt

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3773] opened 2015-01-19 08:51 UTC
```
class Test {
static function main() {
       var pos : UInt = 2;
       $type(1 - pos);
}
}
```

Up to now, the calculus was typed as Int but it's now UInt. This will also affect the result (should overflow with UInt because of the negative value). The problem here is that we consider 1 as an UInt.

I wonder if that's ok this way. The actual error I got out of this was about a comparison later that was complaining about cannot compare Int and UInt.

But let's say I was doing instead : `if( 1-pos >= 0 )`, this will become always true while it was not the case before.

This needs at least to be documented.

**Comment by waneck** [comment] 2015-01-19 15:18
Actually this behaviour was exceptional to Flash and C#, which are the only targets that have native UInt support. This was changed when closing #2990 . When closing it, I've tried to add a test for each operation involving UInt and making sure the compiler sees the same types for all targets.
IMO we should make both the native UInt target and the ones that use the abstract to render the same types resulting from ops. I also considered (UInt + Int) to be UInt (like the actual C# compiler does).

What should we do with this?

**Comment by Simn** [comment] 2015-01-19 15:35
What target and Haxe version are we talking about here? I thought this has always been typed as UInt...

**Comment by waneck** [comment] 2015-01-19 15:41
Yeah, I thought so too. But because in C# and Flash9, we have native `UInt`s, they used the default operation returns (like in #2990, which `UInt << Int` rendered `Int`). This was only changed yesterday - so any version before it was typed as `Int`.

**Comment by Simn** [comment] 2015-01-19 15:42
Yes but this issue is about subtraction. I can't find a Haxe version/target where this is typed as Int.

**Comment by waneck** [comment] 2015-01-19 15:45
Oh yeah, you're right - Nicolas' example was already typed as UInt

**Comment by ncannasse** [comment] 2015-01-19 19:23
The actual regression was fixed here after I got an error after updating Haxe code:
https://github.com/ncannasse/heaps/commit/1d92b50b8d0ebb1ed550b7b1f9a9e20a6cdce49a

**Comment by Simn** [comment] 2015-01-19 19:25
I see, so it's about the shifts after all.

**Comment by waneck** [comment] 2015-01-19 19:41
Yeah. I guess we either:
* say that the old behaviour was the correct one, and change the UInt abstract implementation so other non-UInt targets have the same typing. I feel it's very strange that `(UInt << Int)`'s result is `Int` though. This will still introduce regressions for the non-UInt targets' old behaviour
* define that the new behaviour is correct

**Comment by Simn** [comment] 2015-01-19 19:42
I've started a breaking-changes page here: https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-3.2.0

What worries me is that C# and Flash agreed that it should be Int. Makes me wonder if we're missing some obvious reason for that?

**Comment by waneck** [comment] 2015-01-19 19:56
It came from the @:coreType behaviour when you have from/to Int . It works the same way for `Single`, which is the 32-bit Float.

**Comment by waneck** [comment] 2015-01-19 20:01
It came from here, I think: https://github.com/HaxeFoundation/haxe/blob/development/typer.ml#L2092

**Comment by Simn** [comment] 2015-01-19 20:52
I see, in that case I think we're done here.

**Closed** 2015-02-14 15:16 UTC
