### ISSUE TITLE
DCE with static init

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3916] opened 2015-02-24 17:29 UTC
```
class A {
     var foo = new B();
}
```

It seems that `foo` is DCE, which is fine, but then the new B() is never called.

**Comment by Simn** [comment] 2015-02-24 17:31
I don't get it, that works as intended (by me).

**Comment by nadako** [comment] 2015-02-24 17:33
`new B()` should be called whenever `new A()` is called, which is never in this case, as `A` has no constructor, right?

**Comment by ncannasse** [comment] 2015-02-24 20:48
@Simn for me there should be no difference between putting the new B() in the constructor or in the member var initialization. Both are side effects that should not be DCE'ed.

**Comment by ncannasse** [comment] 2015-02-24 20:49
@nadako of course I meant in the case A has a constructor, is compiled, etc.

**Comment by Simn** [comment] 2015-02-24 20:51
This would mean that every field with an initialization expression is always kept (because that's what happens when you assign to it in the constructor too). I don't see what we gain from that other than a weaker DCE.

**Comment by ncannasse** [comment] 2015-02-24 20:55
@Simn as I said, I don't care about keeping the field, but I want to keep the new B() side effect ;)

**Comment by ncannasse** [comment] 2015-02-24 20:55
@Simn or is it already removed in case the field is DCE'd ?

**Comment by Simn** [comment] 2015-02-24 20:57
But we don't do that for statics either...

**Comment by Simn** [comment] 2015-02-24 20:59
I consider the fact that the initialization ends up in the constructor an implementation detail which shouldn't surface in this way.

**Closed** 2016-12-14 21:42 UTC
