### ISSUE TITLE
[eval] If one thread is blocked other treads stop too

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8525] opened 2019-07-08 18:54 UTC
```haxe
class Main {
	public static function main() {
		var p = new sys.io.Process('haxe', ['-cmd', 'sleep 10']);
		sys.thread.Thread.create(() -> {
			Sys.println('hello');
			Sys.sleep(0.1);
			Sys.println('world'); // this is never printed
		});
		Sys.sleep(0.1);
		p.stdout.readByte();
	}
}
```
```
$ haxe -cp src --run Main
hello
<... hangs for 10 seconds ...>
/usr/share/haxe/std/eval/_std/sys/io/Process.hx:93: characters 4-9 : Uncaught exception Eof
/usr/share/haxe/std/eval/_std/sys/io/Process.hx:80: characters 7-27 : Called from here
src/Main.hx:18: characters 3-22 : Called from here
```

**Comment by Simn** [comment] 2019-07-09 06:35
I don't think there's anything I can do here while Haxe is written in OCaml.

**Comment by ncannasse** [comment] 2019-07-10 08:17
That's strange, because performing I/O should release the global interpreter lock, allowing the other thread to execute.

**Comment by Simn** [comment] 2019-07-30 12:45
The only thing we could do here is place some strategic `Thread.yield()` calls. In this particular case, the problem is that we're still using your Thread implementation from 1789, so OCaml has no idea what exactly we're doing.

My concern is that this would require yielding in a lot of places. I'm inclined to not touch this at all until we have a proper sys API in 4.1.

**Comment by Simn** [comment] 2019-07-30 12:53
Actually, yielding isn't going to help here either because the `Sys.sleep` also yields, so depending on who yields first we just end up with the same situation.

**Comment by Simn** [comment] 2020-06-05 16:54
I'm closing this because I still don't think there's anything I can do here.

**Closed as completed by Simn** 2020-06-05 16:54 UTC
Labels: unresolved, platform-eval
