### ISSUE TITLE
Java TestThreads silently fails

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8131] opened 2019-04-09 11:47 UTC
```bash
$ cd tests/threads
$ haxe --java test build.hxml
$ java --jar test/Main.jar
...
Running TestThreads
$ echo "$?"
0
```

The test runner should output some text ("all tests ok"). The exit code is non-error `0`, even though it seems to be a crash. Any tests following `TestThreads` are not run.

**Comment by Simn** [comment] 2019-04-10 12:57
There must be some interaction with utest going on here. It works fine if we run `TestThreads` outside utest, in which case it happily goes through all 144 permutations of the tests. Under utest it just stops after 26. I also checked again on rc.2 and it looks I was wrong. It stops there too, although it goes to 41 or 42 tests there.

@RealyUniqueName: Any idea what could be going on here? The test is set-up like this:

```haxe
	@:timeout(40000)
	function testSort(async:Async) {
		Thread.create(() -> {
			doTestSort();
			async.done();
		});
	}
```

**Comment by RealyUniqueName** [comment] 2019-04-10 13:45
Looks ok. I'll investigate

**Comment by kevinresol** [comment] 2019-04-10 16:02
Calling `async.done()` inside a thread will cause all the remaining code to be run in that thread, no?

**Comment by RealyUniqueName** [comment] 2019-04-10 16:04
Yes, but `async.done()` is not even executed. The app exits somewhere inside of `ThreadSort.run()`

**Comment by Simn** [comment] 2019-04-10 16:05
I think this reproduces even without the extra thread.

**Comment by RealyUniqueName** [comment] 2019-04-10 16:16
I can reproduce it even without utest.

**Comment by RealyUniqueName** [comment] 2019-04-10 16:32
Apparently, Java just doesn't wait for child threads to complete.
If I add `haxe.Timer.delay(() -> trace('done'), 10 * 60 * 1000);` to the end of  `static main`, then everything works as expected.

**Comment by RealyUniqueName** [comment] 2019-04-10 16:36
I'm not sure if we should workaround this behavior.

**Comment by RealyUniqueName** [comment] 2019-04-10 17:12
Well, we explicitly tell java to not wait for threads :)

https://github.com/HaxeFoundation/haxe/blob/c586004af4e3ef7a064136afdb64dbb4fa0fbce3/std/java/_std/sys/thread/Thread.hx#L118-L124
See `setDaemon(true)`. Commenting it out fixes the issue.

**Comment by Aurel300** [comment] 2019-04-10 17:37
But wait, here:

https://github.com/HaxeFoundation/haxe/commit/df45237db3e568340c00bcf5889c5e51dda612c2

The line was added specifically for consistency with cpp and neko. Why does this test not fail on cpp and neko?

**Comment by RealyUniqueName** [comment] 2019-04-10 18:13
Idk. Maybe something has changed since 2014 :)
Just checked: `Sys.exit()` correctly shuts down java app.

**Comment by Aurel300** [comment] 2019-04-10 18:20
But that's not the issue…

```haxe
class Main {
  public static function main():Void {
    sys.thread.Thread.create(() -> while (true) Sys.sleep(1));
  }
}
```

This needs to exit, not wait for the thread. Neko and Cpp do it this way currently.

**Comment by Aurel300** [comment] 2019-04-10 18:23
The entire point of `async.done` is to allow a test running in another thread to notify the test runner that the test has finished. The issue (I assume), is that the test runner does not correctly wait for the call to `async.done`, or it is waiting for it in a separate thread that gets killed off.

**Comment by Simn** [comment] 2019-04-10 18:41
We shouldn't wait for child threads, but shouldn't utest keep things alive until that `async` is resolved? I thought that was the whole point of it.

**Comment by RealyUniqueName** [comment] 2019-04-10 18:41
I see.
But the code handling `async.done` is the same for all targets. I'll dig deeper.

**Comment by RealyUniqueName** [comment] 2019-04-10 21:34
So, I'm dodging this on the utest side by setting up a `Timer.delay()` repeatedly until all the tests are finished:
https://github.com/haxe-utest/utest/blob/aa39baf189e8bc4d14b93b2056a06a017f739276/src/utest/Runner.hx#L276-L282

However, `async` timeout is also set up using `Timer.delay()` from the main thread. And I don't know why Java target does not wait for `Timer.delay()` of `async`, but waits for `Time.delay()` from the code above. This may be a sign of a bug with timers in java target.

**Comment by RealyUniqueName** [comment] 2019-04-10 21:35
Closed by 8fd98c94ae3995b8ed053bb94e1d3cb8c552f516

**Closed as completed by RealyUniqueName** 2019-04-10 21:35 UTC
Labels: platform-java, regression

**Comment by nanjizal** [comment] 2019-04-11 00:43
https://github.com/HaxeFoundation/haxe/blob/development/std/java/_std/Sys.hx#L147
Have a feeling I was ignored when I suggested that haxe.Timer should use nanoTimer internally?
Is this any use?
https://github.com/nanjizal/JigsawX/blob/master/jigsawxtargets/hxjava/UpdateTask.hx

**Comment by RealyUniqueName** [comment] 2019-04-11 07:50
I don't see how would that help.
`haxe.Timer` is specified to have milliseconds precision anyway.

**Comment by ncannasse** [comment] 2019-04-11 20:45
> We shouldn't wait for child threads

Ideally we should wait until all user-created threads are terminated before exiting.
We should however be able to mark a thread as "not blocking" so we can terminate before it ends.
We already do that for our haxe.MainLoop events (see `isBlocking`)

**Comment by Simn** [comment] 2019-04-11 20:47
Why would we suddenly switch the default behavior here? None of our threaded targets wait for children, so if anything we should make that an opt-in behavior.

**Comment by ncannasse** [comment] 2019-04-11 20:49
Making sure that all threads created by potentially various sources are terminated is very hard for the end user, so this is something the Haxe API should provide as part of its Thread API. The way Java does actually by having daemon=false by default. I think it's the right choice, although might require a bit of additional support for other platforms.

**Comment by ncannasse** [comment] 2019-04-11 20:49
PS: you can always force-exit with Sys.exit if you need it

**Comment by Simn** [comment] 2019-04-11 20:51
I acknowledge the usefulness of this, I just don't see why we should randomly switch the default behavior here...

**Comment by ncannasse** [comment] 2019-04-11 21:14
It's not random, it's better design by default. I'm not saying that we should do it now, but at some point yes.
