### ISSUE TITLE
EReg replace escapes replacement placeholders

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxe#3430] opened 2014-10-01 17:37 UTC
given 

``` haxe
var s = reg.replace(text, "\\$1");
```

`s` will contain $1 instead of the replacement prefixed with `\`

On the other hand this works:

``` haxe
var s = reg.map(text, function(ereg) return  "\\" + ereg.matched(1));
```

**Comment by ncannasse** [comment] 2014-10-01 19:41
Ah, I guess that's a Java specific, which means it should do the `\` -> `\\` in EReg

**Comment by ncannasse** [comment] 2014-10-01 21:02
@waneck it seems that you should use `.split("\$").join("\\$")` in EReg in Java so that `\$` is not considered escaping the $ char (I think we use $$ for that)

**Comment by Simn** [comment] 2015-03-24 13:25
I'm assuming that this is not urgent.

**Comment by waneck** [comment] 2016-04-03 09:04
I've tested this on Neko, PHP, Java, C++, C#, and they all failed with the example:
```haxe
    var ereg = ~/\d+/g;
    var s = ereg.replace('a1234b12', "\\$1");
    eq(s, 'a\\1234b\\12');
```

I couldn't get to test on JS, but I suspect it will be the only one that shows the above behaviour, so perhaps it should be it who gets fixed?

**Comment by ncannasse** [comment] 2016-04-03 10:26
In JS:
```js
r = new RegExp("\\d+");
"a1234b12".replace(r,"\\$1")
> "a\$1b12"
```

It seems good to me to be able to escape $1 in replace, if other platforms don't support it we should support it correctly.

**Comment by ncannasse** [comment] 2016-04-03 10:28
Reading again, I'm not sure I've made myself clear : we should follow JS behavior on all platforms

**Comment by ncannasse** [comment] 2016-04-03 11:48
Uhm, ok I'm reading again again and I understand now better

The character used to escape $ in another $. The example @waneck mentioned should not work anyway because there's not capture parenthesis, so $1 is not defined.

Here's the expected behavior:
```haxe
        trace( ~/\d+/g.replace("a1234b12","$1") == "a$1b$1" );
        trace( ~/(\d+)/g.replace("a1234b12","$1") == "a1234b12" );
        trace( ~/(\d+)/g.replace("a1234b12","\\$1") == "a\\1234b\\12" );
        trace( ~/(\d+)/g.replace("a1234b12","$$1") == "a$1b$1" );
```

@Simn could you check platforms status regarding unit tests for these?

**Comment by Simn** [comment] 2016-04-03 11:48
Yes but not for 3.3.

**Comment by Simn** [comment] 2018-04-25 08:15
> `trace( ~/\d+/g.replace("a1234b12","$1") == "a$1b$1" );`

According to our documentation: "If no such sub-group exists, the replacement is unspecified."

Do we want to specify this after all?

**Comment by ncannasse** [comment] 2018-04-27 14:51
If we can specify it easily ( == *if we can change without too much hassle our current implementation and if native targets regexp are happy with it*) then we should specify it. If not, we can leave the first `trace` of my examples unspecified

**Comment by Simn** [comment] 2018-08-28 15:34
Let's leave the first one unspecified. It would require significant work for me to support this on eval because that's just not how PCRE works. The alternative would be to have a custom implementation like neko and cpp do, but these are pretty insane.

I briefly checked and it fails at least on PHP and HL too.

**Comment by Simn** [comment] 2018-09-18 07:03
One tests fails on Java:

```
src/unitstd/EReg.unit.hx:119: a$1b$1 should be a\1234b\12
```

And one on lua:

```
src/unitstd/EReg.unit.hx:120: a$1234b$12 should be a$1b$1
```

See #7419 for the branch where I added them.

**Comment by jdonaldson** [comment] 2018-09-27 17:56
Lua fix is in : https://github.com/HaxeFoundation/haxe/pull/7419/commits/fa4399b8244885c2c447657bc71a6625e73861c5

**Comment by Simn** [comment] 2018-10-02 07:35
Java still fails this test, which is currently commented out in EReg.unit.hx: `~/(\d+)/g.replace("a1234b12","\\$1") == "a\\1234b\\12";`

**Closed** 2019-10-08 07:16 UTC
Labels: bug, platform-java
