### ISSUE TITLE
haxe.CallStack.exceptionStack() does not work on Haxe 4.1.4, js target

### ISSUE THREAD

**Issue by TC218** [HaxeFoundation/haxe#9968] opened 2020-11-29 06:28 UTC
https://gist.github.com/MT4000/d959fab5e88c47bc92bf042fb9077d0e

**Comment by RealyUniqueName** [comment] 2020-12-01 15:17
I can't reproduce it neither with Haxe 4.1.4 nor with the latest development version.

**Comment by RealyUniqueName** [comment] 2020-12-01 15:38
Fixed in db0fa95

**Closed as completed by RealyUniqueName** 2020-12-01 15:38 UTC
Labels: bug, platform-javascript
