### ISSUE TITLE
Error: Error: Cannot process [(file]: Invalid parameter : (file

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#10670] opened 2022-04-05 08:54 UTC
installation:
```
haxelib git hxml https://github.com/lublak/hxml
```
test file (under test/Test.hx):
```hx
class Test {}
```
buildTest.hxml file:
```hxml
-p test
-lib hxml
Test
```
```
haxe .\buildTest.hxml
```
an ambiguous error:
```
Error: Error: Cannot process [(file]: Invalid parameter : (file
```

**Comment by Simn** [comment] 2022-04-05 09:01
This doesn't reproduce for me and looks crazy.

**Comment by kLabz** [comment] 2022-04-05 09:15
I do reproduce, with a slightly different error because linux

```
❯ haxe buildTest.hxml
Error: /bin/sh: -c: line 1: syntax error near unexpected token `('
/bin/sh: -c: line 1: `haxelib path hxml (file not found)'
```

(haxe 4.2.5, but same with any version >= 4)

**Comment by kLabz** [comment] 2022-04-05 09:19
This should reproduce anywhere I suppose?

```
❯ haxelib newrepo
Local repository created (/tmp/tmp.X0Q9zFU7dy/.haxelib)

❯ haxelib git hxml https://github.com/lublak/hxml

Installing hxml from https://github.com/lublak/hxml
Library hxml current version is now git

❯ haxe -lib hxml
Error: /bin/sh: -c: line 1: syntax error near unexpected token `('
/bin/sh: -c: line 1: `haxelib path hxml (file not found)'
```

**Comment by lublak** [comment] 2022-04-05 09:22
@Simn for me it is very reproducible.
Even with a completely new project.
![grafik](https://user-images.githubusercontent.com/44057030/161722671-98770714-ad23-434c-a284-93e7ac08f1e0.png)

**Comment by kLabz** [comment] 2022-04-05 09:23
Reproduces with any lib with name being "hxml" or ending with ".hxml"

**Comment by Simn** [comment] 2022-04-05 09:24
![explorer_RXEEhocTny](https://user-images.githubusercontent.com/634365/161723038-93e8e69b-2d0a-4032-8bdf-e186a9ab4db8.png)

But I actually have an idea what could cause this.

**Comment by kLabz** [comment] 2022-04-05 09:26
Yeah it's fixed in development branch

**Comment by Aurel300** [comment] 2022-04-05 09:27
I'm guessing anything ending with `hxml` was "processed" to be a `hxml` file and somehow the result of that processing for non-files was "(file not found)" inserted into the command line?

**Comment by lublak** [comment] 2022-04-05 09:46
> Yeah it's fixed in development branch

I can confirm that it is fixed with the installation of:

https://build.haxe.org/builds/haxe/windows64-installer/haxe_latest.zip

**Closed as completed** 2022-04-05 10:11 UTC
