### ISSUE TITLE
Haxe does not work on Java 6

### ISSUE THREAD

**Issue by Atry** [HaxeFoundation/haxe#4220] opened 2015-05-15 05:36 UTC
```
$ javac -version
javac 1.6.0_65
```
```
$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
```
```
$ haxe haxe.io.Bytes -dce no -java java
haxelib run hxjava hxjava_build.txt --haxe-version 3200 --feature-level 1
javac "-sourcepath" "src" "-d" "obj" "-g:none" "@cmd"
src/haxe/io/BytesBuffer.java:648: inconvertible types
found   : java.lang.Object
required: long
						this.addInt64(((long) (dynargs.__get(0)) ));
						                      ^
src/haxe/io/Bytes.java:1259: inconvertible types
found   : java.lang.Object
required: long
						this.setInt64(((int) (haxe.lang.Runtime.toInt(dynargs.__get(0))) ), ((long) (dynargs.__get(1)) ));
						                                                                            ^
2 errors
Compilation error
Native compilation failed
Error: Build failed
```

**Comment by musou1500** [comment] 2015-05-15 07:39
What is your haxe version ?

**Comment by Atry** [comment] 2015-05-15 12:42
Haxe 3.2.0

**Comment by musou1500** [comment] 2015-05-17 02:59
Thank you.
I success to reproduce, but I can't find cause of this issue...

**Comment by yanhick** [comment] 2015-05-29 17:45
I'm also having the same issue.
I'm wondering if it's related to the Int64 breaking changes in Haxe 3.2.0: https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-3.2.0

**Comment by yanhick** [comment] 2015-06-19 21:57
I did some more digging on this issue and it seems to be caused by java 6 not letting boxed values be cast to primitive values. The following Java class builds with Java 7 but not Java 6:

```java
public class Main {
    public static void main (String[] args) {
        Object foo = 1;
        long bar = (long) foo;
    }
}
```

**Comment by waneck** [comment] 2015-06-19 22:05
Yeah. That's pretty strange, actually - since all other values are automatically boxed on Java 6

**Comment by Atry** [comment] 2015-06-20 11:11
On Java 6, We need `longValue`

``` java
public class Main {
    public static void main (String[] args) {
        Object foo = 1;
        long bar = ((Number) foo).longValue();
    }
}
```

**Comment by Atry** [comment] 2015-06-20 11:16
We need a `Runtime.toLong`, like the current `Runtime.toInt`: 

https://github.com/HaxeFoundation/haxe/blob/1585b9b001d35ee1e45d65c9cfa7204635c34798/std/java/internal/Runtime.hx#L139

**Comment by waneck** [comment] 2016-04-03 15:24
This is fixed now. Bear in mind that the use of `-D java6` is needed to deal with the API changes

**Closed** 2016-04-03 15:23 UTC

**Comment by ianharrigan** [comment] 2016-05-07 06:52
Hi, i seem to be facing this exact same issue. Im using git hxjava, haxe 3.2.1 and have tried with JDK 1.7 and 1.8 and cant seem to get anywhere. Any advice on how to get past this?

Thanks,
Ian
