### ISSUE TITLE
[eval] sys.FileSystem.absolutePath doesn't work on inexistant paths Linux 

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7850] opened 2019-02-23 11:57 UTC
Subj. It's supposed to work even if the file doesn't exist, but looks like it ends up using `realpath` on unixes that won't work for nonexisting files.

As a workaround one can use the old implementation:
```haxe
	public static function absolutePath ( relPath : String ) : String {
		if (haxe.io.Path.isAbsolute(relPath)) return relPath;
		return haxe.io.Path.join([Sys.getCwd(), relPath]);
	}
```

**Comment by Gama11** [comment] 2019-02-23 16:57
You said this is a regression? Should probably be marked as such then so it gets fixed before 4.0.0.

**Comment by Simn** [comment] 2019-02-23 17:05
I'm not entirely convinced that this is even defined behavior. Getting the absolute path of a non-existent file doesn't make much sense, and defaulting to cwd + file name seems somewhat random.

What do other targets do in this case?

**Comment by Gama11** [comment] 2019-02-23 17:08
>Returns the full path of the file or directory specified by relPath, which is relative to the current working directory. The path doesn't have to exist.

**Comment by Simn** [comment] 2019-02-23 17:10
Yes but "main.js" is not a relative path.

Anyway, there's definitely something we have to fix here because eval does something entirely different in its implementation.

**Comment by nadako** [comment] 2019-02-23 17:11
> You said this is a regression? Should probably be marked as such then so it gets fixed before 4.0.0.

Yeah, as I found out thanks to Travis, Haxe 3.4.7 works fine here:)

**Comment by Gama11** [comment] 2019-02-23 17:12
Huh, how is "main.js" _not_ a relative path? It's certainly not absolute.

**Comment by nadako** [comment] 2019-02-23 17:12
> Yes but "main.js" is not a relative path.

Why?

**Comment by Simn** [comment] 2019-02-23 17:14
I was under the impression that you had to use "./main.js" on unix systems, but apparently I'm wrong.

**Comment by Gama11** [comment] 2019-02-23 17:15
You might be thinking of how you have to prefix `./` to run scripts / executables from the cwd rather than from PATH.

**Comment by Simn** [comment] 2019-02-24 07:53
<strike>IMO this function should be moved to haxe.io.Path given that it has nothing to do with the file system.</strike>

Well, I guess it uses `Sys.getCwd` so it does in fact have something to do with the file system.

**Comment by Simn** [comment] 2019-02-24 08:36
lua fails the tests:

```
TestFileSystem
  testAbsolutePath: FAILURE F..F
    line: 134, expected "c:\nadako" but it is "/home/travis/build/Simn/haxe/tests/sys/c:/nadako"
    line: 134, expected "/nadako" but it is "/home/travis/build/Simn/haxe/tests/sys/nadako"
```

**Closed as completed** 2019-02-24 09:56 UTC
