### ISSUE TITLE
Macro enigma

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10238] opened 2021-05-02 18:38 UTC
Hej,

I'm sorry for the title, but It's really hard to explain what happens here : https://try.haxe.org/#6D4a0241
I think the try.haxe example will be more eloquent than my explanation.

If I don’t use the `haxe.macro.Context.typeExpr()` all works fine.
If I add “else” statement at the end (the commented part), all works fine, if not it throws me Void should be String
Also, if in the catch block I just trace the error (without throwing a fatalError), all works fine.

Also sorry if it's not a bug, it looks like for me, if someone can enlight me here please, thank you very much.

**Comment by haxiomic** [comment] 2021-05-02 18:44
Doesn't look like a bug, with `typeExpr()` you're asking haxe to type this expression:
```haxe
var x = if (i==1) {
        s += "1";
} else if (i==2) {
        s += "2";
}
```

What is the type of `x`? If either branch is taken, it's String, but if no branch is taken then it's Void, so `x`'s type is either Void or String depending on `i`. This isn't an allow state in haxe – the type of the expression must resolve to a single type.

So it fails with `typeExpr()` because the expression does not resolve to a valid type

**Comment by filt3rek** [comment] 2021-05-02 18:48
Thanks George for the answer,

I use `if` alone without any assignation... I don't know where do you see `var x = if`. I'm missing something ?

**Comment by haxiomic** [comment] 2021-05-02 18:51
The `var x` was just to illustrate that you're asking the compiler to type the expression. If you write `if (...) { }` then the compiler doesn't need to type the expression normally, however by using `typeExpr()` you ask the compiler to determine its type, much like when you use `var x = ` the compiler now needs to type this expression because the variable x needs to have a type

As this is not a bug I'll close this

**Closed as completed by haxiomic** 2021-05-02 18:51 UTC

**Comment by filt3rek** [comment] 2021-05-02 18:55
Feel free to close that of course if it's not a bug.
But I'm sorry, I still doesn't understand because I ask compiler to type the whole `buf`, not only the if statement.

Ooh ! Maybe it's because compiler takes always the last expressions as the return type is it that ?
So it fails when it try to type all the if statement right ?

**Comment by haxiomic** [comment] 2021-05-02 19:10
> Ooh ! Maybe it's because compiler takes always the last expressions as the return type is it that ?
So it fails when it try to type all the if statement right ?

Exactly :)

**Comment by RealyUniqueName** [comment] 2021-05-06 19:35
You can type-hint your expression like this `(expr : Void)` if you want compiler to know it's not supposed to return any value.

**Comment by filt3rek** [comment] 2021-05-07 01:28
Thanks Aleksandr.
I've added a null at the end of the block,it's ok ;)
