### ISSUE TITLE
[cpp] VirtualArray oddities

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#5004] opened 2016-03-31 12:10 UTC
This comes from [the unit tests for tink_json](https://travis-ci.org/haxetink/tink_json/jobs/119763734):

```
/home/travis/haxe/lib/hxcpp/git/src/hx/CFFI.cpp: In function ‘void val_array_set_size(hx::Object*, int)’:
/home/travis/haxe/lib/hxcpp/git/src/hx/CFFI.cpp:410:77: error: cannot dynamic_cast ‘arg1’ (of type ‘class hx::Object*’) to type ‘class cpp::VirtualArray_obj*’ (target is not pointer or reference to complete type)
       cpp::VirtualArray_obj *va = dynamic_cast<cpp::VirtualArray_obj *>(arg1);
                                                                             ^
/home/travis/haxe/lib/hxcpp/git/src/hx/CFFI.cpp:412:12: error: invalid use of incomplete type ‘class cpp::VirtualArray_obj’
          va->__SetSize(inLen);
            ^
In file included from /home/travis/haxe/lib/hxcpp/git/src/hx/CFFI.cpp:1:0:
/home/travis/haxe/lib/hxcpp/git/include/hxcpp.h:239:12: error: forward declaration of ‘class cpp::VirtualArray_obj’
      class VirtualArray_obj;
```

I don't have time to isolate it right now. But by the looks of the position information it seems like for once the problem is not caused by my abuse of the compiler, but is in the latest hxcpp sources. Is this enough to go on?

**Comment by Gama11** [comment] 2016-03-31 13:57
This could be caused by incompatible versions of hxcpp and Haxe. Travis Haxe development jobs use an outdated Haxe version right (942de8c) because that's the last Linux64 build before build.haxe.org stopped working.

**Comment by hughsando** [comment] 2016-03-31 14:16
My goal is to keep compatibility with older versions of haxe for at least a year, so this is actually I good test.  I am thinking an official test against 3.2.1 is probably required.
Anyhow, this should be fixed now.

**Closed by hughsando** 2016-03-31 14:16 UTC
Labels: platform-cpp, regression
