### ISSUE TITLE
js_Boot is not defined

### ISSUE THREAD

**Issue by Marc010** [HaxeFoundation/haxe#4298] opened 2015-06-07 11:40 UTC
This code produces a runtime error on js.
```haxe
class Test {
    static function main() {
        trace(A);
    }
}

enum X
{
    A;
}
```
js:
```js
(function (console) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); };
var Test = function() { };
Test.main = function() {
	console.log(X.A);
};
var X = { __constructs__ : ["A"] };
X.A = ["A",0];
X.A.toString = $estr;
X.A.__enum__ = X;
Test.main();
})(typeof console != "undefined" ? console : {log:function(){}});

```
output:
```
13:23:13:895   Uncaught ReferenceError: js_Boot is not defined
```

Haxe 3.2.0
DCE: std or full
Analyzer: doesn't affect the js output

**Comment by Simn** [comment] 2015-06-07 12:17
@clemos: I cannot reproduce this on 3.2.0 locally but I can reproduce it on try.haxe which also claims to be 3.2.0. I fixed this between the RC and the full release (https://github.com/HaxeFoundation/haxe/commit/15e8bb321dffa5671fa374d461164af213bd7044), which makes me wonder if try.haxe is actually on 3.2.0?

**Comment by clemos** [comment] 2015-06-08 09:04
It's fixed on try.haxe.org.
Indeed the version I compiled wasn't 3.2.0 release; 
it seems `git checkout 3.2.0` was "ambiguous", so I had to `git checkout refs/tags/3.2.0`.
Thanks @Simn and @Marc010 for the report :)

**Comment by Simn** [comment] 2015-06-08 09:04
merci!

**Closed by Simn** 2015-06-08 09:04 UTC
