### ISSUE TITLE
Reflect.callMethod wrt optional arguments

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7524] opened 2018-10-07 14:16 UTC
As part of #3826 , I have added Reflect.callMethod tests to check reflection support wrt optional arguments.

ATM these platforms fails the tests so I have disabled them, but some additional support would be required to have they work correctly:

 * [ ] Java
 * [ ] CS
 * [x] Lua

PS: This is not a show stopper for Haxe 4 as it's not a regression, but I'm still adding it to Release 4 to see if we can have it working for 4.0 final

**Comment by jdonaldson** [comment] 2018-10-11 19:14
Pushed a fix for lua.

**Comment by Simn** [comment] 2018-12-01 13:19
Moved to 4.1 due to lack of Java/C# manpower.

**Comment by ncannasse** [comment] 2018-12-01 20:52
Sorry but we really need that fixed in 4.0

**Comment by ncannasse** [comment] 2018-12-01 20:52
Summon @waneck

**Comment by waneck** [comment] 2018-12-01 20:56
It shall be fixed 😊

**Comment by Simn** [comment] 2018-12-02 07:51
But this isn't even a regression. If we get any @waneck-time I'd greatly prefer to use it on #7617.

**Comment by ncannasse** [comment] 2018-12-03 10:21
@Simn let's pray @waneck, sacrifice a sheep and hope to get both in time for RC

**Comment by ncannasse** [comment] 2018-12-22 13:10
> It shall be fixed 😊

@waneck you didn't say when 😊

**Comment by Simn** [comment] 2019-01-24 11:10
The problem with Java/C# is that the implementation uses native arrays for the implementation and then causes out-of-bounds exceptions on the lookup.

I tried using `Array` instead, but that did not end well. I suppose the filter runs before the proper array transformations are applied or something like that. It's probably also not easy to catch the out-of-bounds exceptions because then you run into `null` vs. `0` situations.

So I'm again moving this to 4.1 because I don't see this being fixed in the near future.

**Comment by ncannasse** [comment] 2019-01-24 13:14
We can push it to 4.1 for C#/Java, please open a new issue specific to these platforms.

**Comment by Simn** [comment] 2019-04-10 14:33
I had a look at this for Java but find it a bit dodgy. We will have to null-pad the missing arguments, but that quickly conflicts in case overloads are involved. At the very least we would have to communicate to the run-time which arguments are optional somehow.

**Comment by Simn** [comment] 2023-03-24 13:35
This will not be fixed for Java and C#.

**Closed as not planned by Simn** 2023-03-24 13:35 UTC
Labels: platform-java, platform-cs
