### ISSUE TITLE
Autocompletion fails when inside an anonymous structure class notation

### ISSUE THREAD

**Issue by ciscoheat** [HaxeFoundation/haxe#5183] opened 2016-04-29 22:32 UTC
I'm using a quite special syntax for haxedci, and just noticed that autocompletion fails at a certain point. Here's a minimal example:

``` haxe
import haxe.macro.Context;
import haxe.macro.Expr;

using Lambda;

#if !macro
@:build(MainBuilder.build())
class Main
{   
    static function main() trace(new Main().test());

    public function new() {}

    public var special : {
        // "test" will be moved to a class field by the build macro.
        function test() : Int {
            // Autocompletion doesn't work in here. 
            // "Error: No completion point was found"
            return 123;
        }
    };
}
#end

class MainBuilder {
    static function build() {
        return Context.getBuildFields().map(function(field) return switch field.kind {
            case FVar(t, _) if (field.name == "special"):
                switch t {
                    case TAnonymous(fields): fields[0];
                    case _: field;
                }
            case _: field;
        });
    }
}
```

The code works, but autocompletion doesn't in the specified place. I wouldn't be surprised if it doesn't work of course, since it's a very special case, but just checking if it should, which would be nice.

Link to the actual use case: https://github.com/ciscoheat/haxedci-example#adding-a-constructor

**Comment by nadako** [comment] 2016-05-21 19:54
Let's see what can we provide for this case for 3.4

**Comment by Simn** [comment] 2018-04-19 06:53
This is a duplicate of some @Gama11 issue.

**Closed by Simn** 2018-04-19 06:53 UTC
Labels: enhancement, feature-completion
