### ISSUE TITLE
[cpp] comparing with null of Array<Int> item not working correctly

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#9110] opened 2020-01-28 09:33 UTC
In following code `item` should be `null`, but `item != null` is true. Tested with haxe 4.0.3 and hxcpp 4.0.64.
```haxe
class Main {
	static function main(): Void {
		
		var foo: Array<Int> = [];
		var bar: Dynamic = foo; 
		var item: Dynamic = bar[0];
		trace(item != null); // traces "true"
		trace(item); // traces 0
	}
}
```
Note that using `var bar: Dynamic = [];` does not reproduce the issue, because it reproduces only if `Array_obj` is used, not `VirtualArray_obj`. 
Also it does not reproduce if `foo` type is `Array<Null<Int>>`.

**Comment by Ilir-Liburn** [comment] 2020-01-28 17:39
That's what I expected on static platforms. Same behavior for CS and HL. To my surprise, Flash and Java behaves differently, tracing false and null. I forgot, Flash is somehow mixture of static and dynamic, nothing to change here, that is how it behaves. On the other hand, Java and CS are both using global::haxe.lang.Runtime.callField(bar, "__get"...), but giving different result. Wonder if behavior of callField is conditioned by platform for those targets. Nice finding, thanks

**Comment by hughsando** [comment] 2020-02-02 13:48
I think this is what it should be.
The Dynamic cast is preventing "Ints can't be null on static targets" compile-time error, but the effect is still the the same.
It is basically:
```haxe
var intItem = foo[0]; // item is Int =0, not null
var item:Dynamic = foo[0]; // item is Dynamic =0, not null
var item:Dynamic = intItem; // item is Dynamic =0, not null
var item = (foo:Dynamic)[0]; // item is Dynamic =0, not null
```
Perhaps you want `foo = new Array< Null<Int> >()`

**Comment by romamik** [comment] 2020-02-03 08:39
Yes, that is how it is described in haxe manual.

The only issue I see here is that type of `array[i]` is not Null on non-static platforms (js) while actually it can return null.

Also this is one more case where haxe behaves differently on different platforms, and that can lead to some well hidden bugs in multiplatform applications.

**Comment by RealyUniqueName** [comment] 2020-02-03 08:47
> The only issue I see here is that type of array[i] is not Null on non-static platforms (js) while actually it can return null.

See https://github.com/HaxeFoundation/haxe/issues/6847:
> Having different typing for something as used as Array depending on the platform creates more issues, we want to avoid platform-specific typing as much as possible.

**Comment by romamik** [comment] 2020-02-03 08:58
I do not know what to do with this. I only see that there is some inconvenience here.

In cpp code there is out of bounds access check and there is call `null()`, that in the end turns out to be 0. So adding one more bounds check in haxe code would lead to double bounds check. Using `Array<Null<Int>>` would lead to null-check while iterating over array.

May be two different array-access functions in array, one more efficient and platform-specific and one less-efficient but with uniform behavior across different targets.

**Comment by hughsando** [comment] 2020-02-03 09:05
I agree it is not great, but the alternative would be to have the static target return different values in the one target  depending on whether it Dynamic access or not, which I think is even harder to diagnose.  Although, it should be possible if you want to hack the code.  You could also use some kind of static extension, or abstract helper:
```haxe
inline public static function at(array:Dynamic, index:Int) : Dynamic return #if js array[index] #else index<array.length ? array[i] : null #end ;
```
It might also be better to throw in these cases - hxcpp could be hacked to do this - perhaps with some define, forcing the bounds check back into the haxe code.  This would make it easier to debug.

**Comment by romamik** [comment] 2020-02-10 08:50
I'm not sure if I should close this issues. It is not a bug.

**Comment by RealyUniqueName** [comment] 2020-02-11 15:58
Well, as we found out this is an intended behavior. And unless you want to insist on changing that, you definitely should close the issue :)

**Closed as completed** 2020-02-12 07:40 UTC
Labels: bug, platform-cpp
