### ISSUE TITLE
is operator doesn't work with qualified paths of secondary module types

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#10174] opened 2021-03-12 20:05 UTC
```haxe
function main() {
	// Module Foo does not define type Foo
	"" is Foo.Bar;

	// compiles fine
	Std.isOfType("", Foo.Bar);
}
```

`Foo.hx`:

```haxe
class Bar {}
```

____

`is Foo.Bar` also compiles fine if `Foo.hx` also contains a `class Foo`, or with `import Foo.Bar` and `is Bar`...

**Comment by nadako** [comment] 2021-03-12 22:41
I can't reproduce this.

**Comment by Gama11** [comment] 2021-03-12 23:18
Huh, interesting... I pushed the repro to this branch: https://github.com/Gama11/HaxeRepro/tree/haxe-10174

**Comment by RealyUniqueName** [comment] 2021-03-16 18:14
Fixed by 996c39daf0fa4bebf8a4fce1f57ad8087ef69a3e

**Closed as completed** 2021-03-16 18:23 UTC
Labels: bug, waiting-for-feedback
