### ISSUE TITLE
haxe 4 jsrequire

### ISSUE THREAD

**Issue by francescoagati** [HaxeFoundation/haxe#8176] opened 2019-04-17 07:58 UTC
Hi,
with haxe 4 i have notice that extern class with jsrequire arent removed also if i use the macro exclude for eliminate some namespaces. with haxe 3 works but with haxe4 the require is mainteined in the output js

**Comment by nadako** [comment] 2019-04-17 08:40
interesting. might be a dce regression, because I don't think we changed anything regarding `@:jsRequire`. could you provide a reproducible example?

**Comment by francescoagati** [comment] 2019-04-17 08:42
i have a big project where i have notice this when i have tested it with haxe 4. for now i have resolve with a macro that remove jsrequire meta. i can try to provide a github repository with a micro project for test

**Comment by francescoagati** [comment] 2019-04-17 08:56
here an example https://github.com/francescoagati/test-haxe-4-extern-jsrequire
see the file js generated https://github.com/francescoagati/test-haxe-4-extern-jsrequire/blob/master/main.js

i import Test.hx with inside an extern class with jsrequire
i call Test.hello inside main (is only a test) and after i do a macro exclude  of Test in build.hxml
the Test class isnt imported but the require is mantained

**Comment by francescoagati** [comment] 2019-04-17 08:56
with haxe 3 the extern class with jsrequire isnt imported

**Comment by francescoagati** [comment] 2019-04-17 08:58
also with recusion active --macro exclude('Test',true) isnt removed the extern class

**Comment by nadako** [comment] 2019-04-20 07:02
Hm, so `exclude` basically means that the class is marked as `extern`. For DCE that means that this class is "always kept", but since the class methods has expressions, it recurses into them and finds the reference to `JsRequire` and marks it as directly used, thus `require` is generated.

I'm not sure why exactly this was different in Haxe 3, maybe we fixed some bugs with marking "directly used" that lead to this :)

Now the question for @Simn: should DCE process expressions of extern classes? I think it's fair to ignore them, at least with the way "exclude" works. I think having non-inline method bodies on extern is a compile-time error nowadays?

**Comment by Simn** [comment] 2019-04-20 08:04
Not processing extern expression seems sensible. Does that fix the issue?

**Comment by nadako** [comment] 2019-04-20 08:38
I assume so :) Will try when I have some time

**Comment by francescoagati** [comment] 2019-04-20 18:49
for now i have resolved remove @jsrequire meta with another macro. i use this for generate a particular file without node require

**Closed as completed** 2020-06-04 18:15 UTC
Labels: bug, feature-dce
