### ISSUE TITLE
PHP: problem with Array.map and bind

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#2587] opened 2014-01-30 02:50 UTC
I try to map an Array<String> with a function and bind like this:

    thumbs.map(Thumbnail.translateFilename.bind(_, id))

In PHP I get:

    $thumbs->map(Test_1($this, $_t, $clip, $files, $meta, $mf, $thumbs, $vfiles))

and two functions:

```
function Test_1(&$__hx__this, &$_t, &$clip, &$files, &$meta, &$mf, &$thumbs, &$vfiles) {
	{
		$a2 = $__hx__this->id;
		return array(new _hx_lambda(array(&$_t, &$_t2, &$a2, &$clip, &$files, &$meta, &$mf, &$thumbs, &$vfiles), "Test_2"), 'execute');
	}
}
function Test2(&$_t, &$a2, &$clip, &$files, &$meta, &$mf, &$thumbs, &$vfiles, $a1) {
	{
		return Thumbnail::translateFilename($a1, $a2, null);
	}
}
```

The call with Array.map is inside a larger function with quite a lot a local vars, that's where the long list of vars seems to come from. But the passed variables seem to get mixed up, so the whole thing breaks. In the end a Map is passed ($vfiles a.k.a. $a1) where there should be a string.
So the PHP-target generates some extra functions, when things get complicated it seems? But why are ALL the local vars from a function passed to these extra functions, even when they are not used in them?
Note that this code used to work a couple of versions (=months) ago. A workaround for now is:
    [for (thumb in thumbs) thumb.translateFilename(id)]

**Comment by Simn** [comment] 2015-02-27 15:43
Could you try reducing the example here to something I can just paste & compile? I want to get this fixed as it looks somewhat serious.

**Comment by Simn** [comment] 2015-02-27 15:44
Or is this the same as #2378?

**Comment by mockey** [comment] 2015-02-27 22:15
I haven't been able to get this error in a reduced example. Very weird. The code above still fails with current Haxe version, though. The problem is in:
```
function Test_1(&$__hx__this, &$_t, &$clip, &$files, &$meta, &$mf, &$thumbs, &$vfiles) {
    {
        $a2 = $__hx__this->id;
        return array(new _hx_lambda(array(&$_t, &$_t2, &$a2, &$clip, &$files, &$meta, &$mf, &$thumbs, &$vfiles), "Test_2"), 'execute');
    }
}
```
In the `_hx_lambda` call there is a var `&$_t2` slipped in out of nowhere with no further reference. This is then passed to `Test_2` in place of the expected `&$a2`.

BTW: Do you know why the functions are split up like this and all the local vars (mostly not used) are always passed around like this (by reference)? This really freaks me out in the generated PHP.

**Comment by mockey** [comment] 2015-02-28 01:10
OK, got it!
```
class Main {
	var e:E;
	static function main() new Main();
	static function add(i:Int, s:String) return i + 1;
	function new() {
		e = A;
		if (e == B) return;
		if (e == B) return;
		var arr = [1, 2, 3, 4, 5];
		arr = arr.map(add.bind(_, "test"));
		trace(arr);
	}
}
enum E {
	A;
	B;
}
```
The problem is that for every enum-check `e == B` a new local var is created `$_t`, `$_t2`,... Then this `_hx_lambda` function passes all the local vars as `array(&$_t, &$_t2, &$arr)` to function `Main_0`, but `Main_0` only expects `&$_t, &$arr` and apparently doesn't know about `$_t2`. If you comment the second `if (e == B) return;` it works.

**Comment by mockey** [comment] 2015-02-28 12:19
Possible fix would be clearing this `tmp` var somehow:
https://github.com/HaxeFoundation/haxe/blob/development/genphp.ml#L1213
or not using it at all or use a better `Enum` check...

**Comment by Simn** [comment] 2015-02-28 12:50
The original intent of that temp var was probably to deal with enum constructors that have arguments. If we allowed `e == A("foo")` you would have to temp var it in order to avoid duplicate creation of the enum value. However, since we don't allow this anyway I'm thinking we can indeed get rid of the temp var.

**Comment by Simn** [comment] 2015-02-28 12:54
Oh, actually that case in genphp deals with any kind of equality, so we cannot avoid the temp var there. Maybe we simply shouldn't officially declare it.

**Comment by Simn** [comment] 2015-02-28 13:52
Can you try running your applications using https://github.com/HaxeFoundation/haxe/tree/php_sane_closures? I'm trying make it pass only those arguments that are actually used by the closure. Our unit tests work but I'm a bit worried about weird edge-case regressions.

**Comment by mockey** [comment] 2015-02-28 20:29
> Oh, actually that case in genphp deals with any kind of equality

Yes, that's what I meant. It deals with enums and anything else. Maybe one case for enums only would be better?

**Comment by Simn** [comment] 2015-02-28 20:30
The problem is still that enums could be hidden behind Dynamic, so we'll still need a case like that.

**Comment by mockey** [comment] 2015-02-28 20:32
Hidden behind Dynamic? Not sure what that means, but you will know...:-)

**Comment by Simn** [comment] 2015-02-28 20:33
```
var d1:Dynamic = YourEnum;
var d2:Dynamic = YourEnum;
if (d1 == d2) { } // has to deal with the enum case
```

**Comment by mockey** [comment] 2015-02-28 20:52
Anything can be hidden behind Dynamic that way, can't it?
Anyway, right now the condition is:
`if((is_object($_t = $this->e) && !($_t instanceof Enum) ? $_t === E::$B : $_t == E::$B))`
It checks for an object that's not an enum (= Dynamic?) and compares it with `===` and everything else (=Enum?) with `==`. Couldn't you have a special case just for TEnum here?

**Comment by Simn** [comment] 2015-02-28 20:54
Yes we could, but that would only be an optimization. My point was that even if we do that we still need the current case to check for enums at run-time.

**Comment by mockey** [comment] 2015-02-28 20:58
Understood. I'll check your branch now.

**Comment by mockey** [comment] 2015-02-28 21:59
> Can you try running your applications using https://github.com/HaxeFoundation/haxe/tree/php_sane_closures?

That looks much saner indeed now, but this is only for the `_hx_lambda` functions, right? I see other cases where sub-functions are created and still unused local vars passed around. Not sure when actually, seems kind of random to me.

But my websites compile and seem to work, my few simple unit tests pass, too.

I only have a problem with a StringMap, that is filled by a macro. Keys are prefixed with `@$__hx__` now, so `@$__hx__Home` instead of `Home`. Any idea where that comes from?

**Comment by Simn** [comment] 2015-02-28 22:10
I can't find any general `__hx__` escaping in genphp. There's only `__hx__this` and a few others in special case, so I don't see how this could happen.

**Comment by Simn** [comment] 2015-02-28 22:11
To answer your question, I've made the change in `gen_inline_function` so I would assume that it applies to all inline functions...

**Comment by nadako** [comment] 2015-02-28 22:11
the `@$__hx__` reminds me of #2642

**Comment by Simn** [comment] 2015-02-28 22:12
Aaah, right... but my changes to genphp shouldn't affect that.

**Comment by mockey** [comment] 2015-03-01 01:23
> the @$__hx__ reminds me of #2642

Something like that, yes. All quoted fields in a `EObjectDecl` (also valid ones like "Home") are prefixed with `@$__hx__` now. Intended?

> Aaah, right... but my changes to genphp shouldn't affect that.

And yes, not caused by genphp changes. But must be a recent change (last week or so).

**Comment by mockey** [comment] 2015-03-01 02:05
> To answer your question, I've made the change in gen_inline_function so I would assume that it applies to all inline functions...

Not really. Apparently this only handles the `_hx_lambda` fake closures.
But something like this also produces an extra function with all local vars passed along:
```
var b = true;
this.o = {
	f: b ? "test" + "1" : "test"
}
```
`$this->o = _hx_anonymous(array("f" => Main_1($this, $_t, $arr, $b, $v1, $v2)));`
As I said, it's kind of random to me, certain level of complexity or what?

**Comment by Simn** [comment] 2015-03-07 08:51
Let's leave it for 3.3. I agree it's annoying, but it's not a regression and whatever changes I could make right now might very well introduce some other problems.

**Comment by nadako** [comment] 2015-03-07 10:54
Are you talking about the `@$__hx__` thing? I think it's a small regression because of the quoted field preserving change. I.e. in 3.1.3 `macro {"a": 1}` was generated as `EObjectDecl([{ field : "a", ...`, but it's generated as `EObjectDecl([{ field : "@$__hx__a", ...`. That could affect users' macro.

**Comment by Simn** [comment] 2015-03-07 10:56
I was talking about the original issue.

**Comment by mockey** [comment] 2015-03-07 13:55
Some questions, just for my understanding:

So you won't merge your branch for 3.2? It seemed to work OK for the `_hx_lambda` functions and it fixes the original issue. It just doesn't catch the other sub-functions.

And the `@$__hx__` issue still exists? Can/will this get fixed? Shall I open a separate issue for this? Or simply apply a workaround in my macro for now?

**Comment by nadako** [comment] 2015-03-07 23:09
Use a workaround for now, there's an issue about that already - #2642.

**Comment by Simn** [comment] 2015-06-08 15:53
@mockey: I had a look again and see what you mean now, but that strikes me as a separate issue because the argument count between declaration and call is at least in sync. I have committed my original fix which does address the closure problem. We can look into filtering the unused temp variables... in the future!

**Closed by Simn** 2015-06-08 15:53 UTC
