### ISSUE TITLE
[js] Std.instance does not work with instance implements interface

### ISSUE THREAD

**Issue by gsun** [HaxeFoundation/haxe#5946] opened 2017-01-18 06:03 UTC
Std.instance(value, c) will fail when the value implements the interface c.

maybe modify as below:
```haxe
	public static inline function instance<T:{},S:T>( value : T, c : Class<S> ) : S {
		return Std.is(value, c) ? cast value : null;
	}
```

**Comment by nadako** [comment] 2017-01-24 20:44
Looks like it's specified like that: https://github.com/HaxeFoundation/haxe/blob/development/std/Std.hx#L46.

@ncannasse please close if working as intended.

**Comment by ncannasse** [comment] 2017-01-24 20:49
I wonder if we could have some kind of warning / error for that (at compiletime, not runtime since we want it to be fast). The problem is that an interface is also a `Class` instance.

**Comment by ncannasse** [comment] 2018-03-05 15:35
Why did we specify that interfaces are not working btw ? that does not seem very legit to do so.
Which platforms are having this bug? If it's only JS the specification should be updated and the platform support fixed.

**Comment by RealyUniqueName** [comment] 2018-03-05 20:17
Because `Std.instance` is specified to work like this. It's "This method checks if a downcast is possible". And `S` is constrained to be a subclass to `T`.
I think we need to introduce another method to avoid breaking backward compatibility.

**Comment by RblSb** [comment] 2018-10-10 19:47
The solution from the first post is suitable for fix?

**Comment by ncannasse** [comment] 2018-10-10 20:00
I think this should be addressed for Haxe 4.0 as we are making changes in Std.is and renaming (see #2976 and #7115)

**Comment by Simn** [comment] 2018-12-15 10:35
I find `Std.instance` to be one of the most confusing functions in the standard library. Its documentation talks about a "downcast", but that's a run-time-specific term. IMO this should be changed to talk about casting to a more specific *type* and shouldn't mention *values* at all.

Within the context of types, it makes sense to allow casting `Dynamic` to an `Interface`. We can consider our types to be ordered from most to least general:

1. Dynamic
2. BaseInterface
3. ChildInterface
4. BaseClass
5. ChildClass

However, this makes no sense in the context of values because `Std.instance((classInstance : Dynamic), Interface)` is _not_ a downcast.

**Comment by ncannasse** [comment] 2018-12-16 10:34
I agree that Std.instance(e,Interface) does not make much sense. 

What the user wants here is cast(e,Interface) instead. But yes, we have this problem with Dynamic, but I think this can apply to pretty much all of others std library functions when Dynamic is involved, so I propose we close this issue.

There are other ways to deal with it, such as InterfaceValue not unifying with `Class<T>` but I don't think we want to change that right now.

**Comment by Simn** [comment] 2018-12-16 18:29
At the very least we have to document something, because even you can never remember how `Std.instance` works. :P

**Comment by RealyUniqueName** [comment] 2019-04-17 08:18
I don't know what to document here as it's already documented:
https://github.com/HaxeFoundation/haxe/blob/88e519536951213b16b3d7cb3ff510070fb07c29/std/Std.hx#L45-L48

**Comment by Simn** [comment] 2019-04-17 08:21
Given that it's supposed to implement downcasting, maybe we should just deprecate-rename `instance` to `downcast`? That way it pretty much documents itself.

Or does casting from a parent interface to a child interface also not work?

**Comment by RealyUniqueName** [comment] 2019-05-14 16:04
> Or does casting from a parent interface to a child interface also not work?

It doesn't work on _some_ targets.

Let's rename it to `downcast`, deprecate `instance` and close this issue. It's already documented to not support interfaces.

**Comment by RealyUniqueName** [comment] 2019-05-14 16:23
Actually, let's just deprecate it as a candidate for removal?
Every time somebody tries to use it for the first time, it causes confusion. Current signature and implementation just make it too specific. It works in a narrow set of cases, while silently fails in other cases. And it's inconsistent across targets in those failures. It's just a bad code for std.
Either it should be replaced with the straightforward implementation `Std.is(v, c) ? cast v : null` or deprecated for removal.

**Comment by ncannasse** [comment] 2019-05-14 21:14
I don't agree with the conclusion. 

Downcast is the most common and somewhat legitimate use of cast in the OO world. Restricting its typing the way Std.instance does is the best for the developer, and it requires a std function so on statically typed platforms there's not some typecheck done twice - one for Std.is and one for cast.

So it should be :
- properly specified, especially wrt interfaces
- tested and fixed across all platforms
- eventually renamed: downcast is good for me.

**Closed** 2019-05-29 11:54 UTC
Labels: documentation, platform-javascript
