### ISSUE TITLE
html5 compilation overhead

### ISSUE THREAD

**Issue by mastef** [HaxeFoundation/haxe#6818] opened 2018-01-14 11:40 UTC
Just stumbled upon this when playing with uglifyjs : 

haxe code :
```haxe
private static var __tempPointer = new BytePointer ();
```

haxe->html5 result :
```js
lime_graphics_opengl__$WebGL2Context_WebGL2Context_$Impl_$.__tempPointer = (function($this) {
    var $r;
    var this1 = new lime_utils_BytePointerData(null,0);
    $r = this1;
    return $r;
}(this));
```

haxe->html5->uglifyjs result :
```js
lime_graphics_opengl__$WebGL2Context_WebGL2Context_$Impl_$.__tempPointer=new lime_utils_BytePointerData(null,0)
```

The anonymous function generated by haxe seems a bit of an overkill?

**Comment by kevinresol** [comment] 2018-01-17 04:53
This looks like some old version of haxe. What is yours?

**Comment by mastef** [comment] 2018-01-17 11:47
`Haxe Compiler 4.0.0 (git build nightly-travis @ 212f0cd)`

**Comment by YellowAfterlife** [comment] 2018-01-21 10:25
I've seen this happen specifically with abstract constructors - `this1` does not get culled because the structure doesn't make it immediately apparent for compiler.

**Comment by mastef** [comment] 2018-01-21 13:58
Oh yes, that makes sense - in this example [BytePointer is an abstract](https://github.com/openfl/lime/blob/c9c5bf0bc5461c0559d5bc801428d1def1029a49/lime/utils/BytePointer.hx#L13),  [BytePointerData isn't](https://github.com/openfl/lime/blob/c9c5bf0bc5461c0559d5bc801428d1def1029a49/lime/utils/BytePointer.hx#L243).

**Comment by nadako** [comment] 2018-02-01 14:38
Does this get optimized with `-D analyzer-optimize`? If not, please provide a reproducible example.

**Comment by Simn** [comment] 2018-04-17 06:30
Closing until follow-up.

**Closed by Simn** 2018-04-17 06:30 UTC
Labels: feature-analyzer, platform-javascript

**Comment by mastef** [comment] 2018-04-19 10:39
Yeah, it looks like it goes away with `-D analyzer-optimize`
https://try.haxe.org/#e753E
