### ISSUE TITLE
abstracts and inline contructors

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#5462] opened 2016-07-15 14:09 UTC
I'm using constructors declared as @:extern inline to make sure that no new object allocations will be made. But if I'm making abstact on top of such class, constructors are not inlined. Also I've found that it's possible to pass object of class with @:extern inline constructor to not-inlined function and it will be allocated on heap.

``` haxe
package;

class Foo {
    public var foo:String;

    @:extern public inline function new() {
        foo = 'foo';
    }

    @:extern public inline function doFoo() {
        trace(foo);
    }
}

abstract Bar(Foo) {
    @:extern public inline function new() {
        this = new Foo();
    }

    @:extern public inline function doBar() {
        trace(this.foo);
    }
}

class Main {

    static function main() {
        // constructor Foo() is inlined
        var foo:Foo = new Foo();
        foo.doFoo(); 

        // Error: Extern constructor could not be inlined
        // And that's how it should work
        //noInline(foo); 

        // constructor Foo() is not inlined
        // but it is declared with @:extern metadata and should be inlined
        var bar:Bar = new Bar();
        bar.doBar(); 

        // Why no "Extern constructor could not be inlined"?
        noInline(new Foo()); 
    }

    static function noInline(foo:Foo) {
        foo.doFoo();
    }

}
```

Jenerated code in javascript (in c++ and as3 is conceptually the same):

``` js
// Generated by Haxe 3.3.0
(function () { "use strict";
var Foo = function() {
    this.foo = "foo";
};
var Main = function() { };
Main.main = function() {
    console.log("foo");
    console.log(new Foo().foo);
    Main.noInline(new Foo());
};
Main.noInline = function(foo) {
    console.log(foo.foo);
};
Main.main();
})();
```

**Comment by nadako** [comment] 2016-07-15 14:25
I'm not sure this can be easily fixed (to do inlining) for 3.3, but IMO it should at least fail with a "could not be inlined" error here.

**Comment by romamik** [comment] 2016-07-15 14:59
More:
```haxe
	static function makeFoo() {
		return new Foo();
	}
	static function main() {
		var foo = makeFoo();
		foo.doFoo();
	}
```
compiles to
```js
Main.makeFoo = function() {
	return new Foo();
};
Main.main = function() {
	console.log(Main.makeFoo().foo);
};
```
I think this also should give "could not be inlined" error.

**Comment by Simn** [comment] 2016-07-18 07:31
Not a regression as far as I can tell so no 3.3 priority.

**Comment by basro** [comment] 2017-05-07 20:44
I think this can be closed now. When opening issue #6034 I misunderstood this issue for being also about abstracts not inlining. Reading this again it seems #6034 is a duplicate of this.

**Closed** 2017-05-07 20:45 UTC
Labels: bug, feature-inline
