### ISSUE TITLE
Eval Pcre Error

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7628] opened 2018-11-20 10:56 UTC
We have some macros that read the filesystem. If a file contains the ö char, it will produce an error on this regexp:

```
var invalidChars = ~/[^A-Za-z0-9_]/g;
var ident = invalidChars.replace(s, "_");
```

This produces an uncatchable `Pcre.Error(2)`.
In the long term, we need eval to use proper Unicode filesystem API.
In the short term, we should try/catch these pcre errors and re-raise an eval error instead (for instance "Invalid input string")

**Comment by Simn** [comment] 2018-11-20 11:02
How exactly do you obtain the string that causes this?

**Comment by ncannasse** [comment] 2018-11-22 22:06
Create a file that contains ö , read the content of the directory with sys.FileSystem.readDirectory

**Comment by Simn** [comment] 2018-11-27 11:20
Turns out this is an OCaml problem: http://www.dra27.uk/blog/platform/2017/10/30/ocaml-unicode.html

I just compiled Haxe with OCaml 4.06.1 and confirmed that it works correctly there. This means we should look into building our binaries with a recent OCaml version @andyli.

**Comment by Simn** [comment] 2018-12-13 13:34
Assigning to @andyli. This isn't critical for the RC but should be sorted out for 4.0 final.

Then again, there's always a chance that an OCaml fix causes us problems, like that evaluation order problem we had at some point. So maybe doing this for the RC would be better...

**Comment by andyli** [comment] 2018-12-14 01:47
Is this a Windows-only issue? Upgrading OCaml in AppVeyor should be easy, but not so much for Linux because Ubuntu 16.04 still ships with OCaml 4.02.3.

**Comment by Simn** [comment] 2018-12-14 08:10
Yes it affects only Windows.

**Comment by andyli** [comment] 2018-12-14 08:13
Alright. AppVeyor uses OCaml 4.07.0 now (874999808730367dbc305007ed1dbfbca45925e4). Please check if it fixed the issue.

**Comment by Simn** [comment] 2018-12-14 08:22
![2018-12-14_09-21-30](https://user-images.githubusercontent.com/634365/49991543-b6f25900-ff81-11e8-98e3-42afb5042d44.png)

Looks good, thanks!

**Closed as completed by Simn** 2018-12-14 08:22 UTC
Labels: bug, platform-eval
