### ISSUE TITLE
[server] calls for auto-generated get_/set_ methods on interfaces can be compiled on the second time

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9039] opened 2019-12-16 21:25 UTC
```haxe
function test1() {
	vfs.putContent("I.hx", "interface I { var prop(get,never):Int; }");
	vfs.putContent("Main.hx", "class Main { static function main() { var i:I = null; } }");
	runHaxe(["--no-output", "-main", "Main"]); // comment this to make it fail
	vfs.putContent("Main.hx", "class Main { static function main() { var i:I = null; i.get_prop(); } }");
	runHaxe(["--no-output", "-main", "Main"]);
	assertErrorMessage("Main.hx:1: characters 57-65 : I has no field get_prop");
}
```

**Comment by nadako** [comment] 2019-12-16 21:27
I actually found this because of the `get_prop` showing in the completion, but so far I'm unable to construct a display test case for it. Will post it here once I can ^^

**Comment by nadako** [comment] 2019-12-16 21:37
Here's the display test case:

```haxe
function test2() {
	vfs.putContent("I.hx", "interface I { var prop(get,never):Int; }");
	vfs.putContent("Main.hx", "class Main { static function main() { var i:I = null; } }");

	runHaxe(["--no-output", "-main", "Main"]);

	var content = "class Main { static function main() { var i:I = null; i.{-1-} } }";
	var transform = Marker.extractMarkers(content);

	vfs.putContent("Main.hx", transform.source);
	runHaxeJson([], DisplayMethods.Completion, {
		file: new FsPath("Main.hx"),
		offset: transform.markers[1],
		wasAutoTriggered: true
	});

	// OR this will also fail:

	// runHaxeJson([], ServerMethods.Invalidate, {file: new FsPath("Main.hx")});
	// runHaxeJson([], DisplayMethods.Completion, {
	// 	file: new FsPath("Main.hx"),
	// 	offset: transform.markers[1],
	// 	wasAutoTriggered: true,
	// 	contents: transform.source
	// });

	assertHasNoCompletion(parseCompletion(), function(item) {
		return switch item.kind {
			case ClassField: item.args.field.name == "get_prop";
			case _: false;
		}
	});
}
```

**Comment by Simn** [comment] 2019-12-19 06:36
This will be a problem with any generated field that is being cached. We would need a mechanism that disallows explicit access to these during typing, but we have to make sure that this is _only_ disallowed during typing and _only_ on explicit access.

Honestly this seems really low priority... I'm leaning towards adding the `@:noCompletion` metadata to these fields so they don't show up in completion, and then worry about the explicit access "later".

**Comment by Simn** [comment] 2019-12-19 07:49
I've dealt with the completion part. Will keep this issue open, but I'm unlikely to actually fix this. It's a pretty dangerous fix to attempt and it's more of a curiosity than a bug because the generated code isn't even wrong.

**Comment by Simn** [comment] 2020-06-04 08:42
Assigning to @RealyUniqueName to check what's going on with this test on Linux, as I cannot reproduce it on Windows.

**Comment by RealyUniqueName** [comment] 2020-06-24 17:00
The failure appeared after 219194de3e36e381e767375650c7fca197a2ff22.
However, the same setup works fine in vscode.
Another test, which fails in the test suite, but works in vscode is 
https://github.com/HaxeFoundation/haxe/blob/c6dabfcc924fa025ed4908b1916426fe846945c4/tests/server/src/cases/display/issues/Issue9423.hx#L21-L22
That makes me think the reason of both failures is our test suite.

**Comment by kLabz** [comment] 2024-02-06 09:00
The test was just wrong (maybe not initially), because it was not invalidating `Main` so the completion request was failing with `Missing ;`

Test was fixed in https://github.com/HaxeFoundation/haxe/commit/b1b235b8a1ea659dbba6793796162f16cd7a8701 and behaves correctly since then so I think this issue can be closed? Unless there's another way to trigger that?

**Comment by Simn** [comment] 2024-02-06 09:01
Well I'm basically assigning these issues to you so you can make these calls!

**Comment by kLabz** [comment] 2024-02-06 09:03
We can reopen if anyone provides another way to trigger that then.

**Closed as completed** 2024-02-06 09:03 UTC
Labels: bug, feature-compiler-cache, priority-netherlands
