### ISSUE TITLE
Abstract: forward construct from the implied type

### ISSUE THREAD

**Issue by ErikRikoo** [HaxeFoundation/haxe#9337] opened 2020-04-22 13:59 UTC
Currently, there is no way to forward the construct from the implied type (at least I found none).
It would be great if we could have a compiler metadata that generates the following code:
```haxe
abstract A(Impl) {
   // Generated code
   public function new(args...) {
      this = new Impl(args);
   }
}
````
With:
```haxe
class Impl {
   public function new(args...) { }
}
```
We can't forward new directly in the @:forward arguments. We get an "Unexpected )" error just after the new keyword.
But maybe there could be a new compiler metadata such as @:forwardConstruct.
It was already suggested in [this issue](https://github.com/HaxeFoundation/haxe/issues/6619#issue-261257424), but it was marked as a bug and no news.

**Comment by RealyUniqueName** [comment] 2020-04-22 14:05
This is basically a duplicate of the mentioned issue. Please, continue that discussion instead of starting a new one.

**Closed as completed by RealyUniqueName** 2020-04-22 14:05 UTC
