### ISSUE TITLE
Arrow function return a wrong type in generated code

### ISSUE THREAD

**Issue by djaonourside** [HaxeFoundation/haxe#9180] opened 2020-02-25 17:01 UTC
```haxe
class Main
{
	public static function main()
	{
		var result = produce((obj) -> {
			obj.id = 2;
		});
	}

	public static function produce<T>(producer: T -> Void): T
	{
		return null;
	} 
}
```
`producer` param of `produce` method is typed as returning `Void` but in generated code the callback returns obj:
```
// Generated by Haxe 4.0.2
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	var result = Main.produce(function(obj) {
		return obj.id = 2;
	});
};
Main.produce = function(producer) {
	return null;
};
Main.main();
})({});
```

**Comment by Aurel300** [comment] 2020-02-25 17:47
(literal duplicate of #9181)

**Closed as completed by Aurel300** 2020-02-25 17:47 UTC
