### ISSUE TITLE
js: missing ";" in output code

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxe#4561] opened 2015-09-30 13:48 UTC
Sometimes I get output js:
```js
...
var __map_reserved = {}
(function() {  // from this line - js code included by macro (includeFile)
	var fullScreenApi = {
...
```
Browser interpret this as "{}()" - calling not a function. If I change `untyped __js__("var __map_reserved = {}");` to `untyped __js__("var __map_reserved = {};");` then I get double ";" in the output js code:
```js
...
var __map_reserved = {};;
(function() {  // from this line - js code included by macro (includeFile)
	var fullScreenApi = {
...
```

**Comment by Simn** [comment] 2015-11-20 16:37
Could you provide some Haxe code which reproduces this issue?

**Comment by Simn** [comment] 2016-01-13 13:13
Closing due to lack of followup.

**Closed by Simn** 2016-01-13 13:13 UTC
Labels: platform-javascript

**Comment by elsassph** [comment] 2018-04-25 14:50
Old ticket, but the current state of Haxe JS is that the semicolon has been added:
```javascript
var __map_reserved = {};
```
