### ISSUE TITLE
"this" is null in StringMap.set on html5 target

### ISSUE THREAD

**Issue by chpla** [HaxeFoundation/haxe#5620] opened 2016-09-05 14:41 UTC
```
haxe_ds_StringMap.prototype = {
    set: function(key,value) {
        if(__map_reserved[key] != null) {
            this.setReserved(key,value);
        } else {
            this.h[key] = value;
        }
    }

```

In Haxe 3.3.0 I sometimes have the issue that javascript throws errors in certain functions where the "this" reference is null. In this case, it says "cannot access property h of undefined".

This is where the call is made:
`project.buttonSprite.set(Std.string(entityId), EntityDefine(0, 0, resId)));`

I ensured that the references are all valid.
project is an anonymous structure, its property buttonSprite is of type StringMap. entityId is an Int, as is resId. EntityDefine also returns an Int.

What's going on here? How can "this" be null?

**Comment by nadako** [comment] 2016-09-05 14:51
Could be a JS context loss issue due to temp vars or something. What's the generated code for that `set` call?

**Comment by chpla** [comment] 2016-09-05 14:54
```
var tmp5 = this.EntityDefine(xPos,yPos) | 0;
var tmp6 = this.project.buttonSprite.set;
var tmp7 = this.EntityDefine(0,0,tmp1) | 0;
tmp6(Std.string(tmp5),tmp7);
```

**Comment by nadako** [comment] 2016-09-05 14:55
Is it possible to reduce this to a small self-contained example? Also what's printed on compilation if you do:
```
$type(project);
$type(project.buttonSprite);
$type(project.buttonSprite.set);
```

**Comment by Simn** [comment] 2016-09-05 14:58
Could you try this on a build from builds.haxe.org?

**Comment by chpla** [comment] 2016-09-05 15:02
Ah, doesn't seem to happen with the latest nightly. Thanks a lot!

**Comment by chpla** [comment] 2016-09-22 15:50
I'm afraid the issue still persists when I compile with the latest build on Windows. Seems to work fine when I compile on OSX.

**Comment by Simn** [comment] 2016-09-22 15:51
I'm fairly certain there's no difference in the JS output between Windows and OS X...

**Comment by chpla** [comment] 2016-09-22 15:56
I might be missing something... but when I compile on OSX it works fine, on Windows the bug surfaces (also if I run the compiled script in a browser on the other platform)

On Windows I'm definitely running the latest build (called 3df5463 from yesterady). On OSX it might be a couple days ago that I downloaded the then latest nightly build.

Is there a way for me to determine the exact build version from my osx system and get the same one for the windows one?

Still, it seems like the bug is there in a newer version and not there in the older.

**Comment by Simn** [comment] 2016-09-22 15:57
Can you try finding a reproducible example of this problem?

**Comment by chpla** [comment] 2016-09-22 16:00
you mean outside of my big complex example? Unfortunately, I have yet to be able to pinpoint why this happens sometimes only... but I'll try naming the build versions where it works....

**Comment by chpla** [comment] 2016-09-22 16:01
Okay, it works fine on ba55444

**Comment by Simn** [comment] 2016-09-28 15:53
How do I reproduce this?

**Comment by Simn** [comment] 2017-01-09 09:37
No followup, closing.

**Closed by Simn** 2017-01-09 09:37 UTC
Labels: platform-javascript
