### ISSUE TITLE
Merge type parameters

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#5225] opened 2016-05-11 12:47 UTC
In code, what I would like to do is something like this:

``` haxe
static function merge<A:{}, B:{}>(a:A, b:B):{>A, >B, } {
  return null;//not my point
}
```

The above won't work, because `Multiple structural extension is only allowed for structures` although `A` and `B` are structures. But fair enough, the compiler doesn't really know much at this point and can't tell if there are conflicting fields and what not.

That led me to trying this:

``` haxe
static function merge<A:{}, B:{}, C:(A, B)>(a:A, b:B):C {
  return null;//still not my point
}

merge({ foo: 5}, { bar: "bar" });
```

But that fails saying:

> Constraint check failure for merge.C
> { foo : Int } should be { bar : String }

Since that happens at the call site, I am wondering whether it could not actually work, i.e. if a type parameter is constrained only to anonymous types with distinct fields, could it not be resolved to become their "sum", i.e. `{>A, >B, }` with concrete `A` and `B`, for which it is indeed defined, as this compiles:

``` haxe
typedef HasFoo = {
    foo:Int,
}

typedef HasBar = {
    bar:String,
}

typedef HasBoth = {
    >HasFoo,
    >HasBar,
}
```

It seems like all the pieces are there and just need to be nudged into place. Currently I have to resort to making a macro that creates the return type itself, but to me it seems like something the type system should be able to handle.

**Comment by frabbit** [comment] 2018-09-21 19:19
Just for the record, this is also called `row type polymorphism`.

**Comment by frabbit** [comment] 2018-09-21 20:09
Another case where this is an issue:

```haxe
static function foo <R:{}>(a:R, b: { foo : Int } & R ):Void {
}
```

fails with `Can only extend structures`

**Comment by Simn** [comment] 2020-06-06 16:58
I tried looking at this again and an initial attempt to implement it caused this failure in the cpp tests:

```
D:\a\1\s\win64Binaries\haxe\std/cpp/Callable.hx:55: characters 3-55 : error: cpp.abi.Abi should be getProcAddress.ABI
D:\a\1\s\win64Binaries\haxe\std/cpp/Callable.hx:55: characters 3-55 :  have: cpp.Function<..., cpp.abi.Abi>
D:\a\1\s\win64Binaries\haxe\std/cpp/Callable.hx:55: characters 3-55 :  want: cpp.Function<..., getProcAddress.ABI>
```

If I understand this correctly the problem is that we unify with the constraint too early there. However, unifying with the constraint early is exactly what this issue is about, so now I'm trying to understand in which cases it is sound to do that.

**Comment by Simn** [comment] 2020-06-07 08:03
Here's an isolated version:

```haxe
class C<A> {}

class Main {
	static public function main() {
		getProcAddress();
	}

	public static function getProcAddress<Constraint:String>():C<Constraint> {
		return getProcAddress2();
	}

	public static function getProcAddress2<Constraint:String>():C<Constraint> {
		return cast null;
	}
}
```

With my rework this fails like so:

```
source/Main.hx:9: characters 3-27 : error: String should be getProcAddress.Constraint
source/Main.hx:9: characters 3-27 :  have: C<String>
source/Main.hx:9: characters 3-27 :  want: C<getProcAddress.Constraint>
```

The reason for that is that we close the call type parameters after finishing the `getProcAddress2()` call. It is unbound at this point, so it gets bound to its only constraint `String`.

If we don't handle this immediately after the call, the monomorph is bound to `getProcAddress.Constraint` due to the `return` unifying it with the explicit return type.

This seems to directly conflict with this feature request.

**Comment by back2dos** [comment] 2020-06-07 10:16
At the risk of stating the obvious, let me recap:

```haxe
static function merge<A, B, C:A&B)>(a:A, b:B):C {
  return null;//still not my point
}
```

Now the question is what happens, if `C` starts out as a monomorph. Currently,  `C` is constrained to `A` first and then to `B`, which fails whenever `A` does not unify with `B`. Meaning that `C:A&B` is implied by `C:B` alone, which makes it pretty useless.

What I basically want is not to mess with how constraints are applied, but avoid multiple constraint application: If `C` is defined with the constraint `A&B` **and `A&B` is defined**, then I would propose computing `A&B` and constraining `C` to that.

This poses one question: **what if `A&B` is not defined?**

The least invasive solution would be to fall back to the current behavior, which I fully expect you to dislike. But it's still a whole lot better than nothing - and will not introduce any regressions. 

Short of implementing [constrained monomorphs](https://github.com/HaxeFoundation/haxe/issues/8746), another option would be to resurrect type intersections for classes from haxe 2, e.g. `{>MovieClip, closeButton:Button }`. There are a few use cases for that, like the infamous `DisplayObject & ItemRenderer`. I suspect it would also prove useful when venturing into Java-land.

**Comment by Simn** [comment] 2020-06-07 10:46
I thought the overall idea here was that this:

```haxe
class Main {
	static public function main() {
		$type(merge({foo: 5}, {bar: "bar"}));
	}

	static function merge<A:{}, B:{}, C:A & B>(a:A, b:B):C {
		return null;
	}
}
```

would print `{ foo: Int, bar: String }`. It doesn't seem very useful otherwise.

**Comment by back2dos** [comment] 2020-06-07 11:45
Yes, that's the whole idea, but it doesn't work, because `C` is checked against `A` and then against `B` and that fails. If it were checked against `A&B` (in this case `{ foo:Int, bar:String }`) instead, then it shouldn't fail as `(merge({foo: 5}, {bar: "bar"}):{ foo:Int, bar:String })` compiles just fine.

**Comment by Simn** [comment] 2020-06-07 13:20
Yes I know why it doesn't work. What I'm trying to understand is in which cases it's actually sound to do this. In both the `merge` and the `getProcAddress` case we return a constrained type parameter, but we only want to use its constraints to define the type in the `merge` case.

**Comment by Simn** [comment] 2020-06-07 13:30
Here are both cases in one example to make it more confusing:

```haxe
class Main {
	static public function main() {
		$type(merge({foo: 12})); // { foo : Int }
		returnC();
	}

	public static function returnC<C:String>():C {
		return notMerge(); // String should be returnC.C
	}

	public static function notMerge<C:String>():C {
		return null;
	}

	static function merge<A:{}, C:A>(a:A):C {
		return null;
	}
}
```

I have removed that whole `&` part from `merge` because that isn't my point. My point is that after calling `merge({foo: 12})`, we "immediately" want the type to become `{foo: Int}` by unifying `C`'s monomorph with its constraint.

In contrast, we _don't_ want that in the `notMerge()` call because doing so leads to `C`'s monomorph becoming `String`, which is too specific. It should instead unify with `returnC`'s return type and only then apply the constraint.

**Comment by back2dos** [comment] 2020-06-09 07:47
Ok, I see what you're getting at. For the most part, we're having two different conversations ^^

With the change you've attempted, I would expect the behavior to be more like this:

```haxe
public static function returnC<C:String>():C {
  if (blargh) return notMerge(); //just fine, because `notMerge.C` is inferred top down to `returnC.C`
  var ret = notMerge();
  $type(ret);// String
  return ret;// String should be returnC.C
}
```

Or not?

----

But well, I'm not sure the behavior above is really a good idea.

My main suggestion was that for `C:A&B` where `A&B` is defined, `C` is constrained against `A&B` (which it is currently not).

All that said, the discussion is probably headed in the wrong direction. I introduced `C` only as a workaround, but what I really want is this:

```haxe
static function merge<A:{}, B:{}>(a:A, b:B):A&B {
  return null;//not my point
}
```

I assume that the problem with that is that `A&B` cannot be represented in the typed AST? I guess that circles back to intersecting class types ...

**Comment by Simn** [comment] 2020-06-09 10:04
I just realized that this already works on my branch:

![Code_r9QkuxhExR](https://user-images.githubusercontent.com/634365/84134441-dd933200-aa48-11ea-88c7-47717b3bf8c0.png)

I think the misconception I've been having is that the returned monomorph has to be bound to the merged structure type, but thinking about this again it should be sufficient to have it be _constrained_ to the merged structure type. As long as the compiler deals with structural access and unification correctly, this behaves exactly like we want it to.

The only problem I'm noticing is that error reporting says `Unknown<0> has no field oh` on unknown field access. That's largely a separate issue though.

**Comment by frabbit** [comment] 2020-06-09 17:11
To make it a bit more complicated, I wonder what happens if A and B have the same field with a different type, so that they cannot be unified?

**Comment by nadako** [comment] 2020-06-10 18:23
> this already works on my branch:
> 
> ![Code_r9QkuxhExR](https://user-images.githubusercontent.com/634365/84134441-dd933200-aa48-11ea-88c7-47717b3bf8c0.png)

Hm, I don't get any completion on `development` after the constraint monomorph merge.

**Comment by Simn** [comment] 2020-06-10 18:32
Hmm, me neither. Not sure what I changed that broke this again, though I was kinda surprised that it already worked in the first place.

**Comment by Simn** [comment] 2020-06-10 18:37
I guess I didn't restart the server after committing https://github.com/HaxeFoundation/haxe/commit/ffdb56041b39d42c5bbabb908d9eb3cd2e82791d.

Anyway, completion should be quite easy to add for this, we just have to close the monomorph when we're completing on it.

**Comment by Simn** [comment] 2020-06-10 19:00
Fixed in https://github.com/HaxeFoundation/haxe/commit/c862176a4fa88a74ca50096a75428c96a1f3b295

**Comment by Simn** [comment] 2020-11-19 13:43
I think I meant to close this.

**Closed by Simn** 2020-11-19 13:43 UTC
Labels: enhancement
