### ISSUE TITLE
[HL] Haxe 3.4.4. Infinite loop

### ISSUE THREAD

**Issue by SlavaRa** [HaxeFoundation/haxe#6777] opened 2017-12-05 13:56 UTC
Please check https://github.com/HaxeFoundation/haxe/blob/development/std/sys/Http.hx#L357

**Comment by ousado** [comment] 2017-12-05 14:31
Which target?

**Comment by SlavaRa** [comment] 2017-12-05 14:36
sorry, HashLink

**Comment by ncannasse** [comment] 2017-12-18 12:12
Please detail more exactly the exact problem and how to reproduce it

**Comment by ncannasse** [comment] 2018-02-25 16:16
Closed by 19f27d0202e3ad11ce44057bcb4f365db7822c9b

**Closed by ncannasse** 2018-02-25 16:16 UTC
Labels: platform-hl, standard library, test-needed

**Comment by RealyUniqueName** [comment] 2018-02-25 21:58
Shouldn't we also add a test for this case?

**Comment by ncannasse** [comment] 2018-02-26 14:35
It's quite hard because it requires a server socket closing the connection.
That goes under all these Sys tests that we should be doing
