### ISSUE TITLE
Nightly 353d877, eval stack trace does not include the line that threw

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#6335] opened 2017-06-05 15:18 UTC
I tried running the nightly Haxe build 353d877 (Linux64) to see how macro speed had improved on my large project. Oddly, it's throwing in the JsonPrinter, indicative of a String problem. But that's not what this issue is about. This issue is about the fact that the stack trace printed does not include the actual line that threw. Here's the last two trace statements, and the trace output:

```
/opt/haxe/std/haxe/format/JsonPrinter.hx:94: a0
/opt/haxe/std/haxe/format/JsonPrinter.hx:195: a1
(unknown): Uncaught exception Unexpected value VNull(null), expected int
/opt/haxe-3.4-nightly-353d877/std/haxe/format/JsonPrinter.hx:95: characters 4-12: Called from here
/opt/haxe-3.4-nightly-353d877/std/haxe/format/JsonPrinter.hx:107: characters 5-19: Called from here
/opt/haxe-3.4-nightly-353d877/std/haxe/format/JsonPrinter.hx:46: characters 2-22: Called from here
/home/jward/dev/nimbee/edu/haxe/third_party/modular-js/src/modular/js/Klass.hx:84: characters 28-64: Called from here
/home/jward/dev/nimbee/edu/haxe/third_party/modular-js/src/modular/js/Package.hx:65: characters 20-36: Called from here
/home/jward/dev/nimbee/edu/haxe/third_party/modular-js/src/modular/js/JsGenerator.hx:437: characters 9-23: Called from here
/home/jward/dev/nimbee/edu/haxe/third_party/modular-js/src/modular/js/JsGenerator.hx:505: characters 46-77: Called from here
```

JsonPrinter:95 is simply a function call to quote -- nothing expecting an Integer (and I added the trace statement):

```
      if( c == String ) {
        trace("a0");
        quote(v); // <---- line 95
      } else if( c == Array ) {
```

You can see that the a1 trace statement (which I added to the quote function), so we know the quote function is indeed called. But **the line number inside the quote function is not identified in the stack trace**.

BTW, I'm trying to reduce the actual cause of the exception to a simple testcase.

**Comment by Simn** [comment] 2017-06-05 15:24
I have an idea what causes this, will take a look.

As for the actual issue: I see that JsonPrinter.quote has a conditional compilation case for neko. Can you try if the problem goes away by adding `|| eval` there?

**Comment by jcward** [comment] 2017-06-05 15:31
Oh, sorry, I just finished filing the issue, #6336. I'll try the `|| eval` now.

**Comment by Simn** [comment] 2017-06-05 16:21
Actually not sure if that closed it, there are more decoding functions without positions.

**Comment by jcward** [comment] 2017-06-05 17:20
@Simn hmm, I just rebuilt Haxe (ensuring I have commit aed9ef8), and I'm still getting the above unknown position in the exception. So indeed, as you said, there are likely still more decoding without positions.

**Comment by Simn** [comment] 2017-06-05 17:52
Any chance for a reproducible example? I'm not really sure what else could cause this for integers.

Also, are you 100% certain you're using your new build? Double-check with `where haxe` I guess to make sure.

**Comment by jcward** [comment] 2017-06-05 18:51
@Simn I can send you a (semi) small example privately. I whittled out app down as far as possible, but there's still some proprietary code in it. Can you email me -- jeff dot ward at gmail dot com?

**Comment by Simn** [comment] 2017-06-05 20:19
The problem in your case is `String.fromCharCode` receiving a `null` argument. This reproduces easily:

```haxe
class Main {
    static public function main() {
        if (String.fromCharCode(null) == null) {
            trace("ok");
        }
    }
}
```

I know why it doesn't give you a position for the error itself (because it happens in a native function which doesn't know any positions), but I don't understand why the call to it doesn't show up in the stack trace. Will have to investigate further.

**Comment by jcward** [comment] 2017-06-05 20:35
Ahh, we overwrote StringTools.hx due to some whitespace issue:

250,253c250
<     // The 160 is for:
http://www.fileformat.info/info/unicode/char/00a0/index.htm
<     // I'm not sure how this can be distinguished from ascii 160, á
< return (c > 8 && c < 14) || c == 32 || c == 160;
---
> return (c > 8 && c < 14) || c == 32;

I'm not really sure if that's correct behavior, so I didn't submit an issue
for it.

Well, shoot, sorry for wasting your time. Thanks for your help!

Best,
-Jeff

**Closed** 2017-06-29 16:37 UTC
