### ISSUE TITLE
haxe.macro.TypeTools.map doesn't actually map anons

### ISSUE THREAD

**Issue by ousado** [HaxeFoundation/haxe#5208] opened 2016-05-07 11:18 UTC
The TAnon case is still a TODO, which contradicts the documentation and the results can be quite surprising.

see: https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/macro/TypeTools.hx#L287

**Comment by ousado** [comment] 2016-05-19 20:47
regression: no

**Comment by nadako** [comment] 2016-05-21 18:50
This is not an easy one, since we have to create a new anonymous type with mapped fields and create a reference to it.

Pushing to 3.4 as it's not a regression.

**Comment by Simn** [comment] 2024-02-06 06:34
This was closed in https://github.com/HaxeFoundation/haxe/commit/e83a43889efe402c3a90aae0bcf620fd64ff1342

**Closed by Simn** 2024-02-06 06:34 UTC
Labels: bug, platform-macro
