### ISSUE TITLE
Statics initialization order

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7561] opened 2018-10-19 10:39 UTC
In CS/Java, it seems class statics are initialized lazily (?)

Related issue:  https://github.com/ncannasse/hxbit/issues/24

**Comment by Simn** [comment] 2019-04-10 20:40
This is a duplicate of #4091, where you said it would be fine to leave this unspecified.

**Closed as completed by Simn** 2019-04-10 20:40 UTC
Labels: bug, platform-java, platform-cs
