### ISSUE TITLE
[cs/java] Cannot implicitly convert type `haxe.ds.StringMap<string>' to `haxe.ds.StringMap<object>'

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5953] opened 2017-01-21 15:54 UTC
Main.hx

```haxe
class Main {
  static function main() {
	var map = foo(null);
	trace(map);
  }
  
  static function foo(m:NativeStringMap<String>)
  	return m.toMap();
}

abstract NativeStringMap<V>(Impl<V>) {
	@:to public function toMap():Map<String, V> {
		return new Map();
	}
}

typedef Impl<V> = cs.system.collections.generic.IDictionary_2<String, V>;
```

build.hxml
```
-cp src
-main Main
-cs bin/cs
```

Output:

```
src/Main.cs(37,46): error CS0029: Cannot implicitly convert type `haxe.ds.StringMap<string>' to `haxe.ds.StringMap<object>'
Compilation failed: 1 error(s), 0 warnings
Compilation error
Native compilation failed
Error: Build failed
```

Generated C#:

```c#
public static global::haxe.ds.StringMap<object> foo(global::System.Collections.Generic.IDictionary<string, string> m) {
	// Note: this is where the error occurs	
	// the following expressions generates a StringMap<string>
	// but the return type is expected to be StringMap<object>
	return global::_Main.NativeStringMap_Impl_.toMap<string>(((global::System.Collections.Generic.IDictionary<string, string>) (m) ));
}
```

Haxe revision = 30bb723

**Comment by nadako** [comment] 2017-02-04 01:32
Slightly reduced example:
```haxe
@:nativeGen
class C<T> {}

class C2<T> {}

abstract A<T>(C<T>) {
    function f():C2<T> return null;

    static function foo(a:A<String>) return a.f();
}
```

**Comment by kevinresol** [comment] 2017-02-23 15:01
I think problem is somewhat related to how Java/C# generate type parameters. Seems that whatever type parameters in haxe becomes object when generated:

like
 ```haxe
// Haxe
public function test():Array<Int> {...}
```
is generated as
```java
// Java (C# is similar)
public haxe.root.Array<java.lang.Object> test() {...}
```

note how `Int` becomes `Object`

**Comment by nadako** [comment] 2017-02-23 15:13
Yes, that's how genjava/gencs work in general.

**Comment by kevinresol** [comment] 2017-02-23 15:19
I am trying to start an initiative to distribute haxe generated code in native form: https://github.com/kevinresol/napi

And this problem may become a major obstacle in properly representing haxe types in native targets

Is there any plan to "fix" it? or it is not considered as bug at all?

**Comment by nadako** [comment] 2017-02-23 15:26
I'd love to look into generating proper types where possible, but with the current cs/java generators it's not considered a bug - it's a compromise to ease handling of type system differences between haxe and java/cs. At least what's what @waneck said when I asked about it :)

For native interop you might check out `@:nativeGen` metadata. I used it quite successfully for C# interop glue.

**Comment by kevinresol** [comment] 2017-02-23 15:39
```haxe
@:nativeGen
class Foo<T> {
	var f:T;
	public function new(f:T)
		this.f = f;
}

public function test() {
  return new Function<Int>(1);
  }
```

```java
public foo.Foo<java.lang.Object> test() {}
```

It is still generating `Object` after using `@:nativeGen`, did I miss something?

**Comment by nadako** [comment] 2017-02-23 15:40
huh, maybe that only works for C#...

**Comment by kevinresol** [comment] 2017-02-23 15:41
> huh, maybe that only works for C#...

Just tried. Confirmed.

**Comment by kevinresol** [comment] 2017-03-18 04:17
I think this is not unique to c#, in some occasions this also happens in java

**Comment by kevinresol** [comment] 2017-03-28 08:02
A reduced example that does not involve abstracts:

```haxe
class Main {
	static function main() {
		foo();
	}
	
	static function foo():Array<Null<Int>> {
		var ret = [];
		ret.push(1);
		return ret;
	}
}
```

**Comment by kLabz** [comment] 2019-06-11 06:19
> A reduced example that does not involve abstracts:
> 
> ```hx
> class Main {
> 	static function main() {
> 		foo();
> 	}
> 	
> 	static function foo():Array<Null<Int>> {
> 		var ret = [];
> 		ret.push(1);
> 		return ret;
> 	}
> }
> ```

Problem here is that `ret` is inferred as `Array<Int>` and then used as `Array<Null<Int>>` without it being a problem to haxe. However, when targeting C# this becomes a problem since `Array<Null<Int>>` is generated as `Array<object>` and C# cannot convert type `Array<int>' to `Array<object>'.

For java, `ret` is typed as `haxe.root.Array<java.lang.Object>` since the beginning, avoiding errors. I'll see how it does and try to reproduce it for C#.

This may be extracted as another C#-specific issue, and this one can be closed as #8387 seems to fix it (see #8399 for added tests).

**Comment by kevinresol** [comment] 2019-06-11 08:01
This should be addressed in https://github.com/HaxeFoundation/haxe/issues/4872

**Comment by Simn** [comment] 2019-06-11 08:06
Indeed!

**Closed by Simn** 2019-06-11 08:06 UTC
Labels: bug, platform-cs
