### ISSUE TITLE
Compilation server and Context.onGenerate called from initialization macro

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#5886] opened 2016-12-16 09:12 UTC
It's a pity, but I failed to create minimal example... The bug only show up in my big project and does not reproduce in test environment. 

If I have code like this:
```haxe
package;

class Temp {
	static function init() {
		haxe.macro.Context.onGenerate(function(types:Array<haxe.macro.Type>) {
			trace(haxe.Json.stringify(types));
			for (type in types) {
				trace(type);
			};
		});
	}
}
```
and compile it with --macro Temp.init() using compilation server, then on first run it works as expected and the first trace gives something like this: [8,2,2,8,2,2,3,2,2,3,3,3,3,3,3,2,3,2,8,8,2,...]
But on second run it traces: {"__a":"???","length":2184} 
And then for loop fails with error: Invalid field access : __a

If I change init function to macro function
```haxe
	public static macro function init() {
		haxe.macro.Context.onGenerate(function(types:Array<haxe.macro.Type>) {
			trace(haxe.Json.stringify(types));
			for (type in types) {
				//trace(type);
			};
		});
		return macro null;
	}
```
and call it somewhere in the project, then it always works as expected without any problem.

**Comment by Simn** [comment] 2016-12-16 17:41
@ncannasse: Any immediate idea?

**Comment by ncannasse** [comment] 2016-12-16 19:46
__a + length are normal neko fields for an Array. The fact that it can't be print the second time as an Array by Json stringify seems to indicate that Type.getClass(types) != Array, maybe because there are two macro contexts involved somewhere. Did you try with Haxe GIT ? I made several fixes wrt multiple macro contexts

**Comment by romamik** [comment] 2016-12-18 19:31
I've just tried with latest development build (git build development @ 67add1d) and the problem persists...

**Comment by Gama11** [comment] 2017-02-01 12:46
A very similar error happens when compiling a Flixel project to Neko through the compilation server two times:

```
Error from Haxe server: C:\HaxeToolkit\haxe\std/haxe/macro/Compiler.hx:250: lines 250-264 : Invalid field access : __a
<null pos>:1: character 0 : Called from
Aborted
```

**Comment by back2dos** [comment] 2017-02-01 13:17
Seems weirdly similar to #5984.

Just guessing, but is there any code in place that explicitly "empties" the wrappers around native strings and arrays as part of cache invalidation?

**Comment by francescoagati** [comment] 2017-02-02 10:20
i have some of similar with pariatl lib (for static mixin) and and cache compiler on haxe 3.4.
when i recompile with cache compiler burned i see that the list of fields are always empty.

**Comment by romamik** [comment] 2017-02-21 08:45
I still do not have minimal example, but I have similar problem in another project. In this case I'm using `--macro include` option along with other `--macro` call. First call to compiler works good, but second call gives this: 

	...std/neko/_std/String.hx:56: characters 10-40 : Invalid call //String.charCodeAt()
	...std/neko/_std/sys/FileSystem.hx:59: characters 44-68 : Called from //FileSystem.kind()
	...std/haxe/macro/Compiler.hx:221: characters 22-67 : Called from //Compiler.include()
	--macro:1: character 0 : Called from

I've tried to add some traces but they also fail, even if I'm tracing constant string. I've tried different things and got a way to not fail when tracing. And it looks like neko.NativeString.ofString('test') returns null. This is the code from Compiler.include():

			for( file in sys.FileSystem.readDirectory(path) ) {
				#if neko
				neko.Lib.print(neko.NativeString.ofString('test')); // output 'testnull' when fail 
				#end

				if( StringTools.endsWith(file, ".hx") && file.substr(0, file.length - 3).indexOf(".") < 0 ) {
					var cl = prefix + file.substr(0, file.length - 3);
					if( skip(cl) )
						continue;
					Context.getModule(cl);
				} else if( rec && 
	//						fails here  VVVV
						sys.FileSystem.isDirectory(path + "/" + file) 
						&& !skip(prefix + file) )
					include(prefix + file, true, ignore, classPaths);
			}

I'm trying to reduce the example, but no luck until now.

**Comment by infidel-** [comment] 2017-04-01 19:10
Would it help if I gave the example based on lime? It's not minimal in any way but its open-source and I don't think I can decouple it from their code. I used Haxe 3.4.2 AppVeyor Linux build and lime 4.0.3.

```
haxelib set lime 4.0.3
lime create BunnyMark
haxe --wait 6000
```

First run completes fine, the second one breaks:
```
infidel@purplestar ~/p/BunnyMark> lime build project.xml html5 --connect 6000
infidel@purplestar ~/p/BunnyMark> lime build project.xml html5 --connect 6000
/usr/share/haxe/std/haxe/macro/Context.hx:293: characters 9-37 : Invalid call
/home/infidel/haxelib/lime/4,0,3/lime/_macros/AssetsMacro.hx:58: characters 15-17 : Called from
/home/infidel/haxelib/lime/4,0,3/lime/utils/AssetCache.hx:29: characters 12-39 : Called from
<builtin>:1: character 0 : Called from
/home/infidel/haxelib/lime/4,0,3/lime/utils/AssetCache.hx:14: lines 14-137 : Called from
/home/infidel/haxelib/lime/4,0,3/lime/utils/Assets.hx:47: characters 38-55 : Called from
Aborted
```

**Comment by RealyUniqueName** [comment] 2019-06-21 18:52
I think this kind of issues is gone when macros moved to eval.
I cannot reproduce an issue using the sample from the first post of this issue.
And it used to be reported fairly often (see this issue history and #5984), but no new reports since the summer of 2017. Just when eval was introduced iirc.

I suggest to close this and #5984

**Closed** 2019-06-23 08:56 UTC
Labels: feature-compiler-cache
