### ISSUE TITLE
Code generation problem: this is undefined for tmp setter function

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxe#6225] opened 2017-04-30 12:25 UTC
Source haxe code:
```haxe
if (adapter.layerIndex >= adapter.layers.length)
{
	adapter.layerIndex = Std.max(0, adapter.layers.length - 1);
}
```

Generated js code:
```js
if(this.adapter.get_layerIndex() >= this.adapter.get_layers().length) {
	var tmp = this.adapter.set_layerIndex;
	var b = this.adapter.get_layers().length - 1;
	tmp(0 > b ? 0 : b); // PROBLEM: tmp not related to `adapter` object, so `this` is undefined inside tmp()
}
```

`Std.max()` is `inline` method: 
```haxe
public static inline function max(a:Int, b:Int) : Int return a > b ? a : b;
```

Tested on haxe 3.4.0 & 3.4.2.

**Comment by nadako** [comment] 2017-04-30 12:40
What `adapter` is typed as? I can't reproduce that, but this seems to be an instance of #4787. Please, provide a reproducible example.

**Comment by yar3333** [comment] 2017-04-30 16:10
https://try.haxe.org/#29eE9

```haxe
class StdEx
{
	public static inline function max(a:Int, b:Int) : Int return a > b ? a : b;
}

class Client
{
    public var a : IA = new A();
    
	public function new() {}
	
    public function getB() return 1;
    
    public function f()
    {
		a.p = StdEx.max(0, a.t + getB());
    }
	
}

interface IA
{
    var t : Int;
    var p(get, set) : Int;
}

class A implements IA
{
	public var t = 1000;
    
    public var p(get, set) : Int;
    function get_p() return 10;
    function set_p(v:Int) return 10;
    
    public function new() {}
}

class Test
{
    static function main()
	{
        var t = new Client();
        t.f();
    }
}
```

**Comment by nadako** [comment] 2017-04-30 16:24
Wow this is a weird case, typing differently depending on type order. E.g. this reduced example:

```haxe
class Main {
    static inline function max(a:Int, b:Int):Int return a > b ? a : b;
    static function getB() return 1;
    static var a:I;

    static function main() {
        a.p = max(0, getB());
    }
}

interface I {
    var p(get, set):Int;
}
```

generates

```js
Main.main = function() {
	var tmp = Main.a.set_p;
	var b = Main.getB();
	tmp(0 > b ? 0 : b);
};
```

but if we place declaration of `I` before `Main`, i'll generate:

```js
Main.main = function() {
	var tmp = Main.a;
	var b = Main.getB();
	tmp.set_p(0 > b ? 0 : b);
};
```

**Comment by nadako** [comment] 2017-04-30 16:26
This seems to be a regression, even.

**Comment by Simn** [comment] 2017-05-23 20:19
Somehow the typer messes this up. If the interface is defined first:

```
[Field:Int -> Int]
	[Field:I]
		[TypeExpr Main:Class<Main>]
		[FStatic:I]
			Main
			a
	[FInstance:Int -> Int]
		I
		set_p
```

If it's defined second:

```
[Field:Int -> Int]
	[Field:I]
		[TypeExpr Main:Class<Main>]
		[FStatic:I]
			Main
			a
	[FDynamic:Int -> Int] set_p
```

Looks like the result of a `quick_field_dynamic` or something similar. This probably involves a typing order change as well, so a bisect would be quite interesting.

**Comment by Simn** [comment] 2017-06-01 18:56
What happens is that the accessor fields on the interface are supposed to be created (#3363), but depending on the type order this happens too late. The access then indeed goes through `quick_field_dynamic` and that results in the FDynamic.

Now the only question is how to fix that...

**Comment by RealyUniqueName** [comment] 2017-08-24 09:57
This seems to be fixed in 3.4.2.
I can't reproduce it.

**Comment by Simn** [comment] 2017-08-24 10:04
Probably https://github.com/HaxeFoundation/haxe/commit/a03477e59e88c59af985283d1065ad037770198f again

**Comment by RealyUniqueName** [comment] 2017-08-24 11:01
No, i tested on try.haxe which does not have that commit

**Comment by Simn** [comment] 2017-09-06 08:33
I just checked, it reproduces on development if https://github.com/HaxeFoundation/haxe/commit/a03477e59e88c59af985283d1065ad037770198f is commented out.

**Comment by Simn** [comment] 2017-09-06 08:46
I think I need a new build pass for this. It should clearly happen after PBuildClass (because we need the original field structure), but before PTypeField (because we need the accessor fields at that point).

**Comment by yar3333** [comment] 2017-10-08 07:13
Is this bug will be fixed in 3.4.4 release? Now the only workaround I know is disabling inlining at all...

**Comment by Simn** [comment] 2017-10-08 07:43
I thought this didn't reproduce on 3.4...

**Comment by RealyUniqueName** [comment] 2017-10-08 19:35
It is and i've found lately that it hits our projects badly, because our code is very interface-heavy )

**Comment by Simn** [comment] 2017-10-08 20:53
I'm very confused, you were the one who said it didn't reproduce...

**Comment by RealyUniqueName** [comment] 2017-10-08 21:26
Yes, i remember. I was confused too )
Maybe that's just a similar bug. Let me check tommorow.

**Comment by ncannasse** [comment] 2017-10-09 09:39
I got one recently but didn't report because it was like `(untyped
root.jstree)([for( x in arr ) x])`

**Comment by RealyUniqueName** [comment] 2017-10-12 19:08
I've managed to reproduce our issue with minimal sample. It's another case: #6672

**Closed** 2017-10-12 19:46 UTC
Labels: bug, feature-analyzer, regression
