### ISSUE TITLE
[display] no completion for arguments inside lambda

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7252] opened 2018-07-06 10:16 UTC
When completing the following:

```haxe
class Foo {
	var a : Array<Int>

	function foo() {
		a.map(function(_) {
			a.concat(|)
		});
	}
}
```

I never get arguments completion for concat() call, instead I get `Call expected` error.

**Comment by Gama11** [comment] 2018-07-06 10:19
Probably a duplicate of https://github.com/HaxeFoundation/haxe/issues/7240?

**Closed** 2018-07-27 08:50 UTC
Labels: feature-ide
