### ISSUE TITLE
Analyzer bug for `[ for(i in iterable) i ]`

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxe#4228] opened 2015-05-17 15:27 UTC
In this case there is unnecessary wrapping in the block. See dump.

Example code for reproduce: [gist](https://gist.github.com/fzzr-/aa7781c9bddf80bdb3d6)

Compare two dumps - with & without `-D analyzer`:
1. with: [lines: 45-61](https://gist.github.com/fzzr-/aa7781c9bddf80bdb3d6#file-dump_cpp_without_analyzer-hx-L45-L61)
2. without: [lines: 42-56](https://gist.github.com/fzzr-/aa7781c9bddf80bdb3d6#file-dump_cpp_with_analyzer-hx-L42-L56)

**Comment by fzzr-** [comment] 2015-05-17 15:28
Sorry, already fixed in latest dev-version. ([(nightly](http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/index.html)). Plz. close.

**Comment by nadako** [comment] 2015-05-17 15:30
That looks like 3.2.1 material.

**Comment by Simn** [comment] 2015-05-17 15:54
I'm staring at the dump but can't really spot the difference. What exactly is the problem here and why would it be critical for 3.2?

**Comment by nadako** [comment] 2015-05-17 23:31
The problem is 
```haxe
class Main {
    static function main() {
        var a = [1, 2, 3];
        var b = [for (i in 0...a.length) a[i]];
        trace(b);
    }
}
```
generates this on 3.2 (`b` is not getting initialized with `_g` and in the end so it ends up being `null` on C++)
```haxe
class Main{
	static main(method) : Void -> Void

	 = function() = {
		var a = [1,2,3];
		var b = {
			var _g = [];
			{
				var _g2 = 0;
				var _g1 = a.length;
				while ((true)) {
					var tmp = _g2 < _g1;
					var tmp1 = ! tmp;
					@:whileCond if ((tmp1))break;
					var tmp2 = _g2 ++;
					var i = tmp2;
					var tmp3 = a[i];
					_g.push(tmp3);
				};
			};
		};
		var tmp = {fileName : "Main.hx",lineNumber : 5,className : "Main",methodName : "main"};
		haxe.Log.trace(b,tmp);
	}

}
```
on current development, however, everything is golden (albeit still ugly):
```haxe
class Main{
	static main(method) : Void -> Void

	 = function() = {
		var tmp = [1,2,3];
		var a = tmp;
		var tmp1;
		{
			var tmp2 = [];
			var _g = tmp2;
			{
				var _g2 = 0;
				var _g1 = a.length;
				while ((true)) {
					var tmp3 = _g2 < _g1;
					var tmp4 = ! tmp3;
					@:whileCond if ((tmp4))break;
					var tmp5 = _g2 ++;
					var i = tmp5;
					var tmp6 = a[i];
					_g.push(tmp6);
				};
			};
			tmp1 = _g;
		};
		var b = tmp1;
		var tmp2 = {fileName : "Main.hx",lineNumber : 5,className : "Main",methodName : "main"};
		haxe.Log.trace(b,tmp2);
	}

}
```

**Comment by Simn** [comment] 2015-05-18 05:51
Does this only happen with -D analyzer?

**Comment by fzzr-** [comment] 2015-05-18 09:45
@Simn In the latest nightly build this bug don't exists. Difference of dumps:
![screen shot 2015-05-18 at 12 35 12](https://cloud.githubusercontent.com/assets/888526/7678165/9f816f18-fd5a-11e4-827b-98562f2fc5ce.png)
_Left - without;   Right - with analyzer_

Main difference in existing (or not) `_g2;` before closing block. I mean block who opening here: `var tmp4 = ({` (dumps lines 45 / 42). Without that return we will always get null.

**Comment by fzzr-** [comment] 2015-05-18 09:46
Yes with `-D analyzer` in Haxe *3.2.0 release*. In nightly all ok.

**Comment by Simn** [comment] 2015-05-18 09:47
Alright, what I wanted to know is if it's fine in 3.2.0 without -D analyzer. In that case we don't have to make a hotfix release and can close this issue. Thanks for reporting!

**Closed by Simn** 2015-05-18 09:47 UTC

**Comment by fzzr-** [comment] 2015-05-18 09:50
I think it is urgent to publish the version with the corrections on the website instead of the current 3.2.0. Because it breaks cool syntax in release.

**Comment by fzzr-** [comment] 2015-05-18 09:51
Okay. :(

**Comment by Simn** [comment] 2015-05-18 09:56
Unfortunately this is likely related to #4187 which is going to require some attention.
