### ISSUE TITLE
[PHP] temp vars generated for every condition

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#5085] opened 2016-04-08 15:40 UTC
@Simn 
I found the culprit.
First of all in addition to the line you showed me you also have to comment out this one:
https://github.com/HaxeFoundation/haxe/blob/development/src/optimization/analyzerTexpr.ml#L433

Then you get "normal" conditions in generated PHP, but also a failing test in Issue1827:
https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/issues/Issue1827.hx#L82

From what I've read, the evaluation order in PHP is undefined and the bottom line always is:
Don't write code that depends on some particular evaluation order. Not sure if Haxe is supposed to change this.

But here's an interesting read:
https://gist.github.com/nikic/6699370
The problem in the failing case seems to be caused by the described CV optimization which changes the evaluation order, but only when you have a simple variable at the left side, so:
`$g = 0; $g - $g++;` results in `1` unexpectedly
while:
`$g = 0; $g - $g - $g++` gives you the expected result.

As a "fix" `@` could be added before simple variables (I guess that means constants?) that are supposed read before evaluation:
`$g = 0; @$g - $g++;` is `0`.
Not sure if this is feasible, though..

**Comment by Simn** [comment] 2016-04-08 16:36
> Don't write code that depends on some particular evaluation order. Not sure if Haxe is supposed to change this.

In Haxe we define that the evaluation order matches the syntax.

I don't know about that `@` thing, looks like a massive hack to me. The gist you linked also mentions that it's terrible for performance, so it might not even be preferable to the current state.

This is not easy to deal with unfortunately. Order of evaluation is a known limitation in C, but there it's not much of a problem for us because we can temp-var at our hearts content and let the native compiler deal with the rest.

**Comment by mockey** [comment] 2016-04-08 17:50
> I don't know about that @ thing, looks like a massive hack to me. The gist you linked also mentions that it's terrible for performance, so it might not even be preferable to the current state.

Sure. If it's not possible to use it only in certain corner cases, that's not a solution at all.

> we can temp-var at our hearts content and let the native compiler deal with the rest 

Well, I don't know what the PHP-compiler makes out of all these temp vars. Who knows, maybe it's not so bad at all. I'll try to benchmark it.
Also I see that with the optimization stuff removed I get much more of these mysterious extra functions generated from genphp, which might be worse indeed, like `function App_0, App_1` and so on. I still don't know when and why these are generated, do you?

Maybe just keep that issue open as a reminder...

**Comment by Simn** [comment] 2016-04-08 17:52
Try looking at the output of `-D dump=pretty` to see in which cases genphp creates these extra functions. It might be an if-expression in value-places or something like that.

**Comment by nadako** [comment] 2016-05-21 18:08
As far as I understood this is neither critical, nor a regression, so pushing to 3.4

**Comment by mockey** [comment] 2016-09-27 15:40
@Simn 
Did you change something with regards to this?
I just recompiled a PHP project and saw that many of these conditional temp vars are gone now.

**Comment by Simn** [comment] 2016-09-28 13:01
Might be that the new side-effect checker handles this more gracefully. In that case, let's close the issue!

**Closed by Simn** 2016-09-28 13:01 UTC
Labels: platform-php
