### ISSUE TITLE
Cannot read + write with type inference

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8081] opened 2019-04-01 14:15 UTC
```
class Main {
    static function foo(o) {
        if( o.x == null ) o.x = 0;
    }
    static function main() {
    }
}
```

This used to work and now gives `Cannot access field or identifier x for writing`

**Comment by Gama11** [comment] 2019-04-01 14:23
Probably a duplicate of #8079?

**Comment by Simn** [comment] 2019-04-01 14:28
Let's revert #8011.

**Comment by ncannasse** [comment] 2019-04-01 15:08
@Simn what's exactly the problem here? We can first infer null write then update it to default write since the anon is still open

**Comment by Simn** [comment] 2019-04-01 15:17
That's what I thought it was doing, but apparently it's not what it's actually doing.

**Closed as completed** 2019-04-05 14:52 UTC
Labels: regression
