### ISSUE TITLE
[flash] Failing on glsl2agal.swc

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7796] opened 2019-02-14 11:30 UTC
With the latest Haxe:
```haxe
class Main {
  static public function main() {}
}
```
```
$ haxe -main Main -swf-lib glsl2agal.swc -swf test.swf -swf-lib glsl2agal.swc 
Error: The input swf glsl2agal.swc is corrupted
```
This is official Adobe's library: https://github.com/adobe/glsl2agal/blob/master/bin/glsl2agal.swc
Works fine with Haxe 3.4.

**Comment by Simn** [comment] 2019-02-14 11:55
That is likely going to require a bisect. I didn't think we changed anything related to this...

**Comment by RealyUniqueName** [comment] 2019-02-28 19:32
Can move this to "Release 4.0" milestone?
This is very bad for the Flash target.

**Comment by Simn** [comment] 2019-02-28 19:36
I can but this isn't exactly high on my priority list.

**Comment by nadako** [comment] 2019-02-28 22:00
The issue here is that `IO.read_bits` is bugged in the current extlib version we use. We fixed it in https://github.com/HaxeFoundation/ocamllibs/commit/97ddb4d99884042469e34d1be94b3605d51fbf43 but then it was unfixed by using extlib from opam. I reported the issue here https://github.com/ygrek/ocaml-extlib/issues/50, but we should think about what can/should we do until the fixed extlib is released. One option of course is to copy extlib back into ocamlllibs again...

**Comment by nadako** [comment] 2019-03-03 14:48
Waiting for the new extlib to be released after https://github.com/ygrek/ocaml-extlib/pull/52 is merged. Then we can pin it and it should be fixed :-3

**Comment by Simn** [comment] 2019-03-12 14:21
Can we close this?

**Comment by nadako** [comment] 2019-03-12 14:40
Not yet, I have to figure out how to actually pin the dependency now.

**Comment by nadako** [comment] 2019-03-12 14:41
(i have a [branch](https://github.com/nadako/haxe/commits/extlib_upgrade))

**Comment by Simn** [comment] 2019-03-12 14:53
Why do we have to pin something though? We should only need pinning if we want to rely on an older version of a lib.

**Comment by nadako** [comment] 2019-03-12 15:08
Well, it's not exactly "pinning", it's ` >= "1.7.6"` to make sure we're using the fixed version.

**Comment by nadako** [comment] 2019-03-12 15:10
The problem is that it currently says `  - No package matches extlib>=1.7.6.`, even though it's there (https://opam.ocaml.org/packages/extlib/) and I didn't have a change to investigate the reson.

**Closed as completed** 2019-03-21 22:10 UTC
Labels: platform-flash, regression
