### ISSUE TITLE
Analyzer inlines a non-constant local variable value

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#4727] opened 2015-12-17 08:52 UTC
Source:
```haxe
public function measure(text:String, ?out:BitFontMeasure):BitFontMeasure {
	var len = text.length;
	var i = 0;
	var outWidth = 0;
	var outHeight = 0;
	var rowWidth = 0;
	var spacing = this.spacing;
	while (i <= len) {
		var char = text.charCodeAt(i);
		if (i >= len || char == "\n".code) {
			if (rowWidth > outWidth) outWidth = rowWidth;
			rowWidth = 0;
			outHeight += height;
		} else if (char == " ".code) {
			if (spacing >= 0) {
				rowWidth += 3 + spacing;
			} else rowWidth -= spacing;
		} else {
			var bc = chars[char];
			if (bc != null) {
				if (spacing >= 0) {
					rowWidth += bc.advance + spacing;
				} else rowWidth -= spacing;
			}
		}
		i += 1;
	}
	if (out == null) out = {
		width: outWidth,
		height: outHeight
	} else {
		out.width = outWidth;
		out.height = outHeight;
	}
	return out;
}
```
Output (normal):
```js
,measure: function(text,out) {
	var len = text.length;
	var i = 0;
	var outWidth = 0;
	var outHeight = 0;
	var rowWidth = 0;
	var spacing = this.spacing;
	while(i <= len) {
		var $char = HxOverrides.cca(text,i);
		if(i >= len || $char == 10) {
			if(rowWidth > outWidth) outWidth = rowWidth;
			rowWidth = 0;
			outHeight += this.height;
		} else if($char == 32) {
			if(spacing >= 0) rowWidth += 3 + spacing; else rowWidth -= spacing;
		} else {
			var bc = this.chars.h[$char];
			if(bc != null) {
				if(spacing >= 0) rowWidth += bc.advance + spacing; else rowWidth -= spacing;
			}
		}
		i += 1;
	}
	if(out == null) out = { width : outWidth, height : outHeight}; else {
		out.width = outWidth;
		out.height = outHeight;
	}
	return out;
}
```
Output (analyzer):
```js
,measure: function(text,out) {
	var len = text.length;
	var i = 0;
	var outWidth = 0;
	var outHeight = 0;
	var rowWidth = 0;
	var spacing = this.spacing;
	console.log(this.height);
	while(i <= len) {
		var $char = HxOverrides.cca(text,i);
		if(i >= len || $char == 10) {
			if(rowWidth > 0) outWidth = rowWidth;
			rowWidth = 0;
			outHeight += this.height;
		} else if($char == 32) {
			if(spacing >= 0) rowWidth += 3 + spacing; else rowWidth -= spacing;
		} else {
			var bc = this.chars.h[$char];
			if(bc != null) {
				if(spacing >= 0) rowWidth += bc.advance + spacing; else rowWidth -= spacing;
			}
		}
		i += 1;
	}
	if(out == null) out = { width : 0, height : outHeight}; else {
		out.width = 0;
		out.height = outHeight;
	}
	return out;
}
```
As can be seen, analyzer for some reason assumes that outWidth is always 0, breaking the function.
More code: https://gist.github.com/YellowAfterlife/4fb0859b8706b58ba015
Occurs both in the current public build and current git (d976532).

**Comment by Simn** [comment] 2015-12-17 08:55
Probably a duplicate of #4399.

Bottom line: don't use the analyzer.

**Closed** 2015-12-24 15:21 UTC
