### ISSUE TITLE
[display] diagnostics runs into an infinite loop

### ISSUE THREAD

**Issue by Neverbirth** [HaxeFoundation/haxe#6324] opened 2017-06-02 14:00 UTC
Running diagnostics into one of the files of my main company project makes Haxe run into an infinite loop. Sadly this file doesn't have anything special and it's just 35 lines of code... but the project by itself is really big and cannot be shared :/.

I know this kind of report is quite useless, sorry for that... what could I do to help locating the problem? I tried Haxe 3.4.2 and latest nightly build (156bda1f9) and both have the same problem.

**Comment by Neverbirth** [comment] 2017-06-03 07:58
I tried to investigate a bit more. I could find that the infinite loop is caused by just 1 import, removing it fixes the infinite loop. The strange thing is that running diagnostics for the imported class is fully fine.

I may not be able to do more checks in some time, but I will do my best.

**Comment by Simn** [comment] 2017-06-25 11:14
I'm not sure how I can help here. It could be one of the known compiler infinite loops, but these are usually related to typedefs.

**Comment by Neverbirth** [comment] 2017-06-25 21:43
Yeah, I guess. The problem is that this is not only some really simple file, but there are many other similar classes (a lot...) in the project: same parent class, exactly same code structure with the same calls inside, etc. I have the feeling there are some other classes hanging the compiler when calling diagnostics, but I didn't confirm (there is a sh*tload of files in the project) and due to the structure of the project I would say they are all probably the same case.

I have some ideas of a few more things to check, but didn't have the time for it yet.

**Comment by jeremyfa** [comment] 2017-10-31 19:30
Having the same issue here. Started to have the issue when I updated from haxe 3.4.2 to 3.4.4.

It happens on multiple files on my project but not all. Unfortunately it is also a pretty big project. Getting it consistently on one file currently. I will try to see if changing something in it make diagnostics work and post here.

**Comment by Neverbirth** [comment] 2017-10-31 19:46
On my side sadly I didn't have the time to do all the tests I wanted, but for example global diagnostics doesn't suffer from this issue, also some refactoring to the file didn't make any difference.

**Comment by jeremyfa** [comment] 2017-10-31 20:07
A bit more info in my case after trying to narrow it down:

While it is not the only case where I had the issue (the issue occured on perfectly valid Haxe code that compiles etc...), I could reproduce it in a class by **referencing a type that doesn't exist**. I tried to make a clean project with the same structure, but the issue disappear unfortunately.

I still hope that my use case can help to catch the problem. This is the code that triggers the issue in my project:

<img width="903" alt="capture d ecran 2017-10-31 a 20 55 06" src="https://user-images.githubusercontent.com/164094/32246461-466e60f0-be7f-11e7-8d0c-397de5ec1eae.png">

The code doesn't compile in that case, but if I replace `SomeInvalidType` with, say, `String` (a valid type), the diagnostics run properly and vscode outputs proper error. If I keep `SomeInvalidType`, `haxe` binary runs forever.

**Comment by jeremyfa** [comment] 2017-11-05 18:10
More feedback on this issue:

My code is using quite a lot of macros, and did rely on `Context.resolveType()` at some places. It seems that sometimes, depending on how the project is structured calling `Context.resolveType()` on some types never returns. I can see that I have some other custom build macros (that may also call `Context.resolveType()`) which are triggered by the blocking call, like some recursive resolution type processing etc I guess... but still it never returns and runs forever. I also got the issue at some point when running a normal build. But that's kind of _random_, it seems to depend on the order in which things are processed?

Anyway, I may not have used `Context.resolveType()` in a proper way, but in that case, I would have expected it to fail and throw an error (as stated in the API docs) at worse, but not run forever. I did check that none of my custom macros run into an infinite loop (there are no `while` statements in them so that's unlikely they would?), they seem to all start and finish to execute properly, except when it blocks at `Context.resolveType()` call.

At the moment I found a better solution for my own problem by relying on `Rtti` (at runtime). It makes the issue disappear and is a better approach in my case anyway so that's good.

But I guess there is an issue with `Context.resolveType()`, that should `return/throw` at worse?

I hope these feedbacks help still!

**Comment by Simn** [comment] 2018-05-18 11:57
Does anyone still experience these problems with the current Haxe version?

**Comment by jeremyfa** [comment] 2018-05-18 12:25
So far it's ok for me since I use ``Context.resolveType()`` much less aggressively than before, and that seemed to be the source of the issue in my case (as explained above).

**Comment by Simn** [comment] 2018-05-28 15:44
Thank you for the feedback. I'll go ahead and close this issue for the time being. Should you come across this problem again, please let me know!

**Closed by Simn** 2018-05-28 15:44 UTC
Labels: feature-completion
