### ISSUE TITLE
ArrayAccess is unable to resolve Enum types for shared instance names

### ISSUE THREAD

**Issue by Geokureli** [HaxeFoundation/haxe#7974] opened 2019-03-11 20:27 UTC
The following results in "Error: No @:arrayAccess function accepts arguments of Bar and Int"

```haxe
enum Foo { X; }
enum Bar { X; }
class Test
{
    static function main()
    {
        var fooMap:Map<Foo, Int> = new Map();
        var barMap:Map<Bar, Int> = new Map();
        fooMap[X] = 0; // Error
        barMap[X] = 0; // Valid
        fooMap.set(X, 1); // valid
        barMap.set(X, 1); // Valid
    }
}
```
When Foo is defined after Bar ArrayAccess fails for barMap instead.

I'm expecting array access to behave identical to set() calls

Observed on 3.4.4 and latest dev. Possibly related to: #6743

**Comment by Simn** [comment] 2019-03-12 13:23
Well, we use the type of the array access index to find the `@:arrayAccess` function, not the other way around. I suppose we could use top-down inference if there's only one applicable `@:arrayAccess` function on the abstract in question.

**Comment by Joncom** [comment] 2019-08-04 09:54
> I'm expecting array access to behave identical to set() calls

Agreed. I thought `[]` was just syntax sugar for the `set` and `get` functions. Any good reason that shouldn't be the case?

In Discord, @Gama11 agrees too:

> yeah, [] should have the same behavior as set() IMO

Here's another example where `[]` does not behave like `set`, and it's annoying:

```haxe
class MyClass { public function new() {} }
class SubClass1 extends MyClass {}
class SubClass2 extends MyClass {}

class Test {
    static function main() {
        trace("Haxe is great!");
        var map:std.Map<String, Array<MyClass>> = new std.Map();
        map['foo'] = [new SubClass1()];
        trace(map);
    }
}
```

Produces the error: `Test.hx:11: characters 8-39 : No @:arrayAccess function accepts arguments of String and Array<SubClass1>`

However, compiles just fine if the line is replaced with: `map.set('foo', [new SubClass1()]);`

**Comment by Simn** [comment] 2019-08-04 10:05
My comment explains just that.

**Comment by nadako** [comment] 2019-08-04 10:11
I think this is a duplicate of #6743

**Comment by Simn** [comment] 2019-08-04 10:13
It is indeed.

**Closed as completed by Simn** 2019-08-04 10:13 UTC
