### ISSUE TITLE
Std.parseInt wrong on android

### ISSUE THREAD

**Issue by Vortelio** [HaxeFoundation/haxe#6759] opened 2017-11-27 13:02 UTC
cpp on linux
```haxe
trace ( Std.parseInt("3221225472") ); // -1073741824 true
trace ( (Std.parseInt("3221225472") : UInt) ); // 3221225472 true
trace ( Std.parseInt("0xC0000000") ); // -1073741824 true
trace ( (Std.parseInt("0xC0000000") : UInt) ); // 3221225472 true
```

cpp on android

```haxe
trace ( Std.parseInt("3221225472") ); // 2147483647 false
trace ( (Std.parseInt("3221225472") : UInt) ); // 2147483647 false
trace ( Std.parseInt("0xC0000000") ); // -1073741824 true
trace ( (Std.parseInt("0xC0000000") : UInt) ); // 3221225472 true
```

Haxe Compiler 3.4.4
hxcpp: 3.4.188
openfl: 6.5.0
lime: 5.8.2
android-ndk-r12

**Comment by markknol** [comment] 2017-11-30 21:26
Is this a bug? I think it's documented that the result is unspecified, since the int seems out of int 32 range?

> [`Std.int` API docs](https://api.haxe.org/Std.html#int):  
> `If x is outside of the signed Int32 range, or is NaN, NEGATIVE_INFINITY or POSITIVE_INFINITY, the result is unspecified.`

**Comment by Vortelio** [comment] 2017-11-30 22:45
3221225472 = 0xC0000000
Problem with a decimal number.
With a hexadecimal number - all is well.

**Comment by markknol** [comment] 2017-12-06 19:59
That's still a number above the max int value, so it follows the docs; the result is unspecified.

**Comment by nadako** [comment] 2017-12-20 11:38
assigning to @hughsando because c++ and to @ncannasse to decide if that's expected behaviour

**Comment by ncannasse** [comment] 2018-01-08 22:42
It is indeed unspecified, I'm closing.

**Closed by ncannasse** 2018-01-08 22:42 UTC
Labels: standard library
