### ISSUE TITLE
[dce][js] dce=full is not perfect for js target

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8797] opened 2019-09-11 13:52 UTC
```haxe
import Random;

class Main  {
	static function main() {
		var arr = [];

		var d1 = Date.now().getTime();

		while (arr.length < 15) {
			arr.push(Random.int(1, 9));
		}

		var index = 0;

		while (index < 3) {
			
			var start = index * 5;
			var end = start + 1;

			while (arr[start] == 9) {
				arr[start] = Random.int(1, 8);
			}

			while (arr[start] == arr[end]) {
				arr[end] = Random.int(1 ,9); 
			}

			var start = (index + 1) * 5 - 2;
			var end = start + 1;

			while (arr[end] == 9) {
				arr[end] = Random.int(1, 8);
			}
			while (arr[start] == arr[end]) {
				arr[start] = Random.int(1, 9); 
			}

			index++;
		}
		trace('time= ${Date.now().getTime() - d1}');
		trace(arr.join(','));
	}
}
```

//and genjs

```js
// Generated by Haxe 4.0.0-rc.4+8663dea0e
(function ($global) { "use strict";
var HxOverrides = function() { };
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Main = function() { };
Main.main = function() {
	var arr = [];
	var d1 = new Date().getTime();
	while(arr.length < 15) arr.push(1 + Math.floor(9 * Math.random()));
	var index = 0;
	while(index < 3) {
		var start = index * 5;
		var end = start + 1;
		while(arr[start] == 9) arr[start] = 1 + Math.floor(8 * Math.random());
		while(arr[start] == arr[end]) arr[end] = 1 + Math.floor(9 * Math.random());
		var start1 = (index + 1) * 5 - 2;
		var end1 = start1 + 1;
		while(arr[end1] == 9) arr[end1] = 1 + Math.floor(8 * Math.random());
		while(arr[start1] == arr[end1]) arr[start1] = 1 + Math.floor(9 * Math.random());
		++index;
	}
	console.log("src/Main.hx:53:","time= " + (new Date().getTime() - d1));
	console.log("src/Main.hx:54:",arr.join(","));
};
Main.main();
})({});

//# sourceMappingURL=hello.js.map
```

//actually,there are no need 

```haxe
var HxOverrides = function() { };
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
```

**Comment by kLabz** [comment] 2019-09-11 14:10
Can be reduced to:

```haxe
class Main {
  static function main() {}
  static function unused() trace(Lambda);
}
```

**Comment by RealyUniqueName** [comment] 2019-09-11 14:27
Caused by assigning `Array` to `Iterable`:
```haxe
class Main {
	static function main() {}

	static function unused():Void {
		([]:Iterable<Int>);
	}
}
```

**Comment by RealyUniqueName** [comment] 2019-09-11 14:34
Commenting out the body of `Array.iterator` makes `HxOverrides.iter` disappear from the output:
https://github.com/HaxeFoundation/haxe/blob/463b108071c03b1118f5809aaba9694559ef87ba/std/js/_std/Array.hx#L77-L79

**Comment by sonygod** [comment] 2020-03-05 09:02
still got this 

Generated by Haxe 4.1.0-rc.1+310eae9e6

**Comment by RealyUniqueName** [comment] 2020-03-05 09:03
Not fixed yet.

**Comment by RealyUniqueName** [comment] 2020-03-05 09:04
Closing in favor of #9185

**Closed as completed by RealyUniqueName** 2020-03-05 09:04 UTC
Labels: feature-dce
