### ISSUE TITLE
Enum var read as null in C#

### ISSUE THREAD

**Issue by kgingras** [HaxeFoundation/haxe#5370] opened 2016-06-13 15:19 UTC
When iterating through the string below, the case with "[" will be true and assign array to the type. type is then seen as null and prints the trace statement. All other enums work properly. Is this a haxe compiler issue or enum problem.
```

 enum PropertyType  
 {
    array;
    boolean;
    number;
    string;
    structure;
 }
   
 function CheckEnum():Void
   {
      var chars:String = "tf\"[{-0987654321";
      var type:PropertyType = null;
      var len:Int = chars.length;
    
      for (i in 0...len)
      {
         switch(chars.charAt(i))
         {
            case 't', 'f':
               type = boolean;
               if (type == null){
                  trace("boolean is null..." + chars.charAt(i));
               }
            case '"':
               type = string;
               if (type == null){
                  trace("string is null..." + chars.charAt(i));
               }
            case "[":
               type = array;
               if (type == null){
                  trace("array is null..." + chars.charAt(i));
               }
            case '{':
               type = structure;
               if (type == null){
                  trace("structure is null..." + chars.charAt(i));
               }
            case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
               type = number;
               if (type == null){
                  trace("number is null..." + chars.charAt(i));
               }
         }
      }
```
output is 
`array is null...[`

**Comment by waneck** [comment] 2016-06-13 22:07
I cannot reproduce that. Are you using Haxe 3.3?

**Comment by kgingras** [comment] 2016-06-14 12:06
Currently using 3.2.0. with Unity3d

**Comment by Simn** [comment] 2016-07-18 08:00
Cannot be reproduce on latest Haxe so I'm closing.

**Closed by Simn** 2016-07-18 08:00 UTC
