### ISSUE TITLE
Void->Void is different from StdTypes.Void->Void

### ISSUE THREAD

**Issue by modjke** [HaxeFoundation/haxe#6739] opened 2017-11-10 12:37 UTC
Haxe 3.4.4 stable
```
var a:StdTypes.Int->Void = function (i) {}; //ok
var b:Void->Void = function () {};  //ok
var c:StdTypes.Void->Void = function () {}; //Error:  Void -> Void should be (Void) -> Void
```

https://try.haxe.org/#Ba639

**Comment by modjke** [comment] 2017-11-10 12:40
I'm writing a [mixin](lib.haxe.org/p/mixin) haxelib which does a lot of manual type resolutions, this bug is pretty annoying when dealing with Void types.

**Comment by frabbit** [comment] 2017-11-16 10:04
Duplicate of #3884

**Closed by frabbit** 2017-11-16 10:04 UTC
