### ISSUE TITLE
[hl] interface with type parameter doesn't support the equivalent structural type

### ISSUE THREAD

**Issue by ousado** [HaxeFoundation/haxe#5821] opened 2016-11-14 13:55 UTC
```haxe
interface I<T> {
  var v:T;
}
class C<T> implements I<T> {
  public function new(v:T) this.v = v;
  public var v:T;
}
class Test {
  static function foo(vs:Array<I<Float>>){
    inline function bar(v /* :I<Float> */,r:Float){
      return v.v + 1.23;
    }
    var r = 0.1;   for (v in vs) r = bar(v,r);   trace(r);
  }
  static function main(){
    var vs = ([for (i in 0...123) new C(1.23)]:Array<I<Float>>);
    foo(vs);
  }
}
```
this fails with an assertion in hl2c.ml, currently

**Comment by ncannasse** [comment] 2016-11-19 09:54
Ok, could reproduce and it is correctly detected as an error when using `-D hl-check`
However I'm not sure if the fix should be in HL or Haxe.

This code produces the following AST:
```
[Field:Float]
	[Local v(3946):I<Float>]
	[FAnon:Float] v
```

Because of the inline, when we replace an anonymous by an interface or class instance, I think we should update the fields accordingly, or that could be done as part of a post process maybe?

@Simn what's your opinion on it?

**Comment by Simn** [comment] 2016-11-19 10:49
I think the problem is that we don't run `map_expr_type` if there are no type parameters involved. I've known about this issue, but the inline implementation has a comment that basically suggests that we shouldn't run it because performance.

**Comment by ncannasse** [comment] 2016-11-19 11:55
Is there any other change to be made other than fixing TField ? we could do a specific local thing for TField FAnon/FDynamic in type_inline (no recursion required on the whole AST)

**Comment by Simn** [comment] 2016-11-19 12:01
There were some other issues with skipping the mapping, but I don't remember what exactly at the moment. I wonder if this really has a measurable performance hit given that inline function expressions are usually not that big.

**Comment by Simn** [comment] 2017-05-29 09:34
This might have been fixed by https://github.com/HaxeFoundation/haxe/commit/a03477e59e88c59af985283d1065ad037770198f, can you confirm?

**Comment by ncannasse** [comment] 2018-02-25 12:38
It's correctly working now.

**Closed by ncannasse** 2018-02-25 12:38 UTC
Labels: platform-hl
