### ISSUE TITLE
Math.floor issue

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4254] opened 2015-05-26 18:58 UTC
```
class Test  {

    var px:Int = Math.floor(20);

    public function new () {        
        trace(Math.floor(20));
        trace(px); 
    }
	
	static function main() {
		new Test();
	}

}
```

This trace 0 in Neko, not sure why

**Comment by Simn** [comment] 2015-05-26 19:04
What's the deal with these Math neko "implementations"? https://github.com/HaxeFoundation/haxe/blob/development/std/neko/_std/Math.hx#L43

This happens because we try to inline static calls if we need a constant expression.

**Comment by ncannasse** [comment] 2015-05-26 19:09
The prototype is overridden in __init__, what are you suggesting to prevent this inlining ?

**Comment by Simn** [comment] 2015-05-26 19:18
No idea, Math.hx on neko is in some weird purgatory between being extern and not...

**Comment by Simn** [comment] 2015-06-18 17:55
See linked commit for my suggestion on how to approach this. The idea is to make Math itself extern so the compiler doesn't get funny ideas about inlining things, then provide the actual implementation in a `@:native("Math") class MathImpl`.

**Comment by ncannasse** [comment] 2015-06-18 19:41
@Simn seems good

**Comment by ncannasse** [comment] 2016-02-13 12:29
I have a similar issue when HL, I would like to prevent all @:hlNative methods to be inlined.

**Comment by Simn** [comment] 2016-02-13 12:31
I don't really like this inlining of static calls to fields that are not marked as inline. Do you think we should just remove it?

**Comment by ncannasse** [comment] 2016-02-13 16:54
Any context when it was added ?

**Comment by Simn** [comment] 2016-02-13 18:06
It's quite old: #926

**Comment by ncannasse** [comment] 2016-02-13 19:00
I agree we could disable it for now

**Comment by Simn** [comment] 2016-02-15 13:38
This might cause regressions on AS3 because it has implied `no-inline`.

**Closed** 2016-03-04 20:42 UTC
