### ISSUE TITLE
Json.stringify on hl adds a spurious field when a class implements an interface

### ISSUE THREAD

**Issue by giuppe** [HaxeFoundation/haxe#11261] opened 2023-06-26 16:36 UTC
The JSON output of Json.stringify in certain cases add a spurious field at the end of the stringified object:
```
"": null
```

This seems to happen whenever a serialized object implements an interface (https://try.haxe.org/#46cD4aA2):

```hx
class Test {
	static function main() {
    
		var data:Data1 = new Data1();
		trace(haxe.Json.stringify(data, "\t"));
		trace(haxe.Serializer.run(data));
		trace(Type.getInstanceFields(Type.getClass(data)));
    
                var data2:Data2 = new Data2();
		trace(haxe.Json.stringify(data2, "\t"));
		trace(haxe.Serializer.run(data2));
		trace(Type.getInstanceFields(Type.getClass(data2)));
    
	}
}

interface Data {}

class Data1 implements Data {
	public var temp:Array<Int>;

	public function new() {
		this.temp = [];
	}
}

class Data2  {
	public var temp:Array<Int>;

	public function new() {
		this.temp = [];
	}
}
```

Output on target hl:
```
Test.hx:5: {
	"temp": [],
	"": null
}
Test.hx:6: cy5:Data1y4:tempahg
Test.hx:7: [temp,]

Test.hx:10: {
	"temp": []
}
Test.hx:11: cy5:Data2y4:tempahg
Test.hx:12: [temp]
```

**Comment by kLabz** [comment] 2023-06-26 18:28
Duplicate of #10971
We should probably re prioritize this now that 4.3 is out there.

**Closed as not planned by kLabz** 2023-06-26 18:28 UTC
