### ISSUE TITLE
Unable to build cache (compilation server failing)

### ISSUE THREAD

**Issue by jeremyfa** [HaxeFoundation/haxe#11102] opened 2023-04-08 19:55 UTC
I started testing [Ceramic](https://github.com/ceramic-engine/ceramic) on Haxe 4.3.0. So far it works and builds fine, even noticed some slight improvement in completion speed so thanks for that update 🙏

However the compilation server (via vshaxe) fails to build cache on some projects. Surprising thing is it does build compilation cache fine on my biggest projects but fails on a default empty project with [edit: `-D no_inline` was being added, leading to a #11005 duplicate].

Further edit (check edit history for original issue):

Fix for 11005, which is included in current `development` and `4.3_bugfix` branches, introduced a regression that is breaking Ceramic. Issue has been reduced to the following (with `-D no_inline`):

```haxe
function main() {
	var foo:Foo = 42;

	switch (foo) {
		// Unknown identifier : LCTRL, pattern variables must be lower-case or with `var ` prefix
		case LCTRL: trace("LCTRL");
		case _:
	}
}

enum abstract Foo(Int) from Int to Int {
	var LCTRL:Foo = 224 | (1<<30);
}
```

**Comment by tobil4sk** [comment] 2023-04-08 20:35
The times when it's failing, are you building with `-D no-inline`? If so, this might be #11005.

**Comment by jeremyfa** [comment] 2023-04-08 20:39
No, not using `-D no-inline` at all. Also worth noting that the project does build fine. It's just the completion cache that fails. But yes, the errors seem to occur at the same place as #11005

**Comment by jeremyfa** [comment] 2023-05-11 15:21
Having users of Ceramic starting to report the same issue. Any update on this?

**Comment by kLabz** [comment] 2023-05-11 15:29
I can look into it tonight or tomorrow.
How do I reproduce this issue?

**Comment by jeremyfa** [comment] 2023-05-11 16:07
Easiest way would be to install Ceramic ([following that guide](https://ceramic-engine.com/guides/install-ceramic/)),

Then create a new Ceramic project with:

```ceramic init --name someproject```

Then open `someproject` with VSCode, if you open `.vscode/settings.json`, you should have this content:

```json
{
    "window.title": "${activeEditorShort} — someproject",
    "search.exclude": {
        "**/.git": true,
        "**/node_modules": true,
        "**/tmp": true,
        "**/out": true
    },
    "haxe.executable": "../some/path/to/ceramic/tools/haxe.cmd",
    "haxelib.executable": "../some/path/to/ceramic/tools/haxelib.cmd"
}
```

By default the project is setup to let vshaxe use the haxe and haxelib embedded with Ceramic (which include a workaround, removed the `inline` keywords as mentioned in a previous message here) so you won't have any error.

However, if you remove those two `haxe.executable` and `haxelib.executable` lines from `.vscode/settings.json`, it will switch back to using your global machine's haxe, and if that haxe version is >= 4.3.0, then you should see the error.

Although I reproduce that with Ceramic, I believe the root issue is something else and could probably happen in other situations on non-Ceramic projects.

**Comment by kLabz** [comment] 2023-05-11 20:19
I don't want to be rude but if that's the easiest way I think I'll just close this as no repro..

After downloading the internet I apparently also need a vscode extension, because even after all those steps there seemingly is no other way to try to build. Tried running that clay thing with no success.

**Comment by kLabz** [comment] 2023-05-11 20:30
I actually can't repro on `development`, `4.3.0` or `4.3.1`.
Had to create a `build.hxml` that contains
```hxml
--cwd out/clay/web/
project.hxml
```

And using that as "classic" vshaxe configuration everything seems to work fine.

**Comment by kLabz** [comment] 2023-05-11 20:40
I suggest you try latest [`4.3_bugfix`](https://github.com/HaxeFoundation/haxe/commits/4.3_bugfix) for which you can download nightlies [here](https://github.com/HaxeFoundation/haxe/actions/runs/4924949124#artifacts).

I suspect that 11005 thing would cover the issue you're having (even though I don't repro on versions that don't have that either), and that will be released in `4.3.2`.

**Comment by jeremyfa** [comment] 2023-05-11 23:09
> I don't want to be rude but if that's the easiest way I think I'll just close this as no repro..
> 
> After downloading the internet I apparently also need a vscode extension, because even after all those steps  

Sorry I forgot to mention the vscode extension, which is indeed needed because the issue happens through vshaxe, which consumes the hxml provided by the ceramic extension and fails when building completion cache.

You can definitely build and run Ceramic projects without vscode, you can also generate a completion hxml file with `ceramic clay hxml web` (for web target). I get that it can be annoying to use a third party framework you are not familiar with to reproduce a haxe issue. It doesn't make the issue any less valid though.

Anyway, I tested again over haxe `4.3.1` then with the `4.3_bugfix` of three days ago:

- The issue consistently happens with `4.3.1`

- When using `4.3_bugfix`, I have a new odd regression, with an enum abstract switch case that drops new warnings and an error that breaks completion cache:

```
ceramic/git/clay/src/clay/web/WebRuntime.hx:610: characters 22-27 : Unknown identifier : LCTRL, pattern variables must be lower-case or with `var ` prefix
ceramic/git/clay/src/clay/web/WebRuntime.hx:610: characters 22-27 : Warning : Potential typo detected (expected similar values are LCTRL, RCTRL). Consider using `var LCTRL` instead
ceramic/git/clay/src/clay/web/WebRuntime.hx:610: characters 30-35 : Unknown identifier : RCTRL, pattern variables must be lower-case or with `var ` prefix
ceramic/git/clay/src/clay/web/WebRuntime.hx:610: characters 30-35 : Warning : Potential typo detected (expected similar values are RCTRL, LCTRL). Consider using `var RCTRL` instead
ceramic/git/clay/src/clay/web/WebRuntime.hx:610: characters 30-35 : Variable RCTRL must appear exactly once in each sub-pattern
```

(The related code is there: https://github.com/ceramic-engine/clay/blob/main/src/clay/web/WebRuntime.hx#L610 and the referenced enum abstract with `LCTRL` and `RCTRL` values is there: https://github.com/ceramic-engine/clay/blob/main/src/clay/KeyCode.hx#L231-L238).

I commented out that code just to see if there are still the `Inline variable initialization` errors, and it seems they are gone, so yes that could have been solved with 11005.

Then there is that new regression though, let me know if I should open a new issue for that.

**Comment by kLabz** [comment] 2023-05-12 05:56
Thing is, vshaxe itself is absolutely fine with this on 4.3.x and 4.3_bugfix (I do get the @:extern and @:enum abstract warnings). You either have a project that does something more than a `ceramic init` project, or ceramic tooling is interfering somehow.

![image](https://github.com/HaxeFoundation/haxe/assets/6101998/e9758505-7af3-4ee9-8d88-44712c0bbba2)

Completion, cache, diagnostics, goto definition, etc. everything is working.

**Comment by kLabz** [comment] 2023-05-12 06:47
> No, not using -D no-inline at all.

Seems like ceramic does use it, which explains why the #11005 fix worked:
![image](https://github.com/HaxeFoundation/haxe/assets/6101998/eb3501f1-5dc4-4e76-b7f5-6ce9f4ba41d3)

That's the kind of interfering that makes it harder to repro. And if I do add that to the hxml then I get the errors you mentioned. Checking what is happening.

Also I'm really not sure you should be adding `-D display`, but issue here is `no-inline` anyway.

**Comment by kLabz** [comment] 2023-05-12 07:08
This is a regression since that #11005 fix (#11192), when using `-D no-inline`:

```haxe
function main() {
	var foo:Foo = 42;

	switch (foo) {
		// Unknown identifier : LCTRL, pattern variables must be lower-case or with `var ` prefix
		case LCTRL: trace("LCTRL");
		case _:
	}
}

enum abstract Foo(Int) from Int to Int {
	var LCTRL:Foo = 224 | (1<<30);
}
```

**Comment by jeremyfa** [comment] 2023-05-12 07:10
I was about to reply mentioning that `no_inline`.

First, my mistake sorry, in contrary of what I said before in this thread (when replying to tobil4sk), indeed in the completion hxml contains `-D no_inline`, which is probably why the first issue was also solved by 11005.

Anyway, I do use the same project as you, and if you want to have the exact same hxml as the one provided via Ceramic extension, you can do it like this:

- `ceramic clay hxml web > build.hxml`

Just to be sure I disabled the ceramic extension and tested over that hxml as a "classic hxml", and got the same issues. Tried after removing `-D no_inline` and they seem gone, so that probably comes from that too.

Thanks for taking the time to investigate despite the wrong information from me 😓

And yes, I will remove that `-D no_inline` from completion hxml in next Ceramic release you are totally right. I suspect I added that a long time ago as a lame attempt to make code completion faster.

**Comment by Simn** [comment] 2023-05-12 07:11
Huh, how could an additional `&&` condition cause that branch to be entered?

**Comment by kLabz** [comment] 2023-05-12 07:13
Don't know yet, need to make some coffee first :D

**Comment by jeremyfa** [comment] 2023-05-12 07:29
> Also I'm really not sure you should be adding `-D display`, but issue here is `no-inline` anyway.

I'll test removing `-D display` as well and see how it goes locally. Also added that a long time ago when I was suspecting vshaxe was skipping it when building compilation server cache, messing things in subsequent calls that did have that `display` define, but many things could have changed since then and it could be totally irrelevant.

**Closed as completed** 2023-05-13 13:38 UTC
