### ISSUE TITLE
File "typer.ml", line 1109, Assertion failed

### ISSUE THREAD

**Issue by Blufedora** [HaxeFoundation/haxe#4327] opened 2015-06-13 23:26 UTC
I started getting this error. I wish I could find what is doing it but I have no way to find the error or what it means. I did edit my code but reverted back after getting this error but it did not fix it. I'll try to give code if I had a way to see what is causing the problem. Thanks for any help.

**Comment by Simn** [comment] 2015-06-13 23:35
It fails because the `this` variable of an abstract member function is not found. I can reproduce the error like this:

```
abstract A(String) {
	static public function _new() {
		trace(this);
	}
}
```

For abstracts `_new` has special semantics. This is basically a leftover from the initial abstract implementation and was never properly addressed. Do you happen to have a function named `_new` as well?

Otherwise it must be something else related to abstract member functions, possibly an abstract constructor.

**Comment by Blufedora** [comment] 2015-06-13 23:47
I don't have a function named _new. BTW I using Abstracts with typdefs if that helps.

**Comment by Blufedora** [comment] 2015-06-13 23:54
My constructors are basically:
this = { };
So I guess I'll check the member functions

**Comment by Simn** [comment] 2015-06-13 23:54
If you set the environment variable OCAMLRUNPARAM=b and post the stacktrace the compiler outputs I might be able to give some additional clues.

**Comment by Blufedora** [comment] 2015-06-14 00:00
Sorry, but could you explain how to set the environment variable ?

**Comment by Blufedora** [comment] 2015-06-14 02:48
I finally got to my computer, heres my stack trace:
Fatal error: exception Assert_failure("typer.ml", 1109, 61)
Raised at file "typer.ml", line 1109, characters 61-73
Called from file "typer.ml", line 1133, characters 15-29
Called from file "typer.ml", line 1354, characters 2-93
Called from file "typer.ml", line 2840, characters 15-68
Called from file "typer.ml", line 2948, characters 5-26
Called from file "list.ml", line 55, characters 20-23
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "typer.ml", line 2937, characters 12-987
Called from file "typer.ml", line 3525, characters 10-38
Called from file "typer.ml", line 3486, characters 10-31
Called from file "typer.ml", line 3194, characters 12-46
Called from file "typeload.ml", line 1533, characters 2-25
Called from file "typeload.ml", line 2410, characters 23-74
Called from file "typecore.ml", line 378, characters 3-6
Called from file "typeload.ml", line 2663, characters 51-59
Called from file "typecore.ml", line 365, characters 3-6
Called from file "main.ml", line 1494, characters 2-21
Called from file "main.ml", line 637, characters 3-11
Called from file "main.ml", line 1743, characters 1-35
Build halted with errors.

**Comment by Simn** [comment] 2015-06-14 07:18
> Called from file "typer.ml", line 2948, characters 5-26

Typing the expression of an `{ field: expression }`.

> Called from file "typer.ml", line 2840, characters 15-68

It's a plain identifier

> Called from file "typer.ml", line 1354, characters 2-93

The identifier is resolved to a static field of the class it's in.

> Called from file "typer.ml", line 1133, characters 15-29

The current class is an abstract implementation class and the accessed field has `@:impl` metadata (which usually means that it is not-static).

> Raised at file "typer.ml", line 1109, characters 61-73

Boom

**Comment by Blufedora** [comment] 2015-06-14 16:40
Thank you so much when I undid my changes I forgot to comment out:
this = {
			name:name,
			parent:parent,
			entities:[],
			terrain:[],
			sounds:[],
			//path:get_path() //<- This Line Right Here is The Problem Because the get_path function is using this before this is initialized.
		};

Thanks again, I Like that you explained each of the lines for the error message for me.

**Comment by nadako** [comment] 2015-06-14 16:41
That should still be a proper error message, not a ocaml stacktrace, no?

**Comment by Simn** [comment] 2015-06-14 16:44
Indeed!

@Blufedora: Do you think you could construct a small reproducible example of this error?

**Comment by Blufedora** [comment] 2015-06-14 17:28
Here's a quick example:

    abstract Example(ExampleData)
    {
	    public inline function new(name:String)
	    {
		    this = 
		    {
			    name:name,
			    path:getPath()
		    }
	    }
	
	    public function getPath():String
	    {
		    return 'a/path/to/${this.exampleVar}';
	    }
    }

    private typedef ExampleData =
    {
	    var name:String;
 	    var path:String;
    }

**Comment by Simn** [comment] 2015-06-18 09:00
I can't compile it like that because `exampleVar` doesn't exist.

**Comment by Blufedora** [comment] 2015-06-19 00:45
* sorry forgot to change exampleVar  to name, (I was using exampleVar as the name then changed it to a more applicable)

**Comment by Simn** [comment] 2015-06-19 07:17
That doesn't crash though: http://try.haxe.org/#BF8d5

**Comment by Blufedora** [comment] 2015-06-19 12:07
When running the try haxe I get this: (The crashing is on the windows CPP target.)

Uncaught TypeError: Cannot read property 'name' of undefined,http://try.haxe.org/program/dfaAb/run?r=0.9721240657381713,line:25

**Comment by Simn** [comment] 2015-06-19 12:11
That is to be expected. By the time it evaluates the `getPath()` call no assignment to `this` has been made, so naturally `this.name` is going to cause that error.

I still cannot get it to crash, not on the CPP target either.

**Comment by Simn** [comment] 2015-06-19 12:15
Actually I wonder why this doesn't cause an "initialized variable" error.

**Comment by Simn** [comment] 2015-06-19 12:21
Ok I've fixed it so your example now errors (as it should).

Still looking for the crash though!

**Comment by Blufedora** [comment] 2015-06-19 13:19
This is very odd but for me the ocaml error was shown for cpp not a normal error as js shows (btw it was more of no compiling than crashing)

**Comment by Blufedora** [comment] 2015-06-19 13:24
Do you have the new Analyzer compile feature set ? because I had it not set at the time I had the error.

**Comment by Simn** [comment] 2015-06-19 13:49
I couldn't compile your code without the analyzer because it would complain about `this` not being initialized, as it should.

**Comment by Blufedora** [comment] 2015-06-19 13:53
Yea that's what I thought, it's weird I got the error (at the title) without the `this` not being initialized error on my openfl cpp project using the exact setup. I was hoping the example would show the problem but I can't tell if it's target specific or something else, I'll check my code again to see if anything else would trigger the problem.

**Comment by Simn** [comment] 2015-06-30 11:17
Alright, I can finally reproduce with that and I also see what the problem is now.

**Comment by Simn** [comment] 2015-06-30 11:30
It's very similar to https://github.com/HaxeFoundation/haxe/issues/2277#issuecomment-27285929. I fixed that by checking if there are no calls in the expression that is being assigned to `this` under the assumption that only those would require an implicit access to `this`. However, `this` is also required when taking closures:

```haxe
abstract Example(Void->Void) {
	public function new() {
		this = fun;
	}

	function fun() { }
}

class Main {
	static function main() {
		new Example();
	}
}
```

This cannot be detected in syntax because it's just a plain identifier.

The best idea I have right now is to give a more descriptive error message, but this is still a bit silly because this only breaks due to an optimization we're trying to make.

**Closed** 2016-01-13 11:30 UTC
