### ISSUE TITLE
[cs/java] accessing constrained type parameter fields go through reflection

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6385] opened 2017-06-22 00:09 UTC
Consider this example:
```haxe
class Main {
    function new() {}

    var field:Int;
    function method() trace("hi");

    static function f<T:Main>(v:T) {
        v.field = 42;
        v.method();
    }

    static function main() {
        f(new Main());
    }
}
```

Current generated code:
```cs
public static void f<T>(T v) {
	global::haxe.lang.Runtime.setField_f(v, "field", 9671866, ((double) (42) ));
	global::haxe.lang.Runtime.callField(v, "method", 156956385, null);
}
```

What could be generated instead:
```cs
public static void f<T>(T v) {
	((Main)v).field = 42;
	((Main)v).method();
}
```

All required info is there, because generator receives `FInstance` field access to proper types, so we just need to cast, however I couldn't figure out how to do that with gencommon. I tried checking out `CastDetect` stuff, but it seems that it already receives the dynamic calls (e.g. `callField`) when it's run, and I think it's transformed by `DynamicFieldAccess` filter before, which is decided by `ReflectionCFs.configure_dynamic_field_access` and that uses `field_access(_esp)` functions which I don't really understand.

@waneck if you have some time to work on it anytime soon, that would be awesome, otherwise, hints are welcome :)

**Comment by nadako** [comment] 2017-06-22 00:12
PS A temporary workaround for this would be to add `var v:Main = cast v;` to the beginning of the function, so we cast manually and then access fields properly.

**Comment by waneck** [comment] 2017-06-25 10:27
Duplicate of #3790

**Closed by waneck** 2017-06-25 10:27 UTC
Labels: enhancement, platform-cs, platform-java
