### ISSUE TITLE
"display" not defined in diagnostics display mode

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#9977] opened 2020-12-02 14:19 UTC
We were getting errors in VS Code's problems list. This was due to some macro code executed while processing completion. So we've added this code:
```haxe 
		#if display
		return "";
		#end
```
This reduced number of errors, but they were still showing under some circumstances.
Today I've tracked this down to that `display` is not defined when using `diagnostics` completion mode.

When I execute this command: `haxe --verbose hxml\cpp.hxml --display c:\work\tmp3\src\Main.hx@0@diagnostics > 1.txt`
I get this line in `1.txt`: 
````
Defines: utf16;true;target.utf16=true;target.unicode=true;target.threaded=true;target.sys=true;target.static=true;target.name=cpp;sys;static;source-header=Generated by Haxe 4.1.4;no_copt;hxcpp_smart_strings;hxcpp_api_level=400;haxe_ver=4.104;haxe4;haxe3;haxe=4.1.4;dump=pretty;dce=std;cpp
````
And there is no `display` in the list.
For other `--display ` calls it is there. For example if I use `toplevel` instead of `diagnostics` in the above command line, I get `display=toplevel`.

**Comment by RealyUniqueName** [comment] 2020-12-13 14:43
I never knew if `display` should be defined in macro context. @Simn ?

**Comment by romamik** [comment] 2020-12-14 16:10
1. I feel I need to clarify, that this issue is not about macro context. `display` is not defined not only in macro context, but it is not defined completely.

2. Having `display` defined in macro context is handy. We are using it for a long time. In particular it helps speed up completion using code like in my original message.

**Comment by neillrobson** [comment] 2021-01-08 20:08
I posted in [another issue](https://github.com/HaxeFoundation/haxe/issues/6000#issuecomment-753687835) about my experience, but I now have a minimal reproduction to share here.

I am on Windows 10, PowerShell, Haxe 4.1.4, OpenFL 9.0.2.

In PowerShell:

```
~\git> openfl create project macro-test
~\git> cd .\macro-test\
```

The contents of `Main.hx` are set to the following:

```
package;

import haxe.macro.Context;
import openfl.display.Sprite;

class Main {
	public function new() {
		Context.registerFileDependency(Context.getModule(), "");
	}
}
```

In VSCode, both of the `Context` method calls are marked as errors ("Class <haxe.macro.Context> has no field getModule"). Furthermore, on the command line:

```
~\git\macro-test> cd .\Source\
~\git\macro-test\Source> haxe --display Main.hx@0@diagnostics
[
    {
        "file": "C:\\Users\\Neill\\git\\macro-test\\Source\\Main.hx",
        "diagnostics": [
            {
                "kind": 2,
                "severity": 1,
                "range": {
                    "start": {
                        "line": 6,
                        "character": 10
                    },
                    "end": {
                        "line": 6,
                        "character": 32
                    }
                },
                "args": "Class<haxe.macro.Context> has no field registerFileDependency"
            },
            {
                "kind": 2,
                "severity": 1,
                "range": {
                    "start": {
                        "line": 6,
                        "character": 41
                    },
                    "end": {
                        "line": 6,
                        "character": 50
                    }
                },
                "args": "Class<haxe.macro.Context> has no field getModule"
            }
        ]
    }
]
```

This error persists no matter where I place the file `Main.hx`.

My use-case is doing development with HaxeFlixel, in which [macros are used](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/system/macros/FlxAssetPaths.hx) to define asset paths at compile-time. 

Any ideas how to get the display flag set in these diagnostic modes?

**Comment by Simn** [comment] 2024-02-06 09:34
Diagnostics doesn't define `display` because it's basically just normal compilation with different error reporting. We also don't necessarily want users to check it in their macros because then we'll run into problems where diagnostics reports problems which don't appear during compilation.

**Closed as completed by Simn** 2024-02-06 09:34 UTC
Labels: feature-ide
