### ISSUE TITLE
Date in Java target

### ISSUE THREAD

**Issue by RuiCuco** [HaxeFoundation/haxe#7941] opened 2019-03-06 17:25 UTC
It uses a deprecated API.

**Comment by ncannasse** [comment] 2019-03-09 20:59
Duplicate of #5294, is part of 4.0 Milestone

**Closed as completed by ncannasse** 2019-03-09 20:59 UTC
Labels: platform-java

**Comment by Gama11** [comment] 2019-03-09 21:08
Not anymore it seems:

![](https://i.imgur.com/NrNgmCN.png)

**Comment by ncannasse** [comment] 2019-03-09 22:45
@RuiCuco interested in submitting a PR ?
