### ISSUE TITLE
[cpp] evaluation order issue

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5667] opened 2016-09-13 09:45 UTC
The following should print `{min: 10, max: 20}` and it does that on e.g. JS, but not on C++:
```haxe
class C {
    public var s:String;
    public var p:{min:Int, max:Int};

    public function new(s:String, p:{min:Int, max:Int}) {
        this.s = s;
        this.p = p;
    }
}

class Main {
    static var v = 10;
    static function main() {
        var start = v;
        var s = getS();
        var c = new C(s, {min: start, max: v});
        trace(c.p);
    }
    static function getS():String {
        v += 10;
        return "hi";
    }
}
```

JS:
```js
var start = Main.v;
console.log(new C(Main.getS(),{ min : start, max : Main.v}).p);
```

C++:
```cpp
HXLINE(  14)		HX_VARI( Int,start) = ::Main_obj::v;
HXLINE(  16)		HX_VARI(  ::C,c) =  ::C_obj::__new(::Main_obj::getS(), ::Dynamic(hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("max",a4,0a,53,00),::Main_obj::v)
            			->setFixed(1,HX_("min",92,11,53,00),start)));
HXLINE(  17)		::haxe::Log_obj::trace(c->p,hx::SourceInfo(HX_("Main.hx",05,5c,7e,08),17,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
```

I guess that's because argument evaluation order is undefined on C++? We have to tempvar here...

**Comment by Simn** [comment] 2016-09-13 09:50
If that can be caused by `@:structInit` it should be possible to recreate it with a normal constructor call...

**Comment by nadako** [comment] 2016-09-13 09:59
You're right, updated the description.

**Comment by Simn** [comment] 2016-09-13 10:05
Hmm yes, I suppose we have to treat TObjectDecl like a call in the fusion handler. Probably TArrayDecl as well.

**Comment by nadako** [comment] 2016-09-13 10:09
Well that one was extracted from a case where was no object declarations (I assume they are transformed to @:structInit constructor calls early), e.g.:
```cpp
HXLINE( 128)	HX_VARI( Int,save) = this->pos;
HXLINE( 130)	return  ::hxjson::Json_obj::__new(::hxjson::JsonValue_obj::JString(this->parseString()), ::hxjson::Position_obj::__new(this->filename,(save - (int)1),this->pos));
```

**Comment by Simn** [comment] 2016-09-13 10:27
Should be fixed. Keeping this open because I didn't add any tests yet and because we have to check which other constructs could cause trouble.

**Comment by nadako** [comment] 2016-09-13 10:32
I confirm this fixes the [hxjson issue](https://github.com/nadako/hxjson/issues/7).

**Closed** 2016-09-28 13:05 UTC
Labels: bug, feature-analyzer, platform-cpp
