### ISSUE TITLE
Sys.command and Process.run escaping

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3603] opened 2014-11-20 22:25 UTC
Escaping of command + arguments is badly handled in Neko/hxCPP : it is actually split between Haxe code and C bindings (sys_command / process_run). I think we should entirely move it to C code after we have confirmed every special shell char is correctly escaped, including funny combinations that one might not thing of.

Does anyone have actual experience hacking windows/unix shell and can make a set of unit tests for it ?

Currently we try to call a command by passing these arguments values and check if they are correctly passed : `["foo", "12", "a b  %PATH% $HOME c\\&<>[\"]#{}|%$"]`

**Comment by ncannasse** [comment] 2015-02-22 21:25
@andyli could you try to make extensive unit tests for this that would cover all the platforms quirks ? I'ld be glad to fix that once and for all once we have the tests in place

**Comment by andyli** [comment] 2015-02-22 21:27
I will look into it next week.

**Comment by nadako** [comment] 2015-02-27 16:35
related #3402 #3411

**Comment by andyli** [comment] 2015-03-08 17:38
I've extracted the sys test arguments to [tests/sys/args.txt](https://github.com/HaxeFoundation/haxe/blob/development/tests/sys/args.txt), such that it is now a single place to define the test arguments.

I've looked into some implementations (and tests) of argument escaping: https://gist.github.com/andyli/d55ae9ea1327bbbf749d
Tomorrow I will extract the relevant bits and put them into args.txt.

At the moment, I have discovered that we have problem handling empty strings.
You may try it by changing args.txt to
```
foo
12

a b  %PATH% $HOME c\&<>["]#{}|%$
```
Then run:
```
cd tests
export TEST=neko
haxe -neko RunCi.n -main RunCi -lib hx-yaml
neko RunCi.n
```
error:
```
Command: neko [sys.n,foo,12,,a b  %PATH% $HOME c\&<>["]#{}|%$]
Class: TestSys F..
Class: TestFileSystem ..
Class: io.TestFileInput .........
* TestSys::testArgs()
ERR: TestSys.hx:8(TestSys.testArgs) - expected '4' but was '3'
```

**Comment by ncannasse** [comment] 2015-03-09 20:24
@andyli ah, nice, do you think you could also test various changes in haxe sources to make sure everything pass ?

**Comment by ncannasse** [comment] 2015-03-09 20:25
(+ don't hesitate to request changes to platform owners in case it's handled at native level)

**Comment by waneck** [comment] 2015-03-09 20:26
By the way, while using sys.io.Process to compile some Haxe projects, it seems that in windows passing `include("some.pack")` gets translated to bad code

**Comment by andyli** [comment] 2015-03-10 10:10
@ncannasse What do you mean by "test various changes in haxe sources"?

**Comment by ncannasse** [comment] 2015-03-10 12:34
@andyli like making sure all tests passes when changing https://github.com/HaxeFoundation/haxe/blob/development/std/neko/_std/Sys.hx#L94 . Also, we might need to check both Sys.command and new sys.io.Process

**Comment by Simn** [comment] 2015-03-24 12:59
@andyli: Are we gonna take any action here for 3.2?

Related issues #3402 and #3411.

**Comment by andyli** [comment] 2015-03-24 22:53
I've just changed the args file to [an xml](https://github.com/HaxeFoundation/haxe/blob/development/tests/sys/args.xml).
The currently failing cases are commented out.

I will write tests for `sys.io.Process` tmr.

**Comment by andyli** [comment] 2015-03-26 10:02
I've upgraded sys test. It now runs tests of `Sys.command` and `sys.io.Process` regarding to passing arguments for all sys targets. Simply use the `tests/sys/run.hxml` to compile and run everything. No need to mess with RunCi.hx for sys test anymore.

In summary, we need to fix the following things:
 * Commented cases in [args.xml](https://github.com/HaxeFoundation/haxe/blob/development/tests/sys/args.xml).
 * PHP sys.io.Process doesn't escape arguments. i.e. `testArguments` in [TestProcess](https://github.com/HaxeFoundation/haxe/blob/development/tests/sys/src/io/TestProcess.hx) is failing on PHP.
 * Python has not implemented sys.io.Processing#exitCode() (#4083), thus [TestProcess](https://github.com/HaxeFoundation/haxe/blob/development/tests/sys/src/io/TestProcess.hx) is not run.

**Comment by Simn** [comment] 2015-03-26 10:15
There's something weird about Sys.command on PHP too:

```
C:\GitHub\haxe\tests\sys>php bin/php/Main/index.php
Class: TestSys << was unexpected at this time.
F'"haxe compile-each.hxml --run ExitCode 0"' is not recognized as an internal or external command,
operable program or batch file.
```

It comes from `if (systemName() == "Windows") cmd = '"$cmd"';`

**Comment by jozefchutka** [comment] 2015-08-31 12:33
may I suggest after having `Sys.command` argument escaping issue resolved, to have an additional simpler api that would consume command line - just like what you would type in terminal, and execute it as it is without any additional escaping and modification? then when similar issue occurs later one could resolve it himself by using the raw command line api?

**Comment by andyli** [comment] 2015-12-24 09:26
After struggling with this for a week, I have some initial success but I have come to a conclusion that we do need a way to let users to by pass our auto quoting/escaping as suggested by @jozefchutka.

The reason is that, on Windows, on the system level, the arguments are passed as a single string to an application. Although most applications use the C runtime library parser, there are some applications (e.g. [cmd.exe](http://stackoverflow.com/questions/34448131/does-the-windows-cmd-exe-parse-arguments-differently)) use a different parsing rule. If we just quote/escape input arguments in the C parser way, it will mess up the arguments for some applications.

So here I propose this change:
 * The `args` arguments for both `Sys.command` and `sys.io.Process` will be made optional.
 * When `args` is not `null`, we do auto quoting/escaping for both `cmd` and `args`, which is the current behavior of haxe 3.2.1.
 * When `args` is `null`, no auto quoting/escaping is done on `cmd`, and users should append the arguments with manual quoting/escaping  to `cmd`.

**Comment by ncannasse** [comment] 2015-12-24 09:50
I'm fine with it

**Comment by andyli** [comment] 2016-01-02 07:59
As of now, the argument escaping/quoting has been improved for all targets. There are cases that remain to be looked into:
 * unicode characters on Windows - it works on my Win10 machine, but failed on AppVeyor
 * backslashes, single quotes, and linebreaks on Mac/Linux for the C# target. Somehow mono itself will mess with the input arguments in someway that I'm not sure.
 * linebreaks on Windows. Possibly is a limitation caused by the cmd.exe... See http://stackoverflow.com/questions/34491463/how-to-pass-a-line-break-as-an-argument-via-the-system-function-on-windows

Other related tasks:
 * implement what I've described in https://github.com/HaxeFoundation/haxe/issues/3603#issuecomment-167076677 for all all targets. I have already implemented that for Sys.command of macros/neko/cpp.
 * documentation
 * the current java/cs implementations of Sys.command are somewhat wrong - they do not output stdout/stderr of the command.

**Comment by andyli** [comment] 2016-01-08 09:44
So line breaks on Windows should be a platform limitation. I wouldn't document it for now since I'm not 100% sure and it is rare to use line breaks in cmd arguments anyway.

I've opened an seperate issue for Unicode: #4773

All other tasks have been completed and I will close the issue once the doc is finalized.

**Closed** 2016-01-08 09:54 UTC
