### ISSUE TITLE
[nullsafety] arguments with non-null default values

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7925] opened 2019-03-06 00:25 UTC
This compiles with null safety purely because of the `= ""` default value. However, unlike optional arguments with `?`, default values do not imply nullability, and the argument isn't typed as `Null<String>`. So IMO this should error just like it does when the argument doesn't have a default value.

```haxe
@:nullSafety
class Main {
	static function main() {
		new Main(null);
	}

	function new(s:String = "") {}
}
```

**Comment by RealyUniqueName** [comment] 2019-05-15 17:23
Now I remember, why it works like this.
It's because of null padding on some targets. Which means `new Main()` become `new Main(null)` during the compilation, and null checker cannot distinguish "manual" null and null padding performed by the compiler.

**Comment by RealyUniqueName** [comment] 2019-05-15 19:00
I can allow explicit `null` value and emit an error on any other nullable value:
```haxe
new Main(null); //ok
new Main(nullableExpr); // Error
```
But I'm not sure if it's the way to go.

**Comment by Gama11** [comment] 2019-05-15 19:13
Explicit `null` shouldn't be allowed either though...

**Comment by RealyUniqueName** [comment] 2019-05-15 19:21
Yes, but it is inserted automatically by the compiler on targets like js.
Those probably could be annotated with some special meta.

**Comment by Aurel300** [comment] 2019-05-15 19:23
I think it would be extremely confusing if the user could write an explicit `null` and get no error. I don't think it's such a rare occurrence that this would be acceptable.

**Comment by Gama11** [comment] 2019-05-15 19:24
>Those probably could be annotated with some special meta.

Maybe the already existing `@:compilerGenerated` could be used for that?

**Comment by nadako** [comment] 2019-05-15 22:30
How about just pushing null-padding filter below null-safety checker? :) And if it's not a filter, then maybe it should be? (although there are some performance implications wrt that).

**Comment by vonagam** [comment] 2020-08-14 13:59
> default values do not imply nullability

The problem is that they do currently imply that. Because otherwise this wouldn't have been allowed:
```haxe
function fun(a: Int = 0, b: Int) {}
```

I do agree though, that they should not imply that, but this is not a null-safety issue, that's a design one.

**Comment by Gama11** [comment] 2020-08-14 14:36
@vonagam I don't really follow. By "imply nullability" I mean "change the type to `Null<T>`", which `?` does, but default values don't.

**Comment by vonagam** [comment] 2020-08-14 18:38
Well, this is an artefact of past intended behaviour, where `a: Int = 0` were saying that `a` is in fact is non-nullable argument, but it was changed later to allow nulls, the part where an argument in a function signature (for outside usage) isn't typed as `Null<String>` was not updated.

**Comment by Gama11** [comment] 2020-08-14 18:45
>but it was changed later to allow nulls

Again, I don't follow - `fun(null, 0)` does not compile on static targets. Nor does `if (a == null)` inside the function.

**Comment by vonagam** [comment] 2020-08-14 18:56
> Nor does if (a == null) inside the function

That is right, that's the only point of this thing now, to type `a` as `Int` for inside code, while in reality it is `Null<Int>` for outside world. Here is a illustration from #9833:

```haxe
function fun(a: Int = 1) {
  // body with a as Int
}
// produces
function fun(a: Null<Int>) {
  var a = a != null ? a : 1;
  // body with a as Int
}
```

> fun(null, 0) does not compile on static targets

Consequence of non-nullable type artefact, nothing in actuality prevents this from working, as in this issue pointed out - static targets actually always put nulls into those arguments (null-padding).

**Comment by Gama11** [comment] 2020-08-14 19:08
> static targets actually always put nulls into those arguments (null-padding).

That may be true, I haven't checked the output of every static target, but nevertheless, that seems like a target-specific implementation detail that doesn't really matter to the Haxe user. Some targets that have native support for default values or similar could choose to generate it differently. Relevant: #7143

**Comment by vonagam** [comment] 2020-08-14 19:16
> that seems like a target-specific implementation detail

Nope, that is the current intended [design](https://github.com/HaxeFoundation/haxe/issues/3826#issuecomment-427639415).

> Some targets that have native support for default values or similar could choose to generate it differently.

Yes, i agree that they could and think that they should. And i want some change in specification regarding this and an explicit way for mark native optional arguments (that are non-nullable). That's the whole point of [the proposal](https://github.com/HaxeFoundation/haxe-evolution/pull/81) to allow expressing "optional, but non-nullable".

**Comment by RealyUniqueName** [comment] 2020-08-17 10:56
After thinking a bit more I've came to conclusion that current behavior related to null safety should not be changed.
`new Main(nullableExpr)` actually means "use the value of `nullableExpr` if present, otherwise use default value of the argument". Null value is never passed to the function through an optional non-nullable arguments.

Making null checker to error out in such cases would force users to introduce unnecessary branching.
E.g `new Main(nullableExpr)` would have to be changed into `if(nullableExpr== null) new Main() else new Main(nullableExpr)`

So, unless Haxe semantics with optional non-nullable args is changed this is a wontfix.

**Closed as completed by RealyUniqueName** 2020-08-17 10:56 UTC
Labels: bug, feature-null-safety
