### ISSUE TITLE
t.anOptionalBool==true is false  in cpp 

### ISSUE THREAD

**Issue by cancerberoSgx** [HaxeFoundation/haxe#8541] opened 2019-07-13 16:02 UTC
This happens only on cpp target, haxe version: 4.0.0-rc.3+68333d85d

```haxe
import utest.Assert;
class MiscTest implements utest.ITest {
	public function new() {}
	public function testOptionalBool() {
		testOptionalBoolAux1(1, true);
	}
	public static function testOptionalBoolAux1(x:Int, ?b:Bool) {
		Assert.isTrue(b == true); // <-----  PASS
		testOptionalBoolAux2({x: x, b: b});
	}
	public static function testOptionalBoolAux2(l:T) {
		Assert.isTrue(l.b == true); // <-----  FAILS
	}
}
typedef T = {
	@:optional var b:Bool;
	var x:Int;
};
```

**Comment by Aurel300** [comment] 2019-07-15 09:24
Reduced a bit:

```haxe
class Main {
	public static function main():Void {
		var b:Null<Bool> = true;
		var s:{b:Null<Bool>} = {b: b};
		trace(s.b == true);
		function check(l) {}
		check(s);
	}
}
```

If the `check(s)` line is commented out, prints `true` as expected. With the line present, prints `false`. The function call forces `s` not to be destructured. With `check(s)`:

```cpp
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_2_main)
HXLINE(   3)		 ::Dynamic b = true;
HXLINE(   4)		 ::Dynamic s =  ::Dynamic(hx::Anon_obj::Create(1)
            			->setFixed(0,HX_("b",62,00,00,00),b));
HXLINE(   5)		::haxe::Log_obj::trace(hx::IsEq( s->__Field(HX_("b",62,00,00,00),hx::paccDynamic),true ),hx::SourceInfo(HX_("Main.hx",05,5c,7e,08),5,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
HXLINE(   6)		 ::Dynamic check =  ::Dynamic(new _hx_Closure_0());
HXLINE(   7)		check(s);
            	}
```

Without `check(s)`:

```cpp
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_2_main)
HXLINE(   3)		 ::Dynamic b = true;
HXLINE(   4)		 ::Dynamic s_b = b;
HXLINE(   5)		::haxe::Log_obj::trace(hx::IsEq( s_b,true ),hx::SourceInfo(HX_("Main.hx",05,5c,7e,08),5,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
HXLINE(   6)		 ::Dynamic check =  ::Dynamic(new _hx_Closure_0());
            	}
```

For some reason `hx::IsEq( s->__Field(HX_("b",62,00,00,00),hx::paccDynamic),true )` fails.

**Comment by RealyUniqueName** [comment] 2019-07-22 17:39
I cannot reproduce this on Linux neither with hxcpp 4.0.19 nor with the latest development hxcpp.
The generated cpp code looks exectly like the first cpp snippet posted by @Aurel300 
Could it be windows-only bug?

**Comment by Aurel300** [comment] 2019-07-22 17:46
Actually this was fixed in https://github.com/HaxeFoundation/hxcpp/commit/8f4396940a8d580b35bc10a9557c0c35581a2900, my bad.

**Closed as completed by Aurel300** 2019-07-22 17:46 UTC
Labels: bug, platform-cpp
