### ISSUE TITLE
API documentation (api.haxe.org) now shows private fields by default

### ISSUE THREAD

**Issue by jasononeil** [HaxeFoundation/haxe#6735] opened 2017-11-04 21:32 UTC
### Expected behaviour:

The public API docs on api.haxe.org should not show private fields of classes, or at least not show them unless you explicitly toggle something to make them visible.

(I would argue there is no need for the standard library to expose the internals on the API doc page)

### Actual behaviour:

At some point recently api.haxe.org started showing private fields:

eg, this page https://api.haxe.org/Sys.html shows:

<img width="920" alt="screen shot 2017-11-05 at 8 30 00 am" src="https://user-images.githubusercontent.com/315158/32409639-940eb67a-c203-11e7-92a8-6ada9f6632b9.png">

---

I can see @andyli was doing some work a few weeks ago to get docs updating through CI, so maybe something inadvertently changed then?

https://github.com/HaxeFoundation/haxe/commit/f2533832ddcdaa65938c5f815bac753202bec9c3

**Comment by andyli** [comment] 2017-11-30 08:18
It was caused by https://github.com/HaxeFoundation/dox/commit/85f684cd5ae4186c82277297612e63440f3b3bc7, in which the `filterFields()` function was mistaken to be modifying the input.

It is now fixed by https://github.com/HaxeFoundation/dox/commit/f3f6b16a77e1484d3b3b28122f9275c75e71e058 and https://github.com/HaxeFoundation/api.haxe.org/commit/f3caf13d6cb5cf336395ae17367e9128a8cadad2.

**Closed by andyli** 2017-11-30 08:18 UTC

**Comment by jasononeil** [comment] 2017-11-30 23:54
Thanks Andy! Glad to see the API docs looking clean and concise again :)
