### ISSUE TITLE
[as3] Map iterators don't work

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7517] opened 2018-10-04 15:00 UTC
```haxe
class Main {
	static public function main() {
		var map = ["1" => "2", "3" => "4"];
		for (v in map) {
			trace(v); // null
		}
	}
}
```

**Comment by Simn** [comment] 2018-10-04 15:01
I should mention that this is specific to StringMap.

**Comment by Simn** [comment] 2018-10-04 15:16
It's also specific to "numeric string keys"...

**Comment by markknol** [comment] 2018-10-04 15:49
Map.get generates
```as3
		public function get(_tmp_key : *) : * {
			var key : String = ((_tmp_key) as String);
			if(this.isReserved(key)) return this.getReserved(key);
			return this.h[key];
		}
```
When logging these values: `var map = ["1" => "2", "3" => "4"];`
```
key=null   _tmp_key=1   isString=false   type=number
key=null   _tmp_key=3   isString=false   type=number
``` 
when using non- numeric keys: `var map = ["1a" => "2", "3a" => "4"];`
```
key=1a   _tmp_key=1a   isString=true   type=string
key=3a   _tmp_key=3a   isString=true   type=string
```

**Comment by markknol** [comment] 2018-10-04 16:04
its already wrong in `keys()`, this is generated like this:
```as3
public function keys() : * {
			var out : Array = (function($this:StringMap) : Array {
				var $r : Array;
				$r = new Array();
				for(var $k2 : String in $this.h) $r.push($k2);
				
				trace($r); // I added this
				trace(typeof($r[0])); // I added this
				
				return $r;
			}(this));
			if(this.rh != null) out = out.concat((function($this:StringMap) : Array {
				var $r3 : Array;
				$r3 = new Array();
				for(var $k4 : String in $this.rh) $r3.push($k4.substr(1));
				return $r3;
			}(this)));
			return out.iterator();
		}
``` 
which logs in this case `["1" => "2", "3" => "4"];`
```
1,3
number
```
but with non-numeric `["1a" => "2", "3a" => "4"];`
```
1a,3a
string
```

**Comment by markknol** [comment] 2018-10-04 16:17
I found the cause of this

In as3 

```as3
var keys = {};
keys["1"] = "4";
for(var v:* in keys) {
    trace(typeof(v));
}
```
traces `number`

but


```as3
var keys = {};
keys["1a"] = "4";
for(var v:* in keys) {
    trace(typeof(v));
}
```
traces `string`

**Comment by jcward** [comment] 2018-10-04 16:50
Can you make it generate a String cast, like this?

```
  for(var $k2 : String in $this.h) $r.push(String($k2));
```

**Comment by jcward** [comment] 2018-10-04 16:53
BTW, I recall that JS / AS3 both have oddities wrt numeric keys, e.g. JS allows you to access an object or array with either (I forget is AS3 does):

![image](https://user-images.githubusercontent.com/2192439/46489823-ad02eb80-c7c3-11e8-8108-47119eba86f9.png)

In other words, `obj[4]` and `obj["4"]` point to the same entry, their value cannot be different -- but I don't think that's an issue here...

**Comment by azrafe7** [comment] 2018-10-04 19:10
Was following the discussion and found this article investigating this odd as3 behaviour: https://jacksondunstan.com/articles/2520

**Comment by markknol** [comment] 2018-10-04 20:10
Anyone cares enough to actually fix this?

**Comment by azrafe7** [comment] 2018-10-04 21:56
I think that the solution proposed by @jcward is fine to solve the issue: "force" the key to be a `String`.
 (I've locally made a simple test modifying the haxe-generated as3 and its output seems to be correct)

What I'm _slightly_ worried about is that it allocates a `String` for every key, _presumably_.

Not ready yet to make a proper PR, sorry. But downloading all the relevant parts to contribute in the future.

**Comment by jcward** [comment] 2018-10-04 22:20
I suppose you could check the type before casting, but I would hope `String(someString)` doesn't cause an allocation.

 ```
 for(var $k2 : String in $this.h) $r.push( ($k2 is String) ? $k2 : String($k2) );
```

BTW, as Mark notes above, looks like the generated `Map.get` is already using a cast (I believe `x as String` is equivalent as3 to `String(x)`:

```
  var key : String = ((_tmp_key) as String);
```

So we're probably fine without a type check (no worse than Map.get).

**Comment by markknol** [comment] 2018-10-05 06:43
@Simn I think it should be fixed in ocaml? https://github.com/HaxeFoundation/haxe/blob/development/std/flash/_std/haxe/ds/StringMap.hx#L90

Since its using magic `__keys__`

**Comment by Simn** [comment] 2018-10-05 06:45
I'm not sure I care enough to fix this...

**Comment by Simn** [comment] 2018-10-07 12:30
Since this definitely falls under the old-weird-flash-specific category, I'm gonna close it as unresolved.

**Comment by ncannasse** [comment] 2018-10-07 18:09
Does replacing `for(var $k2 : String in $this.h)` by `for(var $k2 : * in $this.h)` work ? I think it would be a small fix.

**Comment by RealyUniqueName** [comment] 2019-06-07 19:35
> Does replacing for(var $k2 : String in $this.h) by for(var $k2 : * in $this.h) work ? I think it would be a small fix.

Nope. Doesn't work.

Let's close this again. Because #8295

**Closed as completed by RealyUniqueName** 2019-06-07 19:35 UTC
Labels: bug, platform-as3, feature-iterator, feature-coretype
