### ISSUE TITLE
Cannot redefine StringTools

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#8483] opened 2019-06-26 22:16 UTC
```haxe
class Main {
	static function main():Void {
		trace(StringTools.contains("string", "s"));
	}
}

class StringTools {
	public static function contains(s:String, value:String):Bool {
		return Std.random(2) == 0;
	}
}
```
`Type name StringTools is redefined from module StringTools`

**Comment by Aurel300** [comment] 2019-06-26 22:46
This is not a Java-specific issue.

**Comment by Ilir-Liburn** [comment] 2019-06-27 00:28
StringTools is a standard type, use static extension

```haxe
class MyStringTools extends StringTools {
	public static function contains(s:String, value:String):Bool {
		return Std.random(2) == 0;
	}
}
```

**Comment by Gama11** [comment] 2019-06-27 00:56
What's the point of extending StringTools there? Static fields are not inherited.

**Comment by Ilir-Liburn** [comment] 2019-06-27 01:04
No point. Just standard procedure if extended type have some fields ready to be accessed.

**Comment by ncannasse** [comment] 2019-06-27 02:33
We should either close this or improve the error message, for instance
"Type name StringTools is already defined in standard library"

But it's tricky because we might end up defining the custom StringTools (or another custom type) before we do include it from the std lib.

**Comment by Simn** [comment] 2019-06-27 05:13
I'm confused, why doesn't this simply shadow std/StringTools?

**Comment by kLabz** [comment] 2019-06-27 05:22
Because it's not in StringTools.hx but in another top-level module?

**Comment by Simn** [comment] 2019-06-27 05:26
Right, they are referenced differently... In that case I agree there's nothing to fix here.

**Closed as completed by Simn** 2019-06-27 05:26 UTC

**Comment by RblSb** [comment] 2019-06-27 05:30
This does not work independently of the module package. Can you explain please? Also this shadowing works for js/cpp for example.

**Comment by RblSb** [comment] 2019-06-27 06:04
Probably you mean how code is generated with `_Module` package on some targets.
```haxe
// works only if class has "private" on java and module is top-level
class Sys {
	public static function hi():String {
		return "hi";
	}
}
class Main {
	static function main():Void {
		trace(Sys.hi());
	}
}
```
I think this can be fixed with full paths access / renaming on compilation or blocking such behavior for all targets.

**Comment by Simn** [comment] 2019-06-27 06:06
The problem is that your StringTools is "hidden" inside another module, so any reference to `StringTools` would not pick it up. This means that resolution from Main would reference Main.StringTools, whereas from anywhere else it would pick up std/StringTools.

**Comment by RblSb** [comment] 2019-06-27 06:28
Sorry, don't get it... My example is in one file/module `Main`, there is no `StringTools` module, as error says. You say that `StringTools.contains` call works like `Main.StringTools.contains` inside of `Main.hx`. That's true, and it works without errors http://try-haxe.mrcdk.com/#1A4d3
Or you describe generated code behavior?

**Comment by Simn** [comment] 2019-06-27 06:31
Imagine you're some/module/Somewhere.hx and you reference `StringTools`. What would you get? It would be the StringTools.hx in std because that's the only one you see, right?

**Comment by RblSb** [comment] 2019-06-27 06:40
Right! Even if there is some/StringTools.hx, top-level classes is first. But how about some/Module.StringTools?

**Comment by Simn** [comment] 2019-06-27 06:43
> Right! Even if there is some/StringTools.hx, top-level classes is first.

I don't think that's true, class paths are checked bottom-up (edit: that's confusing terminology... they are checked from the deepest path upwards).

> But how about some/Module.StringTools?

That depends. If some/Module.hx is typed first, then the StringTools type would be known. However, if not, the type would not be seen by the resolution. The type loader doesn't check every module it comes across to see if it happens to contain the type you're looking for. Hence the error.

**Comment by kLabz** [comment] 2019-06-27 06:46
> Right! Even if there is some/StringTools.hx, top-level classes is first. But how about some/Module.StringTools?

This should work as long as `Module` is in any package that is _not_ top level. When `Module` is top level, you are defining `Module.StringTools` but `StringTools` will have a package of `[]` and will conflict with the std one.

Your Main inside `src/some/Main.hx` with `-cp src` will compile (even to java).

**Comment by RblSb** [comment] 2019-06-27 06:54
Oops, messed up that js.Date case, yeah, types checked from the deepest :)
I guess if i will check js/ccp without try.haxe/dependencies i will get same error then. Sorry again and thanks for explanation!
