### ISSUE TITLE
Abstract operator error

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4914] opened 2016-03-08 21:42 UTC
This gives some strange error:

``` haxe
// -lib heaps
class Main {
    static function main() { 
        var s : hxd.UString;
        var life = 8;
        s = (life > 9 ? '' : '0' ) + life;
    }
}
```

It actually depends on the conditional check being there.

**Comment by Simn** [comment] 2016-03-08 21:59
1. Due to #2786 UString is pushed onto the operands as a `with_type`.
2. The TIf typing does `cast_or_unify` of the then/else expressions against the `with_type`. This succeeds because UString has `from String`.
3. You end up with `UString + Int` which the compiler doesn't like.

**Comment by ncannasse** [comment] 2016-12-14 21:53
Looking at this, I understand how it works but I'm still not very happy with the way the compiler react. However doing this properly is quite hard since it would involve resuming from the error and trying again to type this time without the with_type constraint, which I'm sure you will not like :)

**Comment by Simn** [comment] 2016-12-15 09:49
The general problem I see is that "trying again" and our type inference don't work together very well in general. There are too many monomorphs floating around which can be bound to something before the compiler decides to "try again".

**Comment by Simn** [comment] 2018-05-30 18:49
I still don't know what to do with this. I feel like #2786 was a mistake and now we run into situations like this.

**Comment by Simn** [comment] 2019-07-02 17:38
This doesn't reproduce anymore. I don't know why, but let's quickly close it before it comes back.

**Closed by Simn** 2019-07-02 17:38 UTC
