### ISSUE TITLE
ExprTools.map or macro-in-macro bug?

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#3731] opened 2015-01-02 17:52 UTC
```haxe
import haxe.macro.*;
import haxe.macro.Expr;

class Utils {
	/*
		It maps identifier `v` to `__hxAnonCls_this.v`.
	*/
	macro static public function resolve(e:Expr):Expr {
		return switch (e.expr) {
			case EConst(CIdent(varName)):
				macro __hxAnonCls_this.$varName;
			case _:
				ExprTools.map(e, wrapResolve);
		}
	}
	static function wrapResolve(e:Expr):Expr {
		return macro Utils.resolve($e);
	}
}

#if !macro
class Test {
	static function main():Void {
		var __hxAnonCls_this = {
			fun: function(){},
			arr: ["a", "b", "c"]
		};

		Utils.resolve(fun()); //ok
		Utils.resolve(arr.copy); //ok
		Utils.resolve(arr.copy()); //--interp: Invalid field call, JS: Can't create closure on an extern inline member method
	}
}
#end
```

Above is a reduced version of https://gist.github.com/andyli/109d66006d165685f00c

**Comment by Simn** [comment] 2015-01-13 17:47
Actually I don't think this is a bug. You cannot split up an EField expression and type its individual parts like that. There are semantics attached to the expression as a whole, such as pack1.pack2.Type resolving to a type expression.

**Comment by andyli** [comment] 2015-01-13 20:54
I'm not sure. At least the example I posted does not have such `pack1.pack2.Type`.
I am able to achieve my goal with some other code, so this issue isn't really important for me now. Just worried there is a hidden issue.

**Comment by Simn** [comment] 2015-01-14 00:10
It's the same deal with `arr.copy()` if you type it as `(arr.copy)()`. This creates a self-calling closure, hence the JS error.

But I'll reopen to check where exactly the invalid call comes from. I was assuming this was particular to Array because Array is quite particular itself.

**Comment by Simn** [comment] 2015-01-15 18:10
It's a bit of a funny case which can be reproduced like this:

```
class Main {
	static function main():Void {
		var arr = [];
		test()();
	}

	macro static public function test() {
		return macro arr.copy;
	}
}
```

The expression this generates cannot be written in syntax, which is why the compiler doesn't handle this case. It passes a FClosure to `unify_field_call` which doesn't know what to do with that.

**Comment by Simn** [comment] 2015-01-15 18:28
You forced lazy evaluation of a pending FClosure change I wanted to make, so this should work now.

**Closed** 2015-01-15 18:27 UTC
