### ISSUE TITLE
[flash] Unbalanced stack when switching on a nullable type.

### ISSUE THREAD

**Issue by Herschel** [HaxeFoundation/haxe#3061] opened 2014-05-27 18:57 UTC
It seems that invalid bytecode is being generated when using a switch on a `Null<MyEnum>` as a value:
Here's the minimal example I was able to produce:

```
package ;

class Main 
{
	public static function main()
	{
		e = A;
		foo(
			switch( e )
			{
				case A: 1;
			}
		);
	}
	
	static function foo( v : Int ) trace( v );
		
	static var e:Null<MyEnum>;
}

enum MyEnum
{
	A;
}
```

This throws an "Unbalanced stack" error in the AVM. Removing the Null<> makes it disappear.

Occurs on https://github.com/HaxeFoundation/haxe/commit/5493c1ac3d42cfa48a8ba1e14211e94beb63e9cb but not on 3.1.3.

**Comment by ncannasse** [comment] 2015-02-19 20:06
@Simn the generated AST is 
```
		Test.foo({
			var _g = Test.e;
			if ((_g != null))1;
		});

```
This is not be the case since we except a return value for all the paths

**Comment by Simn** [comment] 2015-02-19 20:19
I know it's not correct, I just don't know what you want here. In #3054 you told me to not report `null` as an unmatched pattern for top-level matches. I also don't think it's a good idea to introduce implicit null-values here, especially in cases like this where it would be assigned to a basic type on a static target. So what should I change this to?

**Comment by ncannasse** [comment] 2015-02-20 21:24
Let's look at it:

```
enum E { A; B; }

var x : Null<E>;

// toplevel
switch( x ) {
case A:
case B:
case null: // allow to catch x == null
}

// toplevel, no null check
switch( x ) {
case A:
case B:
}
// no compilation error, but runtime error when switching on x

// as value; null check
var r = switch( x ) { case A: 0; case B: 1; case null: -1; } // ok

// as value; no null check
var r = switch( x ) { case A: 0; case B: 1; } // runtime error if x is null
```

So I guess the problem is the optimization that comes with single case matching. Maybe in that case we should throw an error if null in order to keep the same behavior as unoptimized switch

**Comment by Simn** [comment] 2015-02-20 21:28
I'm getting the same error if in the original issue I add another constructor + case.

**Comment by ncannasse** [comment] 2015-02-20 21:29
Uhm, why ? you should only check for  != null if you have an else with a case null expression

**Comment by Simn** [comment] 2015-02-20 21:58
That's actually a very good question...!

**Closed** 2015-02-20 22:18 UTC
