### ISSUE TITLE
final unification failure despite read-only usage

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7818] opened 2019-02-19 22:13 UTC
This seems somewhat annoying - all usages of `struct.foo` in `foo()` are read-only. Shouldn't `struct.foo` be inferred as `final`?

```haxe
class Main {
	static function main() {
		foo(({foo: 0} : Struct)); // error: Cannot unify final and non-final fields
	}

	static function foo(struct) {
		trace(struct.foo);
	}
}

typedef Struct = {
	final foo:Int;
}
```

At the very least, the error message should be improved to include `final`, as this is quite confusing (similar to #7780). And how does `Dynamic` get involved?

```
source/Main.hx:3: characters 7-26 : error: Cannot unify final and non-final fields
source/Main.hx:3: characters 7-26 :  have: { foo: Dynamic }
source/Main.hx:3: characters 7-26 :  want: { foo: Dynamic }
source/Main.hx:3: characters 7-26 : For function argument 'struct'
```

**Comment by nadako** [comment] 2019-02-19 22:33
There's a difference between read-only and final, as final is more restrictive: it guarantees that the value won't ever change, so all subsequent reads will yield the same result. So there's no reason for this to be inferred as `final`.

But at the same time, this looks like it should compile, because the following seems to compile:
```haxe
var fin:{final f:Int;} = {f: 0};
var ro:{var f(default,never):Int;} = fin;
```

**Comment by nadako** [comment] 2019-02-19 22:43
I guess `struct.foo` is inferred as `default,null`, not `default,never`, hence the failure, but I don't quite understand if there's any difference between `null` and `never` for anonymous structures. Maybe it's safe to set the write access to `never` in this case?

**Comment by Simn** [comment] 2019-02-20 09:55
I don't think we should infer `final`, but yeah the error message is stupid.

**Comment by Gama11** [comment] 2019-02-20 10:15
I thought that would make sense because of similar issues (#7391 and #7394).

**Comment by Simn** [comment] 2019-02-21 06:42
These issues are much more local because it's about an object declaration. We directly declare an object against a type there, in which case top-down inference can deal with final.

The case here is different because the type is inferred across the entire function and would be influenced by all usages of `struct`. I find this a bit too "tricky", and I also find it fair to type-hint your arguments if you want proper type-safety.

**Comment by back2dos** [comment] 2019-02-21 08:12
Here's the thing though:

```haxe
class Main {
  static function main() {
    var aFinal:{ final foo:Int; } = { foo: 42 };// works, because of top down inference
    var aNever:{ var foo(default, never):Int; } = aFinal;// no problem
    var aNull:{ var foo(default, null):Int; } = aNever;// still no problem
    
    aNull = aFinal;// Cannot unify final and non-final fields ... what?

    foo2(aNull);// does not work, because `foo2` has its argument inferred to have `default` write
    foo(aNull);// works, because `foo` has its argument inferred to have `default` write
    foo(aNever);// works too, because `aNever = aFinal` works
    foo(aNever);// works too, because `aNever = aFinal` works
  }

  static function foo(struct) 
    trace(struct.foo);
  
  static function foo2(struct) 
    struct.foo = struct.foo;

}
```

So as we see, the compiler has no problem inferring a field to be readonly, in which case it uses `(default, null)`. Any reason not infer `(default, never)` instead?

**Comment by Simn** [comment] 2019-02-21 08:15
We just discussed this and I wasn't really aware that the compiler already goes for `(default, null)` inference. In that case I agree that we can infer `(default, never)` instead.

What bothers me is that the inference entirely depends on the first field access. But that's a different problem I suppose.

**Comment by Simn** [comment] 2019-03-18 11:40
Closing this in favor of #7838.

**Closed as completed by Simn** 2019-03-18 11:40 UTC
Labels: enhancement, error-reporting

**Comment by Gama11** [comment] 2019-03-18 18:19
There were technically two issues here, one about the shitty error reporting:

```
source/Main.hx:3: characters 7-26 :  have: { foo: Dynamic }
source/Main.hx:3: characters 7-26 :  want: { foo: Dynamic }
```

Could this still occur?

**Comment by Simn** [comment] 2019-03-18 18:19
Wasn't there a separate issue for that?

**Comment by Gama11** [comment] 2019-03-18 18:21
There's one that's similar, not sure if it's the same: https://github.com/HaxeFoundation/haxe/issues/7780 - there `?` is missing, here the `final` was.

**Comment by Simn** [comment] 2019-03-18 18:22
Well it's about the error message, so the exact source probably doesn't matter. Especially if you cannot reproduce it here.
