### ISSUE TITLE
[php] Extern class gets prefixed in static calls

### ISSUE THREAD

**Issue by benmerckx** [HaxeFoundation/haxe#5512] opened 2016-08-09 14:26 UTC
Following code:

``` haxe
@:native('Test')
extern class Test {
    public static function call(): Void;
}

class Main {
    public static function main()
        Test.call();
}
```

Compiled with:

```
-main Main
--php-prefix prefix_
-php bin/
```

Results in:

``` php
<?php

class prefix_Main {
    public function __construct(){}
    static function main() {
        prefix_Test::call();
    }
    function __toString() { return 'Main'; }
}
```

Where `prefix_Test::call();` should be `Test::call();`. This only happens for static calls.

**Comment by mockey** [comment] 2016-08-10 23:57
Why are you using `--php-prefix` at all?

**Comment by benmerckx** [comment] 2016-08-11 09:05
We're developing software with an sdk, used by third parties in plain php. Since haxe does not generate namespaced php, you can see where this can potentially clash. Any std class in the root (eg Date) gets compiled without any prefix. Some are using this with legacy code which isn't namespaced either resulting in classes being defined twice. Using `--php-prefix` we can at least get around those problems.

In case anyone else runs into this problem (which I highly doubt), here's a quick fix:
```haxe
@:native('Test')
extern class Test {
	public static function __init__(): Void
		untyped __call__('class_alias', 'Test', 'prefix_Test');
}
```

**Comment by mockey** [comment] 2016-08-11 10:06
> Some are using this with legacy code which isn't namespaced either resulting in classes being defined twice. Using --php-prefix we can at least get around those problems.

I see. `-php-prefix` is a rather odd option I never used. I just recently discovered it in genphp code. So the problem is, that extern classes with `@:native` are getting prefixed as well but shouldn't be prefixed? Besides this it works?

Maybe it would be a good idea to put all haxe-generated code in its own (configurable) namespace?

**Comment by benmerckx** [comment] 2016-08-11 10:31
> So the problem is, that extern classes with @:native are getting prefixed as well but shouldn't be prefixed? Besides this it works?

I did not encounter any other problems with `--php-prefix`. The prefix also only happens in a static call (`Test.call`), in regular usage (`new Test`) it resolves fine.
I wonder if it's possible that `is_extern` is false [here](https://github.com/HaxeFoundation/haxe/blob/development/src/generators/genphp.ml#L255) for a static call.


> Maybe it would be a good idea to put all haxe-generated code in its own (configurable) namespace?

That would be great. On the other hand it might take about the same amount of effort to namespace everything correctly (reflecting the haxe package structure), which would be even more awesome. In any case some form of namespacing would obsolete php-prefix completely.

**Comment by mockey** [comment] 2016-08-11 11:25
>  The prefix also only happens in a static call (Test.call), in regular usage (new Test) it resolves fine.
I wonder if it's possible that is_extern is false here for a static call.

I see. I'll have a look next time I poke around in genphp (maybe next week).

>  On the other hand it might take about the same amount of effort to namespace everything correctly (reflecting the haxe package structure)

I'm not so sure about this. I played around with namespacing once and encountered some problems that we don't have with current class naming. But I don't remember exactly. I think quite a lot of names are not allowed as namespace or class name or something.
And reflecting the current haxe package structure would still mean a Date class in root, no?
As a quick hack it might be easier to just put a namespace before everything (which woud be not much different from --php-prefix actually).

Anyway, any change to current genphp is just a hack. A complete rewrite of the php target would be much better. Are you planning some bigger projects with haxe-php?

**Comment by nadako** [comment] 2016-08-11 13:02
> next time I poke around in genphp

you may want to cooperate with @RealyUniqueName, since he's currently working on php target as well

**Comment by RealyUniqueName** [comment] 2016-08-11 13:19
Actually I'm building it from scratch, and it already supports namespaces. 
But `--php-prefix` is not implemented yet. I'm going to use it as root namespace for all generated code.
E.g. with `--php-prefix mylib` top-level `Date` class will be generated as `\mylib\Date`

**Comment by benmerckx** [comment] 2016-08-11 13:29
> Actually I'm building it from scratch, and it already supports namespaces.

Wow, that's great news! Any way to track progress?

**Comment by mockey** [comment] 2016-08-11 13:29
> Actually I'm building it from scratch, and it already supports namespaces.

Interesting. Does it have a repo somewhere? Are you interested in cooperation?

**Comment by RealyUniqueName** [comment] 2016-08-11 13:34
My repo is private as of now, but i think i can go public later this week.

**Comment by RealyUniqueName** [comment] 2016-08-13 14:31
@benmerckx @mockey Here is my progress at this moment: https://groups.google.com/forum/#!forum/haxelang

**Comment by RealyUniqueName** [comment] 2017-10-19 14:12
I'm closing this, because old php generator was removed.

**Closed by RealyUniqueName** 2017-10-19 14:12 UTC
Labels: platform-php
