### ISSUE TITLE
hard 'cast' crash on c++ easy/simple to reproduce.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#9626] opened 2020-06-20 02:58 UTC
@hughsando, think I found out why I was failing so badly at GL :)

Works fine on JS, hard crash on ( mac 10.14.6 also on Linux I think ).

```haxe
@:structInit
class Foo {
    public var x = 0.; 
    function new( x: Float ){
        this.x = x; 
    }
}
class Test {
    static function main() {
        var v: Foo = cast { x: 0 }; // <- cast not needed, if removed problem disappears.
        trace( v.x ); // <- hard crashes c++ at runtime when you try to access x.
    }
}
```
```hxml
-main Test
-dce full
-cpp bin
-cmd cd bin
-cmd ./Test
```
this issue or related may effect Neko/HL especially with inline turned off.

My actual code might need 'cast' - with AbstractFoo or where v is TypeDefFoo.

Haxe Compiler 4.2.0-rc.1+308ed91e0 - (C)2005-2020 Haxe Foundation
hxcpp - 4.1.1 or 4.1.11

**Comment by Gama11** [comment] 2020-06-20 08:06
Probably the expected behavior? `@:structInit` relies on the literal being rewritten to a constructor call at compile time, but the `cast` basically disables typing.

**Comment by nanjizal** [comment] 2020-06-20 10:02
It's was certainly not expected, most of the code base is generic it all works in Javascript.
The code with inline disabled mostly works in Neko.
I have run all the concerned libraries through dox on cpp target. no issue were highlighted.

I have just check through large portion of my code:
63 casts in 275 files.

![projectCasts0](https://user-images.githubusercontent.com/20134338/85198530-3e402b80-b2e1-11ea-9a69-f3d6e0b1b920.png)
![projectCast1](https://user-images.githubusercontent.com/20134338/85198539-4b5d1a80-b2e1-11ea-9b56-7a5ce9659249.png)
![projectCast2](https://user-images.githubusercontent.com/20134338/85198552-5ca62700-b2e1-11ea-9e83-99ee62154a06.png)
![projectCast3](https://user-images.githubusercontent.com/20134338/85198558-662f8f00-b2e1-11ea-8af3-d85e095da61d.png)

MatrixDozen and Vertex have been setup so that I can switch the implementation between a bare bones matrix maths approach in trilateral3 and more extensive matrix solutions such as geom for approaches like using DualQuatarnion in 3D.

In future I had intended to support hxMath ( I have been doing some work on adding DualQuaternion to hxMath with it's author ).

https://github.com/nanjizal/trilateral3/blob/master/src/trilateral3/matrix/MatrixDozen.hx

The concept being not to require full maths library for basic use of trilateral3 but allowing more advanced use such as the demos you may have seen posted:

![diceTrilateral](https://user-images.githubusercontent.com/20134338/85198715-d12d9580-b2e2-11ea-9bac-23a279687f95.png)

I have sent well over a week trying to work out why all my code renders on Lime, Heaps JS but seemed to fail with Gluon, Lime, Heaps, NME - I was under the impression it was bugs with my setting up of GL but I now find that likely that was not the main issue.  

ShaunHolt looked at my libraries over a few days and also struggled to understand why the GL code was failing, so more than one person found hard crashes not ideal. 

To have generic code pass all compiler checks, generate dox files, and then hard crash in C++ at runtime makes it very hard to debug, I am more than a little disappointed with the response. :(

It feel the code should work, especially since hard fails are very hard to debug, I don't use dynamic in my code but often find it tricky to avoid casts when your trying to type between abstracts and the class they abstract, or between a typedef and a class implementation.

**Comment by nanjizal** [comment] 2020-06-20 10:31
Very greatful for the two recent bugs that have been fixed, was impressed with how quickly Simn fixed the heaps related one the other day I am hoping him or Dan have really good idea for this one, I suspect it will effect other users in future. Many thanks. (Removed the long post.)

**Comment by nadako** [comment] 2020-06-20 10:50
I have no idea about everything else you're writing about, but the OP example illustrates completely unspecified behaviour. On left side you have a class type, on the right side you have an anonymous object, which, depending on a platform can have completely different in-memory structure at run-time, and then you subvert the type check by using an **unsafe** cast to bring the error to run-time, so stuff like this is expeted.

**Comment by nanjizal** [comment] 2020-06-20 10:55
var fred: Fred = cast new Fred();
I should be able to call methods on fred that exist on Fred, otherwise cast seems a bit pointless if it's only has javascript support?

**Comment by nadako** [comment] 2020-06-20 10:57
That is a completely unrelated example.

**Comment by nanjizal** [comment] 2020-06-20 11:04
This does not fail on c++;
```haxe
@:structInit
class Foo {
    public var x = 0.; 
    function new( x: Float ){
        this.x = x; 
    }
}
class Test {
    static function main() {
        var f: Foo = { x: 0 };
        var v: Foo = cast f;
        trace( v.x );
    }
}
```
this does fail on c++
```haxe
@:structInit
class Foo {
    public var x = 0.; 
    function new( x: Float ){
        this.x = x; 
    }
}
class Test {
    static function main() {
        var v: Foo = cast { x: 0 };
        trace( v.x );
    }
}
```
If the property exists why can't it be accessed, that seems the point of a cast?

**Comment by nanjizal** [comment] 2020-06-20 11:17
I understand now why it fails but seems a mismatch between a language that is typed and one that crashes at runtime. 

Some way to duck type in certain instance seems to be vital, all my structures are typed so it's not like I am using dynamic.

**Comment by RealyUniqueName** [comment] 2020-06-20 11:26
Closing as there's no issue here.
And duck typing is not possible in that example. 
Anonymous structure says "it should be an object with this list of fields", while class says "it should be an instance of this exact class".
That's why you can assign a class instance where an anon structure is expected, but cannot assign an anon structure where a class instance is expected. 
However, dynamic targets (unlike static targets) may allow you to do that  and don't crash on some operations (like field access) by a fortunate coincidence.

**Comment by hughsando** [comment] 2020-06-20 11:26
Quite simply `{x:0}` is not a Foo and "cast" says "assume that this is a Foo, and carry on".  It just happens to work in Js because it finds the member by name.
But check:
```haxe
class Foo {

    public var x = 0.; 
    function new( x: Float ){
        this.x = x; 
    }
    public function printX() trace(x);
}
class Test {
    static function main() {
        var v: Foo = cast { x: 0 };
        trace( v.x );
        v.printX();
    }
}
```
It has an x, but printX is nowhere to be found.

If you want structInit to be called, simply drop the cast so it assigns a struct and knows it needs to call "new". `var v: Foo = { x: 0 };`

**Closed as completed by RealyUniqueName** 2020-06-20 11:26 UTC

**Comment by nanjizal** [comment] 2020-06-20 11:52
I think my real example was perhaps more complex.
```haxe
inline
function transformVertex( v: Vertex, t: MatrixDozen ): Vertex {
    var v2: Vertex = {  x: t.a * v.x + t.b * v.y + t.c * v.z + t.d
            , y: t.e * v.x + t.f * v.y + t.g * v.z + t.h
            , z: t.i * v.x + t.j * v.y + t.k * v.z + t.l  
            , w: 1. };
    return v2;
}
```
called by
```haxe
abstract FlatColorTriangles( dsHelper.flatInterleave.FloatColorTriangles ){
    public inline function new( len: Int ){
        this = new FloatColorTriangles( len );
    }
    public
    function transform( m: MatrixDozen ){
        var pa: Vertex = { x: this.ax, y: this.ay, z: this.az, w: 1. };
        var pb: Vertex = { x: this.bx, y: this.by, z: this.bz, w: 1. };
        var pc: Vertex = { x: this.cx, y: this.cy, z: this.cz, w: 1. };
        pa = transformVertex( pa, m );
        pb = transformVertex( pb, m );
        pc = transformVertex( pc, m );
        this.ax = pa.x;
        this.ay = pa.y;
        this.az = pa.z;
        this.bx = pb.x;
        this.by = pb.y;
        this.bz = pb.z;
        this.cx = pc.x;
        this.cy = pc.y;
        this.cz = pc.z; 
    }
```
called by
```haxe
    inline public
    function addTriangle( ax: Float32, ay: Float32, az: Float32
                        , bx: Float32, by: Float32, bz: Float32
                        , cx: Float32, cy: Float32, cz: Float32 ){
        drawType.triangle( ax, ay, az, bx, by, bz, cx, cy, cz );
        drawType.transform( Trilateral.transformMatrix );
        drawType.next();
    }
```
where 
```haxe
            var transform1000: MatrixDozen = { a : 0.001, b : 0, c : 0, d : -1
                                             , e : 0,  f : -0.001, g : 0, h : 1
                                             , i : 0, j : 0,k : 0.001, l : 0 };
            Trilateral.transformMatrix = transform1000;
```
I probably need to look more deeply to check if there is not something else going on as I am not quite sure if my cut down properly represented the actual crash, but certainly I need to be more cautious on casting strutInit before using them in a cast.

**Comment by nanjizal** [comment] 2020-06-20 11:54
Specifically it was this line.
https://github.com/nanjizal/trilateral3/blob/master/src/trilateral3/drawing/Pen.hx#L108

**Comment by nanjizal** [comment] 2020-06-20 12:00
sorry can't find the cast right now it's probably in the mix somewhere.

**Comment by hughsando** [comment] 2020-06-20 12:23
Code without "cast" is better in general because it means it is well typed.  And it looks like the code will compile without it, so removing the casts is good all around.

**Comment by nadako** [comment] 2020-06-20 15:46
> Some way to duck type in certain instance seems to be vital, all my structures are typed so it's not like I am using dynamic.

Well if you want duck typing you should use structural types (anon structures), not nominal (classes), and you don't need unsafe casts for that, e.g. this is perfectly type-safe:

```haxe
typedef Foo = {x:Float};
class FooClass {
  public var x:Float;
  public function new() {}
}
var fooStruct:Foo = {x: 1.5};
var fooClass:Foo = new FooClass();
```
