### ISSUE TITLE
import and build macro

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#11120] opened 2023-04-11 09:56 UTC
Hej,
I came into a weird issue, it was a pain to make a minimal sample... But I'm sorry if I do something wrong, feel free to shout me :rofl: 
I get `import.hx:1: characters 1-23 : Class<A> has no field foo` when doing exactly that : 
**build.hxml :**
```haxe
--macro B.init()
--main Main
```
**import.hx :**
```haxe
import A.foo;
```
**Main.hx :**
```haxe
class Main {
	static function main() {
		foo();
	}
}
```
**A.hx :**
```haxe
class A  {
	public static function foo(){
		return "foo";
	}
}
```
**B.hx:**
```haxe
class B{
	public static function init(){
		haxe.macro.Compiler.addGlobalMetadata( "", '@:build( B.build() )' );
	}
	public static function build(){
		return null;
	}
}
```
If `haxe.macro.Compiler.addGlobalMetadata( "", '@:build( B.build() )' );` in B is comented, all works fine so maybe something linked with `haxe.macro.Compiler.addGlobalMetadata` idk...

_BTW in `build.xml` there is no output target and it doesn't complain, is it normal ? (But the error occurs also with a target set...)_

Thx for reading me,
Regards

**Comment by Simn** [comment] 2023-04-11 10:25
I always wonder how you end up in these situations... There might be a legit issue here, but you mention import.hx, init macros and addGlobalMetadata, which lead me to believe it has to do with neither of those:

Main.hx:

```haxe
import Main.foo;

@:build(B.build())
class Main {
	static function main() {}

	public static function foo() {
		return "foo";
	}
}
```

B.hx:

```haxe
class B {
	public static function build() {
		return null;
	}
}
```

**Comment by filt3rek** [comment] 2023-04-11 10:32
@Simn : It's like that from when I was born : all problems are for me :rofl: (I'm not against a special mention "Haxe breaker" or "pain in the neck" ? if you want :rofl: )
I'm sorry I thought I have done a minimal sample, I thought I've done a test like you did here but must be not.

**Comment by Simn** [comment] 2023-04-11 12:53
I have looked at this and fixed it on https://github.com/HaxeFoundation/haxe/tree/less_context_init, but in doing so come to the conclusion that this shouldn't work. The problem is that you're accessing the structure of the type you're currently building via the `Main.foo` import. While the argument could be made the the compiler doesn't need to eagerly check this, there are definitely cases where it's required:

Main.hx:

```haxe
import String.fromCharCode;

@:build(B.build())
class Main {
	static function main() {}
}
```

B.hx:

```haxe
import haxe.macro.Context;

class B {
	public static function build() {
		trace(Context.getLocalImports());
		trace(Context.typeExpr(macro fromCharCode));
		return null;
	}
}
```

This works on development but is broken on my branch, because the imports of the module are no longer eagerly initialized. This _could_ be fixed by making sure the context initialization runs upon calling `typeExpr`, but it's unclear in which cases this is necessary. On balance, I prefer to not attempt a fix here.

However, I'll add this as a test because our current tests miss this case.

**Closed as completed** 2023-04-11 12:55 UTC

**Comment by filt3rek** [comment] 2023-04-11 13:01
> The problem is that you're accessing the structure of the type you're currently building via the Main.foo import.

@Simn In your minimal sample it's the case, but in my samples all is well separated so it shouldn't error, should it ?

**Comment by Simn** [comment] 2023-04-11 13:02
It is because you add `import A.foo;` to everything, including A itself, via your import.hx.

**Comment by filt3rek** [comment] 2023-04-11 13:05
So maybe a fix would be to not import the import statement in the type of the import ?
I mean, when propagating imports form `import.hx`, don't `import A.foo` into `A` ? 
@Simn Is there any other workaround so ?

**Comment by filt3rek** [comment] 2023-04-11 13:24
I suppose workaround is **not to use** `import.hx` **with** `haxe.macro.Compiler.addGlobalMetadata( ""` (which is at the end not so amazing IMHO)
...or "stop using Haxe, Michal" :smiling_face_with_tear:
