### ISSUE TITLE
hexmachina tests compilation crash with Haxe 4

### ISSUE THREAD

**Issue by aliokan** [HaxeFoundation/haxe#6583] opened 2017-09-16 13:13 UTC
@Simn - As discuss yesterday, find bellow informations about hexMachina compilation crash with Haxe 4.  

You can find result compilation with nightlybuild on Travis : https://travis-ci.org/DoclerLabs/hexMachina/jobs/274526385

To compile tests locally, you have to install git version of hexmachina : 
```bash
git clone -b master --single-branch  https://github.com/DoclerLabs/hexMachina.git
haxelib newrepo
haxelib install haxelib.json
```
fixe path in `build-each.hxml`
```haxe
#all test sources to run the whole test suite
-cp test
-cp .haxelib/hexunit/git/test
-cp .haxelib/hexlog/git/test
-cp .haxelib/hexcore/git/test
-cp .haxelib/hexreflection/git/test
-cp .haxelib/hexannotation/git/test
-cp .haxelib/hexinject/git/test
-cp .haxelib/hexdsl/git/test
-cp .haxelib/hexservice/git/test
-cp .haxelib/hexmvc/git/test
-cp .haxelib/hexstate/git/test
-cp .haxelib/hexioc/git/test
```

And compile with neko for example `haxe build-neko.hxml`.

**Comment by Simn** [comment] 2017-09-18 07:03
Interestingly, I am getting different error messages than what we had at the summit. Here's one:

```
.haxelib/hexioc/git/test/hex/compiler/parser/flow/FlowCompilerTest.hx:1012: characters 32-92 : Uncaught exception Unexpected value VInstance({{withName: temperature,fromType: hex.event.ITrig
ger<Int->Void>}, {withName: weather,fromType: hex.event.ITrigger<String->Void>}}), expected array
```

This comes from a call that has a shady `cast`:

```haxe
!hex.di.mapping.MappingChecker.matchForClassName( constructorVO.className, cast mappings )
```

The type of `mappings` is `List<{ }>`, but `MappingChecker.matchForClassName` expects an `Array<MappingDefinition>`. I have no idea how that worked in the old interpreter because List and Array are two completely different things. This is definitely something you guys should fix in your codebase first.

I still wonder why I'm not seeing the `null` related errors that we had. Will investigate a bit more.

**Comment by aliokan** [comment] 2017-09-18 13:36
That fixe a bush of errors.  
Could you try again with at least hexdsl and hexioc dependencies in `-branch develop` ? 

I have this bash script to switch all hexmachina in develop (should be runned in hexmachina repo) : 
```bash
#!/bin/bash

for REPO in `ls -d -1 $PWD/.haxelib/hex*`; do (cd "$REPO/git"; pwd; git checkout develop;  git pull origin); done;
```

**Comment by Simn** [comment] 2017-09-19 07:02
I'm now getting this error:

```
c:\github\hexmachina\.haxelib\hexioc/git/src/hex/compiler/parser/flow/StaticFlowCompiler.hx:166: lines 166-176 : hex.util.Transformation<haxe.macro.Expr, { pos : haxe.macro.Position, id : Strin
g, fileName : String, arg : Null<hex.vo.ConstructorVO> }> should be hex.util.Transformation<haxe.macro.Expr, hex.compiletime.flow.parser.ContextImport>
c:\github\hexmachina\.haxelib\hexioc/git/src/hex/compiler/parser/flow/StaticFlowCompiler.hx:166: lines 166-176 : Type parameters are invariant
c:\github\hexmachina\.haxelib\hexioc/git/src/hex/compiler/parser/flow/StaticFlowCompiler.hx:166: lines 166-176 : { pos : haxe.macro.Position, id : String, fileName : String, arg : Null<hex.vo.C
onstructorVO> } should be hex.compiletime.flow.parser.ContextImport
c:\github\hexmachina\.haxelib\hexioc/git/src/hex/compiler/parser/flow/StaticFlowCompiler.hx:166: lines 166-176 : { pos : haxe.macro.Position, id : String, fileName : String, arg : Null<hex.vo.C
onstructorVO> } should be { pos : haxe.macro.Position, id : String, fileName : String, arg : String }
c:\github\hexmachina\.haxelib\hexioc/git/src/hex/compiler/parser/flow/StaticFlowCompiler.hx:166: lines 166-176 : Invalid type for field arg :
c:\github\hexmachina\.haxelib\hexioc/git/src/hex/compiler/parser/flow/StaticFlowCompiler.hx:166: lines 166-176 : hex.vo.ConstructorVO should be String
```

That seems to be a normal typing error. Here's ContextImport:

```haxe
typedef ContextImport =
{
	id 			: String,
	fileName 	: String,
	arg			: String,
	pos 		: haxe.macro.Expr.Position
}
```

This is the code that assigns to `arg`:

```haxe
arg: params.length>1 ? this._parser.parseArgument( this._parser, ident, params[ 1 ] ) : null,
```

And `parseArgument` is typed like so:

```haxe
typedef ArgumentParser 		= ExpressionParser->ID->Expr->ConstructorVO;
```

**Comment by Simn** [comment] 2017-09-19 07:03
Ah, just noticed that the ConstructorVO class has a `toString`, so I guess that's the issue.

**Comment by aliokan** [comment] 2017-09-19 08:53
Should we force casting or call toString manually?

**Comment by Simn** [comment] 2017-09-19 09:21
Are you sure calling toString there is even the right thing to do?

I'm quite confused because I don't understand how this worked before Haxe 4.

**Comment by aliokan** [comment] 2017-09-19 09:37
@FrancisBourre ? :)

**Comment by FrancisBourre** [comment] 2017-09-22 06:01
Oh, my bad. ContextImport.arg should be typed ConstructorVO.
Some parallel refactorings introduced this error, and the compiler was silent with haxe 3.
Thanks for catching it.

**Comment by Simn** [comment] 2017-09-22 07:50
I am now getting errors like this:

```
.haxelib/hexioc/git/test/hex/compiler/parser/flow/StaticFlowCompilerTest.hx:72: characters 18-27 : hex.context.IStaticFlowCompiler_testBuildingString_0 has no field s
```

This occurs at the `locator.s` here:

```
		var code = StaticFlowCompiler.compile( this._myApplicationAssembler, "context/flow/primitives/string.flow", "StaticFlowCompiler_testBuildingString" );
		
		var locator = code.locator;
		Assert.isNull( locator.s );
```

The class definition looks fine:

```
package hex.context;
class StaticFlowCompiler_testBuildingString_0 {
	public function new(assembler) {
		this.locator = hex.compiletime.CodeLocator.get("StaticFlowCompiler_testBuildingString", assembler);
		this.applicationAssembler = assembler;
		this.applicationContext = this.locator.StaticFlowCompiler_testBuildingString;
	}
	public var locator : hex.context.IStaticFlowCompiler_testBuildingString_0;
	public var applicationAssembler : hex.core.IApplicationAssembler;
	public var applicationContext : hex.ioc.assembler.ApplicationContext;
	public function execute():Void hex.compiletime.CodeLocator.get("StaticFlowCompiler_testBuildingString", applicationAssembler).m_a299f8c7aed96aa8a3a6ff10c31b35ca();
	public function clone(assembler:hex.core.IApplicationAssembler):hex.context.StaticFlowCompiler_testBuildingString_0 @:mergeBlock {
		return new hex.context.StaticFlowCompiler_testBuildingString_0(assembler);
	};
}
```

But the interface definition does indeed not have any `s` field:

```haxe
package hex.context;
interface IStaticFlowCompiler_testBuildingString_0 {
	public var StaticFlowCompiler_testBuildingString : hex.ioc.assembler.ApplicationContext;
	@:noCompletion
	public function m_a299f8c7aed96aa8a3a6ff10c31b35ca():Void;
}
```

Any pointers where that `s` field is supposed to come from?

**Comment by FrancisBourre** [comment] 2017-09-22 11:10
I checked it and fixed it. But the compiler's behavior is really weird.
I removed the assignment [here](https://github.com/DoclerLabs/hexIoC/blob/a372bd539247d19769f6d35d311d8f2a16afcca3/src/hex/compiler/core/CompileTimeContextFactory.hx#L197) and move it to the property declaration.
It seems when this assignment is done the reference of this inside an object map is changed to another one... And by cascading it's triggering many errors.

**Comment by Simn** [comment] 2017-09-22 11:11
Yes I know there's a bug in ObjectMap, I've just not gotten to the point where I can reproduce it yet. Will try again with your fixes.

**Comment by Simn** [comment] 2017-09-22 11:20
Hmm, now I'm getting this:

```
c:\GitHub\hexMachina\.haxelib\hexioc/git/src/hex/compiler/parser/flow/StaticFlowCompiler.hx:166: lines 166-176 : hex.util.Transformation<haxe.macro.Expr, { pos : haxe.macro.Position, id : Strin
g, fileName : String, arg : Null<String> }> should be hex.util.Transformation<haxe.macro.Expr, hex.compiletime.flow.parser.ContextImport>
c:\GitHub\hexMachina\.haxelib\hexioc/git/src/hex/compiler/parser/flow/StaticFlowCompiler.hx:166: lines 166-176 : Type parameters are invariant
c:\GitHub\hexMachina\.haxelib\hexioc/git/src/hex/compiler/parser/flow/StaticFlowCompiler.hx:166: lines 166-176 : { pos : haxe.macro.Position, id : String, fileName : String, arg : Null<String>
} should be hex.compiletime.flow.parser.ContextImport
c:\GitHub\hexMachina\.haxelib\hexioc/git/src/hex/compiler/parser/flow/StaticFlowCompiler.hx:166: lines 166-176 : { pos : haxe.macro.Position, id : String, fileName : String, arg : Null<String>
} should be { pos : haxe.macro.Position, id : String, fileName : String, arg : hex.vo.ConstructorVO }
c:\GitHub\hexMachina\.haxelib\hexioc/git/src/hex/compiler/parser/flow/StaticFlowCompiler.hx:166: lines 166-176 : Invalid type for field arg :
c:\GitHub\hexMachina\.haxelib\hexioc/git/src/hex/compiler/parser/flow/StaticFlowCompiler.hx:166: lines 166-176 : String should be hex.vo.ConstructorVO
```

That seems to be the exact opposite of what happened before (`hex.vo.ConstructorVO should be String`). Will double-check that I didn't mess up the setup.

**Comment by FrancisBourre** [comment] 2017-09-22 11:33
Btw, It's still there with the fix, but the serie with 'ContextBuilder not found for this owner.' is gone.
Will check the other ones.
Btw, would it be long to fix the ObjectMap at macro time for you, because I'm pretty sure with have many related to this one ? We use ObjectMap intensively from the core: https://github.com/DoclerLabs/hexCore/blob/master/src/hex/core/HashCodeFactory.hx

**Comment by Simn** [comment] 2017-09-22 11:36
Getting ObjectMap right is a bit tricky. I might be able to commit a hack that makes it somewhat slow but at least working correctly. Would still prefer to have a reproducible example so I can confirm the hack even works.

**Comment by FrancisBourre** [comment] 2017-09-25 07:45
So I put another [fix/hack](https://github.com/DoclerLabs/hexDSL/commit/d484def559552b705343a0cd6e597a8ccd48fca9) for hexDSL, it was related again to Map class that loses references when it's updated.
Tests are passing on my computer, but travis is failing with this week-end latest updates, because of `@:final ` and tink_macro errors as well.

**Comment by Simn** [comment] 2017-09-25 07:48
The Map problem should have been "fixed" by https://github.com/HaxeFoundation/haxe/commit/2bc2f8639f59b82aa2b7d2933abfa390fef6479c.

**Comment by FrancisBourre** [comment] 2017-09-25 07:50
Ok, good to kow, thank you.

**Comment by FrancisBourre** [comment] 2017-09-25 11:40
I found a really odd one.
I can't isolate it for now.
You remember about the interface that doesn't contain the right fields? I found where it comes from. When I run test class using `CompiletimeContextFactory`, it prevents the call of overridden method `StaticCompileTimeContextFactory._buildVO`. Instead, it calls the super method `CompiletimeContextFactory._buildVO`.
I put a trace inside the super method to be sure: `trace('_buildVO', id, this );` and the output is: `hexdsl/src/hex/compiletime/basic/CompileTimeContextFactory.hx:286: _buildVO,s,hex.compiletime.basic.StaticCompileTimeContextFactory`
If you have any clue of what's going on.

**Comment by Simn** [comment] 2017-09-25 11:55
Hmm, the only thing I can think of is that my `is_overridden` check could go wrong here. But I can't think of a reason why that would happen... I'll comment out this optimization and we can check if it helps.

**Comment by Simn** [comment] 2017-09-25 12:17
Never mind, that doesn't quite work yet...

**Comment by FrancisBourre** [comment] 2017-09-26 05:46
I can confirm the checking is broken. I removed inheritance, and its working.

**Comment by Simn** [comment] 2017-09-26 06:42
Could you point me to where that call is made so I can try reducing the issue?

I have to admit that we don't have many inheritance-heavy macro codebases around, so there's a chance that this is some silly oversight which is not covered by our unit tests.

**Comment by FrancisBourre** [comment] 2017-09-27 07:17
I fixed the issue, I meant [I removed inheritance for now](https://github.com/DoclerLabs/hexDSL/commit/f079124a10ea3c881643c2e315ddcce1838c3576), but you can maybe checkout the previous revision if you cant to play with it.
To partially isolate the problem,  you have to run these 2 tests together:  [BasicXmlCompilerTest.testBuildingString](https://github.com/DoclerLabs/hexDSL/blob/develop/test/hex/compiletime/xml/BasicXmlCompilerTest.hx#L105) and [BasicStaticXmlCompilerTest.testBuildingString](https://github.com/DoclerLabs/hexDSL/blob/develop/test/hex/compiletime/xml/BasicStaticXmlCompilerTest.hx#L54). Tell me if I can help you in a better way to isolate the issue.

**Comment by Simn** [comment] 2017-09-29 15:38
I have managed to isolate and understand the issue. I'm gonna document it here because it worries me a bit.

```haxe
// Main.hx
class Main {
    static function main() {
        Macro1.macro1();
        Macro2.macro2();
    }
}
```

```haxe
// Macro1.hx
class BaseClass {
	public function new() { }
	public function f() {
		trace("BaseClass.f");
	}
}

class Macro1 {
	static public macro function macro1() {
		return macro null;
	}

	static public function call(ref:BaseClass) {
		ref.f();
	}
}
```

```haxe
// Macro2.hx
class ChildClass extends Macro1.BaseClass {
	override public function f() {
		trace("ChildClass.f");
	}
}

class Macro2 {
	static public macro function macro2() {
		Macro1.call(new ChildClass());
		return macro null;
	}
}
```

Here's what happens:

1. The compiler sees the `Macro1.macro1()` call and starts typing `Macro1` in macro context.
2. Create `BaseClass` prototype.
3. JIT `Macro1.call`. At this time, the `is_overridden` check returns `false` because there is no override of `BaseClass.f` known.
4. The compiler sees the `Macro2.macro2()` call and starts typing `Macro2` in macro context.
5. Create `ChildClass` prototype. *Now* `BaseClass.f` is considered overridden, but `Macro1.call` has already been jitted incorrectly.

What we have to do is invalidate base classes as soon as a new child class is added or changed.

**Comment by Simn** [comment] 2017-09-29 15:43
Actually it's worse: We would have to invalidate all *users* of the base class...

**Comment by Simn** [comment] 2017-09-29 16:35
I have disabled the call optimizations for now, which should avoid the override problem. I have also added a test for this so I don't randomly break it again in the future.

Please check and see if that helped and let me know if there are still other issues!

**Comment by aliokan** [comment] 2017-09-30 06:44
I have restart Travis, and It compiles! \(^.^)/
Except some tests broken in PHP, all tests are passing on neko, is and Flash. 
https://travis-ci.org/DoclerLabs/hexIoC/jobs/280835970

**Comment by Simn** [comment] 2017-09-30 06:59
That's great news, thanks!

The PHP failures look strange: `'<function>' but was '<function>'`. Some XML equality check going wrong?

**Comment by Simn** [comment] 2017-10-01 10:06
Most of the related tests seem to be about method equality checks failing. It's hard for me to tell if that's within the specified behavior.

I noticed that your Assert.equals has a special case for neko here: https://github.com/DoclerLabs/hexUnit/blob/master/src/hex/unittest/assertion/Assert.hx#L156

My guess is that adding php there would address this issue. The question is if this is a regression in the php7 target, or simply unspecified behavior. For that we would need to look at what is actually being compared.

cc @RealyUniqueName

**Comment by back2dos** [comment] 2017-10-01 10:51
Didn't we introduce method binding caches across the board though, to make sure that `==` holds for all bound methods?

That said, `Reflect.compareMethods` should work across all platforms, so entering that branch on all platforms shouldn't hurt.

**Comment by RealyUniqueName** [comment] 2017-10-01 21:11
Targeting php you have to use `Reflect.compareMethods()`. Otherwise `this.someMethod == this.someMethod` will evaluate to `false`.

**Comment by FrancisBourre** [comment] 2017-10-02 06:29
Thanks, we already use it with neko target on many places but I didn't know we would need it with php as well. Is it the case till php7, or did I miss something?
The funny thing is that it doesn't fail every time on php target, maybe that's because under the hood you made the job for us. A good example is Array,indexOf that works with php but not neko.

**Comment by RealyUniqueName** [comment] 2017-10-02 07:20
That depends on situation. In general case comparing methods of class instance will be evaluated to `false` when targeting php.
Maybe i should change that by following behavior of JS generator, which caches bound methods.

**Comment by Simn** [comment] 2017-10-02 07:21
@ncannasse: Didn't we decide (and even add tests?) that `some.method == some.method` should always hold?

**Comment by RealyUniqueName** [comment] 2017-10-02 07:26
I don't think such test exist. Otherwise genphp7 wouldn't pass it )

**Comment by ncannasse** [comment] 2017-10-02 09:18
@Simn no we don't guarantee that, Reflect.compareMethods does

**Comment by Simn** [comment] 2017-10-02 09:21
Shouldn't we work towards that though? It's not good for performance if every method-read allocates a new closure...

**Comment by RealyUniqueName** [comment] 2017-10-02 09:23
It also surprises people when they build against another target and find their code stopped working.

**Comment by nadako** [comment] 2017-10-02 09:27
> It's not good for performance if every method-read allocates a new closure...

Hmm, maybe I should look into caching method closures in c#/java too...

**Comment by ncannasse** [comment] 2017-10-02 09:28
I wouldn't make it a default for Haxe language, that puts too much
constraint on the underlying platform implementation which we don't always
control.
Also, we might have different strategy depending on the kind of object
you're manipulating.

We could add warnings for some platforms when we detect that case, but we
that would be a bad idea to add Reflect.compareMethods automatically
because it would be surprising == works when typed but not when Dynamic.

**Comment by RealyUniqueName** [comment] 2017-10-02 09:29
Let's do it for all targets. From my experience method comparison is an issue for almost every Haxe newbie who tries to cover multiple platforms.

**Comment by Simn** [comment] 2017-10-02 09:31
Could someone check all targets and list where `==` works/doesn't work? That helps reasoning about it.

**Comment by RealyUniqueName** [comment] 2017-10-02 09:31
> that would be a bad idea to add Reflect.compareMethods automatically because it would be surprising == works when typed but not when Dynamic.

Caching means you get the same instance every time for `obj.someMethod`, so no workaround is required for `==`

**Comment by ncannasse** [comment] 2017-10-02 09:57
Caching is not always feasible, and what about  obj.someMethod.bind(1) ==
obj.someMethod.bind(1) ?
I think Reflect.compareMethods clearly specify about what is being compared.
A warning seems good enough.
And yes we could look at the current status of == , but we also have to
check obj1.sameMethod != obj2.sameMethod, and there was some cases in C++
where two methods had the same runtime pointer because they were the same
code unless they were declared in different files (thanks to optimizing
compiler)

**Comment by RealyUniqueName** [comment] 2017-10-02 10:03
> Caching is not always feasible
We already add some hidden fields on generated types to serve Haxe features. I don't see why we can't implement the same approach for caching methods.

> what about  obj.someMethod.bind(1) == obj.someMethod.bind(1)
That's always `false` just like `function() {} == function() {}`

Anyway i think a warning is nice solution also. 
I just prefer caching `obj.someMethod` because it also reduces incostistency across targets.

**Comment by FrancisBourre** [comment] 2017-10-09 07:02
Quick question about complex type of Map<String, String>. 
Is this breaking change expected?

Haxe 3.4
hexcore/src/hex/util/MacroUtil.hx:239: TAbstract(Map,[TInst(String,[]),TInst(String,[])])

Haxe 4
hexcore/src/hex/util/MacroUtil.hx:239: TType(Map,[TInst(String,[]),TInst(String,[])])

**Comment by Simn** [comment] 2017-10-09 07:06
That's from #6593, so the answer right now is "I don't know". We might move the Map abstract back to toplevel and find a different way to such types.

**Comment by Simn** [comment] 2018-04-18 06:13
I think the original issue has been addressed, and the method equality discussion has been moved to #6705. Closing this for now.

**Closed by Simn** 2018-04-18 06:13 UTC
