### ISSUE TITLE
Haxe 4p4 - You cannot access the js package while in a macro (for js.Map)

### ISSUE THREAD

**Issue by hoseyjoe** [HaxeFoundation/haxe#7260] opened 2018-07-09 14:38 UTC
https://github.com/andyli/jQueryExternForHaxe/issues/23
This was not an issue in 4p3
And it has the
@:noPackageRestrict
meta to no avail

**Comment by andyli** [comment] 2018-07-10 07:49
`git bisect` shows that 7515827ea1ff6569f97b6a446656d9a670bb1279 is the first bad commit. @Simn Any idea?

**Comment by kevinresol** [comment] 2018-07-11 15:31
I encountered this too. Somehow `Map` is resolved as `js.Map`. Changing occurance of `Map` to `haxe.ds.Map` "fixes" it.

**Comment by Simn** [comment] 2018-07-11 15:35
This is worrying... how do I reproduce this?

**Comment by hoseyjoe** [comment] 2018-07-11 23:45
See attached project
[Crap.zip](https://github.com/HaxeFoundation/haxe/files/2186558/Crap.zip)

**Comment by Simn** [comment] 2018-07-12 14:42
I'm starting at this wondering if it's actually unexpected behavior. Resolution order from `pack1.pack2.Module` checks `pack1.pack2.Module`, then `pack1.Module`, then `Module`. So if you're in `js.whatever.Whatever`, `Map` would always resolve to `js.Map` over toplevel `Map`.

However, I don't understand why this used to work differently and what the intended behavior is exactly.

**Comment by hoseyjoe** [comment] 2018-07-12 20:34
Is there any workaround?

**Comment by ncannasse** [comment] 2018-07-13 08:51
@hoseyjoe you can use `std.Map` or `haxe.ds.Map` 
I think this used to work differently because there was no `js.Map` before. Maybe we could rename it to `NativeMap` or something ? ping @nadako

**Comment by nadako** [comment] 2018-07-13 08:59
Not a fan of class names that are different from the native ones. How about we move the "standard library" things to `js.lib` like we do for Python?

**Comment by Simn** [comment] 2018-07-13 09:06
There used to be this code before my rewrite of `load_type_def`:

```ocaml
(match fst ctx.m.curmod.m_path with
	| [] -> raise Exit
	| x :: _ ->
		(* this can occur due to haxe remoting : a module can be
			already defined in the "js" package and is not allowed
			to access the js classes *)
		try
			(match PMap.find x ctx.com.package_rules with
			| Forbidden -> raise Exit
			| _ -> ())
		with Not_found -> ());
```

I removed this because it mentioned haxe remoting and we were going to deprecate that. However, it looks like it this is what caused `js.Map` to be ignored due to the package rules. So the question is if we want to keep this behavior or not.

**Comment by hoseyjoe** [comment] 2018-07-17 13:08
placing import haxe.ds.Map; at top of hx file fixes issue on my end, thank you. Leaving ticket open for the discussion.

**Comment by Simn** [comment] 2018-09-25 20:51
I'll go ahead and close this. The new behavior is consistent, and I don't like having hacks like that in such central code. Plus I'm pretty sure the behavior wasn't exactly intended before my changes either.

**Closed by Simn** 2018-09-25 20:51 UTC
