### ISSUE TITLE
Incorrect unused imports diagnostics with conditionals and import.hx

### ISSUE THREAD

**Issue by AlexHaxe** [HaxeFoundation/haxe#8988] opened 2019-11-23 13:16 UTC
When test driving organize imports feature of languageserver with Haxe 4.0.2 I came accross one file in one of my projects where `Remove unused imports` code action would delete an import that was still in use, albeit both (import and usage) inside an inactive conditional.

I tried boiling it down to a reproducible example and came up with a [demo project](https://github.com/HaxeFoundation/haxe/files/3882438/unused_imports.zip).

It has `haxe.enableCompilationServer` set to `true` via `settings.json`, but that setting has no influence on behaviour.

`display.hxml` sets target Javascript, and in `Main.hx` there is a conditional für `js` and "other", both imports are clearly in use (they don't make much sense though). VSCode tells me that `js.Browser` is unused.
The relevant bit for the demo is that there is an `import.hx` importing a type `Data` that has an error (like a missing import or an incorrect return type hint, haven't tested other ). 

Disabling `-js test.js` from `display.hxml` will mark `#if js` conditional inactive and and declare `#else` import as unused.

Removing imports as suggested will not produce a diagnostic warning in problems view of VSCode.

**Comment by AlexHaxe** [comment] 2019-11-27 09:25
I just realized `Main.hx` inside my zip file is a version that has a nested class that I failed to properly clean up when reducing my initial larger sample project. 
So outer `class TestJS {` (and corresponding `}`) can be dropped without affecting the issue (I assume you already figured that, but wanted to clarify nonetheless).

**Comment by Simn** [comment] 2019-12-03 09:19
I cannot reproduce this, it looks like this for me:

![Code_QYHe46q5rl](https://user-images.githubusercontent.com/634365/70036863-d54bcd00-15b5-11ea-8020-3e27646e4198.png)

I added the `var unused = null` to show that diagnostics is indeed running.

Removing the `-js test.js` I get this, which is what I expect:

![fhkaX8lrJw](https://user-images.githubusercontent.com/634365/70037103-4db28e00-15b6-11ea-9768-9386ffecc0a6.png)

**Comment by AlexHaxe** [comment] 2019-12-03 11:04
Using Haxe nightly fixes issue for me. However it still occurs when running Haxe 4.0.x.

**Comment by Simn** [comment] 2019-12-03 19:04
Right, I suppose this was fixed by my recent diagnostics changes. I don't think I want to backport that to 4.0 though because it's a somewhat involved change.

**Comment by Simn** [comment] 2020-06-04 14:11
I suppose we can close this.

**Closed as completed by Simn** 2020-06-04 14:11 UTC
Labels: bug, feature-ide
