### ISSUE TITLE
Argument resolving in complex template functions

### ISSUE THREAD

**Issue by er453r** [HaxeFoundation/haxe#5870] opened 2016-12-09 14:18 UTC
I've created a gist with this issue: https://gist.github.com/er453r/220ba91e32768b87648701fdca2c06ae

When there is a function template with a type extension and a not-required argument - it is still seen as required by the compiler.

When there are multiple template types WITHOUT type extension - it works as expected.

Removing `null` arguments in lines 31 and 36 exposes this problem and makes the code not to compile.

**Comment by Simn** [comment] 2016-12-10 16:01
This is due to type parameter constraints being checked lazily, which is necessary to avoid too-early type inference in some cases. That means that at the time of the call, the compiler doesn't know if you're providing argument 1 or 2 of the function, and then goes on to failing at a later point. This can be reproduced easily:

```haxe
class Main {
	static function f<T:String>(?t:T, ?i:Int) { }

	static public function main() {
		f(1);
	}
}
```

I don't think we can fix this and since we're considering disallowing optional argument skipping for Haxe 4 anyway I'll go ahead and close this issue.

**Closed by Simn** 2016-12-10 16:01 UTC

**Comment by er453r** [comment] 2016-12-10 16:22
Okay, that sounds reasonable. But since optional parametr skipping was the go-to way for method overloading, do you plan any other method overloading way for haxe 4?

Any hints how to do this another way in the current release?

**Comment by Simn** [comment] 2016-12-10 17:26
The general problem with overloading is that it doesn't play well with type-inference. I'm not sure yet what we're gonna do regarding that.

**Comment by kevinresol** [comment] 2016-12-11 14:05
@er453r try to avoid abusing optional args skipping, use abstracts instead.
http://www.kevinresol.com/2016-11-23/haxe-method-overloading/

**Comment by er453r** [comment] 2016-12-11 22:04
@kevinresol I thought it was a language feature, not an abuse ;) I know about this method, but it does not exactly solve my presented case with varying amount of optional arguments

@Simn I understand that we cant have both - type infering and overloading - since we can't a the same time guess the type and match it. But isn't it one the main language concepts, that you can skip the type declaration, bit if you don't, the compiler can do more? Also, what is the use of the `functionName<T:S>,` notation if the ancestor type is not matched?

**Comment by kevinresol** [comment] 2016-12-12 01:42
@er453r I am not sure how complex your use case is. But abstract casts does solve your specific gist problem. 

http://try.haxe.org/#74f0F
```haxe
class Test {
    static function f(?optional:String, ?handler:Handler, ?more:Int, ?args:Bool) { }

	static public function main() {
		var extended:Extended = null;
        var extending:Extending = null;
        var other:Other = null;
        
        f(extended);
        f(extending);
        f(other);
	}
}


enum HandlerType {
    HExtended(e:Extended);
    HOther(e:Other);
}

abstract Handler(HandlerType) from HandlerType to HandlerType {
    @:from public static function ofExtended(e:Extended):Handler
    	return HExtended(e);
    @:from public static function ofOther(o:Other):Handler
    	return HOther(o);
}

private class Extended {}
private class Extending extends Extended {}
private class Other{}
```
I even tried to add more optional args.

**Comment by er453r** [comment] 2016-12-12 09:48
@kevinresol except I can't get this approach to work with generic listeners, as I showed in the example.

The general problem I'm trying to solve is creating a type-safe event listeners, generated by the generic class provided by the handler.

**Comment by kevinresol** [comment] 2016-12-12 10:31
The problem here is that a handler of type `<U:Extended>, U->Void` is nothing more than `Extended->Void`. Because you cannot guarantee your handler is getting the correct child type.
And in both case you can only access the properties of `Extended` not its children's.

Here is what you can get with abstracts. If you really need to access the children's property, you probably need to go for macros.

```haxe
class Test {
    static function f(?optional:String, ?handler:Handler, ?more:Int, ?args:Bool) { }

    static public function main() {
        var extendedHandler:Extended->Void = null;
        var extendingHandler:Extending->Void = null;
        var otherHandler:Other->Void = null;
        var extendedData:Extended = null;
        var extendingData:Extending = null;
        var otherData:Other = null;
        
        addHandler(extendedHandler);
        // addHandler(extendingHandler); // this isn't really useful
        addHandler(otherHandler);
        call(extendedData);
        call(extendingData);
        call(otherData);
    }
    
    static function addHandler(f:Handler) {
        
    }
    
    static function call(d:Data) {
        
    }
}


enum DataType {
    DExtended(d:Extended);
    DOther(d:Other);
}

enum HandlerType {
    HExtended(f:Extended->Void);
    HOther(f:Other->Void);
}


abstract Data(DataType) from DataType to DataType {
    @:from public static function ofExtended(d:Extended):Data
        return DExtended(d);
    @:from public static function ofOther(d:Other):Data
        return DOther(d);
}

abstract Handler(HandlerType) from HandlerType to HandlerType {
    @:from public static function ofExtended(f:Extended->Void):Handler
        return HExtended(f);
    @:from public static function ofOther(f:Other->Void):Handler
        return HOther(f);
}

private class Extended {}
private class Extending extends Extended {}
private class Other{}
```
