### ISSUE TITLE
Sys.executablePath() in macro returns a directory instead of executable file

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3401] opened 2014-09-25 14:48 UTC
Subj.

Main.hx
```haxe
class Main {
    static function main() {
        trace(Sys.executablePath());
    }
}
```

Execute: `haxe --run Main`

Output:
```
Main.hx:3: D:\Code\haxe/
```

**Comment by nadako** [comment] 2015-01-14 11:35
I don't remember right now, but yeah, I guess I need to find out what went wrong.

**Comment by nadako** [comment] 2015-01-14 14:26
I'll reopen this as we want to test these.

**Comment by andyli** [comment] 2016-01-07 14:16
We really need some clarification of what it is...
Currently, `Sys.executablePath()` returns the following:
 * interp: `haxe`
 * neko: `/usr/local/bin/neko`
 * cpp: `/Users/andy/Documents/workspace/TestHaxe/bin/Test`
 * c# mono: `file:///Users/andy/Documents/workspace/TestHaxe/out/bin/Test.exe`
 * java: `/Users/andy/Documents/workspace/TestHaxe/`
 * python: `Test.py`

**Comment by ncannasse** [comment] 2016-01-07 20:36
It should return the path to the executable file.
If it's a binary (exe, etc) it should return the path to it
If it's a script file, that is run through a VM/interpreter it should return the full path to the script file.

Only CPP seems to be working good in your examples.

**Comment by andyli** [comment] 2016-01-09 12:37
Since the current implementations across target is not unified, and the method name is confusing (it may be a script but not a system executable), what about deprecating `executablePath()` and introduce `programPath()`, which returns the absolute path to the current binary/script.

To confirm, for interp/run, it should return the path to the .hx file of the main module, right?

**Comment by ncannasse** [comment] 2016-01-09 12:43
@andyli ok for programPath, and yes for interp

**Comment by Simn** [comment] 2016-01-09 12:43
I feel like making jokes about `realExecutablePath` in good old PHP-fashion, but I agree that it's the best approach here.

**Comment by Simn** [comment] 2016-04-02 10:25
What's the status here?

**Comment by andyli** [comment] 2016-04-02 12:58
It's basically done except one issue: https://github.com/HaxeFoundation/hxcpp/issues/398
I'm closing this one now since the issue is isolated.

**Closed by andyli** 2016-04-02 12:58 UTC
Labels: bug
