### ISSUE TITLE
DCE/Features and Compiler Cache

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3231] opened 2014-08-06 07:21 UTC
While working on CastleDB (http://github.com/ncannasse/castle) I noticed that the JS output was changing depending on the compiler cache usage.

After two compilations with compiler cache, the ``$estr`` for enum.toString disappear (as if the feature was disabled) and the IMap class appear (while it was not in the original output).

There's also the `@:initPackage` in JQuery which is playing hide and seek.

**Comment by Simn** [comment] 2015-01-15 18:59
I'm assuming this is a duplicate of #3508.

**Closed by Simn** 2015-01-15 18:59 UTC

**Comment by ncannasse** [comment] 2015-01-15 23:35
Might be not. Seems feature-related, whereas we fixed local variable names.
