### ISSUE TITLE
Is the Http class able to handle large, chunked requests?

### ISSUE THREAD

**Issue by rb1147x** [HaxeFoundation/haxe#4950] opened 2016-03-17 01:25 UTC
Is the Http class able to handle large, chunked requests?

The code below returns a status of 200, but an error of "Invalid chunk"

```
 var conn = new Http("http://www.pathofexile.com/api/public-stash-tabs");

 conn.onStatus = function(status:Int) {
   trace("Status: " + status);
 }

 conn.onData = function(data:String) {
   trace("Data: \n" + data);
 }

 conn.onError = function(msg:String) {
   trace("Error: " + msg);
 }

 conn.request(false);

```

I've tried both Neko and C++ targets. Replacing the above URL (which returns a LARGE amount of data) with https://jigsaw.w3.org/HTTP/ChunkedScript works just fine.

Thanks.

**Comment by nadako** [comment] 2016-03-17 01:27
This may be related to #4933

**Comment by nadako** [comment] 2016-03-17 02:26
I can reproduce this, but the `Http` code is really hard to read and understand what's going on. For me, an `Eof` error happens while reading from socket, and it's ignored by this catch: https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/Http.hx#L652 I wonder if it's correct to do. Ping @ncannasse

**Comment by nadako** [comment] 2016-03-17 02:28
BTW, at first I thought this is target-specific, so I compiled to C#, but I'm getting the same error with C#.

**Comment by ncannasse** [comment] 2016-03-17 09:28
Could you try with noShutdown=true ?

**Comment by dstrekelj** [comment] 2016-03-17 10:54
I'd like to add that I recently experienced the same issue with chunks. Setting `noShutdown = true` worked like a charm. I tried the same with @rb1147x example and, as far as I can tell, the entirety of the API response was successfully requested. This was tested on Neko.

**Comment by rb1147x** [comment] 2016-03-17 11:12
Indeed, it does look like it works with `noShutdown = true` (Neko and C++ on a Mac)

What does `noShutdown` do exactly? There's no explanation on the [API](http://api.haxe.org/haxe/Http.html#noShutdown) :)

Thanks!

**Comment by Simn** [comment] 2016-03-17 12:02
Without knowing anything about Http, it looks like we should change `if( !noShutdown )` to `if( !chunked && !noShutdown )`.

**Comment by ncannasse** [comment] 2016-03-17 13:01
shutdown is a socket function that enables to close only a part of the socket connection, for instance in http we send tell the server that we will not send further data by doing the shutdown.

This is necessary since some servers might not close the connexion until their keep alive expires in case we want to make other requests on the same socket. Without shutdown, we would keep being blocked in input.read since we block until the server close the socket on its side.

In that case, it seems the server misinterpret this shutdown by closing the connection before the chunked content is transferred. We could do as @Simn suggested, but I'm worried this would still block until the specified timeout (10 s by default) in case the server doesn't close the socket on its side, even if we have received the whole data.

**Comment by ncannasse** [comment] 2016-03-17 13:03
More info on the topic: https://en.wikipedia.org/wiki/HTTP_persistent_connection
PS: maybe using HTTP 1.0 instead of 1.1 will force the connection to be closed without shutdown

**Comment by ncannasse** [comment] 2016-03-17 13:07
Ok, another way to support this is to add the header "Connection: close" when sending the request. We could use this instead of the shutdown mechanism.

**Comment by rb1147x** [comment] 2016-03-19 00:47
Just adding Connection: close ? I tried that and just receive a status of 302 with no data.

**Comment by ncannasse** [comment] 2016-03-30 22:34
@rb1147x 302 is a redirection, you usually can get the real URL in the Location header https://en.wikipedia.org/wiki/HTTP_302 . But are you sure you were using the good URL, because it should not change the result if you use Connection: close or not.

**Comment by rb1147x** [comment] 2016-03-31 16:54
Trying it again, I'm not sure how I got 302 - I can't reproduce that now.

What works is adding:

`noShutdown = true` 

Without the above and playing around with headers, everything else returns:

`Invalid chunk`

**Comment by ncannasse** [comment] 2016-03-31 19:55
Could you check with HTTP 1.0 instead of 1.1 in header?

**Comment by ncannasse** [comment] 2016-03-31 19:57
Ah, actually what we need is something else.
We need to use notShutdown=true, then find a HTTP server that will have a long keepalive timeout, making the request hang until it expires. Then we need to verify that using Connection: close will indeed close after the connection is completed.

Ping @pperidont if he can help with such a setup

**Comment by ncannasse** [comment] 2016-04-03 10:47
@rb1147x please confirm that everything is fine now

**Closed** 2016-04-03 10:46 UTC

**Comment by rb1147x** [comment] 2016-04-03 13:44
Confirmed. Thanks!
