### ISSUE TITLE
[flash swc] Wrong created getter for interface

### ISSUE THREAD

**Issue by fortegames** [HaxeFoundation/haxe#3706] opened 2014-12-20 15:05 UTC
I'm trying to generate .swc which will be used in another flash application. In this swc I have interface  and  set @:getter for method isInited on it , but haxe compile this at  `function get get_isInited() : Boolean;` . I'm expecting `function get isInited() : Boolean;` . Is this a bug ?
Example: 

``` haxe
interface ITest
{
    #if swc @:extern #end
    var isInited(get, never) : Bool;    

     #if swc @:getter(isInited) #end
    private function get_isInited() : Bool;
}
```

Main class:

``` haxe
class MTest implements ITest
{
    var  _inited:Bool = true;

     #if swc @:extern #end
    public var isInited(get, never) : Bool; 

    #if swc @:getter(isInited) #end
    private function get_isInited() : Bool
    {
        return _inited;
    }
}
```

**Comment by Simn** [comment] 2015-01-14 09:53
Changing this right now would make me too nervous. I'll move it to 3.3 as it's not a regression.

**Comment by peteshand** [comment] 2015-03-26 00:31
I've just run into this issue as well. Is there any work around without changing all the interfaces in my libraries?

**Comment by peteshand** [comment] 2015-05-10 05:32
Has there been any progress on this issue? I've downloaded the Haxe source, but to be honest I'm not really sure where to start.

I've created a simple example project in both AS3 and Haxe. The projects have a "Test" class and a "ITest" interface. They can be downloaded from http://peteshand.net/HaxeSwcInterfaceIssue.zip

After compiling both of them, then decompiling the generated swf and inspecting the decompiled ITest interface class it is clear that the Haxe compiler doesn't generate interface's getter and setter definitions.

pre-compiled haxe
```haxe
package src;

interface ITest 
{
	function testFunc():Void;
	var id(default, default):String;
}
```

compiled haxe and decompiled as as3
```actionscript
﻿package src
{
    public interface ITest
    {
		public function ITest():void;
		function testFunc() : void;
    }
}
```

--------------------------------------------------------

pre-compiled as3
```actionscript
package 
{
	public interface ITest 
	{
		function get id():String;
		function set id(value:String):void;	
		function testFunc():void;
	}	
}
```

compiled as3 and decompiled as as3
```actionscript
﻿package 
{
    import ITest.*;
    public interface ITest
    {
        public function ITest();
        function get id() : String;
        function set id(param1:String) : void;
        function testFunc() : void;
    }
}
```

I'm pretty keen to get this issue resolved because without this fixed it means I'm having to maintain the same code base in both AS3 and Haxe, which is quite difficult. I'd much prefer to have everything in Haxe and simply compile a swc for all "pure" AS3 projects.

**Comment by peteshand** [comment] 2015-06-28 02:48
@Simn is there anything I can do to help progress a solution for this issue?

**Comment by Simn** [comment] 2015-06-28 06:07
@peteshand: I might be missing something, but in your Haxe code there isn't really any getter or setter. Didn't you mean `var id(get, set):String`?

**Comment by peteshand** [comment] 2015-06-28 08:55
Hey @Simn. Yep "var id(get, set):String" is probably more appropriate, but it doesn't change the resulting code in the swc. The interface still doesn't contain any reference to getter/setter. A revised example project can be downloaded from: http://peteshand.net/HaxeSwcInterfaceIssue_v2.zip

After compiling the Haxe to a swf and then decompiling the swf/swc the interface looks like this:
```actionscript
﻿package src
{
    public interface ITest
    {
        public function ITest() : void;

        function testFunc() : void;
    }
}
```

**Comment by back2dos** [comment] 2015-06-28 13:40
@peteshand I think what's slightly confusing is that you have a different issue, that has nothing to do with getters, but with constructors being generated on interfaces. If so, please open a separate issue.

**Comment by peteshand** [comment] 2015-06-29 00:09
Hey @back2dos, I understand it's a little confusing seeing as my code examples highlighting the constructors in red... I have no idea why the markdown is doing this, but regardless the issue I'm describing has nothing to do with constructors and everything to do with getters and setters. If you compile the example project I've linked to and then decompile with a tool like sothink swf decompiler. Then compare the decompiled as3 swf and the haxe swf you'll see that the haxe swf is missing it's interface getters and setters, while the as3 version retains them. Let me know if you still don't follow. Cheers

**Comment by pshtif** [comment] 2017-09-12 11:44
Any news on this? Doesn't seem to be resolved.

**Comment by peteshand** [comment] 2017-09-23 11:43
Hey @pshtif . No update from my end.. I basically just stopped targeting SWCs

**Comment by Simn** [comment] 2018-04-19 08:58
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.

**Closed by Simn** 2018-04-19 08:58 UTC
Labels: platform-flash
