### ISSUE TITLE
[python] unnecessary _hx_local_n() functions generated

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#5939] opened 2017-01-12 17:03 UTC
For example this code:
```haxe
typedef State = {
  var next:Int;
  var arr:Array<Int>;
}

class Test {
  static function main():Void {
    var state = {
      next: 0,
      arr: [0, 1, 2]
    }
    
    use(state);
  }
  
  static function use(s:State):Void {
    var res = 0;
    res += s.arr[s.next++];
    res -= s.arr[s.next++];
    res += s.arr[s.next++];
    
    trace(res);
  }
}
```

generates:
```python
...
class Test:
    __slots__ = ()

    @staticmethod
    def main():
        Test.use(_hx_AnonObject({'next': 0, 'arr': [0, 1, 2]}))

    @staticmethod
    def use(s):
        res = 0
        def _hx_local_1():
            _hx_local_0 = s.next
            s.next = (s.next + 1)
            return _hx_local_0
        s1 = python_internal_ArrayImpl._get(s.arr, _hx_local_1())
        res = s1
        def _hx_local_3():
            _hx_local_2 = s.next
            s.next = (s.next + 1)
            return _hx_local_2
        s2 = python_internal_ArrayImpl._get(s.arr, _hx_local_3())
        res = (res - s2)
        def _hx_local_6():
            _hx_local_5 = s.next
            s.next = (s.next + 1)
            return _hx_local_5
        s3 = python_internal_ArrayImpl._get(s.arr, _hx_local_6())
        res = (res + s3)
        print(str(res))
...
```

Tested on haxe 3.4rc, win7 64bit

**Comment by nadako** [comment] 2017-01-12 18:00
@Simn is that related to unop handling you wanted to rework?

**Comment by Simn** [comment] 2017-01-12 18:00
Yes

**Comment by nadako** [comment] 2017-10-11 06:50
Seems to be a duplicate of #5080.

**Closed by nadako** 2017-10-11 06:50 UTC
Labels: bug, feature-analyzer, platform-python
