### ISSUE TITLE
static member initialized to null compiles to undefined on JavaScript target

### ISSUE THREAD

**Issue by binki** [HaxeFoundation/haxe#5897] opened 2016-12-20 21:20 UTC
This might be like #3877.

In this http://try.haxe.org/#A9e66

```haxe
import haxe.Json;

class Test {
    static var nullStaticMember = null;

    static function main() {
        var x = {z: {}};
        trace(Json.stringify(x));
        x.z = null;
        trace(Json.stringify(x));
        x.z = nullStaticMember;
        trace(Json.stringify(x));
        
        // Exceptional?
        trace(Json.parse(Json.stringify(null)));
        trace(Json.parse(Json.stringify(nullStaticMember)));
    }
}
```

the `nullStaticMember` compiles to `undefined` instead of `null` when targeting JavaScript. Inside of most of Haxe, Haxe doesn’t distinguish between `undefined` and `null`. However, JSON does distinguish these. I think in this case `null` should compile to `null` instead of `undefined` (actually, it’s omitting the initialization for `nullStaticMember` altogether). I.e., the following statements should be equivalent:

```haxe
x.z = null; // Assign null directly, compiled to null
x.z = nullStaticMember; // Assign a class variable of the same type initialized to null, compiled (wrongly?) to undefined
```

It is unintuitive that those statements behave differently. This matters more when using a format such as JSON which is often an interchange format. It is conceivable that services which validate JSON might even require you to provide a key explicitly set to `null` instead of omitting the key. Or if you expect to be able to pass the results of `Json.stringify()` to `Json.parse()` you’ll find that `null` can be round-tripped while `undefined` cannot. JavaScript runtimes even throw a `SyntaxError` if you try to parse the result of stringifying `undefined`.

I see this in both haxe-3.3 (try website) and haxe-3.4rc1/3.4.0 (local CLI).

**Comment by Simn** [comment] 2016-12-20 21:24
genjs indeed skips the assignment when the expression is `null`. Does anyone remember why it does that?

**Comment by binki** [comment] 2016-12-23 06:26
If this issue is considered valid, how is #5905 invalid? They’re both instances of Haxe exposing developers to JavaScript’s `undefined` value but through different means. This bug is about an `= null` being omitted resulting in variable access returning `undefined` instead of `null` in user-authored code. The other is about the Haxe std-provided `Map.get()` implementation returning `undefined` when the API documentation declares it would return `null`. They would need different test cases ;-).

**Comment by Simn** [comment] 2016-12-23 09:03
I'm mostly curious why we skip `null` assignments on JavaScript.

**Comment by RealyUniqueName** [comment] 2016-12-23 09:43
My quess it was some sort of optimization: why spend time assigning `null` if `undefined` and `null` are the same for haxe?

**Comment by binki** [comment] 2016-12-23 15:30
But if `null` and `undefined` are really the same for haxe, shouldn’t its [`Json.stringify()`](http://api.haxe.org/haxe/Json.html#stringify) behavior reflect that? Depending on where I get `null` from, it outputs something different—even though haxe has compile-time type information that says that my object should have a key, it is omitted from JSON if I get a runtime `undefined`:

http://try.haxe.org/#8c488

```haxe
import haxe.Json;

class Test {
    static var uninitializedVar:String = null;
    
    static function main() {
        var x:{id:String,} = {
            id: null,
        };
        trace(Json.stringify(x)); // {"id":null}

        x = {
            id: ['a' => 'b',].get('c'),
        };
        trace(Json.stringify(x)); // {}
                 
        x = {
            id: uninitializedVar,
        };
        trace(Json.stringify(x)); // {}
    }
}
```

In my observations so far, `undefined` and `null` behave differently, even in specified situations (though right now the only specified situation I can think of is `Json.stringify()`).

**Comment by RealyUniqueName** [comment] 2019-06-21 18:37
This seems like a bad tradeoff: too small gain for such a big flaw.
I think we should change it to always generate uninitialized fields. And after implementing that proceed to #7002 
@ncannasse ?

**Comment by ncannasse** [comment] 2019-06-25 07:07
Initially the idea was to remove the explicit null initializer because in Haxe null == undefined and there was not known behavior when setting undefined instead of null would create a difference in terms of runtime.

Now with JSON it seems there is indeed a difference :-/ 

However I don't think we should fix our entire code generation because of this particular case. For instance we will also get target-specific differences when accessing unset fields or outside of bounds arrays:

```haxe
var o : { ?x : Int } = {};
o.x = [][-1];
haxe.Json.stringify(o);
```

So the problem is more about JS not setting the field when the value is undefined.
And this actually makes a single difference in the whole Haxe API (apart from JSON string value) which is Reflect.hasField(), because in both cases `haxe.Json.parse(o).x == null` as it should.

So I would vote for a wontfix here. It's a very peculiar case that can't be fixed in any sane way. A fix would only fix this very particular instance of a more global problem.

**Comment by binki** [comment] 2019-07-05 15:54
> Initially the idea was to remove the explicit null initializer because in Haxe null == undefined and there was not known behavior when setting undefined instead of null would create a difference in terms of runtime.
> 
> Now with JSON it seems there is indeed a difference :-/

This would still be acceptable as long as Haxe guaranteed that it was impossible to observe the difference. For example, if it preprocessed all calls to external functions to ensure that `undefined` is converted to `null` first. However, it’s probably way more efficient to just initialize things to `null` instead of walking object graphs passed to `JSON.stringify()`.

> However I don't think we should fix our entire code generation because of this particular case. For instance we will also get target-specific differences when accessing unset fields or outside of bounds arrays:
> 
> ```hx
> var o : { ?x : Int } = {};
> o.x = [][-1];
> haxe.Json.stringify(o);
> ```

In this case, it is known that indexing into an array of unknown length in JavaScript could result in `undefined`. In fact, this example could be improved:

```hx
static function main() {
  f([null]);
  f([]);
}
static function f(arr:Array<Int>) {
  trace(haxe.Json.stringify(arr[0]));
}
```

To be fully correct, Haxe should also guard such things and coerce them to `null` too. Or it needs to add the concept of `undefined` to its own type system.

I don’t understand why holes would intentionally be left in the type system like this. There are basically two ways Haxe could implement this without confusing code authors:

1. Always coerce to `null` in places where the type system cannot guarantee that the value has already been coerced to `null`. This would include array/string indexing and all optional arguments of exported functions. This would catch everything “entering” the Haxe-controlled parts of the program. This seems simpler to think about and could only be bypassed by the developer by writing an entire assignment expression or call inside of `untyped __js__()`.
2. Use the existing style where `null` and `undefined` are treated as equivalent and ensure that the difference between `null` and `undefined` is not observable. This would need to catch everything “exiting” the Haxe-controlled parts of the program. For example, an assignment to a dynamic/any object would need to have the value coerced from `undefined` to `null` prior to letting the assignment happen and calls to `extern` functions would need the expressions (including the full object graph of complex objects) checked for `undefined` properties and have them replaced with `null` prior to making the call. This seems more complex and, to do correctly, requires majorly expensive operations (graph traversal of potentially large objects passed to not only `JSON.stringify()` but any extern function).

In both cases, it would be work to identify all of the situations where such coercion would be needed to get the correct behavior.

> So I would vote for a wontfix here. It's a very peculiar case that can't be fixed in any sane way. A fix would only fix this very particular instance of a more global problem.

Is it not a goal of Haxe to provide type safety and isolate the developer from platform-specific peculiarities? I understand that Haxe provides a very lightweight extern call system which doesn’t try to hide platform peculiarities from those gluing to external libraries. But shouldn’t developers writing pure Haxe at least be able to write platform-portable code that has no observable differences in behavior between platforms?

**Comment by Aurel300** [comment] 2019-07-05 16:04
> So I would vote for a wontfix here. It's a very peculiar case that can't be fixed in any sane way. A fix would only fix this very particular instance of a more global problem.

This particular instance seems like a one-line fix that shouldn't cause any other issues. Yes, there are other ways to get `undefined` instead of `null`, but we can treat those separately.

**Comment by ncannasse** [comment] 2019-07-06 17:41
Haxe does it's best to hide the platform specific peculiarities, but not at the cost of performances impact. 

The fact that JS chooses to return undefined instead of null for out of bounds Array and the fact that JSON does not print undefined fields (because assigning undefined to a field will "remove" it) are both JS specific things that cannot be avoided without adding extra checks for all Array and field accesses to convert the undefined into null. We will not do these things as it would ruin the performances of Haxe/JS.

While the JSON output is different, it does not change the fact that `JSON.parse(JSON.stringify(v)).x == null` so in terms of actual runtime, I fail to see how it would change something. For instance we also do not give warranty on fields ordering in JSON.stringify (it might vary per platform).

**Closed by ncannasse** 2019-07-06 17:41 UTC
Labels: platform-javascript
