### ISSUE TITLE
Unable to compile with the .NET 4.5 framework

### ISSUE THREAD

**Issue by joel-arthur** [HaxeFoundation/haxe#4586] opened 2015-10-12 15:54 UTC
When trying to compile with .NET 4.5,

adding
-net-lib C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.5\mscorlib.dll

Or

Including Mono's .NET 4.5 dlls with:
-D net-ver=45

results in the following error:
PeReader.Error_message("Error reading compressed data. Invalid first byte: e5")
Build halted with errors (haxe.exe).

I have also seen this error:

File "ilMetaReader.ml", line 577, characters 34-40: Assertion failed
error 0x2

trying to set -net-std to "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.5"

**Comment by waneck** [comment] 2015-10-12 16:05
What Haxe version are you on? Are the binaries downloaded from haxe.org ?

**Comment by joel-arthur** [comment] 2015-10-12 16:11
haxe -version
3.3.0 (git build development @ 36bb144)

Downloaded version 3.3 from build.haxe.org to work around some issues I had that you already fixed

**Comment by waneck** [comment] 2015-10-12 18:33
Can you upload the dll somewhere? I'm under linux so it's not very easy to get the windows `mscorlib.dll`

**Comment by joel-arthur** [comment] 2015-10-12 18:38
Sent you an email with the link.

**Comment by hoseyjoe** [comment] 2017-07-10 13:57
Was anything discovered with this? I am bouncing into this issue currently.

**Comment by kLabz** [comment] 2019-06-14 05:57
Duplicate of #4151, should be fixed by #8413 too.

**Closed** 2019-06-14 06:24 UTC
Labels: platform-cs
