### ISSUE TITLE
[php] SPOD db.Manager on 3.2.0 rc2

### ISSUE THREAD

**Issue by erixtekila** [HaxeFoundation/haxe#4144] opened 2015-04-08 14:49 UTC
I got a regression on the new haxe version that didn't appeared in 3.1.3
While I use SPOD with php, I get an exception at php generated for the makeCacheKey method.

``` haxe
$k = Reflect::field($x, $this->table_keys[0]);
```

returns `NULL`

When I try to output `$this->table_keys[0]` I got its value (object field) duplicated.
Strangely, the php outputted code seems the same ?…
Could it be called twice ?

I use such haxe code :

``` haxe
var changeLocale
            = switch( Router.locale )
            {
                case LocaleString.fr : Locale.manager.select( $lang != fr ).lang;
                case LocaleString.en : Locale.manager.select( $lang != en ).lang;
            }
```

Here is the SPOD object definition

``` haxe
package model.db;

import sys.db.Types;
import sys.db.Manager;

/**
* Manage the locale table from SPOD macros
**/
@:id( lang )
class Locale extends sys.db.Object
{
    public static var manager = new Manager<Locale>(Locale);

    public var lang:SEnum<LocaleString>;
    public var locale:SString<5>;
}

enum LocaleString
{
    fr;
    en;
    /*TODO es;  de;*/
}
```

And I get this type of error `Missing key lang`

**Comment by waneck** [comment] 2015-05-01 22:27
I cannot reproduce the bug with the information added. Can you please submit a reproducible example where the bug happens? Thanks

**Comment by erixtekila** [comment] 2015-05-02 09:53
Hi @waneck, I 'll check once more with a fresh code base.

**Comment by waneck** [comment] 2015-06-25 20:24
@erixtekila any news? We'll probably have a 3.2.1 release and it would be nice to solve this if possible

**Comment by erixtekila** [comment] 2015-06-25 22:09
Will check asap

**Comment by erixtekila** [comment] 2017-01-20 15:24
@waneck Same error on the last 3.4.0 RC2

**Comment by RealyUniqueName** [comment] 2017-01-22 17:31
Can you try with new php generator (add `-D php7` to compilation)? You will need PHP7 to run compiled app.

**Comment by erixtekila** [comment] 2017-01-25 17:43
@RealyUniqueName Is SPOD for php7 backward compatible ?
I get other errors of sql requests.

**Comment by erixtekila** [comment] 2017-01-25 18:30
:(( @RealyUniqueName  I know have problems with externs.
Any new way to include them in the output ?!

**Comment by RealyUniqueName** [comment] 2017-01-25 19:57
Unit test for SPOD passed without error.
Externs also work for me.
Can your provide a minimal example, so i can reproduce your issue and fix it?

**Comment by erixtekila** [comment] 2017-01-25 23:38
To be more clear, my code that was build for php 5 used externs (MobileDetect.php for example).
At that time the include was made like so :
```haxe
extern class Mobile_Detect
{

	static function __init__():Void untyped
	{
		__call__("require_once", "lib/Mobile_Detect.php");
	}
}
```

But my code actually fails when build for php7.
All he externs are gone from the output.

My question was : does php7 changes the way externs are treated ?

**Comment by waneck** [comment] 2017-06-25 10:49
I'm going to close this, for lack of reproducible example. Feel free to reopen at https://github.com/HaxeFoundation/record-macros

**Closed by waneck** 2017-06-25 10:49 UTC
Labels: feature-spod
