### ISSUE TITLE
[php] signed right bit shift issues

### ISSUE THREAD

**Issue by jdonaldson** [HaxeFoundation/haxe#3414] opened 2014-09-28 14:04 UTC
I came across a really strange issue with php bit shifting:

I have a number, and I want to extract a signed portion of the bits.  Say I want to extract the first four bits of the number 200015, which are all set. Since the last bit of the four is set, I want to treat the extracted value as a negative integer.

And, in php, this works in some cases.  Shifting to the left 28 bits, and then to the right 28 bits lets me extract the 4 initial bits as a signed integer.

``` haxe3
        trace((((200015 << 28)) >> 28));  // -1
```

However, if I apply this operation against a variable, rather than a constant number, I get the wrong result:

``` haxe3
        var x = 200015;
        trace((((x << 28)) >> 28));  // 200015
        trace((((x << 28) & 0xffffffff) >> 28));  // 200015... even with a bit mask.
```

Note that this was occurring even when I try to apply a bit mask on the intermediate result.  I can't really find a good workaround.

**Comment by Simn** [comment] 2015-02-27 16:18
I still cannot reproduce this and neither can our CI. This is the generated Main.php I have:

```
<?php

class Main {
	public function __construct(){}
	static function main() {
		$x = 200015;
		haxe_Log::trace($x << 28 >> 28, _hx_anonymous(array("fileName" => "Main.hx", "lineNumber" => 4, "className" => "Main", "methodName" => "main")));
		haxe_Log::trace(($x << 28 & -1) >> 28, _hx_anonymous(array("fileName" => "Main.hx", "lineNumber" => 5, "className" => "Main", "methodName" => "main")));
	}
	function __toString() { return 'Main'; }
}
```

**Comment by jdonaldson** [comment] 2015-02-27 23:39
Yeah, this is strange.   I'm thinking it's a 32/64 bit issue, but I'm not sure why it's only happening for me on yosemite.  I'll keep poking around on it.

**Comment by ncannasse** [comment] 2015-02-28 10:35
looks like a 32/64 bit issue. Notice as haxe generates -1 instead of 0xFFFFFFFF, which means it will never mask on 64 bit system, since -1 will be 0xFFFFFFFFFFFFFFFF...

The problem is that we cannot make the difference in our compiler if the user either wrote 0xFFFFFFFF or -1, but both have different runtime values on a 64 bit Int system.

I think that only PHP is concerned ? -- ping @waneck @hughsando -- actually an eventual OCaml backend would be concerned too).

I wonder how we are going to fix this...

**Comment by ncannasse** [comment] 2015-02-28 10:42
The only "correct" fix I can see would be to use Int64 internally in Haxe so the 0xFFFFFFFF doesn't overflow, but that would cause a lot of mess everywhere.

An alternate option might be to store the Int64 repr of our Int32 in case both differs at the Lexer level, then be able to retrieve it inside the generator, the same we do for singly quoted strings.

But then that would also require us to perform additional checks in optimizer to prevent us to perform calculus if one of the values is Int64 or if the result might overflow...

**Comment by ncannasse** [comment] 2015-02-28 10:43
...or introduce a Int64 constant kind, that would be necessary anyway if we introduce "real" Int64 literals

**Comment by ncannasse** [comment] 2015-02-28 10:45
(but I don't think the later would fix the reported issue)

**Comment by Simn** [comment] 2015-03-15 09:17
Our CI actually can reproduce it without -D analyzer in place.

**Comment by Herschel** [comment] 2015-09-08 08:03
I encountered this while working on Int32, which I handle by inspecting `PHP_INT_SIZE` and masking off the extra bits if 64-bit. (https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/Int32.hx#L1840) The above code works correctly if you use Int32.

So the question is whether Haxe should guarantee this shift behavior for standard Int. My impression was no, because Haxe does not specify the size/overflow behavior of Int in general, and I don't think it'd be possible in general without some performance penalty.

**Comment by ncannasse** [comment] 2015-09-08 10:57
One way to fix this would be be for us to disable optimization of `<<` when it overflows on 32 bits and `>>` on negative values if the system might have native 64 bit ints. At least that would give same result in both constants and variables.

**Comment by clemos** [comment] 2015-10-06 12:10
Pasting these tests here too: https://gist.github.com/clemos/fc48d8076d936531a386

**Comment by RealyUniqueName** [comment] 2019-04-08 10:12
> trace((((200015 << 28)) >> 28));  // -1

This works as expected because of being calculated at compile time by the compiler and compiled as `trace(-1)`

> var x = 200015;
> trace((((x << 28)) >> 28));  // 200015
> trace((((x << 28) & 0xffffffff) >> 28));  // 200015... even with a bit mask.

This is because it's calculated at runtime by PHP with 64bit integers.

Since it's decided to [keep `Int` as native integers](https://github.com/HaxeFoundation/haxe/issues/8095), I'm closing this issue.

**Closed by RealyUniqueName** 2019-04-08 10:12 UTC
Labels: platform-php
