### ISSUE TITLE
Operator overloads using their own dependent type parameters are never matched

### ISSUE THREAD

**Issue by matrefeytontias** [HaxeFoundation/haxe#9123] opened 2020-02-04 02:44 UTC
It's pretty hard to explain simply, so have this code instead (tested on both Haxe 4.0.5 and the latest nightly build as of February 4th 2020).
```haxe
class Main
{
    static public function main()
    {
        var c:MyType<Int, Array<Int>> = { val1:0, val2:[0], name:"a" },
            d:MyType<Int, Array<Int>> = { val1:1, val2:[1], name:"b" };
        
        trace(c < d); // error : cannot compare ... (see below)
        trace(MyType.test(c, d)); // true
    }
}

typedef MyWrapper<T, C> = {val1:T, val2:C, name:String};

@:forward
abstract MyType<T, C:Iterable<T>>(MyWrapper<T, C>) from MyWrapper<T, C>
{
    @:op(a < b)
    static public inline function test<U, D:Iterable<U>>(a:MyType<U, D>, b:MyType<U, D>) : Bool
    {
        return a.name.charCodeAt(0) < b.name.charCodeAt(0);
    }
}

```

In this code, compilation fails with `Cannot compare MyType<Int, Array<Int>> and MyType<Int, Array<Int>>`. However replacing `c < d` with `MyType.test(c, d)` works fine, which indicates that the culprit is the process trying to match the usage of `<` with an overloaded implementation.

---
After messing around with it, I figured out that operator overloads that have their own dependent type parameters (ie one type parameter that references a previous type parameter in a constraint, here `function test<U, D:Iterable<U>>`), while working correctly when called explicitly (here `MyType.test(c, d)`), will fail to be matched when using the operator syntax (here `c < d`). In addition to this observation, here are some things of interest that I found, on their own, to either fix or not fix the situation. In the following, "fixes the issue" refers to code that leads to `c < d` being recognized and matched against the overloaded operator implementation.

- Making `test` non-static changes nothing as long as you keep `test`'s own type parameters U and D.
- Making `test` non-static in addition to using `MyType`'s type parameters T and C and removing `test`'s own type parameters U and D fixes the issue, but forbids more specific filtering on which types `test` should work on, like when doing `test<U, D:Iterable<U> & Comparable<U>>`.
- Making the type constraint on the second type parameter not reference the first type parameter in both the abstract definition and the `test` function definition fixes the issue, but obviously is less generic. Example: `abstract MyType<T, C:Iterable<Int>>` and `function test<U, D:Iterable<Int>>`
- Getting rid of `D` in the `test` type parameters and replacing it with `Array<U>` in the type of the arguments to `test` fixes the issue, but obviously makes the operator only work with arrays over U instead of working with any iterable over U (using `Iterable` instead of `Array` doesn't work according to the usual Haxe rules on unification of type parameters). Example : `function test<U>(a:MyType<U, Array<U>>, b:MyType<U, Array<U>>)`

**Comment by RealyUniqueName** [comment] 2020-02-04 10:00
I think it's a consequence of type param constraints typing being delayed.
We have other issues caused by constraints implementation. E.g. https://github.com/HaxeFoundation/haxe/pull/8985

**Comment by Simn** [comment] 2020-06-09 14:32
This passes with #9549 merged.

**Closed as completed** 2020-06-10 21:40 UTC
Labels: feature-abstracts
